### ISSUE TITLE
1.4.5.1429: Mousegrab camera control is unpredictable

### ISSUE THREAD

**Issue by jsiren** [leezer3/OpenBVE#1]
In window mode (build 1.4.5.1429), working with the mousegrab camera control in window mode, with default window size, route Birmingham Cross-City South OpenBVE, train Class 323 unrefurb OpenBVE (3D cab). Right-click on the center of the speedo, the camera rotates right and down, so that the top of the horn lever comes into view. Check both cab door windows once. Check both cab door windows again, the motion range is no longer sufficient to get the right-hand side window completely into view. The third time it's no longer possible to view the offside window at all, only the driver's side. Restore the default view by eye, right-click to end the capture, and start again by right-clicking on the center of the speedo; the view now shifts to the power/brake handle.

The expectation is for the view to either remain still or center on the right-click point. Also the camera motions should be consistent and repeatable.

**Comment by jsiren** [comment]
Platform: Ubuntu Linux 14.04 LTS, Mono version details:
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by leezer3** [comment]
Probably fixed as of 1.4.7.1068-
The previous mouse position was being carried over between mousegrab sessions, which caused a jump if the mouse had been moved.

**Comment by jsiren** [comment]
Works as expected in 1.4.7.1068.
