### ISSUE TITLE
BVE4trains class 168 missing faces in exterior model

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#1000]
I've noticed the BVE4trains class 168 found on https://sites.google.com/a/bve4trains.com/bve4trains/trains-for-open-bve-and-bve-4/class-168 has issues in the newer builds (I am currently using the 25/02/2024 nightly build). I thought maybe I had installed it incorrectly but when I did a fresh reinstall, the same issues have come up. Objectviewer shows no errors but displays the model as in the attached screenshots. 

What could be the problem? Is there anything my end I need to fix? Is it a settings Issue? 

<img width="473" alt="image" src="https://github.com/leezer3/OpenBVE/assets/50995356/7604525a-8b74-41ee-80f6-8a9c14885484">

<img width="480" alt="image" src="https://github.com/leezer3/OpenBVE/assets/50995356/9099ce43-a3fc-4706-81ab-dd6794f68049">

**Comment by leezer3** [comment]
OK, it's a PNG variant the new decoder isn't handling nicely.

Will see what I can do.

**Comment by leezer3** [comment]
OK, please try this build:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2024-03-01.zip

That should sort out things.

**Comment by soyachoin104** [comment]
Sorted. Thanks a lot.
