### ISSUE TITLE
 "The selected route is corrupt:   No objects defined." was there  When I was tired to open the NYCTA 6 Line route

### ISSUE THREAD

**Issue by openbvefan** [leezer3/OpenBVE#1003]
This happened to me around 10 times when I wanted to play the 6 line route.

 Route:
6 EXP from Pelham Bay to Brooklyn Bridge NTT
Link to Route:
https://www.bvestation.com/download/122
 Train: 
R62 Kawasaki 2020
Link to Train:
https://drive.google.com/file/d/1_kd8kX7aLJJtCiTKkaK5CTXNyvGmxgxm/view

**Comment by leezer3** [comment]
This error I thrown when we can't find any objects.

This means you're probably missing one or more object packs / other routes. (Or haven't installed them correctly)

NYCTA stuff is an interdependent mess.
I'll have a look later and see what that actually requires.

**Comment by openbvefan** [comment]
where can i check if im using the 64 bit version on openbve

**Comment by openbvefan** [comment]
I am using the 64-bit version but it still has the same error

**Comment by openbvefan** [comment]
I put the object and sound again and its working now
