### ISSUE TITLE
Urgent:NearestTrainFilter

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1007]
### Description

Crosshatch has released new data.
https://kanakyusubway.web.fc2.com/bve/route/chiba/
However, there were many reports that this data did not work.
Upon investigation, he was using an Animated function called NearestTrainFilter.
It is possible that Crosshatch created and released the data in a state where S520 was unable to do PR because his illness worsened without PR.
If leeser3 was produced at some point instead of S520, please implement it as soon as possible.
Also, it seems that he is using Crosshatch without understanding the function specifications, so I can't ask for details.
First of all, I wanted to check if leeser3 made it, so I created an issue.

I also his train read the route, but it stayed at 0% and didn't proceed.
This may be unrelated, but in fact, when I run it in mono, it stops progressing from 0% on any route, no matter how simple it is, and now I'm running it on wine, but the Crosshatch's route doesn't  0% even on wine.

How to using: for animated
![GKfq4lsbIAA-cyK](https://github.com/leezer3/OpenBVE/assets/22734699/1d31db6d-8e63-4cc1-8c09-6d3d13109e07)

### Reproduction

https://kanakyusubway.web.fc2.com/bve/route/chiba/

## Route

https://kanakyusubway.web.fc2.com/bve/route/chiba/

## Train

Maybe Any, but he distribute train for this route.

### Related information 

My PC's spec:
OS:Ubuntu 22.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (polaris10, LLVM 15.0.7, DRM 3.54, 6.5.0-21-generic)

**Comment by leezer3** [comment]
Definitely not me :(

I can fix the freeze later (probably) but figuring out what exactly he intended the function to do may be interesting.

**Comment by leezer3** [comment]
Latest build will fix this, and it's going to be significant enough for me to put out a new release, as there are some (uncommon) PNG decoder issues which I hadn't got as far as putting into a new release too.

This is building now, but will take a few hours for me to sort out properly.

**Comment by leezer3** [comment]
1.10.0.0 is now on the main site.
