### ISSUE TITLE
[Question] Can the route creator set it so that the player can't control Track.Switch switching?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1008]
### Description

When creating a route that runs on a different track, I would like to disable the player's ability to operate the switchgear and allow only the route creator to set the route of their choice.
Can this be achieved with Track.Switch or other instructions?

**Comment by leezer3** [comment]
Not with the current implementation- I think it'd probably require a new command.

Not quite sure what this would achieve though- Wouldn't just not adding switches, and just using dummy freeobjs / rails work for places where the player isn't supposed to change?

**Comment by ginga81** [comment]
![OtherTracks](https://github.com/leezer3/OpenBVE/assets/22734699/a340caee-29e0-4e8b-8405-ee6bb83b0530)
If we want to create a route like the one shown in the diagram, I have to create a route one by one with 4 different branches based on Rail0.
However, if the route creator lock the branch settings, we can easily without having to create four routes from scratch only create one route.
Because I want to do this.
Similarly, even when coming from a terminal station to a starting station on a double track, we can run in any direction by just creating one line from the starting station to the ending station.
Therefore, if players are allowed to freely manipulate the branch settings, there is a risk that unintended actions such as security devices may occur, so I would like to restrict this.

**Comment by leezer3** [comment]
OK, I see what you're trying to do.
I'm not entirely sure it wouldn't be easier just to build the station / scenery as a single object and use a null object on Rail0 (and this is somewhat working around the limitations of the current format)

---

Added the command:
**PlayerPath** *railIndex1; railIndex2*
If the train is on *railIndex1* it will be switched to *railIndex2* and vice-versa in reverse.

The path will still show up on the switch map.

**Comment by ginga81** [comment]
If I use PlayerPath and don't use Track.Switch/T, will I be able to do what I hope?(The player can't change switch)

Please close this if possible.

**Comment by ginga81** [comment]
Thank you very much!
I think it's resolved, so I'll close it.
I will test it before implementing it on the Tohoku Shinkansen.
