### ISSUE TITLE
Some 3D Panel Touch Zone not registering click

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#1010]
### Description
Haven't got time to look at the specifics yet, but it appears that at least on the train I tested on, nothing happens when you left click a majority of the touch area zone.

Log shows the following entry:
```
Value is invalid in Command in Touch at line 85 in /media/lx86/Data/OpenBVE_Content/Train/HKTSS/LRV P4/Latest/Release/HKTSS MTR Light Rail Phase IV (Coupled-Set)/panel.xml
```

But they all worked on v1.9.2.5, just not v1.9.2.7 and above.
Some commands like SANDERS and HEADLIGHTS seems to work fine, just not for others like security key, doors, wiper etc.

## Routes
[TFO Demo route by ginga81](https://drive.google.com/file/d/17GEHSa13GMeS7G1cVe7GkuMdkP_GyhNt/view?usp=sharing)

## Train
[HKTSS.MTR.Light.Rail.Phase.IV.v3.0.1.zip](https://github.com/HKTSS/LRV-P4/releases/download/3.0.1/HKTSS.MTR.Light.Rail.Phase.IV.v3.0.1.zip)

Touch area chart as follows:
![image](https://github.com/leezer3/OpenBVE/assets/28094366/54b970b3-8ed9-41e4-a01c-dda81b315190)
(Unfortunately in mandarin, but there should be bilingual tooltips showing what it is when you actually hover on these touch areas)

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/14921479/log.txt)

### Related information 

* Operating system: Debian 13 Trixie
* Method of control: Keyboard

**Comment by leezer3** [comment]
That's related to the language loading, and specifically some work to sort out the mess of using an underscore as both an argument separator and a valid part of a command name. (commands now internally do not contain an underscore)

Anything with an underscore in got broken (completely forgot these were used in the XML panel parser)

Please try the build from today- I'll put out a hotfix tomorrow, as this is reasonably important.

**Comment by Kenny-Hui** [comment]
I think you also need to apply the patch to [PanelAnimatedXmlParser.cs](https://github.com/leezer3/OpenBVE/blob/194f28855e6d69af38abf169c1f66e2d6b7ab569/source/Plugins/Train.OpenBve/Panel/PanelAnimatedXmlParser.cs) as well
