### ISSUE TITLE
[Question] Cannot bypass vehicles on another track

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#1011]
### Description

I uncoupled some cars onto another track and tried to bypass them, but I was blocked by the extended "Global Ghost Collision Box" of these cars, as if I were on the same track as these cars.

![Global obstacle](https://github.com/leezer3/OpenBVE/assets/114210303/16b406df-0b4e-4eb6-8aad-c8d0068307e4)
I labeled these ghost collision boxes with a faint red "global obstacle" mark.

Let me know what width can do.
#

This makes me feel that the original orbit command should have a global effect...? It seems like I was lost in thought while watching RailBuffer...

**Comment by leezer3** [comment]
Thanks.
That's not something I'd tried yet. Must be doing something with the track position, not taking into account the rail index- Will look into it. (Reasonably certain there's no collision box)

Unfortunately, this just shows how much of a mess I'm trying to untangle.
