### ISSUE TITLE
PlayerPath don't work from another rail to another rail?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1013]
### Description

My crossing in front of Morioka is written with the distance and number shows below.
![OtherTracks2](https://github.com/leezer3/OpenBVE/assets/22734699/2dbb8736-8bcf-446a-84d9-753309ff47f0)

Rail4 is an upward track and distanceX is always 4.3m from Rail0.

The same distance in the file below is written as follows.
$include(include/H1東北新幹線盛岡駅停車v0.01.csv )	
![Screenshot from 2024-04-11 23-46-00](https://github.com/leezer3/OpenBVE/assets/22734699/ead2ea4c-6539-455f-83d8-5f81fd4d9065)
![Screenshot from 2024-04-11 23-18-57](https://github.com/leezer3/OpenBVE/assets/22734699/e3ffc9b8-7603-448f-9331-5fa65fe4e05b)

Then, I wrote the following at the end of one of the route data CSV files.
```
171100
.PlayerPath 0; 1

171250
.PlayerPath 1; 4
```

The rail arrangement of this distance is common to all files.
However, when I selected the route file, an error appeared and I was unable to drive.
171100 .PlayerPath 0; 1 succeeded.
But, when I added 171250 .PlayerPath 1; 4, an error occurred and I couldn't read it.
![Screenshot from 2024-04-11 23-22-44](https://github.com/leezer3/OpenBVE/assets/22734699/399dd917-5453-4a64-b43e-e6a69d88781c)

### Reproduction

Any my Tohoku Shinkansen from Sendai v6.xx(Currently v06.02, but only add the Announce voice)

## Route

Any my Tohoku Shinkansen from Sendai v6.xx(Currently v06.02, but only add the Announce voice)

## Train

any

## Logs

This issue can't choice data. So no log.

### Related information 

My PC's spec:
OS:Ubuntu 22.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (polaris10, LLVM 15.0.7, DRM 3.54, 6.5.0-21-generic)

**Comment by leezer3** [comment]
Thanks.
I'd overlooked the edge-case where the rail we switched to existed in the first block.

I think that should work now.

**Comment by ginga81** [comment]
Thanks!
I can read the data!
But, there is happened a
![Screenshot from 2024-04-12 03-05-39](https://github.com/leezer3/OpenBVE/assets/22734699/7f630c45-535a-4ad5-a338-df902516c5df)
s this.
```
171100
.PlayerPath 0; 1

171250
.PlayerPath 1; 4

171275
.PlayerPath 4; 5

```

**Comment by ginga81** [comment]
For example, is it possible to run a non-Rail0 rail at a dead-end station like King's Cross station from the beginning?

**Comment by leezer3** [comment]
PlayerPath seems to work from one rail to another here at the minute, but I'm testing with somewhat less complex files to start with :)

I haven't yet got as far as trying to see what's going on with the reversal of the setting of SwitchT on non-zero tracks, but I don't think this is going to be related to the glitch above.

Something obviously isn't right with your screenshot, but it's a little confusing as to what exactly- Is it that the train is on two different tracks, or is it something to do with the one ahead getting stuck?
That would be expected if the rails are at different world positions when the switch is traversed (and I'd guess that the train would probably glitch horribly whilst doing so). This isn't tested at the minute, but possibly should be.

**Comment by ginga81** [comment]
As shown in the csv and PlayerPath presented at the beginning, from 171250, the moving Rail1 became Railend, and it moves to switch to the parallel Rail4.
However, as shown in the photo, it suddenly returned to Rail0 from 171250. I tried running several cars as it was, or I think that it will follow the next PlayerPath and go to Rail5, but it kept returning to Rail0 as shown as screenshot.
For this reason, I expected that although I could move from Rail 0 to the next Rail, I would not be able to move between rails that are not Rail 0.

**Comment by ginga81** [comment]
[Playerpath-demo.zip](https://github.com/leezer3/OpenBVE/files/15004618/Playerpath-demo.zip)
![PlayerPath-test-figure](https://github.com/leezer3/OpenBVE/assets/22734699/65338080-41fe-47f9-8281-c9cb80922c54)
In this data, after leaving the starting station on Rail0,
250m, change to Rail2
375m, change to Rail4
400m, change to Rail3
525m, change to Rail5
There are designed to run on the rails.
So PlayerPath is written as at the end
```
250
.PlayerPath 0;2
375
.PlayerPath 2;4
400
.PlayerPath 4;3
525
.PlayerPath 3;5
```
As I wrote, it seems that switching is only possible at 250m.
Vehicle is any.

**Comment by leezer3** [comment]
The immediate cause of the is that you're issuing a .RailEnd command at the same position as the switch.

If you switch your rails to null and move the railend command one block further (25m) this works around the issue.
May take a little re-working of the logic somewhere, I'm not sure yet.

**Comment by leezer3** [comment]
Build from today *should* sort this.

**Comment by ginga81** [comment]
Thank you!
I think there is no problem even if we start on another rail and move to another rail, and it works correctly even if we back to.
I also think that the behavior of having to place all vehicles at a distance of 0m or more in order to put the entire train onto another track is correct behavior, so I will close it as resolved.
Thank you for the great feature!
Now we can freely run , freely directioning all of rails just by creating one data in one direction!
Banzai!
Now that we only have to create one thing deeply, creating data has become extreme easier.
![Screenshot from 2024-04-19 17-28-47](https://github.com/leezer3/OpenBVE/assets/22734699/993ff2ee-8da1-4f76-8828-612251baddb0)
