### ISSUE TITLE
[Bug] Rail start position is 0 and using switch, route cannot be played

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#1018]
### Description

The route will report error of "index out of range"
```
With Track
0
.RailType 0;0
.RailStart 1;4;;0

1000, .RailStart 33;0;;0, .Switch 0;33;;;Crossover Down U
1025, .Rail 33;1
1050, .Rail 33;3
1075, .Rail 33;4, .SwitchT 1;33;;;Crossover Down D
1100, .RailEnd 33;0
```

**Comment by JunmoreHeavyBox** [comment]
My example is still too rough.

### Reproduction

## Route

[Side Lines And Switches Test.csv](https://github.com/leezer3/OpenBVE/files/14984696/Side.Lines.And.Switches.Test.csv)

**Comment by ginga81** [comment]
I think your question is probably the same as mine.
https://github.com/leezer3/OpenBVE/issues/1013#issuecomment-2057012174

**Comment by leezer3** [comment]
I think this one is now fixed after todays fiddling....
