### ISSUE TITLE
will there be a chance for openBVE to finally be supported on MacOS Sanoma on Apple Silicon Based Machines

### ISSUE THREAD

**Issue by aairbus016** [leezer3/OpenBVE#1023]
is there version fully supported for M1 MacBooks

I compared performances of my old Laptop with a Core I5 10th gen at full performance and the M1 MacBook Air I got both having the same 8gb of ram and my old laptop was faster attuning openBVE.

**Comment by leezer3** [comment]
It's complicated, and largely out of my hands I'm afraid.

Please check that you're running comparible resolution settings (remember that Retina displays have a *much* higher default resolution), and let me have some examples of things that are significantly slower.

To note, I *do not* have access to a M1 Mac.

---

The TLDR:
As you're hopefully aware, the M1 powered series of Apple machines run a completely different CPU architecture to a standard laptop.
This breaks the legacy WinForms main menu, as well as most train plugins, and makes it very hard for me to do anything.
For some very techincal reasons, it's likely to be slower than an equivilant age Windows laptop, but for most content, this is unlikely to be significant. 

Most content for OpenBVE uses 4gb or less of RAM, so it's unlikely a lack of it will cause the problems you're experiencing.

**Comment by aairbus016** [comment]
Thank you for your email

**Comment by alopix** [comment]
I can confirm that openBVE at least runs on macOS Sonoma on an M3 without to many issues. Obviously the menu is very limited and some features fully crash (some options like e.g. the load route shortcut the RouteViewer will crash, so you have to load files via command line etc.).

**Comment by leezer3** [comment]
Thanks.

Object Viewer and Route Viewer use a standard Mono file picker to load stuff, which obviously isn't available on Sonoma. 
(I would suspect that this is another manifestation of the fact that WinForms doesn't work on 64-bit Apple, and has been abandoned by Mono)

I may be able to implement a similar file picker to the main game for the viewers, but further than that it's a bit of an issue.
Unfortunately, writing a GUI is a long, hard task whatever you do it in :)

**Comment by alopix** [comment]
I have been looking into some cross-platform C# UI frameworks yesterday and there always seems to be a catch these days (also, VS Code’s support for C# is appalling which makes trying to contribute to openBVE not fun…). I feel like I have not found a good cross-platform desktop UI lib for any language for that matter (apart from using Qt in C++ or Python). And I am always looking at them given I would prefer not implementing my own stuff over and over again for every desktop platform I would like to support.

**Comment by leezer3** [comment]
I'm surprised you've found VS Code to be bad for C# (whilst I use Visual Studio itself, AFAIK it's one of the better options...)

Good cross-platform UI libs are a massive issue. You've got to rebuild everything in something like XAML, which often also requires shipping native platform libs with your binaries, deal with 'interesting' licencing choices, which with the general history of this project I'm not going into, or just plain roll your own.

With regards to QT, I'm not a personal fam of anything GPL. 
LGPL is 'better' but to me the whole attitude there isn't exactly one I'm happy with, meh. Dunno if you've noticed our little licence history / discussion issue here, which has some of the details: https://github.com/leezer3/OpenBVE/issues/305

Either way, if you choose to contribute, it'll be most welcome.

**Comment by alopix** [comment]
As a macOS user/dev I don’t have stable enough access to Windows and VS.

I have also always been wary of GPL, though am quite happy about the LGPL, which prevents many of the issues GPL introduced. I have come across the license thread before and decided not to delve in too much as I know the pains haha

I might look into adding better main menu support on macOS, given it is (understandably given Mono WinForms are 32bit only) quite lacking. Depends on how much time I end up having tbh. Ideally it would use one code-base for all platforms but who knows what the best cross-platform solution is.

Sorry for hijacking this issue.

**Comment by aairbus016** [comment]
You should try to convert openBVE in this Apple software called Game
Porting Toolkit
https://developer.apple.com/games/game-porting-toolkit/
It should run better

**Comment by leezer3** [comment]
I'm absolutely not attempting a port to an Apple specific toolchain.
Amongst other things, it doesn't support C#, and we'd have to write the windowing from scratch.

I'm actively working GL on menu support for the viewers at the minute, but this is as far as things are likely to go.

This has always been a fully multi-platform project.

**Comment by aairbus016** [comment]
How is the progress going for openBVE running on newer macOS and Apple
silicon chips I have an m1 Mac so you could send me the file to test

**Comment by leezer3** [comment]
The build from today contains GL menus / file pickers in both Object Viewer and Route Viewer, similar to that in the main game.
As noted above, they aren't mega pretty, but they work.

(To access these, you'll need to launch the respective programs from the archive via command-line)

I'll also see about getting the basic route map working in the main game menu at some point, but I think this issue can now be closed.

**Comment by DBAG423** [comment]
What would be the command to open Route/Object Viewer on MacOS? 

I've tried 'open -a RouteViewer', 'open -a RouteViewer.exe', and 'open RouteViewer'. Usually, these commands would work when attempting to launch an app ('open -a Audacity') however, won't work with RouteViewer or ObjectViewer.

**Comment by leezer3** [comment]
You need to do that from terminal.

```
mono RouteViewer.exe

mono ObjectViewer.exe
```

(I think the casing on those is correct; I'll check that later)

**Comment by DBAG423** [comment]
I've tried both `mono RouteViewer.exe` and `mono/Applications/OpenBVE.app/Contents/Resources/RouteViewer.exe`. Could the fact that it's a .exe file be what's preventing it from launching?

![SCR-20240930-il6](https://github.com/user-attachments/assets/bd9ccd8b-f60d-4434-bc16-b8fe0f0c44e3)
![SCR-20240930-imy](https://github.com/user-attachments/assets/6ee50db2-6662-433e-9b7e-46e4d6d6fa6a)
![SCR-20240930-in2](https://github.com/user-attachments/assets/43c135c4-5658-42e4-be28-138e416762d0)

**Comment by leezer3** [comment]
Basically, it depends on exactly which download you're using, and exactly where you've extracted / saved it.
(And to a certain extent how good you are with terminal)

For the minute, let's assume you've downloaded the ZIP file. (The .dmg file & app is only a fancy wrapper for this)

Extract this to your home directory, into a folder named **OpenBVE**

Open terminal.

Enter the following:
```
cd ~
```

This just tells terminal to change the current working directory to the root of your home directory.

Now enter:
```
cd OpenBVE
```

This gets you into the OpenBVE directory you just created.

Finally, try:
```
mono RouteViewer.exe

mono ObjectViewer.exe
```

This will hopefully now launch the tools.

It sounds to me like what we probably need is a sub-menu for tools, which contains both the package menu and Object Viewer / Route Viewer.
Apple is pretty unique in the way we need to create the app....

**Comment by DBAG423** [comment]
Unfortunately, this method did not work and it gave me the same error as before.

![SCR-20241001-174](https://github.com/user-attachments/assets/3c3886a3-0767-4450-b865-2b75770fedc6)

**Comment by leezer3** [comment]
Please try the most recent build:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2024-10-04.dmg

This adds a 'Tools' menu to the main menu.
Package Management has been moved into this menu, and it now provides a link to Object Viewer and Route Viewer in addition.

(I think you're confusing terminal locations somehow FWIW)

**Comment by DBAG423** [comment]
I've just tried it, and both Object and Route Viewer loaded. Thanks for adding a simple menu to help with that. I have found a few issues with the programs though.

Route VIewer:
Clicking ‘P’ to show rail paths causes a crash.

Object Viewer:
Unable to move forward and backwards (might be because of the lack of a keyboard on MacBooks).

Unable to clear currently opened objects (pressing the 'delete' key did not work).

-----------------------------------------------

I really appreciate the addition of development tools for Silicon Mac devices, as the lack of them has made route/train development a pain, with me constantly having to reload the actual route to see any additions I have made. Hopefully in the future we'll be able to see a more fleshed out version of the program for Mac devices that include some more options like being able to change the number of allowed sounds, and having the program remember some settings you've previously changed.

**Comment by leezer3** [comment]
OK, the rail paths is going to be an issue.

That's a relatively complicated Windows Form. I'll probably just end up disabling that under Mac unfortunately.

Object Viewer being unable to move, as you surmise is lack of numpad.
W (up) A (left) S (down) D (right) Q (forward) E (back) should also work in current builds. Unfortunately, I don't think there's actually a way to tell whether there's a numpad present or not, to display them on-screen.

Delete not working:
I'll check, but I suspect we're only handling the DEL key (found under INSERT on a 'standard' keyboard) and not BACKSPACE, which is what the key marked delete on a Macbook keyboard actually is :)

**Comment by DBAG423** [comment]
> That's a relatively complicated Windows Form. I'll probably just end up disabling that under Mac unfortunately.

Understandable, since I don't usually work on TFO's, or anything involving pathing, I don't think I would've used it much anyway.

> W (up) A (left) S (down) D (right) Q (forward) E (back) should also work in current builds.

I'll try Q & E out. Once again, thanks for adding these tools to aid with Mac BVE Development.

**Comment by leezer3** [comment]
The options were saving, it was just the resolution that wasn't- I've fixed this oversight, and fixed a couple of bits which were ending up off-screen if the resolution changed too much.

I've also hidden the RailPaths prompt and fixed the crash on 64-bit Apple.

This build should fix (or at least mask) most of the issues you've highlighted.
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2024-10-04.dmg

(It's the same link, the automatic build server ought to update it in a minute or two)

**Comment by DBAG423** [comment]
Been enjoying using the Object/Route Viewer tools on MacOS (once again, thanks for adding full support for the tools), but would it also be possible to get the other tools working on Mac? (Object Bender, Train Editor, CarXMLConverter, etc.)

**Comment by leezer3** [comment]
Not really, sorry.

These are all complex WinForms and unlikely to be portable to the menu system.

**Comment by DBAG423** [comment]
I understand, thanks.
