### ISSUE TITLE
StateChangeSound's Position operates on the 'Object' section one level above.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1031]
### Description

It behaves as the title suggests.
OpenBVE version is v1.10.0.1

### Reproduction

Crosshatch reported.
https://x.com/cross_hatch/status/1787824376202887288
Take a look at his sample objects in ObjectViewer.
[ScreenDoor.zip](https://github.com/leezer3/OpenBVE/files/15236257/ScreenDoor.zip)

**Comment by leezer3** [comment]
I believe the build from today will solve this.

**Comment by ginga81** [comment]
I have received a report from Crosshatch that it worked successfully, so I will close it.
