### ISSUE TITLE
[Bug] Converting XML cars with extra indentation characters

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#1035]
### Description

On the annotation of the acceleration product and pressure units. As the number of power notches increases, the excess indents gradually increase.
Look like
```
<Part>
    <AccelerateCurves />
    <!---->
        <Element />
    </Part>
    <Part>
        <AccelerateCurves />
        <!---->
            <Element />
        </Part>
        <Part>
            <AccelerateCurves />
            <!---->
                <Element />
            </Part>
            <... />
```
The increase in indentation characters for single file conversion is more pronounced.

### Reproduction

This my XML train.
[oBVE_C601J_R.zip](https://github.com/leezer3/OpenBVE/files/15314060/oBVE_C601J_R.zip)

### Related information 

* OpenBVE Version: Build 2024-05-11

**Comment by leezer3** [comment]
I can't explain that.

The code adds *no* whitespace whatsoever.

My first suspicion would be whatever editor you're using to open the file after the conversion.
It would appear to be interpreting comments as unclosed XML tags and adding an indent.

Please try opening the converted files with a plain text editor (On Windows that would be plain Notepad, on Linux something like nano on the console) *before* using your preferred editor and see if this still occurs.

**Comment by JunmoreHeavyBox** [comment]
I am using Notepad to open the file, it is not an issue with the editor.

**Comment by JunmoreHeavyBox** [comment]
Thank!
