### ISSUE TITLE
Crosshatch's route can't load at 1.10.1.0

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1036]
Crosshatch's route can't load at 1.10.1.0
### Description

It is as the title.
The moment I start to load the route, OpenBVE returned to the menu with the following error log:
```
Z:\home\user\Desktop\tmp\Railway\Route\千葉市営地下鉄\千葉市営地下鉄1号線.csv
00:14:04  The route and train loader encountered the following critical error: Object reference not set to an instance of an object.
00:14:04  WARNING: Program crashing. Creating CrashLog file: C:\users\user\Application Data\OpenBve\Settings\OpenBVE Crash- 2024.5.19[00.14].log
```
### Reproduction
Route
https://kanakyusubway.web.fc2.com/bve/route/chiba/
Train
https://kanakyusubway.web.fc2.com/bve/train/0-type/

## Route

Route
https://kanakyusubway.web.fc2.com/bve/route/chiba/

## Train

https://kanakyusubway.web.fc2.com/bve/train/0-type/

**Comment by leezer3** [comment]
:(

Why do these things always pop up the moment I've made a release.....

I've fixed this in the nightly, will push out a release in a few minutes with a couple of other small changes from today.

**Comment by leezer3** [comment]
Should have the new build up on the website as soon as Github runs the update batch.

**Comment by ginga81** [comment]
He contacted me to say it worked.
It's already been closed, but I'd report it.
