### ISSUE TITLE
[ERROR] Objectviewer can no longer load extensions.cfg files

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#1037]
I'm using latest stable version 1.10.1.0 and I've noticed that full train consists no longer appear in objectviewer. It displays the errors that can be viewed with F9 but the objects themselves do not show up at all. 

I've tested this on several trains in my archive and have not been able to find one that works. These are all ones that have displayed with few problems in previous builds. Just to save you time looking for a specific model to test with I've attached a train that previously worked but now no longer shows up when its extensions.cfg is loaded into objectviewer https://drive.google.com/file/d/1-ijvgpe5YSTr1t9o2t9BNcRe93D2mJ4t/view?usp=sharing

**Comment by leezer3** [comment]
That's really odd.
This is what appears to break it:
https://github.com/leezer3/OpenBVE/commit/5a152d96d432197fc55a83370efe38eba4675983

Specifically, it doesn't like the fact that the the track element array is initialised by default.
I think there must be something a little wider hiding somewhere in the visibility update that this has brought to light.

Investigating, but might take a day or two to get to the bottom of.....

**Comment by leezer3** [comment]
OK, replaced the original hack with a slightly better one that works again.

The whole train viewing in Object Viewer is a bit of a bodge though, and needs re-visiting, somewhere on a rather too long list of things to do.
