### ISSUE TITLE
[Question] How do I connect MTC on Windows and Linux?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1038]
### Description
Sorry. A Windows user asked me on Discord that they don't know how to connect.
But I don't know how to connect either.

I've connected with Linux the TYPE-II Densha De Go USB and ZUIKI, but...
I don't have one myself, but I'd like to know how to connect on Linux as well.
Thank you in advance.

**Comment by leezer3** [comment]
@MarcRiera 

I believe all they should need to do is to install the UDev rules (found in the DenshaDeGo! controller plugin config) and probably restart the system for it to show up.
n.b. If these have already been installed previously, they've been updated for the new controller.

**Comment by ginga81** [comment]
Sorry. There's no problem, I just don't know how to connect it.

For Windows, when we using TYPE-II and Ryojouhen, turn on the Densha de GO! controller plugin, and then

1. Extract the Windows drivers.
2. Download and run Zadig.
3. Load the appropriate CFG file for your device ("Device > Load Preset Device").
4. Press "Install Driver" and wait for installation to complete.

As it says,
Shinkansen.cfg
Type2.cfg
Ryojouhen.cfg
I think we should install them using zadig.

I've heard that ZUIKI works without any effort.
But MTC doesn't have cfg.

In Linux, we are only install
99-ps2-train-controllers.rules
Should we only this action also for MTC?

**Comment by MarcRiera** [comment]
Sorry, I added the CFG files for Zadig when MTC support was included, but I forgot to link them to the button in the "Help" window. I have now submitted a PR with the fix.

You can find the required files here: https://github.com/leezer3/OpenBVE/tree/master/source/InputDevicePlugins/DenshaDeGoInput/Drivers For the MTC you need both `MTC.cfg` and `TrainMascon.cfg` (the latter for the P5/B5 cartridge).

**Comment by MarcRiera** [comment]
> I'm sorry for asking an additional question, but I said to him that the cassette can be replaced, but is that correct?

You can use all the cartridges (P4/B7, P4/B2-B7, P5-B5, P5-B7, P5-B8 and P13-B7), but changing them in-game is not possible (you need to go back to the plugin config and select the new one).

**Comment by ginga81** [comment]
Thank you! I will pass this information on to him!

**Comment by ginga81** [comment]
It seems that MTC users are not very knowledgeable about it, so they asked me to write a tutorial on how to install it.
I hope that will find it useful.
