### ISSUE TITLE
Crash when disconnecting the coupler

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#1053]
### Description

The moment I switched to outer view with F2 and disconnected the coupler, OpenBVE crashed.
This happened in 1.11.0.0.

### Reproduction

Download Series-E6
https://www.youtube.com/watch?v=yRBr-Dsa1U4

Additionally, outer-views
https://drive.google.com/uc?export=download&id=198rhbi_hNyaK4ZVsTxUEFEY81RfwyL8h

## Route

Maybe any

## Train

Use Series-E6+outer view

## Logs

[OpenBVE Crash- 2024.8.06[01.32].log](https://github.com/user-attachments/files/16500566/OpenBVE.Crash-.2024.8.06.01.32.log)

### Related information 

My PC's spec:
OS:Ubuntu 22.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (polaris10, LLVM 15.0.7, DRM 3.54, 6.5.0-45-generic)

**Comment by leezer3** [comment]
Thanks.

I think the build from today should sort this.

**Comment by ginga81** [comment]
[OpenBVE Crash- 2024.8.07[20.06].log](https://github.com/user-attachments/files/16522448/OpenBVE.Crash-.2024.8.07.20.06.log)
I tried it with build 20240807, and it crashed again.
The log is here.

**Comment by leezer3** [comment]
OK, that's odd, same crash; what I changed *should* have sorted that :/

I'll have to see about getting this to actually reproduce, which as this appears to be timing related may be tricky.
(Essentially, it appears to be attempting to update the brake system for a car (the uncoupled one) which is no longer in the train)
