### ISSUE TITLE
[Suggestion] Add number of allowed sounds option to MacOS version

### ISSUE THREAD

**Issue by DBAG423** [leezer3/OpenBVE#1071]
I would like to see an option to increase the number of allowed sounds on the MacOS version of OpenBVE. Currently, the limit is 16, which interferes with the number of sounds I would like to have to play at once on the route I am building. I know this is a feature on the other versions of the game, so I'm hoping it won't be a pain to add to the MacOS version.

**Comment by leezer3** [comment]
Sure, that's no problem- Added that.

For what it's worth, all the options are actually there if you edit the config file, it's just that it's a lot harder to add them to the options menu, as this is essentially hand-written.

**Comment by DBAG423** [comment]
Oh- I didn't know that. I'll definitely take a look in the config file.

Thanks!
