### ISSUE TITLE
Transparency issue in .x object files 

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#1074]
I recently downloaded the new 1.11.0.6 build and also a new released train, found here: http://ryuutazx1370.blog.fc2.com/blog-entry-27.html However, loading this train into the game shows all the supposed transparent parts of the object as black (see screenshot) 
<img width="663" alt="image" src="https://github.com/user-attachments/assets/34c71806-03f0-419e-bb93-adf5c6a82354"> I also tried this with today's (15th Oct) nightly build, same issue. Looking into the file contents, it seems all the objects are .x files which can't be directly edited.

**Comment by leezer3** [comment]
Have you tried this in-game, or just in Object Viewer / Route Viewer?

It's using the old method of creating transparency in an X file (pure black e.g. 0;0;0) in a texture being rendered as transparent.
This is only set / used in the main game, and that only with the **Enable Hacks for Buggy Older Content** setting enabled.

Note:
This setting should be enabled unless you're debugging something specifically.

**Comment by soyachoin104** [comment]
Seems like that was unchecked for some reason. Seems to load fine in-game now. Thanks
