### ISSUE TITLE
[Suggestion] Pass station forward/backward tolerance to train plugins

### ISSUE THREAD

**Issue by marcriera** [leezer3/OpenBVE#1076]
Currently, `elapseData` in train plugins includes a list of stations in the route. Among other data, the stop position is passed, but not the forward/backward tolerances. This may be interesting for ATC systems which restrict door opening to certain sections of track (the use case where I missed the data, actually).

I was about to send a PR of https://github.com/leezer3/OpenBVE/commit/022e37f76cf2b112ec30ac7968b2da058c2eb375 but then realised that this probably breaks the API for existing plugins and I'm not sure about how to make it compatible, so let's see if there's a way to make this possible.

Thanks!

**Comment by leezer3** [comment]
Famous last words, but i don't think it is breaking.
New members are fine, it's altering the signature of existing members / methods that aren't.

I'll check that tomorrow, but it looks OK at first glance.

Basically though, this comes down to the eternal question of re-writing, or adding more bodges to the existing :)
The existing plugin interface is a mess these days, but a re-write first pretty much requires someone to be implementing a new consumer at the same time.

**Comment by leezer3** [comment]
OK, looking at it, it's *concievable* that someone has consumed the constructor in a plugin.

Easiest way to do this non-breaking is just to add another constructor, and update our references to point to the new one.
Visual Studio / the compiler will then complain that the constructor is unused, but it's part of a shipped API, so really wants to stay, just in case.

**Comment by marcriera** [comment]
I was looking at the history of `elapseData` and it has expanded since the initial definition several times, most recently in https://github.com/leezer3/OpenBVE/commit/be93ce178dda5a3534938a353e352a718573c2b8. Yet I use older plugins (such as OdakyufanAts) which haven't been recompiled, use elapseData and there are no crashes in sight. I can see how that works; the old plugin doesn't "know" about the new properties.

I'll try building my plugin with the current API and using `Stations` specifically with a build of OpenBVE with the modified class, to check that it works. If you consider there's no problem and that this case is the same as the commit linked above, let me know and I'll get a PR ready.

Thanks!
