### ISSUE TITLE
BVE5: DetailManager.dll not working right

### ISSUE THREAD

**Issue by breathtakingwhale** [leezer3/OpenBVE#1079]
### Description

When launching the route, I get an error that reads ''An attempt was made to read or write to protected memory. This is usually an indication that additional memory has been corrupted. DetailManager.dll''. From my experience, this has only happened to me with trains from FWCH.

### Reproduction

![6af73a9d-ceb2-4a1c-8ff5-697b039a717f](https://github.com/user-attachments/assets/c32a8363-526f-4cbf-ae5b-c00c344c606b) (Translated through Google translate.) _An attempt was made to read or write to protected memory. This is usually an indication that additional memory has been corrupted. DetailManager.dll_

As you can see, the notch display does not work. Also, motor sounds cannot be heard, only train running sounds can be heard.
![image](https://github.com/user-attachments/assets/07e577ac-3701-495b-95a1-28629d255df0)

## Route

Bve山陽本線 (広島→糸崎) from 三矢車両所
(https://sites.google.com/view/mitsuya-ry/bve-data/bve%E5%B1%B1%E9%99%BD%E6%9C%AC%E7%B7%9A%E5%BA%83%E5%B3%B6%E7%B3%B8%E5%B4%8E)

## Train

JR西日本227系 from FWCH
(https://sites.google.com/view/fwchbve/top/bve%E3%83%87%E3%83%BC%E3%82%BF%E3%83%BC%E5%85%AC%E9%96%8B/jr%E8%A5%BF%E6%97%A5%E6%9C%AC227%E7%B3%BB)

### Related information 

- Processor - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
- GPU - NVIDIA GeForce GTX 1050 Ti

Thanks for any response at all!

**Comment by leezer3** [comment]
Will try to take a look, but it might be Monday.

IIRC there's an updated version of detailmanager I did (it's not originally mine, but this definitely rings a bell) which might well solve this though.
@ginga81 I think knows more about this :)

**Comment by ginga81** [comment]
The Bve5 parser does not support vehicles.
Vehicles for Bve5 and 6 cannot be selected.
Please select OpenBVE or vehicles up to BVE4.
I was able to load only the routes with 1.11.0.6.
![Screenshot from 2024-10-19 04-52-05](https://github.com/user-attachments/assets/322983ce-99b3-406d-a60f-eb48d6d98151)

※I reverted from Ubuntu 24.04 to 22.04.

**Comment by breathtakingwhale** [comment]
@ginga81 That's strange, there's a lot of videos on YouTube where the route with 227系 runs fine without any errors (e.g. https://www.youtube.com/watch?v=XRaOLxEnQJQ). Also, the route works for me fine with another train (115系 from https://github.com/sankakujirusi12/Bve_Kito_Oka_Hiro_Seki_Trainpack/blob/master/README.md) without any errors.

**Comment by ginga81** [comment]
The video you introduced 'launches Bve5' and operates a Bve5 227 series on the Bve5 Sanyo Main Line, so this is only natural.
And but the Bve5 'route parser' of OpenBVE operates the Bve5 'route' in OpenBVE, so it cannot operate vehicles for Bve56.

Vehicles for Bve56 are not compatible because they are separate software.

**Comment by leezer3** [comment]
Well, I'm not actually sure how on earth you've managed to load the linked train at all.....

I've now had a chance to look into it, and as noted above, we definitely don't load BVE5 / BVE6 format trains at the minute.
Some trains still contain an old train.dat, and we can load these, but that's not the case with the one above.

Can you clarify a bit as to how you actually got it loading?
I don't think there's anything we can realistically do at present, but I'm curious as to how you got it in-game.

**Comment by ginga81** [comment]
@leezer3 
Is this says to me?
Or to him?
I think it's to him, but I wanted to confirm cafully.

**Comment by leezer3** [comment]
It's to @breathtakingwhale :)

**Comment by breathtakingwhale** [comment]
@leezer3 Lol, I never thought it might be that bad!! But I did it how I would with other trains—I just put the stuff in the train's Scenarios folder in the BveTs > Scenarios folder, and it works. 
![image](https://github.com/user-attachments/assets/0732adf0-d2ef-4f3a-b10f-515ce75fd716)
I was pretty sure it was a train meant for Bve5/6 though. I'm not this skilled (I've been playing this game for ages smh.) but I can't distinguish all the different versions of Bve. Ever since I've been playing Bve, I've been doing stuff according to this tutorial. https://www.youtube.com/watch?v=pXNRrG1iE3o&t
Anyway, this is how the train's files look. 
![image](https://github.com/user-attachments/assets/b01224a0-5c57-430d-958e-912f155778f1)
Thanks for everything!
