### ISSUE TITLE
Cannot launch OpenBVE v1.11.0.7 under mono

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#1087]
### Description

With the latest nightly build / 1.11.0.7, OpenBVE will crash on startup under mono:
![image](https://github.com/user-attachments/assets/c5f4a45c-cd2c-456f-a4e9-20847962fbf9)
Followed by
![image](https://github.com/user-attachments/assets/14ca2f0a-991b-4cf3-a736-7175c7788c1e)

This doesn't happen on the 2024-11-07 nightly build.

### Logs
Log files are generated, but no stacktrace inside.

### Related information 

* Operating system: Arch Linux
* Method of control: Keyboard

**Comment by leezer3** [comment]
That's very odd.

At an educated guess, your box must be returning a scale factor of zero.
I'll try and reproduce that later.

**Comment by ginga81** [comment]
After seeing your post, I tried it myself.
The same thing happened to me on Ubuntu 22.04.
![Screenshot from 2024-11-10 04-05-37](https://github.com/user-attachments/assets/a916e537-d159-4685-83b9-ca5459afa9ef)
![Screenshot from 2024-11-10 04-05-39](https://github.com/user-attachments/assets/761806a6-60b7-4519-9760-7d5b9531fb5a)

**Comment by leezer3** [comment]
OK, I think the build from today will solve that.

I need to investigate further why it's returning zero for the scale factor in OpenTK though.

**Comment by ginga81** [comment]
I tested 1.11.0.8.
In my Ubuntu 22.04, run properly.
Thank you very much for fix!
