### ISSUE TITLE
ObjectViewer_fileopen drag and drop

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#109]
ObjectViewer is only to open file(s), press F7 key and select file.
I want to open file(s) by drag and drop operation.
Please consider this issue.

**Comment by leezer3** [comment]
Not currently included in openTK.

https://github.com/opentk/opentk/pull/542
Tracking this PR, and when merged will revisit.

**Comment by ginga81** [comment]
I didn't know that the drag and drop is by OpenTK.
I thought that it is by .NET.
I am waiting for that applied the drag and drop version of OpenTK.

By this correspondence, the creator can very easy and smoothly checking at the same time the rail, train and platform etc.
Thank you very much for considering this request.
