### ISSUE TITLE
[Question] Does the Train.Destination command work in the game and what does it do?

### ISSUE THREAD

**Issue by DBAG423** [leezer3/OpenBVE#1092]
I found this in a 1986 NYCTA (N) Line Route, and I'm not completely sure what it does or how to use it. 

> Train.Destination(14)

I remember a friend a while back mentioning that it could be used to automatically set a train's signage based on the route it was loaded on, but when attempting to look in the documentation for both the route.csv & .animated format, I found no instance of "Train.destination". 

Was this feature in the game before, is it still used, and how does it work?

Forgive me if I missed a mention of it in those documents.

**Comment by leezer3** [comment]
It's definitely in the current documentation, but you want **Track.Destination**

https://openbve-project.net/documentation_hugo/en/routes/csv.html

You may access the destination set in animated files via **Destination**
