### ISSUE TITLE
Can openBVE be in a .pkg format, or become a app in the App Store for Mac only(intel and Apple silicon)

### ISSUE THREAD

**Issue by aairbus016** [leezer3/OpenBVE#1093]
Hi, I was wondering if developers/contributors around the world of openBVE can figure out or maybe adding a new path to Mac users, you could make an alternative download format in like pkg or reach out to Apple to propose to them of approving openBVE under Apple, i hope it’s possible for y’all to get back the classic menu like on windows of its on the App Store which I am not sure if it’s rare to impossible, but I am inquiring about this to have a shot at adding compatibility 
macOS Big Sur or later

**Comment by aairbus016** [comment]
Or give game porting toolkit a try

**Comment by leezer3** [comment]
The classic menu is essentially impossible, 
The WinForms toolkit has been abandoned on non-Windows platforms.

The Game Porting Toolkit is essentially useless. V1 is just a wrapper around WINE (which depends internally on WinForms), and V2 is nothing more than a glorified set of examples....

We're already running everything as native OpenGL in the new menu, so it offers absolutely nothing useful to us. 
It doesn't have the polish of the original main menu, as you've got to write the entire thing from scratch.

Doing anything more than we do already requires a significant investment in time and money.
Essentially, that's a $99 / year Apple developer sub, plus a machine to build it on, plus time to actually submit things to Apple for verification.
Unfortunately that's not happening....
