### ISSUE TITLE
[Request] Add coupled sound and coupler animation states

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#1097]
### Description

As shown in the title.

```ini
[Coupler]
Couple = Coupling.wav
; The sound played when a coupler is coupled.
```
**rearCoupler**: The state of the rear coupler.
**rearCoupler[carIdex]**: The state of the rear coupler of car _carIndex_.
**frontCoupler**: The state of the front coupler.
**frontCoupler[carIndex]**: The state of the front coupler of car _carIndex_.

**Comment by leezer3** [comment]
Added the animated variables. (n.b. a possibly easier way to figure out whether the front coupler is coupled or not is to test whether the car index is non-zero)

The XML format sounds has an uncoupling sound, but no coupling one:
https://openbve-project.net/documentation_hugo/en/trains/xml/sound.html

Thinking about it. we might also want an in-cab coupling / uncoupling sound.
Let me think on that one a bit....

**Comment by leezer3** [comment]
Added the following to the XML format:
**Couple**
**CoupleCab**
**UncoupleCab**

See the documentation link above, but should be relatively self-explanatory.

Ideally I'd much rather not add these to to the original format.
It's a mess with too much added to it already, and the newer formats have been designed to be much more easily extensible.

**Comment by JunmoreHeavyBox** [comment]
Okay, Thank you.
