### ISSUE TITLE
openBVE 1.5.0.9 — "Unhandled Windows Form Exception"

### ISSUE THREAD

**Issue by MelioraCogito** [leezer3/OpenBVE#123]
"Unhandled Windows Form Exception"

Just installed oBVE 1.5.0.9 this evening (2016-12-15) over a previous stable installation (dopey me didn't back it up, but I'm sure I have the previous installation file around somewhere... but I digress).  

As soon as I went to select a route, the above error occurred, and continues to occur regardless of what route I select and where it resides (within the ...\LegacyContent\Railway\Route... folder or sub-folders).

The error also occurs when trying to select train files.

See attached oBVE generated Bug Report.Unhandled Windows Form Exception
[2nd openBVE Bug Report15_12_2016.zip](https://github.com/leezer3/OpenBVE/files/656552/2nd.openBVE.Bug.Report15_12_2016.zip)

[openBVE Bug Report15_12_2016.zip](https://github.com/leezer3/OpenBVE/files/656536/openBVE.Bug.Report15_12_2016.zip)

**Comment by leezer3** [comment]
May I guess Windows 10?

Something very funny is going on, but I can't get to the bottom of it at the minute.
I installed 1.5.0.9 on a VM which had 1.5.0.7 installed on it.
This gave me the error you're seeing.

I then reinstalled 1.5.0.7- No error.
I then installed 1.5.0.9 again, and still had no error.

Can't get the error back at the minute (Even installing from fresh..), and it's a very generic exception from the Window message pump.

I'd suggest a reboot & reinstall and see if that fixes it.

Not really a solution, but I strongly suspect it's Windows 10 being funny.

**Comment by Sirflankalot** [comment]
I'll take a look at this in the debugger in a bit. 

What exactly were you doing when you got the error? Is it when you click on the train file?

**Comment by leezer3** [comment]
It's not the first time I've seen this reported, but nothing stands out to me.

The error occurs when you click on an item in the listview for either the route or the train files.
This then triggers this method (route):
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/UserInterface/formMain.Start.cs#L158

Or this method (train):
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/UserInterface/formMain.Start.cs#L418

The exception is rather generic, and doesn't tell us anything other than a threading context error occurs. (No inner exception either....)

Only initial at all suspicious thing I can see is that I'm not specifically checking for null on the two backgroundworkers before checking IsBusy(), but I'd expect that to crash with a null reference exception.

There's a possibility that it's crashing inside the background workers, and a little more specific error checking could be added there (I don't know what it'd do if the Result.RouteFile was null for example)
Threading race somewhere?

**Comment by leezer3** [comment]
Found, really sorry for the trouble.

Had accidentally missed out a new file from the configuration which creates the Windows installer, hence why reinstalling 1.5.0.7 made the problem go away for me.

1.5.0.9 has been re-uploaded correctly.
