### ISSUE TITLE
NYCT1 Train Silently Fails to Load on OpenBVE 1.5.0.X

### ISSUE THREAD

**Issue by Sirflankalot** [leezer3/OpenBVE#124]
I've heard a report of the NYCT 1 Train found on bvestation isn't properly loading on the 1.5.0.X version. I have confirmed the problem on the current trunk version of the game on Windows 7 built with MSVC#. 

The loading bar hits 8% before the game stops loading and it goes back to the home screen. 

This happens no matter what train you select. 

I will investigate shortly and post more information.

**Comment by leezer3** [comment]
It's being caused by a bug in the routefile.

Line 15457:
```
SIGNAL ON TRACK 2: 66 V
```
The parser has detected this being a signal declaration,  with the relative path of ```ON TRACK 2: 66 V```and has attempted to combine this with the object folder path.
It then throws an exception because a semi-colon is not a valid path character.

**Comment by leezer3** [comment]
In order to get around this, two potential avenues off the top of my head:
* Wrap every OpenBveApi.Path.Combine in a try/ catch block. Not really a sensible solution, there are '00s of them in the routefile parser alone.
* Change the OpenBveApi.Path.Combine function to not throw an exception. As this mirrors/ extends the System.IO.Path.Combine function, I don't see this as a good idea either.

I suppose a check could be added for malformed lines somewhere in the preprocessor, but you'd almost inevitably end up with a massive list to check through, and that's not really good code either....

**Comment by leezer3** [comment]
OK, better idea.

https://github.com/leezer3/OpenBVE/pull/122

This pull essentially changes every Path.Combine into a wrapper function.
It's designed for loading compatibility objects, but there's no reason why it shouldn't be used to catch the Path.Combine error while we're at it.

Will modify that pull to suit and try and get a bit more if it's implementation done, unless you have any better ideas?

**Comment by leezer3** [comment]
That fixes the breaking issue.
However, the routefile and supplied objects are an absolute, utter mess.

I'm still 135 objects short, despite installing everything in the file (No instructions, a mess in there too...) and having most of the NYCTA stuff installed too.

Looking at some of the textures and file structures, I'm not at all surprised the route has performance issues either, I've discovered the same 256 x 2560 texture repeated in multiple places.
IIRC this *will* be loaded once for each time it's found, and is going to be taking up ~25mb of memory on the GPU.
Absolute worst offender is a 15mb snow texture (.......) I've discovered in the Culver folder, but not sure if that's actually being used here or not.

**Comment by Sirflankalot** [comment]
Yeah a lot of the NYCTA stuff is a complete mess with a decent amount of it dating back ages. I don't think I've ever loaded an NYCTA line without errors or at least warnings. I think if you do put a check in to counteract this, make sure to comment it as a workaround specifically for the NYCTA 1 line so that we hopefully will be able to deal with it later in a less hacky way. I've really got no better ideas that can be implemented in a short time scale. 

As for performance, the new renderer will have an actual resource manager so that these textures shouldn't be that much of an issue (one texture for all uses). 

Holy crap that's a big texture. Any new tooling should have something to downscale textures, but that's something for another discussion.

**Comment by Sirflankalot** [comment]
Question, where were you able to figgure out this information? What methods should I be looking into with the debugger that would be causing this problem?

**Comment by leezer3** [comment]
Short answer is knowing my way around the code base rather too well!

I just set VS to catch all exceptions (Including those from try/ catch blocks), and went digging from that point onwards.
IIRC it was the first actual exception caught when loading the route, but you can always carry on execution.

**Comment by Sirflankalot** [comment]
Haha, that's a good idea. I am currently on linux so I only have sdb which I don't believe has that capability. I'll use that more once when I'm on windows though.

**Comment by leezer3** [comment]
OK, so the compatability manager is merged, and this now works OK at my end.

If it's still broken for you, please let me have a log & I can do some further digging.
Not tested under Linux just at the moment, but I can't see why the fix shouldn't work there too....
