### ISSUE TITLE
Semi-transparent face issue

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#134]
Continued from here:
https://github.com/leezer3/OpenBVE/pull/126

**Current checks:**

- Only smooth transparency mode is affected

- Only happens when RenderFace is called on a dynamic Alpha face immediatly before

- Previous dynamic alpha face must use additive blending

**Comment by leezer3** [comment]
OK, a 'solution' is to simply reset the openGL state to what the renderer expects if the last face was additive.
Renderer.cs, replace at line 303:
```C#
	            bool LastAdditive = false;
                for (int i = 0; i < DynamicAlpha.FaceCount; i++)
                {
                    int r = (int)ObjectManager.Objects[DynamicAlpha.Faces[i].ObjectIndex].Mesh.Faces[DynamicAlpha.Faces[i].FaceIndex].Material;
                    if (ObjectManager.Objects[DynamicAlpha.Faces[i].ObjectIndex].Mesh.Materials[r].BlendMode == World.MeshMaterialBlendMode.Additive)
                    {
                        if (!additive)
                        {
                            UnsetAlphaFunc();
                            additive = true;
                        }
                        RenderFace(ref DynamicAlpha.Faces[i], cx, cy, cz);
	                    LastAdditive = true;
                    }
                    else
                    {
	                    if (LastAdditive)
	                    {
							ResetOpenGlState();
							GL.Enable(EnableCap.Blend); BlendEnabled = true;
							SetAlphaFunc(AlphaFunction.Less, 1.0f);
							GL.DepthMask(false);
		                    LastAdditive = false;
	                    }
                        if (additive)
                        {
                            SetAlphaFunc(AlphaFunction.Less, 1.0f);
                            additive = false;
                        }
                        RenderFace(ref DynamicAlpha.Faces[i], cx, cy, cz);
                    }
                }
```

**Comment by leezer3** [comment]
A little further digging-
Something's a little broken with the emissive states.
Calling a reset on the emissive state works:
```c#
GL.Material(MaterialFace.FrontAndBack, MaterialParameter.Emission, new float[] { 0.0f, 0.0f, 0.0f, 1.0f }); EmissiveEnabled = false;
```

Next attempted to check where the emissive states are handled.
Our issue appears to be triggered from this line here:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/OldCode/Renderer.cs#L605

(Presumably, if a nighttime polygon was provided, the second one of these would also trigger)

Changing the else-if to an else corrects our issue.

Our only access to GL.Material are within these two functions, and once a frame when the GL state is reset.
If the emissive state is changed, but the next face does not require it, it should as far as I can see from the current codepaths be reset automatically.....

Puzzled.

**Comment by leezer3** [comment]
A mildly better hack:
```C#
for (int i = 0; i < DynamicAlpha.FaceCount; i++)
                {
                    int r = (int)ObjectManager.Objects[DynamicAlpha.Faces[i].ObjectIndex].Mesh.Faces[DynamicAlpha.Faces[i].FaceIndex].Material;
                    if (ObjectManager.Objects[DynamicAlpha.Faces[i].ObjectIndex].Mesh.Materials[r].BlendMode == World.MeshMaterialBlendMode.Additive)
                    {
                        if (!additive)
                        {
                            UnsetAlphaFunc();
                            additive = true;
                        }
                        RenderFace(ref DynamicAlpha.Faces[i], cx, cy, cz);
                    }
                    else
                    {
                        if (additive)
                        {
                            SetAlphaFunc(AlphaFunction.Less, 1.0f);
							//HACK: Reset mesh material after using additive blending (Shouldn't be necessary, but there's a bug somewhere, probably in openTK)
							GL.Material(MaterialFace.FrontAndBack, MaterialParameter.Emission, new float[] { 0.0f, 0.0f, 0.0f, 1.0f });
							additive = false;
                        }
                        RenderFace(ref DynamicAlpha.Faces[i], cx, cy, cz);
                    }
                }
```

Don't understand this one though, but that hack is probably the best we're going to get.
Smells of an openTK bug.

**Comment by Sirflankalot** [comment]
I've been a bit busy, I'll take a good look at it tomorrow night (my time). I'll warn you that I've never really done Fixed Function Pipeline stuff so it may take me a little longer than normal. It smells of something to do with the sorting algorithm (all transparent faces have to be sorted), but I won't be sure until I play around with things. In theory combining faces that are on different depth values means that it only uses one of the faces to do the depth comparison as opposed to each on individually. I'll see if I'm able to fix the issue as I would prefer not to implement another hack. 

I don't think OpenTK bugs are that rampant as they really are just forwarding crap to the native OGL interface.

**Comment by leezer3** [comment]
It's no rush.

From what I can see after digging (I don't know too much openGL, but I'm perfectly capable of reading the machine state), it's not the depth check which appears to be at fault, but that the GL.Material state isn't actually being reset from the prior face, even though everything I can see says it is.

Interestingly, it doesn't appear to reproduce on Linux either, which lends weight to it being someone else's bug.
(vmware drivers, I suppose it could be a nVidia bug)

**Comment by Sirflankalot** [comment]
I'm gonna be honest, I completely don't understand this either. This is part of the reason I really want to rewrite the renderer, using the fixed function pipeline requires way too much state for me to be comfortable with. 

For me, with a GTX 760 on native Windows 7 64-bit (Driver Version 368.81) neither of your hacks work. I'm very inclined to think that either this is a problem with Nvidia's drivers (I don't blame them for not supporting FFP stuff, nor are they required to), or some state problem that is technically against the standard, but mesa happily accepts it. I've also tested on Linux (Haswell GT1) and the bug doesn't happen. It's not possible that some feature got deprecated between the 3.3 (my laptop) and the 4.2 (my desktop) standards as ALL of the FFP stuff was removed completely in 3.1. I don't have an AMD card available to test right at this moment. 

It's ultimately up to you, but I say we put your hack in if it works for you, and hope I can write the new renderer fast enough that no one who is affected will really notice that there were visual problems.

**Comment by leezer3** [comment]
Possibly we're somewhere in between an nVidia bug and a piece of undefined behaviour.

The second hack is considerably cleaner, and it's just really a distilled version of the first, when I'd figured out that it was the GL.Material causing it, as opposed to just doing a complete reset of the state.
I'll commit that one and see if anyone else complains for the minute.

Another (essentially unrelated) thing on my sorta list is to detect the graphics card & vendor from the openGL extensions string for implementing system specific performance reccomendations etc.

FWIW:
Windows 8.1 x64, driver version 362.0
I might try updating the drivers, but I generally tend to leave well alone unless something is broken.

**Comment by Sirflankalot** [comment]
Vendor specific optimizations is something that I'll keep in mind when I'm making the new renderer. I don't think it will be much of a problem until we really start beating up GPUs, and we're far from that stage. 

This kind of stuff is hard, with FFP being removed officially from the standard, so I wouldn't be surprised if there are driver bugs.
