### ISSUE TITLE
[Suggestion] Allow train plugin API to lock doors

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#143]
While developing a complex ATP/ATO train plugin and trying to make it as close to real life as possible, I came across this "issue". Most of these systems (if not all of them) lock the doors while the train is in motion to prevent the driver from accidentally opening them, and only unlock them when the train stops between two points defined at stations. So far I have been able to inform the train of the stop position using virtual beacons, but in trains with manual doors nothing prevents them from opening.

I think this feature could become very interesting in some cases (for example, in a route where driving backwards is not allowed, overrunning would force the user to skip the station, like in real life). Would you like to see it? I can add this myself, but I want to know what do you think.

Regards,

**Comment by leezer3** [comment]
Sounds highly reasonable.

You'd probably want two modes (Plugin controlled entirely and plugin overriding driver), but that should be an interesting addition :)

**Comment by MarcRiera** [comment]
I was thinking of a boolean in ElapseData that would lock the doors if true and unlock them (current behaviour) when false. I guess this is what you mean by overriding the driver. What would be the other mode?

**Comment by leezer3** [comment]
Totally plugin controlled- e.g. the plugin can lock the doors in any state.

Your proposed solution (Unless I've not quite understood) wouldn't allow the doors to be locked *open*, but would rather just prevent the driver opening them unless the specified set of conditions were met.

Useful for simulating proper interlocking, and even guard procedures if you want to go that far,

**Comment by MarcRiera** [comment]
Oh, I see what you mean. I hadn't considered the option of locking the doors open, but it sounds great.

Should this lock affect trains with automatic doors as well? I can't come up with a real life example of that particular situation.

**Comment by leezer3** [comment]
I'd say yes, simply because if you're implementing it you might as well do all possibilities at once.
Only immediate thought that might use it I've got is locking the doors open based upon the departure signal state. (e.g. Departure time has been reached, therefore the automatic doors should close, but the signal state is still red, hence doors are locked open. I suspect something like this must happen in some of the newer underground systems with gated platform edges, else a signal delay could cause some havoc)

For that matter, it's inevitable that if you don't add it, someone down the line will think of a use for it, and I speak from experience there....

**Comment by MarcRiera** [comment]
I agree, if we add it people may use it, while if we do not, we are not giving the option to people to experiment and find new uses for the feature. Also, what you mentioned about red signals is true, I had never thought of that possible use.

So far I have managed to get it working, but semi-automatic are being problematic. OpenBVE currently only tries to close doors once (when the departure time is reached), so if there's a lock, it doesn't try to close them again. There's a specific part of the code that keeps trying to close 100% automatic doors and is checked every frame (what we need), but using this for semi-automatic doors prevents the driver from overriding the process.

I'll try to add a flag so that it only happens once, but I'll make sure first that nothing is broken.

**Comment by leezer3** [comment]
Merged this one.

It's also given me a rather good idea:
Plugins should be able to add scores too, so that if we trigger a safety intervention, this is actually reflected in the after-game review.
Will try and implement this next week sometime, I've been rather wound up in the joystick code for openTK recently....

**Comment by leezer3** [comment]
Score added here:
https://github.com/leezer3/OpenBVE/commit/1c2d07763b3246010090bf31f88be47e914b7f95

I'll try and re-roll BVEC_ATS so that it logs all EB interventions as scores sometime this week as an example.

**Comment by MarcRiera** [comment]
I was thinking today, someone may want to take the door interlocking feature further and having only two states (locked and unlocked) may not be enough. Adding two additional states (one for each side) to have a total of four (fully unlocked, left unlocked, right unlocked and fully locked) shouldn't be hard.

Opinion?

**Comment by leezer3** [comment]
Seems reasonable, but I'm a little wary of overcomplicating things...

If you really wanted to go overboard, real railways allow independent locking on a per door basis :P

Adding a failure mode (Automatic doors not working, so must be done manually??) is also something that might be interesting, but I think probably out of scope.

**Comment by MarcRiera** [comment]
Of course, that's how real trains sometimes lock specific doors (the LU Northern Line is a good example, some stations have shorter platforms). However, I think it is unnecessary to have this level of detail in OpenBVE, as it's used in very specific situations.

I think locking doors only on one side will be useful to prevent opening the doors on the wrong side (most if not all ATP-equipped trains can do this in real life). A failure mode sounds interesting too, but it affects existing content directly in a way different to what the developers initially expected. Maybe we could add it to the list of possible features to add once the train format is redesigned?

**Comment by leezer3** [comment]
Merged.

I completely agree that this sort of thing is for the new train format primarily, it's just a matter of adding the plumbing on each bit as we add it.
Working on that is high on my list of stuff to do *soon* , but I think it'll probably the feature for 1.6.0, as 1.5.0 has mostly been about getting the port done and the package system into place and working :)

**Comment by leezer3** [comment]
Hmm, something seems to have got confused in the conditionals in your last commit.

I've changed the function a little here, which appears to fix things:
https://github.com/leezer3/OpenBVE/commit/d9159ed966a0128faa80f562478ce6df3494be31

Seemed a little easier & clearer to just __switch__ on the interlock state and then have the single set of conditionals for each.

**Comment by MarcRiera** [comment]
Oops, sorry for that, I didn't test the commit enough and missed it. Thank you, now everything is clearer.
