### ISSUE TITLE
[Possible solution] Joystick in WinForm

### ISSUE THREAD

**Issue by JakubVanek** [leezer3/OpenBVE#16]
I posted a possible solution on following thread, sadly it's waiting for moderation: http://forums.uktrainsim.com/viewtopic.php?f=66&t=143351&st=0&sk=t&sd=a&start=30

**Comment by JakubVanek** [comment]
In short from what I remember: we must call Toolkit.Init(), because it calls equivalent of SDL_Init(SDL_INIT_VIDEO), which sets up SDL event loop. Then we must enable [SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS](https://wiki.libsdl.org/SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS) by P/Invoking SDL_SetHint. We must then provide our own checking if the WinForm is focused. We must disable this hint when we start the GameWindow part.

**Comment by leezer3** [comment]
Whilst that sounds relatively reasonable, would it be better actually doing that inside the OpenTK source and submitting a pull request to them?
That keeps P/Invoke well out of it, and IMHO doing that on a system lib out of our control isn't the most clever of ideas. If it works now, that's good, but if the interface changes, then that may break us in the future.

Would seem to me that the logical place to do this would be in the base OpenTK SDL2 joystick init function- 
https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/SDL2/Sdl2JoystickDriver.cs#L77

That keeps things clean on this side, and enhances the OpenTK joystick driver to boot.
I'm sure this isn't the first time this has come up, although whether it's been discarded is another kettle of fish entirely.

I'll try and knock-up and test an OpenTK build with this change later today or tomorrow evening.

**Comment by JakubVanek** [comment]
OK, thanks, but if I understand it correctly this will require some new functions/properties for enabling and disabling it. GameWindow's Joysticks potentially rely on that it will not catch events from background (LegacyJoystickDriver is just a proxy to the new joystick system), and indirectly there's a dependency on it as when it OpenTK runs on SDL, GameWindow is a SDL window (which controls if SDL will catch the joystick event).

**Comment by leezer3** [comment]
From reading the SDL2 page, that suggests that this is only for joystick/ gamepad events, so this would actually make the behaviour match with the other OpenTK platforms.

In some ways, I suppose that to get a pull accepted to OpenTK, it'd probably want the full set of SDL hints, and an interface to them.

**Comment by leezer3** [comment]
OK, so I've done a brief bit of hacking with OpenTK. 
My code is a horrible mess, but if you're interested, I can upload a sample repository for you to look at.

I set the hint just fine when the joystick driver inits, and the hint works as expected, but only if a GameWindow is open.
Need to do some more digging on exactly what's happening inside OpenTK- I *suspect* that that it's only setting a SDL2 window handle when the gamewindow opens.

Thus, if we were to implement this, I *think* we'd need to first set the SDL2 window handle to our main form, then set the hint.
Finally, clear all hints on init of the gamewindow.

**Comment by leezer3** [comment]
Futher notes:
OpenTK calls Toolkit.Init() by itself as soon as the first OpenTK function is called. When running on a SDL2 backend, this would appear to simply call SDL_INIT
This then enumerates the joysticks & displays available and lists them, but does not call SDL_INIT_VIDEO or SDL_INIT_JOYSTICK

As far as I can tell, SDL_INIT_VIDEO & SDL_INIT_JOYSTICK are called when a gamewindow is opened, and not before, which is largely logical, except in this edge case.

We *may* get away with P/Invoking SDL_INIT_JOYSTICK, as no specific SDL2 window is created until the gamewindow is.
