### ISSUE TITLE
Race condition when switching to full screen

### ISSUE THREAD

**Issue by City-busz** [leezer3/OpenBVE#174]
Many times when I switch the window to full screen with `Ctrl+F`, I get an error message dialog even if the window is successfully switched to full screen. So this condition fails when it shouldn't:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Graphics/Screen.cs#L89

When I put `System.Threading.Thread.Sleep(1000)` before this line, I never get the error message dialog, so there is apparently a race condition.

**Comment by leezer3** [comment]
This smells related:
https://github.com/opentk/opentk/issues/616

I don't think anything above that line should be blocking, except possibly the call to unload all textures. (Why?? Will have to check that)

The only other thing off the top of my head is that the renderer could be sticking somewhere if the switch is triggered mid-frame.
 I suppose a lock could be added

**Comment by City-busz** [comment]
Probably it's related to the bug in OpenTK that you mentioned. But a small delay fixes the problem for me, so I created a PR.
