### ISSUE TITLE
Freeze when closing

### ISSUE THREAD

**Issue by stemy2** [leezer3/OpenBVE#182]
Hello,

The game freezes when i try to close the main menu.

**Comment by JonnyTech** [comment]
Which build? Which operating system? What steps are required to reproduce?

**Comment by stemy2** [comment]
Version: 1.5.1.6
OS: Ubuntu
Steps: In the main menu, clck on the close button.

**Comment by JonnyTech** [comment]
Which build of Ubuntu - 15, 16, 17? Is it 32bit or 64 bit? Which version of mono is it running with? What graphics card is in use. What do you get in the terminal console if you start it from there - please post the whole output from when you start the application. It is difficult to diagnose with the very limited information and lack of logs that you are providing. I am running with Linux without issue so must be something specific to your system.

**Comment by MarcRiera** [comment]
I can recreate this in my computer running v.1.5.567.1302-travis under Arch Linux (64 bits), Mono 5.0.0 and two graphics cards (Intel HD 530 and Nvidia GeForce 940MX, same problem on both).

No error messages are shown in the terminal and OpenBVE generates no logs. It looks like the window is not getting disposed of correctly and gets stuck.

**Comment by leezer3** [comment]
Hmm, if the window is getting stuck with no errors, a call to
Application.DoEvents() in the close method for the window in question tends
to sort it.....

Does it also hang around when launching the game or just when hitting Close?

**Comment by MarcRiera** [comment]
The window disappears when starting a route, but when OpenBVE is closed from the in-game menu, even if there are no windows, it still fails to properly quit (the terminal command doesn't finish unless Ctrl+C is used to kill OpenBVE).

**Comment by leezer3** [comment]
I can't reproduce this on a small collection of Ubuntu VMs (14.04 to 16.04)

I've added the Application.DoEvents() call I mentioned though, so see if today's build helps.

If not, I'll try rolling an Arch VM and see where that gets us. Might be a Mono regression though (And I don't fancy chasing that.....)

**Comment by stemy2** [comment]
Problem solved, i click on the «close» button situed above.
