### ISSUE TITLE
ATS.dll fails to load on Linux / Ubuntu

### ISSUE THREAD

**Issue by nekromoff** [leezer3/OpenBVE#192]
Different types of ATS DLL extensions fail to on Linux making the system unusable (i.e. textures completely missing and other stuff happening making screen mostly black with  just few objects loaded)

This happens for multiple unrelated routes with trains that have ATS DLL extensions.

**Comment by v1993** [comment]
ATS.dll is not C#, but compiled for windows, as I know.

**Comment by leezer3** [comment]
Something is funny here.

Its expected that most ATS files fail to load under Linux, as they're Windows specific.
Generally speaking though this should only make trains function a little differently.

A totally black screen or missing textures sounds more like you've not installed something properly.

Can we see some screenshots and a log from a broken combination please?

**Comment by nekromoff** [comment]
Sure, where is log located?

**Comment by nekromoff** [comment]
![obrazok](https://user-images.githubusercontent.com/8550349/31054132-35ba031c-a6ac-11e7-8b21-d1d1b185872c.png)

**Comment by leezer3** [comment]
From that, I'd be almost certain your objects are in the wrong place.

Logs may be accessed from the link 'Report Problem' in the bottom left of the main menu.

**Comment by nekromoff** [comment]
OK, thanks. Based on the log it seems that the route downloaded is not compatible for Linux as it has the folder names confused and disregards Linux differentiating between uppercase and lowecase.

**Comment by leezer3** [comment]
Mismatched case in folder & file names should be handled automatically by the API.

The only (absolute edge) case I can think of which might not be handled is if you have the same folder *twice*, but with differently cased names.

I'll try some testing in a VM when I get back from work, but it still sounds like something is misplaced :/

**Comment by nekromoff** [comment]
Well, no, it doesn't work. After changing first letter to capitalized it
loads OK.

**Comment by JonnyTech** [comment]
@leezer3 what are us Linux users missing out by not being able to utilise ATL.DLL?

**Comment by leezer3** [comment]
Train plugins.

Some use these to simulate (e.g.)  safety systems such as British AWS/ TPWS, but you can also do a degree of traction modelling through the plugin interface.
See the Western, Manor and 81xx from BVE Cornwall for cross-platfom examples of what can be done with train plugins :)

**Comment by JonnyTech** [comment]
I see, will train plugin ever be possible with Linux?

**Comment by JakubVanek** [comment]
Hmmm, it might be possible to implement a plugin proxy through Wine, either
by launching standalone Wine with a Win32 plugin server, or by integrating
Wine by means of P/Invoke into some Unix-only plugin.

Dne 1. 10. 2017 5:00 PM napsal uživatel "JonnyTech" <
notifications@github.com>:
