### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by nekromoff** [leezer3/OpenBVE#193]
OpenBVE would enjoy some kind of package management rather than current messy state of downloading routes and trains separately.

Is there something like this planned? I see "package management" button in the latest version, but that just crashes the whole program and moreover, no further info or help is provided on what kind of package is expected. Is it .7z, is it a .zip?

**Comment by leezer3** [comment]
Doesn't crash here on Windows, but will again try and reproduce when I'm back from work :(
Linux and Mac were both tested when this was implemented, but I dont use them on a day to day basis......

This creates an archive which contains a couple of custom metadata files.
Theae are then extracted to the location set in Options.

**Comment by nekromoff** [comment]
![obrazok](https://user-images.githubusercontent.com/8550349/31055786-71305e98-a6c8-11e7-8b6a-f342a0f5bac8.png)
Unhandled Windows Forms Exception

**Comment by leezer3** [comment]
OK, issue found.

This was caused by opening a file which the build of SharpCompress we're using didn't recognize.
This threw an exception which wasn't handled.

Have now pushed 1.5.2.1, which fixes this issue.

**Comment by nekromoff** [comment]
Still crashes in 1.5.2.1. Tried to install 
http://www.bvecornwall.co.uk/downloads/plymdem1700.zip

Same Unhandled forms exception.

**Comment by leezer3** [comment]
Hmm, must be a different issue to the one I found, as i can't reproduce now...

Has it generated a crash log at all?
In theory it should do so when the error message occurs
