### ISSUE TITLE
Link to official DEB file is broken

### ISSUE THREAD

**Issue by nekromoff** [leezer3/OpenBVE#194]
Clicking on "Check for updates" takes me to:
http://openbve-project.net/intro/V1.5.1.6/

going to Downloads this link is broken for DEB distributions:
https://vps.bvecornwall.co.uk/OpenBVE/Stable/openBVE-1.5.2.0.deb

**Comment by leezer3** [comment]
Fixed with 1.5.2.1

TLDR:
Travis seems to have decided to stop installing fakeroot by default when I wasn't looking.....

**Comment by nekromoff** [comment]
thanks for both fixes!
