### ISSUE TITLE
Reading .flac as a Audio File

### ISSUE THREAD

**Issue by Dragon951** [leezer3/OpenBVE#206]
Hello,

Hello, i actually use the Program to develop routes and i have a question, when i install an .flac format audio file, why does an error pop up saying it will be read as an .wav instead, im pretty sure this may be a easy fix but if possible can this be fixed so these errors dont come back???

**Comment by leezer3** [comment]
OK, try this build:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2017-11-22.zip

I've had to port the plugin interface across to Route Viewer, but it should now load FLAC sounds.

(Note: FLACs have always worked in the main program, just not Route Viewer)
