### ISSUE TITLE
Small issue with Train Signs

### ISSUE THREAD

**Issue by XxchapoxX** [leezer3/OpenBVE#208]
The trains and routes load correctly and have no issues. However, the rollsigns are present but a grey box covers the signs and aren't able to be seen. Does this have something to do with the animated file? Any help would be much appreciated!
![untitled1](https://user-images.githubusercontent.com/34703076/34193434-b65f3a4c-e521-11e7-9dd0-c01fb567d101.png)
![untitled](https://user-images.githubusercontent.com/34703076/34193435-b6687562-e521-11e7-9765-3f81f5ee1231.png)

**Comment by leezer3** [comment]
Which exact train and route combo are you trying to run?

I've tried a few of the NYCTA trains, and the rollsign appears to work OK in those, which suggests it's either a train or a route specific issue (Possibly the combination...)

**Comment by Dragon951** [comment]
Well i can tell you this, 

I use The IRT 1 Line That I've Developed With the R142A HD that is released & im getting the same issue as above (Roll-signs Disappearing)

IF you Can look into This

Thanks
NYC-T-Driver
IRT 1 Line Developer

**Comment by leezer3** [comment]
I believe this should fix things:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2017-12-24.zip

Several different issues at play here, so please test and report back :)

**Comment by Dragon951** [comment]
hello,

This issue has returned in the newest version 1.5.3.1
