### ISSUE TITLE
joystick in v1.5.3

### ISSUE THREAD

**Issue by oddpodlbkk** [leezer3/OpenBVE#211]
joystick does not control train in the game, but in the settings, it says the joystick is connected and working(and yes, it is mapped to certain controls).

https://youtu.be/SpXXUaRnpjA

**Comment by mdiamond14** [comment]
I have the same exact issue as well

Max

**Comment by oddpodlbkk** [comment]
I can use an older version, but then I cant use it in full screen

**Comment by oddpodlbkk** [comment]
Yes but i am missing alot of textures, mainly the objects below the tracks and the tracks

**Comment by leezer3** [comment]
That's really odd...
Screenshot and a route link please?

**Comment by oddpodlbkk** [comment]
http://openbveconnect.com//index.php?action=downloads;sa=view;down=108
https://bvestation.com/download/122

**Comment by oddpodlbkk** [comment]
https://youtu.be/mSbVNUoy1G4

**Comment by leezer3** [comment]
I'm assuming you're referring to the effect seen in the bottom left of this screenshot from your video?
![bug](https://user-images.githubusercontent.com/7688245/34631790-fec6a00e-f269-11e7-9746-544fa088fa49.jpg)

Which should look like this?
![bug2](https://user-images.githubusercontent.com/7688245/34631825-2f32a3e6-f26a-11e7-8f63-db52b700cbc2.jpg)

I can't reproduce this, looks totally normal on my two standard test machines.
It looks like something isn't working quite right in the lighting/ fog effects, but that's only a guess.

Things to check:
* Your viewing distance is set to 600m or greater
* You're using the Smooth transparency mode
* You're on the latest graphics card drivers.
* Try enabling / disabling AA & AF

The graphics card drivers are IMHO the most likely culprit here, but without being able to reproduce this, I'm a little stuck.

**Comment by oddpodlbkk** [comment]
Viewing Distance - 800
Transparency - Sharp
AA - 4 AF - disabled
graphics drivers are latest.

**Comment by oddpodlbkk** [comment]
i do have an idea that might work, what is the file(s) that are in charge of mapping the joystick to the game

**Comment by leezer3** [comment]
That won't work :)
(It's not the mapping, rather a call in the wrong place)

Can I ask what graphics card you've got please?
Need to try and find something I can reproduce this on.

**Comment by oddpodlbkk** [comment]
radeon RX480

**Comment by oddpodlbkk** [comment]
if you can make 1.5.0.9 work in full screen for me that would be fine

**Comment by oddpodlbkk** [comment]
any ideas?

**Comment by leezer3** [comment]
I have nothing specific to give you, sorry.....
I can't reproduce this on my end, which leaves me a little stuck.

It's *probably* an AMD driver bug, in which case playing around with driver versions may get you results.
Specifically, if you're on the absolute latest, I'd try going back a couple of versions as this has a known issue with older stuff:
http://www.pcgamer.com/amd-vows-to-fix-adrenalin-driver-bug-affecting-some-directx-9-games/

**Comment by leezer3** [comment]
Odd thought:
Have you tried Route Viewer, and does it exhibit the same issues?

**Comment by oddpodlbkk** [comment]
I’ll look into that

**Comment by oddpodlbkk** [comment]
Doesn’t have that issue on route viewer

**Comment by oddpodlbkk** [comment]
https://youtu.be/vlWlErJPM3M
