### ISSUE TITLE
Freeze on exit

### ISSUE THREAD

**Issue by City-busz** [leezer3/OpenBVE#213]
When I try to close the OpenBVE's main window with the close button, it just freezes instead of exit from the application. I can close it with Ctrl+C on command line, but anything else don't work. The result is the same when I build it from the sources and when I use the prebuilt archive. I also tested some earlier versions with the same results.

Distribution: Arch Linux

Package versions:
- mono 5.0.0.100-2 and 5.4.1.7-2
- libgdiplus 5.6-1
- openal 1.18.2-1
- openbve 1.5.3.0-1

Locale: LANG=hu_HU.utf8

**Comment by leezer3** [comment]
Going from past experience, the probable fix is going to be to add an Application.DoEvents() call to the method that the button calls.

Will try and roll an Arch VM tomorrow and take a closer look; I'm sure the form closes alright on Debian though :/

**Comment by leezer3** [comment]
Closes OK for me using XFCE, which suggests a desktop / WM issue.

I note the hack I mentioned is already in place:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/UserInterface/formMain.cs#L1353

**Comment by City-busz** [comment]
Thanks for testing this.

I experience the same problem in desktop environments where I tested: GNOME Flashback (Metacity), MATE (Marco), LXDE (Openbox).

Some details:
- When I click on the close button on the window decorator, the form freezes.
- When I click on the "Close” button on the bottom left corner of the form, the window disappears, but the 'openbve' process still running in the background.
- When I start a route and try to exit from the simulation, the window closes, but the 'openbve' process still running in the background.

**Comment by leezer3** [comment]
Interesting.

I can reproduce using the button in the top-left. Let me do some digging.

**Comment by leezer3** [comment]
Try the branch here:
https://github.com/leezer3/OpenBVE/pull/214

This explicitly issues an Environment.Exit(0) call after any close request. This appears to get rid of the hanging around issue with no effects I can see on the Arch VM.

I don't think this should do any harm, as all de-initialisation should have been done by this point, but needs more testing on other combos before I merge into mainline.
I think it's really a Mono bug mind, but I don't want to try and chase whatever is locking.

**Comment by City-busz** [comment]
I tried the patch, and I'm able to exit the form, but when I try to start a game, the program exit instead of starting it.

**Comment by leezer3** [comment]
Ah, oops....

Pushed another commit, which I think clears things up, although I've had to hack around the closing logic quite a bit, which I'm  not happy with at all.

**Comment by City-busz** [comment]
Thanks! The patch is better now, but still incomplete.

I can exit from the main form with the "Close" button or by closing the window. But I still can't exit from the game window neither via menu or by closing the window (the openbve process remains running in the background).

**Comment by City-busz** [comment]
But now I'm able to exit from the game window via menu. I don't know what happened I tried it multiple times and it works now.

So the remaining problem is when I try to close the game window with the close button on top right (in windowed mode, not in full screen).

**Comment by leezer3** [comment]
That makes reasonable sense.

Not in front of the code, but the other two cases call a specific closure method.
Probably need to override the openTK window closing event to add the Environment.Exit(0) call at the end of it.

Note thst closing via the game menu now complains about openAL not being cleaned up on Debian, but that's I think harmless.

**Comment by City-busz** [comment]
Now I found why I was unable to exit from the game window via menu. Here is the test case:
1. Start a game.
2. Exit to the main menu.
3. Start another game.
4. Now try to exit from the game via menu, and the openbve process remains running in the background.

I can see the openAL error message at the end of the game on Arch Linux too.

**Comment by leezer3** [comment]
Latest commit fixes the first case, but not the second.

Need to investigate that one a little, but it's edge-case enough for me to not be too worried.

Something seems to have broken the recently used route listing though when doing this, which is marginally interesting, so possibly we're locking on an open file somewhere.

**Comment by leezer3** [comment]
Another interesting datapoint is that under Ubuntu 15.04 (Floating around in my VM stack), the window originally closed just fine without any hacks.

This now adds the openAL error mentioned above :/

**Comment by leezer3** [comment]
```
AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe
AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe
AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe
AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe
AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe
AL lib: (EE) ALCplaybackAlsa_mixerProc: available update failed: Broken pipe
```

So, I've got the errors above constantly spamming in console if I attempt to restart from in-game on Arch, when the loading process gets to 100% (and presumably it attempts to trigger a sound).
Your freeze is probably related. 

At this point, I'd suspect an Arch bug as opposed to an openBVE one. From the log above, I'd say it probably lies somewhere in the audio stack or openAL, but that's rather above my pay grade.

**Comment by City-busz** [comment]
> AL lib: (EE) ALCplaybackAlsa_mixerProc: mmap commit error: Broken pipe

I don't see these error messages on Arch Linux.

I think this bug is unrelated to openAL, because it happens even on the main form when no game is loaded yet. Even if I remove the openAL library from the system, I'm able to start the main form and reproduce the freeze on exit when the patch is not applied.
