### ISSUE TITLE
Inconsistancy between BVE2, BVE4 and openBVE

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#217]
Take the following code:
```
.wall 0;L;8
```
This produces the following results:
### BVE2:
Wall 8 placed to the left side of Track 0
### BVE4:
Ignored (L is no longer valid)
### openBVE:
Wall 8 placed to both sides of Track 0

The same issue also appears to be present with the .Pole command, and presumably the .Dike command (Not found any examples of this in the wild at the minute)

Domodossola_Trontano.csv, http://bve.altervista.org/ssif.html

As we have no way to detect whether a file was written for BVE2 or BVE4, the *probable* solution will be to use the BVE2 behaviour, but leaving this one for a bit more testing / consideration before patching.

**Comment by leezer3** [comment]
Current build changes to recognise L and R as valid directions for walls/ dikes.

I can't see any reason for anyone to have used this behaviour deliberately, as it would always have been broken entirely in BVE4, and spammed an error message in openBVE.

**Comment by leezer3** [comment]
And another one:
```
.background 5
```

## BVE2
Background 5 is set

## BVE4
Command is ignored

## openBVE
Command is ignored

**Comment by Sirflankalot** [comment]
I would encourage them to be documents as fallback. I personally feel that having the docs describe the behavior of the program is better. Put a disclaimer not to use it, but have it there for transparencies sake.

**Comment by leezer3** [comment]
I don't normally disagree with that, but in this case there are too many 'versions' of the program floating around.
Its hard enough to to add new stuff without adding potentially broken older commands into the mix.

They're noted in the errata notes, and I think this is probably the best place for them at the minute.
