### ISSUE TITLE
crashing on loading

### ISSUE THREAD

**Issue by oddpodlbkk** [leezer3/OpenBVE#220]
every time I load the game, I load, then immediately crashes.

**Comment by leezer3** [comment]
Can I have some logs please?

Bottom left of the main menu: Report Problem
The crash log (hopefully) says what happened to make it crash, and the main log will let me take a look into what the route is doing.

**Comment by oddpodlbkk** [comment]
[log.txt](https://github.com/leezer3/OpenBVE/files/1721730/log.txt)
[OpenBVE Crash- 2018.2.13[16.16].log](https://github.com/leezer3/OpenBVE/files/1721732/OpenBVE.Crash-.2018.2.13.16.16.log)

**Comment by leezer3** [comment]
Hmm....
It's crashing somewhere in the depths of this function:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/System/MainLoop.cs#L151

This is the root function which polls the keyboard and joystick input.
It feels very much joystick related, but I can't see any immediate issues here.
Joystick input appears to work OK from a very brief test too....

I'll try and investigate properly tomorrow, but if it's joystick related, unplugging it temporarily will likely make things work with the keyboard.

It'd be useful to know if you've got multiple joysticks connected, or if your joystick is something unusual :)

**Comment by oddpodlbkk** [comment]
well i wasn't using the joystick but when I pluged it in, it worked

**Comment by leezer3** [comment]
I've tried a couple of boxes, and I can't reproduce this one at all.

My best guess is that something funny is going on with your specific joystick, perhaps it's showing up internally when it's not plugged in or something?
Regardless, this build makes some changes which *may* help:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-02-14.zip
