### ISSUE TITLE
$Sub broken in certain cases

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#221]
Consider the following command sequence [Declared in the __With Texture__ section] :
```
$Sub(48)=

   25,Track.Announce JRTozai\Kyobashi0.wav
  100,Track.Announce JRTozai\KyobashiPoint.wav
  2$Rnd(50;99),Track.Announce JRTozai\Kyobashi2.wav
  7$Rnd(50;99),,Track.Announce JRTozai\Kyobashi3.wav
 1$Rnd(150;225),Track.Announce JRTozai\Kitazume2.wav
 20$Rnd(0;5)0,Track.Announce JRTozai\Kitazume3.wav
 25$Rnd(0;5)0,Track.Announce JRTozai\Temmangu2.wav
 33$Rnd(5;9)0,Track.Announce JRTozai\Temmangu3.wav
 3675,Track.Announce JRTozai\Kitashinchi0.wav
 4000,Track.Announce JRTozai\Kitashinchi2.wav
 4475,Track.Announce JRTozai\ShinfukushimaPoint.wav


 $Sub(0)=0
```

This is somehow breaking, and causes all commands to be ignored.

Thoughts:
* Removing some of the trailing lines causes parts of the route to work. Probably related to distance somehow.
* Removing the Track. parts of the command or substituting a constant number does not change this behaviour.
* Moving the $Sub into the __With Track__ section causes it to work correctly

**Comment by Sirflankalot** [comment]
Is the expected behavior of this to set $Sub(48) to nothing?

**Comment by leezer3** [comment]
I get the nasty suspicion that BVE4 probably inserts the whole lump into $Sub(48)

Running up a test route for this is on my list of things to get round to, but BVE4 only works on my laptop....

**Comment by Sirflankalot** [comment]
Oi, for real? That's not expected at all.

Unrelated, but where do you get the various BVE versions?

**Comment by leezer3** [comment]
I won't guarantee it without testing it under BVE4, but it's a strong suspicion based upon years of experience of the utter mess it sometimes accepts as valid code.....

Other BVE versions are here:
http://bvets.net/old/

Getting them to run is another different ball-game entirely. They rely on the Visual Basic Retained Mode for DirectX, which isn't available on anything above XP.
You can copy in the VBRM dll files as per these instructions:
https://www.railforums.co.uk/threads/how-to-run-bve4-under-windows-vista-x86-and-x64-and-windows-7.13429/

Assuming that works, getting a video driver that actually functions is a crapshoot too.
I don't think there's been a working nVidia driver for years, ATI Catalysts IIRC stopped at something like v13, but oddly enough Intel integrated graphics still seem to be OK. (Ivy Bridge, don't have the number off the top of my head)
IIRC the vmware virtual driver doesn't like it either.

**Comment by leezer3** [comment]
I won't guarantee it without testing it under BVE4, but it's a strong suspicion based upon years of experience of the utter mess it sometimes accepts as valid code.....

Other BVE versions are here:
http://bvets.net/old/

Getting them to run is another different ball-game entirely. They rely on the Visual Basic Retained Mode for DirectX, which isn't available on anything above XP.
You can copy in the VBRM dll files as per these instructions:
https://www.railforums.co.uk/threads/how-to-run-bve4-under-windows-vista-x86-and-x64-and-windows-7.13429/

Assuming that works, getting a video driver that actually functions is a crapshoot too.
I don't think there's been a working nVidia driver for years, ATI Catalysts IIRC stopped at something like v13, but oddly enough Intel integrated graphics still seem to be OK. (Ivy Bridge, don't have the number off the top of my head)
IIRC the vmware virtual driver doesn't like it either.

**Comment by leezer3** [comment]
Having done some digging, the bug is rather wider than I thought.

It's occuring whenever an expression consisting of a single number is found outside the track namespace, e.g.
```
With Texture
25,

With Texture
25, .Track.Announce Test\Test.wav

With Texture
	.Load(OdakyufanAtsTestRoute\Background.png)
	.Aspect(1),25,
```
All of those are broken.

I'm actually somewhat surprised this is the first we've seen of this bug, but there we go.

The branch above goes some way to fixing this issue, by ignoring the offending numbers.
Unfortunately, in the case of the code block above, it dumps all the code in question at position zero.
