### ISSUE TITLE
Multi-Column Objects

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#223]
[FBR.zip](https://github.com/leezer3/OpenBVE/files/1747866/FBR.zip)

I've never seen an object like this one before....

BVE2 structure viewer loads it OK:
![bve2stv](https://user-images.githubusercontent.com/7688245/36539280-316e6530-17ce-11e8-8002-2160ce67a722.jpg)

openBVE is not liking it at all:
![obvestv](https://user-images.githubusercontent.com/7688245/36539330-5dd4a0ee-17ce-11e8-85d1-efb63b663130.jpg)

I'm not surprised at all by this (example section):
```CreateMeshBuilder,,,,,,CreateMeshBuilder,,,,
AddVertex,6.8,-0.38,25.4,,,AddVertex,6.8,-0.38,25.4,
AddVertex,6.8,-0.38,0,,,AddVertex,6.8,-0.38,0,
AddVertex,2,-0.38,0,,,AddVertex,2,-0.38,0,
AddVertex,2,-0.38,25.4,,,AddVertex,2,-0.38,25.4,
AddFace,0,1,2,3,,AddFace,0,1,2,3
GenerateNormals,,,,,,GenerateNormals,,,,

LoadTexture,FB2.bmp,,,,,LoadTexture,FB2.bmp,,,
SetTextureCoordinates,0,0,5,,,SetTextureCoordinates,0,0,5,
SetTextureCoordinates,1,0,0,,,SetTextureCoordinates,1,0,0,
SetTextureCoordinates,2,1,0,,,SetTextureCoordinates,2,1,0,
SetTextureCoordinates,3,1,5,,,SetTextureCoordinates,3,1,5,
SetDecalTransparentColor,0,0,0,,,SetDecalTransparentColor,0,0,0,```
```

Opening the file with Excel shows us that the first 320 lines of the object have been built in 'two-column' format.

Thinking about it, but I've got no sensible ideas about how to handle this.
Routefile comment:
```
愛知環状鉄道線
高蔵寺-新豊田
２両
ATS-S
ver2.00
（C）2004 Otti
```
A bunch of the files from here share the same issues, which means I can't just implement an object specific hack.
A 'proper' fix for this one will probably be a massive PITA too......

**Comment by Sirflankalot** [comment]
That's....mean.

You might be able to find a fix if you count the amount of args then split, but that has the problem of people putting comments after the end of a command. ex:

```
AddVertex,6.9,-0.38,25.4,,, I like writing comments weird.
```

**Comment by leezer3** [comment]
Oh, I know!

I'm deliberately going through my collection of obscure junk though, it finds all sorts of interesting tidbits (Note the errata thread earlier)
Best solution I can even semi-come up with is to detect this by counting the number of meshbuilder / addvertex statements in a line & assuming that if these are found a couple of times we need to split.
Michelle adding the normals as extra parameters didn't help though, if they'd been left as a separate array as per just about every other 3D format, this would be much simpler. (And for that matter sort out a bunch of the hacky crap I've omplemented for other stuff.....

**Comment by Sirflankalot** [comment]
I have pipe dreams of dumping the formats involved and moving to a new format that has more sane properties, but that will REQUIRE an automatic converter and that won't happen at least until libparsers is mature enough... not to mention complimenting a new parser. 

> Best solution I can even semi-come up with is to detect this by counting the number of meshbuilder / addvertex statements in a line & assuming that if these are found a couple of times we need to split.

That is really sketch, I agree is the best _solution_ but...eh.

**Comment by leezer3** [comment]
Patched.

For reference, this is permanently enabled in Object Viewer / Route Viewer, and hidden behind the BVETS Hacks option for the main program.
Shouldn't cause any issues, but I really don't want to encourage multi-column stuff......

**Comment by Sirflankalot** [comment]
What solution did you end up using? 
---
Connor Fitzgerald

**Comment by leezer3** [comment]
Ran up a small function to find the second CSV command index in a string +
loop.
Not mega pretty, but reasonable enough.
