### ISSUE TITLE
Object Loading

### ISSUE THREAD

**Issue by Dragon951** [leezer3/OpenBVE#224]
Hello,

My Name is NYC-T-Driver,

Im currently working on a new route of mine and i seem to be having an issue,

Apparently there is a Slight 2-3 second pause when a certain object loads and i wanted to see what could be causing this issue,

Object is Broadway Bridge from the IRT 1 Line

**Comment by Sirflankalot** [comment]
Could you provide the route for us to test?

**Comment by Dragon951** [comment]
[Test File.zip](https://github.com/leezer3/OpenBVE/files/1754738/Test.File.zip)

Here is the test file, which contains the 1-3 second freeze when the object loads up, (note that this is not the official line, just a test file)

**Comment by leezer3** [comment]
With that number of textures, I'm not at all surprised it freezes- 828 of them for a single object.

There appear to actually only be 2 unique textures, so this version should be considerably faster to load:
[Broadway Bridge.zip](https://github.com/leezer3/OpenBVE/files/1758725/Broadway.Bridge.zip)

The mesh could do with optimizing too, but not a lot we can do about that without the original 3D file.

**Comment by Dragon951** [comment]
I have the original 3D file actually, would that help with optimizing it

**Comment by Dragon951** [comment]
This Resolved the Issue, Thank You, the bridge loads much better now, no more pauses in loading
