### ISSUE TITLE
Issue with Specifying Normals

### ISSUE THREAD

**Issue by wizdagamer** [leezer3/OpenBVE#225]
I am working on a new vintage subway car, and the roof is very curvy. I wanted to use the normal commands  (AddVertex, vX, vY, vZ, nX, nY, nZ) to make it seem curvy instead of jagged. But when I would put the numbers down it say like nY any number I put would make it go at a 90 degree angle up. No matter what number I put it will do it. I have no idea why or what to do. Here is my code and my issue: 

Before:
![image](https://user-images.githubusercontent.com/8211934/36639549-f7d69764-19dc-11e8-97af-171b2a10f93d.png)

![image](https://user-images.githubusercontent.com/8211934/36639550-fc08b75e-19dc-11e8-8df4-3258e7d0ff0c.png)

After:
![image](https://user-images.githubusercontent.com/8211934/36639542-bf4fb72c-19dc-11e8-87be-e370b581a4d8.png)
![image](https://user-images.githubusercontent.com/8211934/36639545-c99f7816-19dc-11e8-91b3-b1722810e971.png)

![image](https://user-images.githubusercontent.com/8211934/36639663-a61f334c-19df-11e8-9d05-e494979898d4.png)
![image](https://user-images.githubusercontent.com/8211934/36639662-a23d7edc-19df-11e8-8438-55e289c9ae6b.png)

![image](https://user-images.githubusercontent.com/8211934/36639614-706bbea6-19de-11e8-8c95-b8e41bf748e9.png)
![image](https://user-images.githubusercontent.com/8211934/36639616-76473efe-19de-11e8-9ced-3686561c955e.png)

![image](https://user-images.githubusercontent.com/8211934/36639681-3ce76754-19e0-11e8-8dc0-f2349dad6ad7.png)
![image](https://user-images.githubusercontent.com/8211934/36639683-42488e58-19e0-11e8-8acc-897199bb6d82.png)

**Comment by leezer3** [comment]
The normal is a 3D vector moving away from your point.

Your roof is on the right, so you want something like this:
```
Top center: 
0,1,0 - This pulls the normal straight up
Center of the curved bit:
0.5,0.5,0- This pulls the normal diagonally right and up
Bottom:
1,0,0- This pulls the normal directly right
```
For the ones in the middle, just move proportionally between the values above.
If it's a funny shaped curve, they can be adjusted as you require.

**Comment by wizdagamer** [comment]
Alright, I'll see if it works, thanks.

**Comment by wizdagamer** [comment]
Woops, hehe. Wrong button. Thanks I'll check it out.

**Comment by wizdagamer** [comment]
Alright that did fix my issue. thanks!
