### ISSUE TITLE
Reference to issue #208

### ISSUE THREAD

**Issue by Dragon951** [leezer3/OpenBVE#226]
The Issue Has returned again to where the signs are not working, wheels spin on their own as they may be referencing the AI Train, signs change on their own/disappear (all with the train) 

Version 1.5.3.1

**Comment by leezer3** [comment]
Too many things in the air....

Have you tried the latest daily build?
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-02-27.zip
I *think* this has been nailed down again, but there are a lot of special-cases with this one.....

**Comment by Dragon951** [comment]
so,

after review, the signs are working again, but the wheels keep spinning even when the train is not moving, can this be fixed as well?

**Comment by leezer3** [comment]
I can't reproduce that.

Can you describe *exactly* what you need to do to for that to happen please?

**Comment by leezer3** [comment]
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-03-06.zip

Fixed hopefully.

**Comment by Dragon951** [comment]
ok, so this fixed the wheel and sign issue, another issue arises, now it takes 7-10 seconds to switch from cab view to exterior view when the game first loads and your at the beginning terminal, can this be looked into?

**Comment by leezer3** [comment]
That one is a little more complex.

We appear to have previously had a bug, which caused all exterior cars other than the driver's car to be rendered ( http://bveworldwide.unlimitedboard.com/t1483-what-s-this#16178 ), no matter whether they were visible or not.
You can test this yourself by moving the driver car back one (or by unlocking the camera and rotating it through 180 degrees) in any prior version of openBVE, including 1.4.3 etc.

Having fixed this, the external for a train, and hence it's textures are now first swapped into memory when they appear, *not* when the sim is first loaded.

If you measure the load time with (e.g.) the R142A HQ, you'll find it's dropped by approximately the same timeframe it takes for the first switch between cab and the exterior.

---

The short answer is that you (or the authors in general really....) need to seriously downsize the number and size of textures you're using.
They're totally oversize, and when the external first comes into view, it swaps these textures into GPU RAM, causing somewhere in the region of 600mb to 1gb worth of memory hit.

This is never going to be fast, and it's only as a result of a completely different bug that it worked tolerably in the first place.

From a brief prod, I'd say you can easily halve the size of most textures with absolutely no visible quality loss, and in a lot of cases going half again would be virtually un-noticable unless this was being looked for.
---
I'll try and do something about this, but I don't know what off the top of my head....

**Comment by leezer3** [comment]
This build should be back to approximately the same load speed:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-03-09.zip

It's a pretty iffy workaround (Load in external mode first, and immediately hide), and I'd strongly encourage you to work with the other NYCTA developers to consider reducing your texture sizes drastically.

Just a few examples from the R142A HQ:

- AD Card.jpg - This is 2520 x 884 pixels in size. It doesn't conform to the power of two rule, meaning it'll be upsized to 4096 x 1024 pixels in memory, and uses well over 16mb of video memory. You could quite easily drop this to 512 x 256 pixels, which drops the size in video memory to 512kb
- AD9.jpg through AD14.jpg - Will be upsized to the same size, previous comments apply.
- Floor.jpg - There's absolutely no need for a 1024+ pixel long floor texture in a relatively simple repeating pattern. Most of the time you can't see this anyways, and using a bit of texture repetition could reduce this to under a quarter of it's size.

Please remember that the JPG size bears no relationship to the size taken up in video memory.
This is calculated as follows:

1. Upsize to the nearest power of two.
2. Multiply the width by 4 (1 byte each for Red, Green, Blue & Alpha)
3. Multiply by the height

This gives us the total size the texture will take up in video memory in bytes. You can convert to megabytes by dividing by __1048576__ , and it might shock you to compare the total size of the textures used by the R142A to your video memory size :)
