### ISSUE TITLE
Use HTTPS for openbve-project.net

### ISSUE THREAD

**Issue by WPFilmmaker** [leezer3/OpenBVE#228]
At the moment the website does not uses HTTPS (not even for the download page). Switching to HTTPS would provide security for the user and would make the site future-proof (both Firefox and Chrome are enabling tactics to warn users against non secure websites).

**Comment by Sirflankalot** [comment]
Unfortunately that isn't possible. We use github-pages for hosting and HTTPS isn't available for custom domains. If @leezer3 wants to, I would be willing to sponsor hosting for the website on an actual VPS. 
---
Connor Fitzgerald

**Comment by WPFilmmaker** [comment]
@Sirflankalot Thanks for the reply,  browsers are pushing hard to move to secure connections so in the future you will probably have to add it anyway, but for now what about redirecting to github for the download? It would be safer and at no cost since github already uses HTTPS.

**Comment by Sirflankalot** [comment]
That would be possible and is probably the best solution until me and leezer3 can work something out. 
---
Connor Fitzgerald

**Comment by leezer3** [comment]
I think we can actually use Cloudflare to proxy the current hosting setup with SSL, although I'm by no means convinced it needs it.
It's only simple Jekyll generated static HTML, with no data input or anything like that, which is where the browsers are pushing.


FWIW, the downloads are served via my VPS with SSL at the minute (256mb, 2 core + nginx) :)
Load averages are currently low, but I dunno what adding the main site to the mix would do; It's surprisingly high traffic, as we pickup a *lot* from searches such as 'Free train simulator'

**Comment by Sirflankalot** [comment]
So I think that at least solves the problem is the downloads :)

I think he does have a point regarding Chrome and Firefox's warning about http. It will detract possible users from playing the game of they set big scary warnings.
---
Connor Fitzgerald

**Comment by leezer3** [comment]
OK, download links changed to https

Cloudflare also ought to be proxying the main site whenever the DNS config updates, let's see how that works before we try anything else.....

FWIW:
Big scary warnings are never going to happen with static sites IMHO, too much of the internet uses them.
Worst we're going to see is the little unsecure icon there.

**Comment by WPFilmmaker** [comment]
@leezer3 Thanks! Hope to see #229 implemented as well when you got time and resources.

**Comment by Sirflankalot** [comment]
@leezer3 That's a very fair point, if we see problems we can fix it.

**Comment by leezer3** [comment]
Right, complete site is now https served and working, so closing this one :)

**Comment by Sirflankalot** [comment]
Awesome! Thanks!
