### ISSUE TITLE
More of a feature request

### ISSUE THREAD

**Issue by wizdagamer** [leezer3/OpenBVE#234]
Not so sure how to request a feature but i have some I would like to share. If you can, move it to the correct spot please. 

- For trains that have the Lap position brake (AMUE is what we call them in NY) add a initial release. This would then release the brake pressure slowly. 

- Add a option for cab sway...Sorta like in WoS V4. I noticed in some videos that they crack up the swaying of the train. How would I go about that till you maybe add a slider? 

- Another thing I would like is the Continuous Range Motion. The new technology trains in NYC have this, and it would be especially cool if you have a throttle controller and can simulate it. 

- The ability to put the throttle into deadman with the brake in emergency with Panel2.cfg (Don’t know how to do it if you already can. Separate handles btw)

I believe that is is. If I have anymore I’ll be sure to let you know! Thanks for listening.

**Comment by leezer3** [comment]
```
Add a option for cab sway...Sorta like in WoS V4. I noticed in some videos that they crack up the swaying of the train. How would I go about that till you maybe add a slider?
```
Have you looked into the __Track.Accuracy__ command?
This accepts floating-point values from 0 (No cab sway) ==> 4 (Max cab sway)


Will have a think about the other stuff and see what I can come up with.

**Comment by leezer3** [comment]
```
The ability to put the throttle into deadman with the brake in emergency with Panel2.cfg (Don’t know how to do it if you already can. Separate handles btw)
```
Not currently possible.
However, it's easy enough to do:
https://github.com/leezer3/OpenBVE/pull/236

Will merge this into the main branch in a day or two once I've thought about things a little more and checked there's nothing I've forgotten.
