### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by afarlie** [leezer3/OpenBVE#238]
Currently OpenBVE assumes that it is being run directly by a user.

Whilst for it's uses to date, this is reasonable, for other uses it would be reasonable to have a 'kiosk' mode that could be enabled for uses cases where a single route would be loaded/rendered and run many times.

The London Transport Musum usage of OpenBVE would for example benefit from "kisok/cabinet" mode.

An AI driver is already present in OpenBVE, albiet it needs routes/trains to support it.

"Kisosk" mode, would also need:

    Resest time-outs. The route resets , invokes the AI mode or enters a demonstration mode after a certain definable timeout. it would also perhaps need time-outs to go back to the start of the route.

    "Operator" PIN to enter a maintenance mode, (which is effectively the non kiosk mode of the progam)
    and so on.. (will add more to this if I think of things)

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/3b802e965040308486e43b6e80bd7bb6f5630261  implements a very basic kiosk mode.

This doesn't have all the features you're after, however it now does the following:
- Removes the exit options from the menu.
- After a (configurable- Set to 5 mins by default) timeout, returns the camera to the cab, and enables AI.

Only keyboard controls reset the timeout at the minute; I'll need to think of a way to handle joysticks as they're a little more complicated....

**Comment by afarlie** [comment]
Thank you,  The above was more a 'suggestions for the future, after a disscussion' than an actual feature request, but thanks for implementing this anyway :) . 

I'm not linked with the museum mentioned in anyway, but it was one of the more prominent 'kiosk' use cases I was aware of.
