### ISSUE TITLE
OpenTK.dll.config not deployed under Linux / OSX

### ISSUE THREAD

**Issue by mgavioli** [leezer3/OpenBVE#25]
Under Linux and OSX, for OpenTK to work correctly, the file `OpenTK.dll.config`is required. The file is present in the `Dependencies` folder, but it is not deployed.

**Comment by leezer3** [comment]
That's a pain, it copies under Windows/ VS2013....

I think that adding this on line 320 of OpenBve.csproj ought to work, but I don't have a Monodevelop box handy to test:
``<PostBuildEvent Condition=" '$(OS)' == 'Unix' ">cp -rf "$(ProjectDir)../Dependencies/OpenTK.dll.config" "$(TargetDir)"</PostBuildEvent>``

(Alternatively I'm  sure Monodevelop has a section to add post-build events via the GUI, but I don't know where off the top of my head)

**Comment by JakubVanek** [comment]
Example from PR #10 (which fixed this for the Data folder)
```
<PostBuildEvent Condition=" '$(OS)' != 'Unix' ">xcopy "$(ProjectDir)Data\*.*" "$(TargetDir)Data" /Y /I /E /C</PostBuildEvent>
<PostBuildEvent Condition=" '$(OS)' == 'Unix' ">cp -rf "$(ProjectDir)/Data" "$(TargetDir)"</PostBuildEvent>
```

**Comment by leezer3** [comment]
Yep, that was basically where the idea came from!

Needs someone with a Monodevelop box to test it though.

**Comment by mgavioli** [comment]
Haha! There it is! I looked everywhere (or so I thought)...

If MonoDevelop has a way, it is not obvious, as the "Custom Commands" tab of the project options does not list the _existing_ commands, so I was afraid to mess with it. Editing the .csproj file by hand was easy and it **worked**!

PR coming...

**Comment by leezer3** [comment]
PR merged.
