### ISSUE TITLE
Single Handle Control Issue (??)

### ISSUE THREAD

**Issue by oddpodlbkk** [leezer3/OpenBVE#255]
I have an issue where when I am using a train with one handle when I apply the brake, the ATC/ATS will also apply the throttle, thus when I am stopped at a station, the brakes and throttle are both applied.

**Comment by leezer3** [comment]
Train and route please?

My first thoughts:
* Sounds like ATC not ATS. IIRC ATS can't increase power.
* May well be being affected by a buggy beacon / signal distance setup.

**Comment by oddpodlbkk** [comment]
Trains are R46, R142, R142A, R160, R179, R188, on the F line, and the 5. I've noticed that the issue also occurs on other routes and trains, but those are the ones I can think of now.

**Comment by oddpodlbkk** [comment]
this video shows the issue, using the R46 on the A Line 
https://youtu.be/Ce6xTpvVP9M

**Comment by leezer3** [comment]
I can't reproduce the sequence of events in your video at the minute.

From what I can see, you do the following:
* Load the A-Line with the R46.
* Before the video starts, you must have selected Forwards on the reverser?
* I then see you dropping the brakes to N.
* The brakes are then reverted to B1

Trying this, my brakes remain in N, and the train starts to roll backwards.
I'm testing with the 8-car version of the R46 - 
https://www.bvestation.com/download/17
and this version of the A Line:
https://www.bvestation.com/download/2

However, my initial thought would be that the behaviour you're seeing is actually 'more' correct.
With the doors open, if the train starts to roll backwards, I'd fully expect a safety system intervention to stop it.

All of these use a variant of the OS_ATS plugin, which is something the program has no control over, so in any case I'm not sure it's a program issue.

**Comment by oddpodlbkk** [comment]
https://www.youtube.com/watch?v=cim57SxYlsc&feature=youtu.bep

**Comment by leezer3** [comment]
Still can't reproduce anything remotely similar.

Are you using (or have connected) a joystick, gamepad, RailDriver or similar?

**Comment by oddpodlbkk** [comment]
i am using a rail driver, but i have the same issue with a joystick

**Comment by leezer3** [comment]
Just tried with the RailDriver and a joystick here, can't reproduce with either of them.

Does it do the same thing with a keyboard?
