### ISSUE TITLE
Can't find Current Routes/Trains

### ISSUE THREAD

**Issue by ohnonot** [leezer3/OpenBVE#267]
#### First I should clarify a few things:

I have been using [OpenBVE on Archlinux](https://www.archlinux.org/packages/community/any/openbve/) for a couple of years, on and off.  
I am amazed at the backwards compatibility, and thrilled that there's still some development.

I'm not any sort of train hobbyist; I just like this sort of laid-back gaming and being able to drive through different countries and even get some cultural context. It's strangely fascinating.

#### The Issue

I am aware that (open)BVE is very fragmented, not only are tracks and trains found all over the internet, but even the program itself has different versions, even here on github (*).  
I did find routes and trains! (**) But there's a discrepancy that makes me wonder if I'm missing something:
- There's current development on openBVE, even adding new features, but
- I can find only very old (+10 years) routes/trains...

__Am I missing something?__

So it would be nice to add some links to the README, or maybe even one or two dedicated default routes/trains that are added to the program itself.

(*) but those are a little old, too. Can this repo be considered the most current & usable version for Linux users?  
(**) [here's a list of my bookmarks](http://dt.iki.fi/stuff/openbve/bookmarks.html). That's all I could find so far. Some of the links are dead already. Many tracks are full of errors. And I never figured out how to install (Windows?) plugins.

In any case, this is fun. Thanks for keeping it alive.

PS: I'm sorry if this isn't really an Issue. I couldn't think of a better place to post it.

**Comment by leezer3** [comment]
Ah, try http://bveworldwide.forumotion.com
The board hosts changed the URL. The old one redirects for some but not all.....

East asian, not sure off the top of my head; My side of things / interest is primarily EU based.
There's definitely an Indonesian site somewhere mind- will take a look for it when not replying from a phone.....

**Comment by OpenBveTrainSim** [comment]
ohnonot
More links here to Asian routes and trains for openBVE
https://obts.wikia.com/wiki/OBTS_Addons

Good day

**Comment by leezer3** [comment]
http://bveworldwide.forumotion.com/t1013-indonesia

That's got a link and registration details for the Indonesian site I was thinking of.

Also, a secondary note:
Unfortunately, most routes generate errors, but in general these are harmless and can be ignored.
BVE2 / BVE4 were much more tolerant of error, and I've actually spent a large amount of time repairing these!
If you see anything that looks broken, feel free to link me to it with details, and I'll happily take a look.

**Comment by ohnonot** [comment]
^ thanks again, will check Indonesian routes.

broken: i can live with most glitches, but very often the background image is missing, and that is very disturbing. will try to post some details.

> try http://bveworldwide.forumotion.com

now that makes a lot more sense!  
shouldn't that be changed in the Readme?  
also if i may suggest to mention the possibility of getting routes/trains from these links. make it a little more prominent.

> More links here to Asian routes and trains for openBVE
https://obts.wikia.com/wiki/OBTS_Addons

thanks; i think it was you who used my contact page? thanks for that too.  
i must admit i did not check out that one before asking about East Asian routes.

**Comment by v1993** [comment]
It seems that https://railsimroutes.net/blog/ have resumed work after long delay. So we may hope for upgraded version of one of best OpenBVE routes!
