### ISSUE TITLE
Chinese characters in (some?) in-game interface strings

### ISSUE THREAD

**Issue by mgavioli** [leezer3/OpenBVE#27]
Since the recent changes in language management, some strings appear as "missing char" empty rectangles; the most evident are:
- Power and brake indicators in the bottom left corner if value is 0 ("Pn" and "Bn" for n != 0 are displayed correctly)
- Door indicators in the bottom centre

The debugger shows that the programme is attempting to display Chinese characters (rendered as "missing character" empty rectangles on my system).

Apparently, the programme is using the last language added with the `AddLanguage()` function in _System/Translations/LanguageFile.cs_ which, on my system, happens to be `zh-TW.cfg`.

If relevant, please note that the function `LoadLanguage()` in the same file is never executed.

Just for reference, the system language of my machine is English (Ireland). The language set in openBVE options is English (US).

I'll try to gather more details but, perhaps, this might ring some bell already...

**Comment by leezer3** [comment]
Certainly does....
Some strings have special handling (The names of controls, and those called every frame), as it's not a good idea to run '00s of times a frame.

Missed some.....
