### ISSUE TITLE
.Animated Variables FrontAxleCurveRadius & RearAxleCurveRadius

### ISSUE THREAD

**Issue by OpenBveTrainSim** [leezer3/OpenBVE#272]
Chris
Consider these .Animated variables, which require specifying a car number 0 to N:
FrontAxleCurveRadius[carIndex]
RearAxleCurveRadius[carIndex]
Are improved versions possible which assume the current car number?
FrontAxleCurveRadius
RearAxleCurveRadius
and thus not error when using car subfolders which are common to multiple consists\trains
with the same versatility of these existing variables:
Odometer vs. Odometer[carIndex]
Speed vs. Speed[carIndex]
Speedometer vs. Speedometer[carIndex]
Acceleration vs. Acceleration[carIndex]

You may wish to consider other variables as well
CurveCant[carIndex]
Pitch[carIndex]

Thanks
OBTS

**Comment by leezer3** [comment]
Should be able to add those, will check once home.

**Comment by OpenBveTrainSim** [comment]
leezer3
Any luck on this?
Thanks
OBTS

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/0183335d7854957f738ca0afd9a428a3987044ad

https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-09-14.zip

Should do it I think.

**Comment by OpenBveTrainSim** [comment]
Chris AKA leezer3
Will be trying these new for bogies ("Axles" in extensions.cfg) animated logic.
Thanks
OBTS

**Comment by OpenBveTrainSim** [comment]
Chris AKA leezer3
Suggest documentation of variables with optional [carIndex] use a generic description such as:
VariableName[carIndex]  "Description"
Omitting [carIndex] Returns Value For "Current Car"
A Specific [carIndex] Returns Value For "Car 0 To N", 0 = First Car, N Or -1 = Last Car
