### ISSUE TITLE
Adding HALT.WAV Configuration To Sound.cfg

### ISSUE THREAD

**Issue by OpenBveTrainSim** [leezer3/OpenBVE#284]
Leezer3\Chris:

IIRC from the early days of openBVE and Michelle,
the question was raised several times as to why HALT.WAV was excluded from Sound.Cfg.
Michelle acknowledged the issue, but refused to provide a reason or remedy the problem.
Thanks for this long needed fix.
OBTS

**Comment by leezer3** [comment]
No probs.

I think the probable reasoning behind that one is that BVE4 using the sound.cfg doesn't support this.
I'd have to check, but I have the strong suspicion BVE4 doesn't have the pass alarm, as at this point the 'default' devices were going in favour of the ATS plugin route.

It's set for every car at the minute, which might actually be 'wrong' , but it all depends on what
