### ISSUE TITLE
No action of station stop process when we are attempt to station jumping command. Also no processing of signaling system.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#293]
I think maybe that happen from this commit.

https://github.com/leezer3/OpenBVE/commit/62f274a65fcbbc0e1ba1a113cd55b5a3977a1053#diff-430a5b1e85b9a9846321097ed618a324R71

First of all, a train cannot jump to passing station.
Nonetheless, this commit is written.
Please tell us why you wrote this commit.

**Comment by leezer3** [comment]
The referenced commit was intended to fix the following behaviour:
 A route with 5 stops, as follows:
1. Starting station.
2. Player to pass.
3. Player to stop.
4. Player to stop.
5. Player to stop.

Jumping from station 1 to station 4 / station 5 in this case produced the 'passed station at which you should have stopped' message.
As a jump is a player initiated action, we shouldn't be displaying this message.

You're right though that the station arrival seems to be iffy now :(
Let me take a look.
