### ISSUE TITLE
Something wrong with UI font

### ISSUE THREAD

**Issue by Symbian9** [leezer3/OpenBVE#295]
### Description

Most of text in the UI look like rectangular symbols

![pic.1](http://i.imgur.com/ztSnzor.png)

### Related information 

- OpenBVE version: `1.5.3.11`
- Operating system: `Debian 9.x` (x86_64)
- Method of control: keyboard + mouse

**Comment by leezer3** [comment]
This usually occurs on Linux when the ststem fallback font only contains a partial set of non ASCII characters.

What language?

**Comment by Symbian9** [comment]
> What language?

Hm, strange, my system language is `en-US`, but *OpenBVE* after installing automatically choose `zh-TW` locale (why?).

I just set `en-US` inside `~/.config/OpenBve/Settings/1.5.0/options.cfg` and now all seems work well.
