### ISSUE TITLE
Joystick does not respond on Windows XP.

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#299]
### Description

Joystick seems to recognize, but it does not react on Windows XP.
On Windows 8.1 and 7, it recognizes and responds like a second screenshot. (Joystick1 does not matter.)

![hqr2arvf](https://user-images.githubusercontent.com/29241703/50038194-0bb7d180-005f-11e9-8cef-173016389ad3.jpg)
![controls](https://user-images.githubusercontent.com/29241703/50038219-58031180-005f-11e9-8384-393ee4d7cbeb.png)

### Reproduction

Connect OHC-PC01 on Windows XP.
However, since OHC-PC01 is recognized as a general joystick from OS, general joystick does not seem to respond.

### Related information 

* Windows XP
* OHC-PC01

**Comment by s520** [comment]
Logicool Gamepad F310 did not react in the same way.

**Comment by leezer3** [comment]
Don't know :(

I might try and get something based upon this chip and do some testing, but XP is well out of support even from Microsoft.
Mono is dropping XP support going forwards, and IIRC OpenTK were thinking of it too.

**Comment by s520** [comment]
It might be a problem with OpenTK.
Because OpenTK supports Windows XP, I thought it would work normally.

**Comment by s520** [comment]
This issue is closed because .NET 4.6.2 does not support XP.
