### ISSUE TITLE
1.4.7.1068: Joystick axis controls only go between 0 and positive maximum

### ISSUE THREAD

**Issue by jsiren** [leezer3/OpenBVE#3]
As per OpenTK documentation, a joystick axis should vary between -1 and +1, 0 being the neutral or center position. Any controls assigned to a joystick axis seem to only have the 0 and +1 positions. The negative side is completely dead, and the positive side goes to +1 as soon as the axis deviates from zero. To verify: add the following line to controls.cfg and try driving any train with a combined power/brake handle (UK examples classes 323, 220):

SINGLE_FULLAXIS, joystick, 0, axis, 1, 1

Manual editing is required because of #4

**Comment by leezer3** [comment]
Rats, didn't mean for that to happen :(

Axis control is now working much better, but the changes I've made here won't fix the current problem, which is the fault of the SINGLE_FULLAXIS handling.

**Comment by leezer3** [comment]
OK, should now be fixed in the most recent build- I've reverted to code very close to Michelle's original implementation.

This doesn't fix the joystick detection issue under Linux- Investigating :)
