### ISSUE TITLE
SanYing Heavy Industry OHC-PC01 USB joystick support announce officially.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#300]
Official announce on Twitter:
https://twitter.com/SanYingOfficial
Official website:
http://rm.rp.com.tw/

SanYing Heavy Industry OHC-PC01 USB joystick supports for OpenBVE and announced officially.
Please add this joystick information and company's link to official website.
https://openbve-project.net/

**Comment by leezer3** [comment]
Good idea.

Added a page detailing the supported cab controllers:
https://openbve-project.net/play-cabcontrollers/

This is linked from the bottom of the 'Play' menu.

**Comment by s520** [comment]
Thanks!

**Comment by ginga81** [comment]
Thank you very much for adding to webpage!
Close this issue.
