### ISSUE TITLE
Suggestion of the improvement of the Developer Documentation.

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#304]
We are working on the improvement and multilingualization of the Developer Documentation for OpenBVE.

It is hard to edit the present HTML, and update of the Developer Documentation can't catch up with development speed of OpenBVE.

In addition to this, though the Developer Documentation is an important source of information, multilingualization does not advance at all.

We thought that fact is the cause that people of the non-English zone to be interested in openBVE are hard to enter newly.

We think that these are serious problems.

Therefore we developed the method suggested in Issue #260 and built the translation flow such as the chart below.

![translation flow2](https://user-images.githubusercontent.com/29241703/51000724-42efa480-1571-11e9-998d-fea75d614e8d.png)

1. A developer does push the original document of the Markdown form  to GitHub .

2. txgh(https://github.com/transifex/txgh) built in Heroku receives a notice from GitHub in Webhook

3. txgh updates a source file of Transifex based on the contents mentioned in step 1.

4. A translator works on translation in Transifex and completes it.

5. txgh receives a notice from Transifex in Webhook.

6. txgh makes a pull request based on step 4 in GitHub (e.g. https://github.com/OpenBVE-JapaneseTeam/OpenBVE-Site-Japan/pull/2).

7. When a developer merges pull requests in step 6, netlify deploys it and shows a site.

NOTE: Step 2, 3, 5 and 6 is automated.

We think that this method includes following merits.

- So update of the original file and the upload to GitHub are automated, the translator can concentrate on only translation work because.

- By using translator support tools such as translation memory or the vocabulary, the burden on translator can be reduced.

- We can preview it at the time of a pull request in netlify. In addition, we can do the static check of the translation result by using Travis CI.

- Besides, all this translation flows use free service, and we can maintain it being FREE without worrying about Viral license.

Our site using this translation flow can access it than the following URL.
https://openbve-japan.netlify.com/en/

You can change it to a Japanese edition by a pull-down menu of the top right corner. (translation completes only a top page now)

The repository as follows.
https://github.com/OpenBVE-JapaneseTeam/OpenBVE-Site-Japan

We hope OpenBVE will be more user-friendly.

Thank you for your consideration.

This post was translated by F81 tec200. I really appreciate it.

**Comment by leezer3** [comment]
No problems.

Some other stuff rather got in the way when that suggestion was made, and I haven't got as far as trying to sort this out.

I'm currently trying to get Travis to auto-generate the Hugo site you've done and commit it back to the main documentation repo as an experiment.
Test branch here:
https://github.com/leezer3/OpenBVE-Site/tree/hugo-docs

Travis currently errors with a Hugo error 255:
https://travis-ci.org/leezer3/OpenBVE-Site/builds/478379109

If I'm reading the error correctly, it doesn't like something about the mixed languages part...
Will carry on playing.

**Comment by s520** [comment]
Well, I think Hugo's version is old.

I use v0.53.

**Comment by leezer3** [comment]
You're absolutely right about the old Hugo version!

That's what comes from not reading the template script very well....
I'll try some testing later at home, as if the auto merge messes up I'll need to revert manually.

**Comment by s520** [comment]
Personally, if you use Hugo, I recommend that you deploy with netlify.

That is because netlify can also preview PR as follows.
https://app.netlify.com/sites/openbve-japan/deploys/5c349125d6336a000855fab5

**Comment by leezer3** [comment]
If I can get Travis to build it & successfully insert into an existing repo, the aim would be to use in both the main source and the website documentation. (Note the main source contains a copy of the docs)

**Comment by s520** [comment]
I see.

It is convenient to have PR preview function in GitHub Pages...

**Comment by leezer3** [comment]
OK, so we now have a Hugo documentation copy available here:
http://openbve-project.net/documentation_hugo

This is (currently) stored in this branch for testing purposes, mostly because I didn't want to try cross repository commiting with Travis:
https://github.com/leezer3/OpenBVE-Site/tree/hugo-docs

### Currently needs doing (?):
* Move this into a separate repository.
* Automatically commit to both the main site and the source whenever a translation changes.
* A more sensible commit message for the two production repos. I think we can access the base commit message through Travis and probably just pipe this in. Needs a little tinkering.
* Transifex implementation? https://docs.transifex.com/projects/open-source-project ==> My biggest issue here is that due to the historical issues with Michelle, our licence situation is a little fuzzy.
* Make the new Hugo docs work better on mobiles / small screen resolutions.

@MarcRiera any suggestions or further input?

**Comment by s520** [comment]
Is cheers for good work.

Well, it seems that language switching does not work well.

I will explore the solution.

We also discussed the license of transifex.

The conclusion at that time was that if we were asked to present a license we were to make it a dual license for public domain and MIT.

**Comment by s520** [comment]
I confirmed that the language switching function is working properly.

Thanks!

**Comment by leezer3** [comment]
Language switching fixed.

At the moment, I've had to use a hardcoded BaseURL to make this work, and this won't work for local URLs, so commiting a copy of this to the main source won't currently work right.
Could probably just switch out the config file before the second build, or build some sort of more fancy shell script to build both if we really wanted.

**Comment by s520** [comment]
Is there a better way to link from a dropdown list?

The reason why I am concerned about the drop-down list is that even if more languages are available, we can deal with it.

**Comment by s520** [comment]
I think that it is good to be able to use a drop down list like bootstrap 4.

It should have been able to switch without java script.

**Comment by leezer3** [comment]
I haven't done much with Hugo, but it seems to me the Javascript is being used to dynamically populate the list of languages for each available file.

In a large site with many non-complete translations, this might differ from page to page, and would probably create a quite large overhead compared to doing it in JS.

**Comment by s520** [comment]
hugo creates a link to a page that can be used when building.

This is static.

I used java script to create a drop down list.

So if you have alternative means script.js is unnecessary.

**Comment by MarcRiera** [comment]
Great to see further interest in updating the documentation!

The proposed workflow seems robust enough to be able to use it without having to worry too much about it. Most importantly, it is future-proof, as we will not be losing any localization data if for example Transifex decides to close (it is free-as-a-service for open source projects but not open source, so it is possible). There are other projects such as [Weblate](https://weblate.org/ which are open source and can even be self-hosted, and they are alternatives to commercial products such as Transifex, but in this case Weblate does not support Markdown and would not be useful. Transifex is a bit limited in many aspects, but as long as we configure the Transifex project properly (and enable the option to allow offsite translations to prevent user lock-in), I think everyone will be comfortable using it. Besides that, everything looks great.

Updating the repositories directly (instead of creating pull requests) is what I have seen in other projects. Usually there is a bot user with special permissions to the repository which directly updates the localization files each time there is a change.

I cannot really help with the licensing aspects, but I can give a hand with design and Hugo. And of course, once this is up and working, I will be working hard to translate the documentation to my language.

**Comment by s520** [comment]
Hello, MarcRiera.

Thank you for making a wonderful idea of using hugo.

We want to multilingualize not only documents but also sites by the same method.

**Comment by MarcRiera** [comment]
> I haven't done much with Hugo, but it seems to me the Javascript is being used to dynamically populate the list of languages for each available file.
> 
> In a large site with many non-complete translations, this might differ from page to page, and would probably create a quite large overhead compared to doing it in JS.

As @s520 mentions, the advantage of Hugo is that everything is generated on build, so usually there is no need to use Javascript (and the current script.js is unnecessary). Hugo knows at build time if a page is translated or not and generates the appropriate list for each page. If there are new translations, given that the whole documentation is rebuilt after a new commit, every list in every page would be updated.

**Comment by s520** [comment]
The PR(https://github.com/leezer3/OpenBVE-Site/pull/8) enables language switching even locally.

Please check it.

**Comment by leezer3** [comment]
I've opened a dedicated issue for licensing discussion here:

https://github.com/leezer3/OpenBVE/issues/305

Will merge your PR and see whether that works on the main site.
If that does, I'll try and separate it into a dedicated new repository and get that commiting to the site tomorrow hopefully.

**Comment by s520** [comment]
I would like to multilanguage the entire site in the same way.

I think that you should create a site with Hugo for that.

I prepared a demo site created with Hugo.
https://openbve-hugo-demo.netlify.com/en/
https://github.com/s520/OpenBVE-Site-Hugo-Demo

Regardless of the design of the site, please consider it.

**Comment by leezer3** [comment]
That doesn't look bad at all :)
The theme was a relatively quick modification of something pre-existing, nothing special really.

Small flaw with both Hugo versions (documentation / main site) at the minute:
We really want to return the base English page if no un-translated version is available.

This is more important for the main site (documentation can always carry a note saying that some portions may not be available in all languages).
I think we need to play with `{{ .IsTranslated }}` , but the Hugo documentation is not particularly clear on that front.

**Comment by leezer3** [comment]
Hmm, might not exist at all:
https://discourse.gohugo.io/t/i18n-fallback-translation/7444

That's absolutely a problem for the main site, as it would make updating the download page for multiple languages (for example) an utter mess :(

I suppose you could hack it to embed a specific pageblock containing the links, don't know.

**Comment by s520** [comment]
Thank you for checking!

I also want to make fallback possible.

If this becomes possible it will also be applicable to document pages.

I will explore the method.

**Comment by s520** [comment]
About updating version information I think that it can be solved by using ".Site.Params" and shortcode.
https://gohugo.io/variables/site/#example-site-params
https://gohugo.io/templates/shortcode-templates/

Let's do it for a moment.

**Comment by MarcRiera** [comment]
> Hmm, might not exist at all:
> https://discourse.gohugo.io/t/i18n-fallback-translation/7444
> 
> That's absolutely a problem for the main site, as it would make updating the download page for multiple languages (for example) an utter mess :(
> 
> I suppose you could hack it to embed a specific pageblock containing the links, don't know.

This will not be a problem thanks to the workflow. When translating anything using Transifex (or any other CAT tool), the files are not edited directly: the source language (English) files are the base, and translations are per-segment. The translated files are always generated by applying the segment translations to the source files, and if a segment has not been translated, it is left untranslated in the target file. Target files are never empty, at least not if the project is configured correctly. In summary, there is no need to handle this in Hugo, do not worry.

> About updating version information I think that it can be solved by using ".Site.Params" and shortcode.
> https://gohugo.io/variables/site/#example-site-params
> https://gohugo.io/templates/shortcode-templates/
> 
> Let's do it for a moment.

This is what I do in my personal [BVE site](https://en.bvebarcelona.cat) to remind users to always use the latest openBVE version. GitHub exposes an API for tags/releases in JSON format that can be checked by Hugo on build time to retrieve information such as the latest release number and the date (which is what keeps changing in the Downloads page). Instead of hardcoding this info, it can be retrieved via the API so that there is never the need to edit the page, not even the download links if they use the version number as-is, which is the case of openBVE.

Check the following Hugo shortcode: https://gitlab.com/MarcRiera/BVEBarcelona-site/blob/master/layouts/shortcodes/openbve_notice.html

On build time, it checks for "tag_name" in https://api.github.com/repos/leezer3/OpenBVE/releases to add the latest openBVE release version to the warning text. At first, it may seem to tricky, but it then allows you to update the website automatically, simply by triggering a deploy.

**Comment by s520** [comment]
I did it!

I succeeded in rewriting the link to the English version if there is no other language link of navbar.

Please check it. Since there is no HTML other than "Download" on the site below, java script is rewriting the link to the English version.
https://openbve-hugo-demo.netlify.com/ja/

Next I will check @MarcRiera 's short code.

**Comment by s520** [comment]
> This will not be a problem thanks to the workflow. When translating anything using Transifex (or any other CAT tool), the files are not edited directly: the source language (English) files are the base, and translations are per-segment. The translated files are always generated by applying the segment translations to the source files, and if a segment has not been translated, it is left untranslated in the target file. Target files are never empty, at least not if the project is configured correctly. In summary, there is no need to handle this in Hugo, do not worry.

However, in the workflow proposed by me, since the pull request is created when Transifex completes the translation, the translated version may not exist.

Is there a way to improve it?

**Comment by s520** [comment]
I tried to get information on the release page of GitHub with reference to @MarcRiera 's shortcode.
https://github.com/s520/OpenBVE-Site-Hugo-Demo/blob/master/themes/openbve/layouts/shortcodes/version_info.html

The download link will be updated automatically when building the site.

I think that @leezer3 's concern has been resolved.

Please check it.

**Comment by MarcRiera** [comment]
> However, in the workflow proposed by me, since the pull request is created when Transifex completes the translation, the translated version may not exist.
> 
> Is there a way to improve it?

I had forgotten about the pull requests part. I think I mentioned it earlier, but my suggestion would be to have a bot committing the changes directly to avoid having a long queue of translation pull requests and allow full syncing. It should be possible, at any given time and for any commit, to generate target files for all the languages enabled in the Transifex project (even if translations have not been completed yet) and commit them to GitHub so a build can be deployed with all the translations available at that moment. This procedure should also trigger every time the English files are updated in GitHub, and we would be sure everything is up to date for every language.

Of course, this also means potentially having partially translated pages on the website and documentation, but given the big amount of text it sounds better than making users wait until everything is done, at least they would see there is progress being made (and maybe they would like to contribute!).

**Comment by s520** [comment]
Thanks!

Since Transifex's Webhook is activated at the completion of translation and review, it can not be used.
https://docs.transifex.com/integrations/webhooks

Is BOT the Probot of GitHub?
https://github.com/probot/probot

**Comment by s520** [comment]
The possible mechanisms are as follows.
1. Receive push notification from GitHub's Webhooks.
2. Create and update Transifex source files from the commit contents via API.
3. Acquire Transifex's translation file via API and commit it to GitHub.

I thought that there are the following options to realize this mechanism.
1. Improve txgh written in Ruby.
2. Combine GitHub Probot and node-transifex. These two are written in nodejs.

However, the documentation of node-transifex is out-of-date.
Is there any other way?

(I am lacking knowledge of two languages, so your cooperation is necessary.)

**Comment by s520** [comment]
Also, have you logged in to Transifex with GitHub's account etc.?

There is a possibility that setting of txgh may fail.

**Comment by leezer3** [comment]
![tfx](https://user-images.githubusercontent.com/7688245/51258006-d45f7c00-19a0-11e9-904a-614b3d3d2bed.png)

This is what I've got at the minute in Heroku.
Transifex project is here & empty:
https://www.transifex.com/openbve/openbve-developer-documentation/

Heroku's log seems to stick on processing the changed file:
```
2019-01-16T15:05:56.602229+00:00 app[web.1]: * Listening on tcp://0.0.0.0:57527
2019-01-16T15:05:56.602459+00:00 app[web.1]: Use Ctrl-C to stop
2019-01-16T15:05:57.775885+00:00 heroku[web.1]: State changed from starting to up
2019-01-16T15:06:06.922358+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : Processing request at /hooks/github
2019-01-16T15:06:06.922411+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : processing payload from form
2019-01-16T15:06:07.122769+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : request github branch: heads/master
2019-01-16T15:06:07.122779+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : config github branch: heads/master
2019-01-16T15:06:07.122827+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : found branch in github request
2019-01-16T15:06:07.122877+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : processing commit
2019-01-16T15:06:07.122913+00:00 app[web.1]: I, [Wed 16-01-2019 1506 #4]  INFO -- : processing modified file: content/en/objects/other/x/_index.md
```

**Comment by s520** [comment]
Could you show me ./config/tx.config?

Also please fix GITHUB_PUSH_SOURCE_TO to "openbve-developer-documentation".

**Comment by leezer3** [comment]
```
[main]
host = https://www.transifex.com
lang_map =

# Create one such section per resource
[openbve.openbve-developer-documentation]
file_filter = content/<lang>/_index.md
source_file = _index.md
source_lang = en
type = MD
```

**Comment by s520** [comment]
Example:
```
[main]
host = https://www.transifex.com

[openbve-site-japan.objects-other-_index-md]
source_lang = en
source_file = content/en/objects/other/_index.md
file_filter = content/<lang>/objects/other/_index.md
type = GITHUBMARKDOWN
```
I would like to be able to operate without this file.

That's because you need to edit tx.config every time you add files or change file paths.

**Comment by leezer3** [comment]
Ah, I think I see what's happening.
I was assuming that Transifex would wilcard pickup anything matching the path, which it doesn't appear to do.

Heroku is started via Git, so I suppose you could create a bot that reads in any new files & commits to Git, but we're starting to get far too many bots flying around the place.

**Comment by s520** [comment]
I did it!

I realized the method @MarcRiera  suggested at https://github.com/leezer3/OpenBVE/issues/304#issuecomment-454566676.

The program using Probot of GitHub are in the following repository.
https://github.com/s520/txgh-js-bot

It can be used by installing it in the repository used as GitHub App and deploying it to Heroku.
https://probot.github.io/docs/deployment/

Set environment variables as follows.
https://github.com/s520/txgh-js-bot/blob/master/.env.example
![fireshot screen capture 050 - txgh-js-bot-openbve-site-japan settings i heroku - dashboard_heroku_com_apps_txgh-js-bot-openbve-site-japan_setting](https://user-images.githubusercontent.com/29241703/51383034-af633880-1b5b-11e9-9006-c9607b9d8164.png)

Unlike the original txgh, this program does not require setting for each file.

Also upload newly added files automatically to transifex.

Any questions and suggestions are welcome!

**Comment by s520** [comment]
Environment variable TX_ALL_UPDATE was added.

If set to true all target files included in head commit will be uploaded to Transifex.

You can upload existing files to Transifex by combining this with an empty commit.

In addition, the result is reflected in the commit status.

**Comment by s520** [comment]
Required GitHub Permissions:
- Repository contents: read & write
- Repository metadata: read
- Commit statuses:  read & write

**Comment by leezer3** [comment]
Private key is set, and I think permissions are right.

I've added you as a collaborator to the temp Heroku app, see if you can see anything wrong :)

**Comment by leezer3** [comment]
Note:
You should also be able to see the password for Transifex in Heroku.

I'm wondering if something is actually wrong there....

**Comment by s520** [comment]
In addition, I think that it is good to set a character string generated by the following command to Webhook secret.
openssl rand -base64 32

**Comment by s520** [comment]
I think that the name of the application is "txgh-js-bot-openbve-doc".

**Comment by s520** [comment]
It seems that we succeeded in synchronizing with Transifex and it was good.

Since this application needs to be installed for each repository, it is best to name the identifier.

**Comment by leezer3** [comment]
We're nearly there!

The bot has successfully uploaded to Transifex, and I've created the ja-JA language there, and copied in your translations.
The webhook seems to fail in Heroku though:
```
2019-01-20T12:56:46.466896+00:00 app[web.1]: 12:56:46.466Z  INFO http: POST / 400 - 1.71 ms (id=0cc14888-df47-4954-a0f4-9bfd316ef333)
2019-01-20T12:56:46.467000+00:00 heroku[router]: at=info method=POST path="/" host=safe-badlands-79060.herokuapp.com request_id=0cc14888-df47-4954-a0f4-9bfd316ef333 fwd="134.213.112.160" dyno=web.1 connect=0ms service=4ms status=400 bytes=255 protocol=https
2019-01-20T12:58:24.053736+00:00 app[web.1]: 12:58:24.053Z ERROR probot: Go to https://github.com/settings/apps/YOUR_APP and verify that the Webhook secret matches the value of the WEBHOOK_SECRET environment variable.
2019-01-20T12:58:24.053750+00:00 app[web.1]:   Error: Required headers missing: x-github-event, x-hub-signature, x-github-delivery
2019-01-20T12:58:24.053752+00:00 app[web.1]:       at middleware (/app/node_modules/@octokit/webhooks/middleware/middleware.js:28:19)
2019-01-20T12:58:24.053755+00:00 app[web.1]:       at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2019-01-20T12:58:24.053756+00:00 app[web.1]:       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-01-20T12:58:24.053758+00:00 app[web.1]:       at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-01-20T12:58:24.053760+00:00 app[web.1]:       at /app/node_modules/express/lib/router/index.js:284:7
2019-01-20T12:58:24.053762+00:00 app[web.1]:       at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-01-20T12:58:24.053763+00:00 app[web.1]:       at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-01-20T12:58:24.053765+00:00 app[web.1]:       at /app/node_modules/probot/lib/middleware/logging.js:35:9
2019-01-20T12:58:24.053767+00:00 app[web.1]:       at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2019-01-20T12:58:24.053768+00:00 app[web.1]:       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-01-20T12:58:24.053769+00:00 app[web.1]:       at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-01-20T12:58:24.053771+00:00 app[web.1]:       at /app/node_modules/express/lib/router/index.js:284:7
2019-01-20T12:58:24.053773+00:00 app[web.1]:       at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-01-20T12:58:24.053774+00:00 app[web.1]:       at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-01-20T12:58:24.053776+00:00 app[web.1]:       at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
2019-01-20T12:58:24.053777+00:00 app[web.1]:       at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2019-01-20T12:58:24.053779+00:00 app[web.1]:       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-01-20T12:58:24.053780+00:00 app[web.1]:       at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-01-20T12:58:24.053782+00:00 app[web.1]:       at /app/node_modules/express/lib/router/index.js:284:7
2019-01-20T12:58:24.053783+00:00 app[web.1]:       at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-01-20T12:58:24.053785+00:00 app[web.1]:       at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-01-20T12:58:24.053787+00:00 app[web.1]:       at query (/app/node_modules/express/lib/middleware/query.js:45:5)
2019-01-20T12:58:24.053788+00:00 app[web.1]:       at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2019-01-20T12:58:24.053790+00:00 app[web.1]:       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-01-20T12:58:24.053791+00:00 app[web.1]:       at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-01-20T12:58:24.053793+00:00 app[web.1]:       at /app/node_modules/express/lib/router/index.js:284:7
2019-01-20T12:58:24.053794+00:00 app[web.1]:       at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-01-20T12:58:24.053796+00:00 app[web.1]:       at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-01-20T12:58:24.053797+00:00 app[web.1]:       at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
2019-01-20T12:58:24.053799+00:00 app[web.1]:       at Function.handle (/app/node_modules/express/lib/application.js:174:10)
2019-01-20T12:58:24.053800+00:00 app[web.1]:       at Server.app (/app/node_modules/express/lib/express.js:39:9)
2019-01-20T12:58:24.053803+00:00 app[web.1]:       at emitTwo (events.js:126:13)
2019-01-20T12:58:24.053804+00:00 app[web.1]:       at Server.emit (events.js:214:7)
2019-01-20T12:58:24.053806+00:00 app[web.1]:       at parserOnIncoming (_http_server.js:656:12)
2019-01-20T12:58:24.053807+00:00 app[web.1]:       at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
2019-01-20T12:58:24.056666+00:00 app[web.1]: 12:58:24.056Z  INFO http: POST / 400 - 3.54 ms (id=971c9df0-94b2-4065-b848-14f6e6041edd)
2019-01-20T12:58:24.057239+00:00 heroku[router]: at=info method=POST path="/" host=safe-badlands-79060.herokuapp.com request_id=971c9df0-94b2-4065-b848-14f6e6041edd fwd="134.213.29.85" dyno=web.1 connect=1ms service=6ms status=400 bytes=255 protocol=https
```

The webhook secret is definitely right (using openbve at the moment), so I think that's a red herring.
It's also definitely worked when pushing to Github, it's coming from Transifex that's the issue at the minute.

**Comment by s520** [comment]
This application will not accept Webhook from Transifex.

Because there is no flexibility in setting Transifex's Webhook.

Please do an empty commit to GitHub to synchronize translation.

**Comment by s520** [comment]
It seems that you have successfully synchronized Japanese files.

Are there any questions or suggestions?

**Comment by leezer3** [comment]
I think it's now working OK, although the update procedures are a little confusing; 
If I understand it right, when a set of translations are completed within Transifex and a page is marked as reviewed, an empty commit needs to be added to the repository in order to trigger an update, or alternatively, it'll sync all languages when the English language files are updated.
Updating the English language files will also trigger an update to add the necessary strings for all languages.

Some improvement thoughts:
* Having the target languages set via an environment variable isn't perfect. Ideally speaking, we'd pull them back from Transifex's list of available languages. Not clear whether that's possible or not at the minute; I'd need to sit down with the API documentation :)

**Comment by leezer3** [comment]
Looking at it, I think this is probably more likely to be what you want:
https://docs.transifex.com/api/languages

It allows us to read the list of languages and add / delete them.

**Comment by s520** [comment]
Oh, I seem to have misunderstood.

What you are suggesting is that BOT adds languages according to TX_TARGET_LANG, is not it?

I'm sorry if I made a mistake...

**Comment by leezer3** [comment]
This is what I understand your bot does:
* Commit is pushed to github containing the English files.
* Bot reads the TX_TARGET_LANG key from it's environment.
* On Transifex, updates (or creates) the strings for all languages defined in this key.
* Updates the translations FROM Transifex for all languages defined in this key.
* Commits back to Github with the translated strings, or an English copy if they do not exist.

Now, on Transifex, I've manually created the fr-FR language.
At the minute, I don't think the bot will process this without adding it to the TX_TARGET_LANG ?

**Comment by s520** [comment]
Thank you for being kind enough to explain.

I feel I could finally organize it.

I tried to compare the reactions of / project / <project_slug> / languages / and / project / <project_slug>, but the latter feels more appropriate.

Let's make it reflect on BOT.

**Comment by s520** [comment]
I have completed updating BOT.

Deploy the latest source code from my repository to Heroku.

It is OK to delete TX_TARGET_LANG.

Please try to make an empty commit to GitHub.

**Comment by leezer3** [comment]
Great, that works perfectly :+1: 

I've translated the French title page, which appears correctly.
@MarcRiera should hopefully now be added as the ca-ES translator.

**Comment by s520** [comment]
Do you think that it is better to receive Transifex's Webhook?

If so, it may be possible to use [github-app](https://github.com/probot/github-app) instead of Probot.

**Comment by MarcRiera** [comment]
Yes, I am now able to translate strings in Transifex, thanks! I will notify you if I see anything wrong or that could be improved from the translator's point of view.

I will also try (in my free time) to help converting the old pages to the new format and improving the CSS.

**Comment by s520** [comment]
Please set up placeholder delimiters for Hugo's shortcode.

- Starts with: {{
- Ends with: }}

https://docs.transifex.com/setup/setting-translation-checks#checking-for-custom-variables

This can only be set by the administrator of the organization.

**Comment by s520** [comment]
Thanks!

I am not good at English, so I can not contribute much to translation.

That's why I would like to contribute by programs and so on.

Let's challenge to receive Transifex's Webhook.

**Comment by MarcRiera** [comment]
@leezer3 I can take care of the "Routes" section, if you like. It has quite a lot of content, but a great part is done (CSV route) and the rest should not be too difficult.

**Comment by s520** [comment]
I suggest that you regularly make an empty commit with [Travis CI's cron jobs](https://docs.travis-ci.com/user/cron-jobs/).

I changed programs so that Transifex's Webhook can be processed, but new access tokens such as GitHub will be necessary.

Although it may not be a very good method, I thought it better to do an empty commit on a regular basis.

**Comment by leezer3** [comment]
Would it be easier to setup a cron job to trigger the bot directly, rather than the empty commit you're suggesting?
Assuming it only checks the JSON sent out, this would be pretty easy to replicate in a BASH script.

It'd also be useful if the bot didn't create an empty commit when pushing back to Github-
I updated the readme and gitignore files, which then triggered this empty commit:
https://github.com/leezer3/OpenBVE-Documentation-Hugo/commit/c07c131809b7a072614f6c70d6012dfa8c1850aa

I *think* that if we check the tree's object length for non-zero this would work?

**Comment by s520** [comment]
I seem to be verifying the source of Webhook such as X - Hub - Signature, so I can not judge whether it is so easy.

If so it may be better to receive Transifex's Webhook even though some environment variable increases.

Also, my bot does not check whether to generate an empty commit.

My bot is uploading all of Transifex's non-English resources.

**Comment by s520** [comment]
I have updated the BOT.

Please try deploying the source code of the [develop branch](https://github.com/s520/txgh-js-bot/tree/develop) to Heroku.

See .env.example for added environment variables.

Also remember to set NODE_MODULES_CACHE=false.

Since the URL of Webhook is changed, please set as follows.
- For GitHub's Webhook   :  https://HEROKUNAME.herokuapp.com/github
- For Transifex's Webhook:  https://HEROKUNAME.herokuapp.com/transifex

**Comment by leezer3** [comment]
Great, thanks!

I've converted a couple of the train files to test, which work nicely.

**Comment by s520** [comment]
Thank you for testing!

As suggested, let's declare the work part of the conversion with a pull request so that conflicts do not occur. (e.g. https://github.com/leezer3/OpenBVE-Documentation-Hugo/pull/2)

Also, what do you think about the multilingualization of the entire site?

**Comment by leezer3** [comment]
Both sound like good ideas.

However, I think the entire site needs to wait for a little longer.
The bot and methods of doing things are changing extremely rapidly at the moment, so I think it'd be better to work out the issues whilst doing the developer documentation before moving onto the site?

**Comment by s520** [comment]
I see.

I was relieved to find that you are positive also for the translation of the entire site.

As you say, we first convert and translate the developer manual.

**Comment by s520** [comment]
We are ready to merge https://github.com/leezer3/OpenBVE-Documentation-Hugo/pull/2.

We have completed converting all the items.

Next, how do we improve the display of documents on smartphones?

**Comment by s520** [comment]
I close this issue because the goal has already been achieved.

Also, improvements in display for smartphones are discussed in the PR below.
https://github.com/leezer3/OpenBVE-Documentation-Hugo/pull/16
