### ISSUE TITLE
GL_INVALID_VALUE with anisotropic filter

### ISSUE THREAD

**Issue by mgavioli** [leezer3/OpenBVE#31]
If I set interpolation to anisotropic in the options screen, I receive a `GL_INVALID_VALUE` exception as soon as the simulation starts (the first frame is shown, though). Note that it seems not possible to set the anisotropic level to anything but 0.

This happens with all the routes and all the trains I have tried (about 4/5 of each). All other interpolation settings work fine. As a reference, on my system, version 1.4.3 runs fine with anisotropic interpolation (level 16) on those same routes/trains.

OS: Linux Mint 17.3; graphic adapter: AMD/ATI Radeon HD 5770, driver xserver-xorg-video-ati version 1:7.3.0-1ubuntu3.1 (the latest and recommended driver for my distro).

This is the MonoDevelop debugger report:

- System.InvalidOperationException: MainLoop: GL_INVALID_VALUE
-   at OpenBve.MainLoop.CheckForOpenGlError (System.String Location) [0x000dc] in /home/mmg/Documents/projects/openBVE/leezer3/openBVE/OpenBve/OldCode/MainLoop.cs:485
-   at OpenBve.OpenBVEGame.OnRenderFrame (OpenTK.FrameEventArgs e) [0x0021b] in /home/mmg/Documents/projects/openBVE/leezer3/openBVE/OpenBve/OldCode/NewCode/GameWindow.cs:143
-   at OpenTK.GameWindow.OnRenderFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <filename unknown>:0
-   at OpenTK.GameWindow.RaiseRenderFrame (Double elapsed, System.Double& timestamp) [0x0000c] in <filename unknown>:0
-   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame (System.Object sender, System.EventArgs e) [0x000d5] in <filename unknown>:0
-   at OpenTK.GameWindow.Run (Double updates_per_second, Double frames_per_second) [0x000c6] in <filename unknown>:0
-   at OpenTK.GameWindow.Run () [0x00000] in <filename unknown>:0
-   at OpenBve.MainLoop.StartLoopEx (MainDialogResult result) [0x0021e] in /home/mmg/Documents/projects/openBVE/leezer3/openBVE/OpenBve/OldCode/MainLoop.cs:97
-   at OpenBve.Program.Main (System.String[] args) [0x00605] in /home/mmg/Documents/projects/openBVE/leezer3/openBVE/OpenBve/System/Program.cs:230

If more data are needed, I assume I can provide them (with proper instructions?). Thanks!

**Comment by leezer3** [comment]
It's tripping up on a function Michelle added to check for errors which
occurred in OpenGL whilst rendering the previous frame. This is only called
when running debug builds, so you may find it actually works OK in release
mode.

First tech thoughts-
It doesn't do this in Windows on an ATI card (6870) or the Nvidia one in
myy second PC which means I'm inclined to think driver bug.

Can you try with the proprietary ATI driver, as opposed to the open source
one? (Catalyst)
I'll try and get a physical Linux install on the desktop, as the hardware
is similar enough in this case to give a reasonable chance of catching this.

Could probably also detect the failure condition and turn off AF I suppose.

**Comment by mgavioli** [comment]
I didn't try Catalyst (yet?...), but release works fine indeed. I'll keep you posted, though.

**Comment by leezer3** [comment]
So, the function in question is this:
https://github.com/leezer3/OpenBVE/blob/master/openBVE/OpenBve/OldCode/MainLoop.cs#L438

With a build in Debug mode, this is called once a frame, once loading has completed.

GL_INVALID_VALUE suggests that the Ansiotropic filtering level we supplied to the driver wasn't accepted.
See what the commit above does for you- I wasn't checking the max AF level reported by the driver before (Seem to have forgotten that when I initially ported to OpenTK)

Even if it doesn't fix your error, it should help those edge case systems which don't support AF at all, or where users set the AF setting too high.

**Comment by mgavioli** [comment]
Yes, I found that function, but thanks anyway! The above commit seems to fix the issue (very quick test); so, GREAT, thanks!

A possible part of the matter is that, as I said, in the option window it is not possible to set the anisotropic level to anything but 0; possibly, before the commit, the level value was never set. Now it is always set to the max reported by OpenGL.

Incidentally and separately, the current project configuration sets the define "DEBUG" also for the release mode. I could change this easily, but we would end up with a "MonoDevelop-ized" .csproj file; possibly fine, but who knows?

**Comment by leezer3** [comment]
The max level for the anisotropic level selection box should now be that reported by the driver.
This certainly seems to be working on Windows. Will try and get a Linux test going.

In your case, I'd say it looks like your driver is reporting a max value of 0.

Have fixed the DEBUG definition:
https://github.com/leezer3/OpenBVE/commit/cf1bd96bc9e30b4b53ab7dac85f8dae95e31840f

**Comment by mgavioli** [comment]
The edit box in the option pane reports the correct value (16) and can be set at will since the second time I run the programme. This makes sense: the new value is detected when the OpenGL simulation is started and, at the first run after the commit, the non-OpenGL part of the programme could not know the proper value yet.

As far as I can tell, the issue is fixed.

Incidentally, my driver report 16 as max anisotropic level.
