### ISSUE TITLE
Issue with ObjectViewer on #312

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#313]
### Description

When building from the makefile, the setting screen will not be displayed with F10 in ObjectViewer.
This phenomenon is common between Windows and Linux.
However, when building from Visual Studio or Mono Develop, this phenomenon does not occur.

### Reproduction

Build ObjectViewer from makefile.

### Related information 

* Operating system: Windows / Linux

**Comment by leezer3** [comment]
No idea exactly why that helps, I'm presuming MCS must be partially initialising it somehow, but there we go.

**Comment by s520** [comment]
I would like to confirm one, why use mcs?
Can we use xbuild instead?

**Comment by s520** [comment]
This problem does not seem to depend on the version of mcs.
I am using the latest stable version of mono.
`Mono C# compiler version 5.18.0.240`

By the way, why use mcs? Why not xbuild?

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/256e62ec23d59c8f76381c076b085d23afea3bda

Second attempt seems to work at this end on Windows, but it's broken the icon. (Adding it back again makes it crash as it can't find the embedded resources)

There's something a little funny about the form somewhere, can't put my finger on it at the minute.

mcs-
I didn't write the makefile myself, however:
It dates from ~2.5 years ago, and deliberately targets being able to build on Mono 3.2.8.
At the time it was written there were definitely issues with compatibility with xbuild vs. msbuild (I think they're discontinuing xbuild anyway in favor of msbuild?)

**Comment by s520** [comment]
I used this method at first.
There was a demand from the tester that we wanted to display the setting screen.
With this method, the setting will not be reflected unless you close the screen one after another.

I think that you may raise the lowest version of mono already.
In many distributions update of mono is stopped ...

**Comment by leezer3** [comment]
It's not quite clear what you mean there.

I **think** you're saying that something isn't refreshing after changing the settings?

If that's the case, then why not pull out the F5 refresh into a function, and call this immediately after closing the dialog?
Only issue with that would be that refresh of large objects can be slower than ideal.....

**Comment by s520** [comment]
I am not confident that it will be transmitted in my poor English...

I mean the following.

- Animated objects are animated immediately after setting the state of the vehicle.
- However, the current method stops updating the screen of the parent window while the dialog is displayed.
- I want to update the screen of the parent window while I display the dialog.
- So I suggested a way to open a dialog in a separate thread.

**Comment by leezer3** [comment]
Right, I see.

That's actually extremely problematic.
Winforms and threading are something that's been tried- The issues were actually Linux related in that case.

At this point, I'd say the blocking dialog is the better solution really.

**Comment by ginga81** [comment]
First, there is the completely difference between with F5(reloading) and parameter setteings.
When we are attempt to check the animated object with ATSxx parameter and accelerator notch, brake, doors and more, we must to run OpenBVE.
Additionally, we must do the same driving operation.

This PR is a breakthrough new debugging system of 'real-time parameter setting and check immediately' in ObjectViewer!
So, this is not a re-load action.

At the real-time parameter setting, the dialog closing everytime is a bad idea for User Interface.
If so, there is not difference from run OpenBVE everytime.

For example, my D51's drain cock is using two ATSxx parameters and accelerator notch.
If the dialog close everytime, we have to re-open everytime for each change combination.

If the dialog is always opening, only to switch each parameters and press apply button.
This is very easy, and useful operation for debugging.
So, we must to open always setting dialog.
![d51-6](https://user-images.githubusercontent.com/22734699/52902579-33413b00-3256-11e9-9a8f-87c7152e332b.jpg)
