### ISSUE TITLE
Problems with TrackFollowingObject

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#332]
### Description

Hello, I have been finally able to try out the new TrackFollowingObject feature and I am really impressed. Thanks to all the people involved for their effort!

However, I am also experiencing a few issues that I would like to point out. One is major, and the rest are aesthetic:

1. The TrackFollowingObject feature seems to be broken in the master branch after the commits related to the Station/Train refactor (merged later on the same day). The route and train tested, which are from the shinkansen demo, should be working out-of-the-box just by updating parts of the code to reflect the current name (TrackFollowingObject instead of OtherTrain). However, the result is that no train ever appears when it should. In addition, openBVE complains in the logs about not recognising the "Route.TFOXML" command.

2. Motor sounds are incorrect when running backwards. If the other train's direction is set to -1, B1 and B2 motor sounds are played instead of P1 and P2 when accelerating.

3. Brightness is ignored when another train appears. Other trains seem to be always placed at maximum brightness, regardless of the brightness defined for the track position where it initially appears.

![Captura de pantalla de 2019-03-31 15-45-33](https://user-images.githubusercontent.com/12414284/55290135-5cb1c280-53cf-11e9-8eaa-cd07eec94665.png)

### Reproduction

For all issues, first adjust the naming of "Route.OtherTrainXML" to "Route.TFOXML" in the CSV file and "\<OtherTrain>" and its closing tag to "\<TrackFollowingObject>" in the XML file.

1. The first issue can then be reproduced by compiling the current state of the master branch of openBVE and trying to load the route "single_line-waiting.csv" .

2. (Reproduced by building the s520:OtherTrain branch) Remove the motor B1 and B2 sections from E6's Train.dat file. When the other train accelerates after the crossing at the second station, no motor sound is played.

3. (Reproduced by building the s520:OtherTrain branch) Add a ".Brightness 0" command at the beginning of the route. While the player's train is dark, the other train seems to be unaffected by the brightness setting.

### Route and train

Touhoku Shinkansen + E6 with extra files (as provided by @s520 in https://github.com/leezer3/OpenBVE/pull/326). Specifically, route "single_line-waiting.csv" was used for the tests.

**Comment by leezer3** [comment]
Brightness is linked to the track segments using events.
Should be fixable without too much trouble, although the brightness really
wants setting on a per-track basis.....

Not sure how the station refactor broke things (arrgh....), but will be
dead simple again I'm sure.
All that reall did was to move a couple more bits around slightly.

Will sort tonight or tomorrow.

**Comment by leezer3** [comment]
Fixed the brightness and the loading issues.

Motor sounds will need a little investigation, I wonder if there's a wider bug.....

**Comment by MarcRiera** [comment]
Thanks, the train now is displayed and appears with the correct brightness.

I have done further tests with brightness and it seems, however, that interpolation is now completely ignored. Try placing two .Brightness commands with 0 and 255 one after another and you will notice that the other train changes brightness suddenly, unlike the player's train, which does it smoothly.

But I have also found the culprit for the false warning in the log: line 2857 in source/OpenBVE/Parsers/BVE/CsvRwRouteParser.cs still contains a reference to "othertrainxml". Changing it to "tfoxml" makes the warning disappear.

**Comment by leezer3** [comment]
We're getting there....

The brightness is actually somewhat of a pain in the neck.
In the current state (as of the last commit), it'll work *except* for the first brightness change of a track following object running in reverse.

Might just leave it at that; Re-writing the brightness with a track-specific command is on my todo list, and it might end up with this being chucked out the window.....
