### ISSUE TITLE
Type -3 for Track.Signal

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#336]
Hello,

I have come across a Japanese route for BVE4 using -3 as "type" for Track.Signal, which is not documented. While I have not been able to test it yet with BVE4 directly, from what I have been able to see in videos of this route, a regular three-aspect signal is displayed (it is treated as type 3).

openBVE handles it differently: while the parser includes the "-3" case for preprocessing (resulting in an error-free log), there is no case for it when parsing, which leads to the catch-all case being used (2-aspect signal, yellow and red). The real problem with the route is that this effectively lowers the speed limit to 45 kmph, which forces slow driving and makes the train run extremely behind schedule.

The route is "Kurumi Cape Line", available as an installer from https://web.archive.org/web/20120401012849/http://www.pure-and-tears.com/BVE/BVE4KTR.exe

Should we add a warning for this value and treat it as a regular three-aspect signal?

**Comment by leezer3** [comment]
BVE4 produces a standard 3-aspect GYR signal with this.

I think that's good enough to mimic but leave it undocumented.

**Comment by MarcRiera** [comment]
Perfect, thank you!
