### ISSUE TITLE
Problem starting OpenBVE-1.6.0.0 on Linux Mint 19.1

### ISSUE THREAD

**Issue by art-rasa** [leezer3/OpenBVE#337]
### Description

Hello all,

I downloaded the latest "openBVE-1.6.0.0.deb" package from "https://openbve-project.net/download/" but I'm having some issues starting it. My OS is Linux Mint 19.1 Tessa. I have also installed the "mono-complete" (version 5.20.1.19-0xamarin2+ubuntu1804b1) package from mono-project.

After installation, when I try to run the software from the command line, I get a dialog box that says: 
An older key-configuration file was found.
The current key-configuration has been reset to defaults.

When I click OK, another one appears:
Warning: The default key assingment file is an older version or corrupt.

After that another dialog appears:
Unhandled exception:
Index was outside the bounds of the array.

Following text is printed to the terminal:
[ERROR] FATAL UNHANDLED EXCEPTION: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at OpenBve.Interface.LoadControls (System.String FileOrNull, OpenBve.Interface+Control[]& Controls) [0x00242] in <d5078fc0703c4355b6dd6355b9e6eefe>:0 
  at OpenBve.Program.Main (System.String[] args) [0x0029c] in <d5078fc0703c4355b6dd6355b9e6eefe>:0

## Logs

I cannot get the software to start at all, so I cannot access the log feature.

### Related information 

* Operating system: Linux Mint 19.1 Tessa (based on Ubuntu 18.04 (Bionic Beaver))
* Method of control: keyboard

**Comment by leezer3** [comment]
I'm trying to reproduce at the minute. 
* First thing I note is that a clean install on a Ubuntu Bionic VM (what I had floating around, sorry....) with no prior versions of openBVE works OK. 
* Installing openbve-data (not required with the deb from the site) and then force-installing openBVE also seems to work.

---

Have you had installed any previous versions of openBVE?

The error sequence suggests that 1.4.3 was installed previously, and that we're picking up some older data, which is now incompatible.
Crashing isn't good though :(

Initial suggestion-
Delete the OpenBVE folder from your **.config** directory.

**Comment by leezer3** [comment]
A clean Mint 19.1 (Pulled straight from Osboxes) also works, so you've got something old hanging around somewhere.

First try removing the OpenBVE folder from your .config folder.
If this doesn't do the trick, I'd try purging all openBVE related packages:
```
apt-get --purge remove openbve
apt-get --purge remove openbve-data
```

Then reinstall the 1.6.0.0 deb.

If this doesn't work, we'll have to do a little more digging as to where it's finding the offending file.

**Comment by art-rasa** [comment]
I was able to start the simulator after removing the directory "~/.config/OpenBve".
Thanks a lot!

**Comment by leezer3** [comment]
No bother.

I think the next version will probably handle this a little more gracefully also.
