### ISSUE TITLE
Problem when open extensions.cfg in Object Viewer

### ISSUE THREAD

**Issue by khrismasugandi** [leezer3/OpenBVE#339]
### Description

Hello, in my Object Viewer can't read Length value, when me write it, object not load and 1 error message. 

> Unhandled error (Object reference not set to an instance of an object.) encountered while processing the file...

And when I load [car0] and [car1] not with Length, only [car0] appear, [car1] get error like Length.

Can you check it ? All my train get that error, sorry for my bad grammar, thanks.

### Related information 

* Windows 10
* 4GB RAM
* Object Viewer v1.5.2.0 (in installer Openbve v.1.6.0.0)

**Comment by leezer3** [comment]
Should be fixed from this build onwards:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2019-04-23.zip
