### ISSUE TITLE
Train headlights are not working

### ISSUE THREAD

**Issue by art-rasa** [leezer3/OpenBVE#342]
### Description

When I try to drive a night-time route, it's very difficult to see anything because the train's headlights do not seem to work. 
When the simulation begins and the reverser is in Neutral position, the train appears to be glowing some very dim light on the tracks ahead. But when the reverser is moved to "Forward" position, the lights are immediately turned off. On "Backward" position I can see the glow of the red tail lights. I noticed that there's a key binding ("H" key) for Headlights but it does not seem to make any difference for me. 
I took the following three screen shots of the game:
1. Reverser "Neutral":
![1neutral](https://user-images.githubusercontent.com/10067188/56982795-c833af00-6b8a-11e9-84dd-cd3b91269f5a.png)
2. Reverser "Forward":
![2forward](https://user-images.githubusercontent.com/10067188/56982813-d255ad80-6b8a-11e9-9d4f-66dab4412570.png)
3. Reverser "Backward":
![3backward](https://user-images.githubusercontent.com/10067188/56982824-daade880-6b8a-11e9-83d8-a9e88d6a1e26.png)

### Reproduction

It happens every time I drive the Birmingham night route.

## Route

I installed the route "Birmingham Cross City South" from the Ubuntu software repository. 

## Train

I have installed the Class 323 EMU from the Ubuntu software repository.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.
[log.txt](https://github.com/leezer3/OpenBVE/files/3132497/log.txt)

### Related information 

* Operating system: Linux Mint 19.1
* Method of control (Keyboard, joystick, RailDriver): keyboard

**Comment by leezer3** [comment]
That's actually exactly how it's supposed to look.

The headlights keybinding only works on a few trains (it's a much newer addition & not well used), but at least in UK practice the headlight is not intended to light the route ahead, but rather to make your train visible to others :)

**Comment by art-rasa** [comment]
Okay, thanks for your clarification. I just realized that I had no idea what kind of headlights trains actually have. I always assumed their brightness would be (at least) comparable with the headlights of a bus or truck.

**Comment by leezer3** [comment]
No problem.

I can only speak from experience for UK / EU practice, but as far as I'm aware this is a pretty universal thing.

The fundamental difference between a train and a bus / truck is that a train travels on a fixed route, and the signalling system is the guarantee that the track ahead is clear.
Hence, you drive to your knowledge of where you are / the route ahead, not what you can see  :)

**Comment by art-rasa** [comment]
I decided to close this issue. Again, thanks for your input & information.
