### ISSUE TITLE
[Suggestion] Cab mouse support

### ISSUE THREAD

**Issue by JakubVanek** [leezer3/OpenBVE#35]
Hi,
I've seen this feature in TRS 2006 and I'd be happy to see it in openBVE. Example: you can use mouse drag to increase brake pressure. I understand that this is virtually impossible to implement with current train format,  so I suggest it as a feature for eventual new format.
<img width="300" alt="trainz_2014-0424-07_driver_cab_mode_sequence_norfolk_ _western_route-02" src="https://cloud.githubusercontent.com/assets/6003171/13550548/b3dc5d7c-e320-11e5-962f-a032f9830500.png">
Best regards and thanks for continuing openBVE development,
Jakub Vaněk
Note: as I read documents in #34, I read Michelle has also thought of this, see "The potential future"

**Comment by mgavioli** [comment]
Are we sure "_this is virtually impossible to implement with current train format_"? Just a few days ago, I tried to learn more about this point; eventually I lost my track (!) in the intricacies of the code, but things might be incomplete but not hopeless!

A number of controls are unequivocally identified in the panel2.cfg (`[DigitalNumber] / Subject = power / Location = <x>, <y>`, `[DigitalNumber] / Subject = brake / Location = <x>, <y>` and so on) and end up in a specific screen position. Then, the system has all the info needed to know when the mouse pointer clicks on them.

Figuring out the exact final screen coordinates, according to POV movements, might be non-trivial (particularly for 3D cabs, I would say), but it should be deterministic.

For some, it might be unclear whether they are controls or displays (`[DigitalNumber]` in itself does not tells if it refers to a numeric read-out or to discreet-step input); for other, the `Subject` should be enough.

So, even with the current train format, **some** mouse operations could be possible; and this would already be a plus. A complete solution might need an extended train format, for which the extended functionality should be weighted against the cross-version compatibility issues.

An I missing something? (Well possible, given that I am still familiarizing with openBVE internals)

**Comment by leezer3** [comment]
Virtually impossible is a little OTT-
It's certainly possible, but not trivial.

Internally, 2D cabs are simply translated to a 3D animated object, and a specific set of camera restrictions applied.
This means, that in order to actually do this, we'd need to add a field to animated objects, which describes the specific mouseover function of each item.

The 3D code is a classic case of making it hard to do this though.
Rather than moving the camera through a scene (Whereby each object retains the 'same' 3D co-ordinates to be tested against), the scene is destroyed, moved and recreated each frame.

As I understand it, this was done because of the limitations of the current routefile format (Note the 
separate topic on the OpenBVE2 techdemo)

In a 2D cab, I think it should probably be possible to extrapolate from reading the current zoom and pan figures, but 3D cabs get ugly fast....

Thinking about it.

**Comment by JakubVanek** [comment]
For what I meant virtually impossible - that was mainly for handles in 2D cabs - I don't know how to analyze bitmaps to know how to handle mouse move. Of course some kind of popup would solve that.
Buttons and 3D cabs could be less difficult.

**Comment by mgavioli** [comment]
Well, I may easily fail to see the obvious, but it seems to me that the mouse operations could be limited to (only?) two, largely independent from the actual bitmap images:
- if the control is a button (`[PilotLamp]`), just click to operate; once the `Subject` is properly identified, this could tell if the button is a toggle (1 click to engage - 1 click to disengage, like doors) or an engage-while-pressed type, like the horn
- if the control is a slider/lever (`[DigitalNumber]`), drag UP to increase and DOWN to decrease, regardless of the actual orientation of the control.

This is what I personally would expect anyway. Too simplistic?

Of course, this still assumes that:
- a fair number of controls can be identified by `[<Type>]` and `Subject`
- actual on-screen coordinates of a relevant point of the control can be identified and computed from `Location = <x>, <y>`

Not trivial at all, but perhaps doable for a decent amount of useful controls on a decent amount of existing trains?

Later on, an extended train format could allow more (but I believe 3D-to-2D projection issues and POV-dependent calculations -- which are the hard part -- would still apply and be largely the same, though).
