### ISSUE TITLE
Questions about the motor sound section of sound.xml

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#359]
I think that the current sound.xml is as follows, according to [this](https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Xml.cs#L544).

```xml
<?xml version="1.0" encoding="utf-8"?>
<openBVE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <CarSounds>
    <Run>
      <Sound>
        <Index>0</Index>
        <FileName>Sound\run0.wav</FileName>
      </Sound>
    </Run>
    <Motor>
      <0>
        <FileName>Sound\motor0.wav</FileName>
      </0>
    </Motor>
  </CarSounds>
</openBVE>
```

There is no problem with the Run section, but because the Motor section contains numbers in the element name, it is invalid XML.

However, [this](https://github.com/leezer3/OpenBVE/blob/master/source/CarXMLConvertor/Convert.SoundCfg.cs#L96) is normal XML because it is written in the same way as the Run section.

May I modify the parser to match the CarXMLConvertor writing method?

**Comment by leezer3** [comment]
No trouble, go for it :)

Must have slipped through, surprised the Microsoft XML parser thinks it's valid XML at all....

**Comment by s520** [comment]
Thank you.
I will put out PR along with the update of MotorSoundEditor.
I think that I got an error in XDocument.
