### ISSUE TITLE
Incomplete Display Of Extensions.Cfg & *.Animated In ObjectViewer.Exe

### ISSUE THREAD

**Issue by OpenBveTrainSim** [leezer3/OpenBVE#373]
Chris:
Downloaded & briefly tested the 2019.0820 beta version.
OpenBve.Exe seems good on a quick test run, but ObjectViewer.Exe only partially displays 
the consist assemblies Extensions.Cfg & Train.Animated for this train
http://www.mediafire.com/?ertdlgmf0818gv0

My previous version was the 2019.0801 beta.
Several significant code revisions since then, not sure in which this bug first appears.
Thanks, OBTS.

**Comment by leezer3** [comment]
I believe fixed by https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2019-08-21.zip

**Comment by OpenBveTrainSim** [comment]
Chris:
Fixed with 2019.0821 beta.  Your quick response is always appreciated.
Thanks, OBTS
