### ISSUE TITLE
[Suggestion] Aggregation of bug information

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#375]
I think bug reports are now distributed across GitHub and forums.
I am particularly concerned that it is unclear how bug reports in the forum have been resolved and, if so, how they have been resolved. (Difficult to track)
In the future, I think you should consolidate on GitHub or use another BTS.

What do you think?

**Comment by leezer3** [comment]
Agreed this is an issue, but actually getting people to post here is a challenge in the first place.

Most 'regular' users don't know what source code is, let alone how to file a bug in here.
I probably ought to open issues for the major bugs that are being worked on (e.g. http://bveworldwide.forumotion.com/t1297p475-openbve-1-5-0-rc1-bugs#top )

**Comment by s520** [comment]
Well... at least can you not split the forum bug report posts?
In addition, it would be nice to have a bug report template like this one.

**Comment by s520** [comment]
Since the bug report item has been newly added to the forum, this issue will be closed.
http://bveworldwide.forumotion.com/f20-bug-reporting
