### ISSUE TITLE
[Suggestion] Manage XLF files with Trainsifex

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#382]
I created a test project to manage XLF with Transifex and confirmed that it was good.

I can also synchronize the multi-language and update the en-US.xlf.

I sent a request to transfer my test project to the Transifex OpenBVE organization.
https://www.transifex.com/openbve/public/

Please check it.

Please refer to the following page for cooperation with GitHub.
https://docs.transifex.com/transifex-github-integrations/github-tx-ui

Since only en-US.xlf is the target this time, it is better to use the functions built into Transifex.

**Comment by s520** [comment]
In addition, would you give me admin rights for the maintenance of the Transifex project?

**Comment by s520** [comment]
@leezer3 
What do you think?

**Comment by leezer3** [comment]
This *should* now be in place (I think....)

**Comment by s520** [comment]
Thank you for your hard work.
