### ISSUE TITLE
MisInterpreted [MESHBUILDER] Lines In *.B3D Objects

### ISSUE THREAD

**Issue by OpenBveTrainSim** [leezer3/OpenBVE#383]
Chris:
Downloaded & briefly tested 2019.0905 beta version.
On loading ObjectViewer.Exe with Extensions.Cfg & Train.Animated for this train
http://www.mediafire.com/?ertdlgmf0818gv0
Press [F9] for details of specific errors on [MESHBUILDER] lines in *.B3D objects;
possibly trailing ";" comments on those B3D lines which are being mistranslated?
Same error possibly contributing minor but irritating annomolies to the locomotive assemblies in the main program openbve.exe?

2019.0828 beta version & prior did not have these errors.
Thanks, OBTS.

**Comment by leezer3** [comment]
Latest build should fix this when it generates.
