### ISSUE TITLE
[Urgent] About Transifex permissions

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#385]
Currently, Korean users are applying for participation in our Transifex project.
I would like to approve immediately while they are interested, but I am not authorized.
So give me administrator rights for the Transifex organization.
Please.

This post was translated by F81 tec200. I really appreciate it.

**Comment by leezer3** [comment]
I've added you as admin and approved.

Please remember that I work, and I'm in a different timezone :)

**Comment by leezer3** [comment]
n.b. Not sure it'll let us transfer across the XLIFF test on Transifex.
It has a warning about exceeding the allowed word count if we do so.

I will try and get in touch with them (likely to be next week), as I can't see any clear limits as to what the open source does or doesn't allow, and it may just be a case of asking nicely.

**Comment by s520** [comment]
Thank you for listening to my sudden request.
I was saved.

**Comment by s520** [comment]
I understand that you live in different time zones.
It was absolutely necessary. I'm sorry.
