### ISSUE TITLE
Nuget Issues

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#387]
### Description

Have just noticed that the DotNetZip file which is now being used to provide Zlib decompression is broken with MSZip (Doesn't allow the dictionary state to be set unconditionally any more).
I've opened a PR at their end:
https://github.com/haf/DotNetZip.Semverd/pull/176

Depending on what the response from this one is, may need to revert back to the local copy.
cc @s520

**Comment by s520** [comment]
Oops, it seems that the activity has stopped for more than two months, so it seems to need to be restored. (At least temporarily?)
