### ISSUE TITLE
No motor sounds when using sound.xml

### ISSUE THREAD

**Issue by PC28K** [leezer3/OpenBVE#388]
### Description
no motor sound using sound.xml, normal for sound.cfg, no error in log.
run and other sounds are normal.
original train data was imported into trainediter2 to export sound.cfg to xml.
https://pcws.kr/file/2019.09.10-19.32.mp4

## Route
route is uchibo line for bve4 (bvets.net)

## Train
train is https://www.youtube.com/watch?v=tBweD9T2b3Y

## Logs
openBVE Log: 2019-09-10 오후 7:47:08

19:47:09  Initialising game window of size 960 x 600
19:47:09  Game window initialised successfully.
19:47:09  Loading route file: G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:09  G:\ob\userdata\railway\Railway : Railway folder found.
19:47:09  Route file format is: CSV
19:47:10  FileName G:\ob\userdata\railway\Railway\Object\PCheck.bmp not found in Track.Marker at line 307, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 345, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 428, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1493, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  RailIndex1 6 could be out of range in Track.Crack at line 1529, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1560, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1622, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1702, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1741, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1788, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1870, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 1886, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 2008, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 2087, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  BeaconStructureIndex 5 references an object not loaded in Track.Beacon at line 2178, column 1 in file G:\ob\userdata\railway\Railway\Route\Uchibo\1157M.csv
19:47:10  Route file loaded successfully.
19:47:10  Loading player train: G:\ob\userdata\train\test
19:47:10  Loading train panel: G:\ob\userdata\train\test\panel2.cfg
19:47:11  Train panel loaded sucessfully.
19:47:11  Loading train plugin: G:\ob\userdata\train\test\atc\atcfs.dll
19:47:11  Train plugin loaded successfully.

### Related information 
win10 x64 korean, .net 4.0

**Comment by leezer3** [comment]
This build should fix the not playing motor sounds issue:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2019-09-10.zip
(Refreshed just now)

I can also get that train to cause a crash in TrainEditor2 when attempting to playback the motor sounds.
I believe @s520 is working on that in this branch at the minute:
https://github.com/s520/OpenBVE/commits/TE2_Fix

**Comment by s520** [comment]
Thank you for your correction.
Check the linked pull request for your problem.

**Comment by PC28K** [comment]
It works well. thank you

**Comment by leezer3** [comment]
No problem, and thanks!
