### ISSUE TITLE
Project homepage's link is broken

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#391]
https://openbve-project.net/ 's link is broken now.
At the top page,  Latest Stable Release: is not changed to 1.7.0.0.
At the download link's, Windows and Debian is 404 not found.
Please repair these.

**Comment by leezer3** [comment]
Ouch, thought I checked those :(

**Comment by ginga81** [comment]
Thank you for fix rapidly.
Latest Stable Release:'s message is still not change to 1.7.0.0.
Please re-check it.

**Comment by leezer3** [comment]
Try again.....

Might get there eventually.
Need to automate this though.

**Comment by ginga81** [comment]
Works well!
Thank you very much to repair!
