### ISSUE TITLE
TrackFollowingObject does not works well(ver 1.7.0)

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#394]
Now, I am creating TrackFollowingObject on 1.6.0.
My data is works well on 1.6.0.
Recently, I tested same data on 1.7.0.
But, the TFO cannot see at the same position on the route.
And the sound is hears at the all of route(100km over away, not relate the distance).
The time of sounds hearing is the same time of TFOXML's data, but not change the volume, always maximum.
So, I checked the daily-builds.

OpenBVE-2019-07-08.zip OK
OpenBVE-2019-08-08.zip OK
OpenBVE-2019-08-09.zip OK
OpenBVE-2019-08-11.zip OK
OpenBVE-2019-08-13.zip OK
OpenBVE-2019-08-15.zip NG. same issue of ver 1.7.0
OpenBVE-2019-08-26.zip NG. same issue of ver 1.7.0
OpenBVE-2019-08-28.zip NG. same issue of ver 1.7.0
OpenBVE-2019-08-29.zip NG. same issue of ver 1.7.0
OpenBVE-2019-09-01.zip NG. same issue of ver 1.7.0
OpenBVE-2019-09-02.zip NG. cannot choose the route.
OpenBVE-2019-09-03.zip NG. same issue of ver 1.7.0
OpenBVE-2019-09-05.zip NG. before the choose, cannot preview the route.
(displaying the route information's textbox with the message of "A null reference or invalid value was found [GDI+ status: InvalidParameter]")

So, I suspect with trouble from OpenBVE-2019-08-15.zip(v1.5.1295.1080-travis) or later version (also with 1.7.0).

Please check this issue.

**Comment by leezer3** [comment]
My apologies, I think today's build should fix this.

What I was expecting to be stored as a reference type was actually cloning an array unexpectedly, as there's a getter / setter in use elsewhere.
Rather complicated to explain clearly.....

Also found a related issue with sound positioning relative to moveable animated objects, which this should also fix.

Let me know, and I'll get a hotfix pushed out.

**Comment by ginga81** [comment]
I tested at OpenBVE-2019-09-22.zip(v1.5.1333.1186-travis), the TFO works well again!
Thank you very much for fix this.

**Comment by leezer3** [comment]
Good.

Found & fixed several more issues this morning, although a couple of those were rather more long-standing.
Will try and get the hotfix out tomorrow assuming nothing else comes up.

**Comment by ginga81** [comment]
I checked 1.5.1134.651-trabis, good result and sound hearing from direction is repaired.
Thank you very much!

**Comment by leezer3** [comment]
Hotfix version 1.7.0.1 now live on the main site.
