### ISSUE TITLE
Error in file system

### ISSUE THREAD

**Issue by ManuelMejias** [leezer3/OpenBVE#398]
A friend of mine is haviving troubles with openBVE version 1.7.0.1 he can't run this version on Windows 8

Here is a screenshot
![image](https://user-images.githubusercontent.com/38114108/65714689-a0794200-e069-11e9-8fac-f51dec9ad618.png)

And here are the PC specs.
![image](https://user-images.githubusercontent.com/38114108/65714669-95bead00-e069-11e9-9b2b-bb6242802401.png)

**Comment by s520** [comment]
This error occurs when .NET Framework 4.6.1 or higher is not installed.
Current OpenBVE requires 4.6.1 or higher. Recommended is 4.7.2 or higher.
