### ISSUE TITLE
Website: clearly publish Public Domain/Copyright status

### ISSUE THREAD

**Issue by sladen** [leezer3/OpenBVE#400]
The important part of the *OpenBVE* project is the source code being *open*.  At the moment the website states only:

  https://openbve-project.net/

    © 2019 The OpenBVE Project. Powered by Jekyll.

Ideally text would be updated to something like:

    © 2009‒2019 OpenBVE contributions + released into the Public Domain.  Website powered by Jekyll.

and a link to a new page:

* https://openbve-project.net/copyright

giving the exact details of the licence/contributors/authors/copyright situation.  For this page, it should be possible to view + use some of the information from:

* https://salsa.debian.org/debian/openbve/blob/debian/sid/Contributing.md#code-licencing
* https://salsa.debian.org/debian/openbve/blob/debian/sid/Contributing.md#list-of-contributors
* https://salsa.debian.org/debian/openbve/blob/debian/sid/debian/copyright#L8
* https://salsa.debian.org/debian/openbve/blob/debian/sid/debian/copyright#L13
* https://salsa.debian.org/debian/openbve/blob/debian/sid/debian/copyright#L217

*(see discussion at: https://github.com/leezer3/OpenBVE/issues/330#issuecomment-536654637 )*

**Comment by leezer3** [comment]
Footer updated.

Draft page here, which covers the discussion I think:
https://openbve-project.net/copyright/

(not going public with this at the minute without discussion from elsewhere)
It's been easiest to simply add the current contributors as a link to the GitHub generated list.

n.b. The open-source and licence-free status has always been the first line on the homepage (Lifted from the original site!), but it's definitely a good call to make things clearer.

**Comment by s520** [comment]
Is cheers for good work.
After that, I think that it is necessary to add authors of translation files that are not listed on the GitHub contributor page.

**Comment by leezer3** [comment]
Now in the public footer, and linked from the Links bit of the menu for good measure.
