### ISSUE TITLE
2019Oct07 Beta ObjectViewer.Exe Errors

### ISSUE THREAD

**Issue by OpenBveTrainSim** [leezer3/OpenBVE#404]
@leezer3,
Test runs of 2019Oct05 Beta + 2019Oct07 Beta:
~ OpenBve.Exe works using OLD+NEW renderer, did not notice any missing or distorted objects.
~ ObjectViewer.Exe improperly displaying Extensions.Cfg or Train.Animated for train
http://www.mediafire.com/?ertdlgmf0818gv0
Misplaced components of *.Animated assemblies 
If Ctrl+G is enabled, erroneous red ground plane, instead of XYZ\RGB axis vectors.
Thanx OBTS

**Comment by leezer3** [comment]
I think we're finally getting there (previous fix seems to have been incomplete in some areas).

Today's build fixes those along with some other stuff, and may be marginally faster.
Still need to do more work on the speed, but need to get these kinks worked out first....

**Comment by leezer3** [comment]
Hmm.

The Z axis pitch seems to be reversed, Somethings interacting somewhere, will take a look, as it's a little funky...

**Comment by leezer3** [comment]
Today's build fixes that one, thanks for the help :)

**Comment by OpenBveTrainSim** [comment]
Appears to be fixed.
Another one can be closed!
Thanx OBTS
