### ISSUE TITLE
Panel.xml is not works well at 1.7.1.0

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#411]
This sample touch elements demo data is works well at 1.7.0.3.
[testpanel-demo.zip](https://github.com/leezer3/OpenBVE/files/3935760/testpanel-demo.zip)
But at 1.7.1.0, this data is seems as panel.animated.

Additionally, the touch area can recognition seems perfectly, it cannot work to the changing the screens.
(It seems not work, but the screens are in close contact with each other and displaying quickly about 60fps. So, it is working maybe good.)

When we are using the Panel.xml, the all of 3D object's UV are not pasted, all white.
Please look at this screenshot.
![Panel xml](https://user-images.githubusercontent.com/22734699/70382874-d65e6f00-19a6-11ea-8302-bf78e7b76e86.jpg)

When this sample data is loading and if the Load in advance option is off, and Unload unused textures or Enabale the new renderer option is on, OpenBVE is crash with coredump.

Can you check it out ?

**Comment by leezer3** [comment]
I can reproduce the crash, but not the UV issue.
I presume you should have a grass texture on the ground and textures on the objects in the background?

May take a few days to get to the bottom of it, but will try and do so. First impressions is that a bufffer isn't bound correctly somewhere.
cc @s520 any thoughts?

**Comment by s520** [comment]
I cannot reproduce the UV problem, but I can reproduce the panel display problem.
I think the display issue on this panel is due to [the commit](https://github.com/leezer3/OpenBVE/commit/52b8b08346fe2025b37680474d6a0280f582b8c7) made to the #405 proposal.

The following nightly builds were normal.
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2019-11-24.zip

**Comment by leezer3** [comment]
Interesting, thanks!

I can't see anything immediately obvious in the camera restriction commit, and it doesn't touch any openGL / VBO calls at all.

I'll try and pull apart all the commits from the 28th over the next few days and see where we go.

**Comment by s520** [comment]
I think the camera restriction has been lifted accidentally in the case of Panel.xml.
I think the following parts are suspicious.
https://github.com/leezer3/OpenBVE/commit/52b8b08346fe2025b37680474d6a0280f582b8c7#diff-6dea8cfed5f14fc09b2fefad85e9802cL75

**Comment by s520** [comment]
Also, it seems that the screen transition due to touch is not successful in the November 24 nightly build.
This should be investigated separately.

**Comment by leezer3** [comment]
Now something is definitely interesting.

The linked build from the 24th definitely seems to be demonstrating the texture bug here, but it seems to have been fixed (accidentally, wasn't looking for it!) in the master branch.
Probably this commit: https://github.com/leezer3/OpenBVE/commit/965a29ee057739422a40a9739f3b8e5d088c7ac2

I can get the crash going all the way back to the first merge of the new renderer though.
Suggests to me we're missing stupid- Sharing the vertex data with the visble and touch faces, but clearing it after the render pass for the visble face or something?

**Comment by leezer3** [comment]
I think we've got a timing / threading problem here.

Specifically, on a minimal install, I've discovered the cause of the access violation to be that the VAO handle is 0 when it crashes.
This looks very suspicious:
https://community.khronos.org/t/glgenvertexarrays-returns-0-without-glerror-in-worker-thread/69974

**Comment by leezer3** [comment]
Yep, that nails it....

The commit above is a slightly dodgy fix, but it'll do for the moment.
Longer term, we'll need to think about specifically checking for the openGL context and add a locker or something for anything like this.

Should hopefully just be the glitch with camera restriction now. (I suspect the touch glitch is just an artifact of that TBQH)

**Comment by leezer3** [comment]
Better, but not there yet....

That fixes the restriction problem, but the screen hiding is still funny.
Shifting the camera around makes the correct object appear / disappear, which is odd. The click zones are still in the right place though.....

**Comment by leezer3** [comment]
OK, I think all issues should now be fixed after today's build generates.

I'm still working on lighting and render speed, but will try and get a fixed version out over the next day or so (This may still have a minor glitch or two, but it's in a lot of cases an order of magnitude faster than 1.7.1.0 and is important to get out there)
