### ISSUE TITLE
Improve SDL2 joystick input

### ISSUE THREAD

**Issue by v1993** [leezer3/OpenBVE#412]
I'm using SDL2 input backend for a bunch of reasons and would like to suggest some improvements:

1. Quite obviously, make it possible to configure it in main menu.
2. It seems that GameController API is used (correct me if I'm wrong)? If so, you probably should use just Joystick, it can make life a lot easier.
3. SDL2 provide both names and GUIDs for joysticks, so you can detect same and different ones with ease, making connection order irrelevant and names fancy. You still use numbers for other backend as placeholder.
4. SDL2 have hotplug support. Not top priority, but would be very nice to have.

**Comment by v1993** [comment]
By the way, I'd really like to thank you for your efforts on OpenBVE development. It is an excellent simulator and your improvements are great!

**Comment by leezer3** [comment]
Will take a look, although may be next week.

We don't use SDL2 directly though, just the OpenTK SDL2 backend.
IIRC being unable to configure a SDL2 joystick in the main form is an artifact of this, something to do with contexts I think...

Could possibly add an axis dropdown or something for use in this case?

**Comment by v1993** [comment]
So you're not using SDL2 directly? Man, this removes a lot of improvement possibilities :\

Probably even entering entering joystick id + button number/axis number and direction would be pretty fine (would be even better if both systems were in place where it is possible as some joysticks have switches which report as constantly pressed buttons and screw whole "press the button" thing).

Speaking of, with a bit of coding I managed to use WiiRemote as power/brake lever with OpenBVE. This seems pretty nice to me.

**Comment by leezer3** [comment]
Hotplug and name support are now in the latest version with an OpenTK bump, so closing this.
