### ISSUE TITLE
1.7.1.0 does not load route. Gets SIGABRT. Linux/Mono

### ISSUE THREAD

**Issue by edgreenberg** [leezer3/OpenBVE#414]
### Description

OpenBvE 1.7.1.0 oes not load a route. It gets SIGABRT.  1.7.0.0 seems to load that route fine. 

### Reproduction

Run openbve 1.7.1.0 from the command line with "mono OpenBve.exe" and launch a route

## Route

Happens with several routes  

## Train

Happens with several trains

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system
Fedora 28
* Method of control (Keyboard, joystick, RailDriver)
Happens with or without joystick connected. 
[OpenBVE Crash- 2019.12.20[18.28].log](https://github.com/leezer3/OpenBVE/files/3991368/OpenBVE.Crash-.2019.12.20.18.28.log)

[openbve1710run.txt](https://github.com/leezer3/OpenBVE/files/3991376/openbve1710run.txt)

**Comment by leezer3** [comment]
The stacktrace suggests that Mono itself is falling over when it tries to load the shaders into openGL.
We simply can't guard against that one I don't think.

My immediate suggestion would be to try updating Mono with the most recent version from Mono direct, as the distribution supplied versions tend to be somewhat outdated.
openBVE officially requires Mono 5.20 (IIRC most things other than TrainEditor2 work on lower versions, but I haven't actually tested that properly recently), and I believe Fedora 28 shipped with Mono 4.8.

Fedora 28 is also out of support with Fedora themselves.

Mono provide packages for Fedora:
https://www.mono-project.com/download/stable/#download-lin-fedora
