### ISSUE TITLE
rail sounds is not seem to change or hear at 1.7.1.1

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#419]
I tested my route of Tohoku-shinkansen at 1.7.1.1.
But, it was not hear the railroad switch's sound.
And tunnel's sound is also not change.
I think perhaps more rail sound - such as bridge is may be not changed.
Could you please confirm it?

**Comment by leezer3** [comment]
Fixed.

1.7.1.2 should be up shortly, my apologies. 
(This relates to a somewhat complicated side-effect of the dynamic keyword- Child structs of a class called using this seem to clone)

**Comment by ginga81** [comment]
Thank you very much for fix.
My data, especially the car modeling is more than 10000 polygons of a each car.
This version is seem to more faster drawing. 
High performance drawing is more helpful for all users.
Thank you very much for release this version!
