### ISSUE TITLE
LinearGauge isn' t working?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#421]
I tested this sample data. 
I think that the LinearGauge isn't works.
Would you please check?
[lineargauge.zip](https://github.com/leezer3/OpenBVE/files/4061287/lineargauge.zip)

**Comment by leezer3** [comment]
Can you describe exactly what you're trying to do with this?

It looks to me like you're trying to do a spinning seconds dial?

Not sure this is going to be supported with the current LinearGauge without some fiddling.

Might need to add some more time related variables if you're thinking of a rotating digital clock :/

**Comment by ginga81** [comment]
Now, I am writing the TrainEditor2's tutorial.
I want to show what doing the LinearGauge act at sample.
At this sample, I am going to create a LinearGauge, Subject is set to sec.
I think that the LinearGauge is get from a Subject, and convert to bar-type value.
If the Subject set to sec, I think that the LinearGauge is changing automatically from 0 to 59sec.
The time that the 0 sec equal the LinearGauge shows gauge zero(nothing fill).
And If the value is 59, the LinearGauge shows maximum and fillng full.
I imagine like above.
I think also imagine that the LinearGauge is deformation a image file by value.
But, did not deformation and filling.

This time, this data is for tutorial.
I thought that the Subject can set to freely.
If it is not, I change the sample, so, not necessaly for fix.
If the Subject is not set freely, please tell me what Subject can set to LinearGauge.

**Comment by s520** [comment]
The current LinearGauge applies the amount of change only in the horizontal direction in the X and Y directions.
https://github.com/leezer3/OpenBVE/blob/0801e1abc8036b8948ba59adf4cbb918ba7deddb/source/OpenBVE/Parsers/Panel/Panel2CfgParser.cs#L754

So I think I should add "Minimum" and "Maximum" for Y direction.
Ex: Minimum = 1, 3

**Comment by leezer3** [comment]
That seems OK.

Other option would be to swap the values based upon the texture shift direction, but that creates confusion about what's actually W / H :/

**Comment by s520** [comment]
Please tell me the vehicles and samples on which LinearGauge works.

We may have a perception gap.
I want to display something like a bar graph.
This may not be what LinearGauge is expecting.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/pull/101

See the first comment in this for what this was intended for- A needle or similar which moves horizontally or vertically along a track.
I can't remember offhand who has implemented this (sorry!), but there's at least one user about.

**Comment by s520** [comment]
Thank you.
After this explanation, I felt that the description of the document was insufficient.
https://openbve-project.net/documentation_hugo/en/trains/panel2_cfg.html#lineargauge

Our documentation lacks descriptions such as DaytimeImage.

**Comment by ginga81** [comment]
Liniarguage itself's issue is fixed.
If we want to 'another' LinearGauge, we create new issue.
So, this issue is closed.
