### ISSUE TITLE
Issue with DaytimeTexture in CSV object

### ISSUE THREAD

**Issue by s520** [leezer3/OpenBVE#425]
### Description

This is the problem that my friend encountered.

He is trying to reproduce the reflection of the LCD screen in CSV objects.

At that time, he wants to separate the base LCD screen from the reflected object, display the reflected object during the day, and not display it at night.

Specifically, look at the CSV object of the attached file.

[test.zip](https://github.com/leezer3/OpenBVE/files/4111619/test.zip)

The description of each image is as follows.
- base.bmp : base LCD screen image
- alpha.png : reflected image
- no.bmp : transparent image

In the current process, the Nighttime polygon is overlaid on top of the Daytime polygon, the Nighttime image is transparent and the Daytime polygon is displayed as it is.

I tried to make Daytime polygons transparent like Nighttime polygons.
https://github.com/s520/OpenBVE/commit/db3194cf6e7811c11c96f16ea466c1381ecca5df

Daytime polygons are now transparent, but are white when transitioning from day to night.
(Please check with ObjectViewer of my branch.)

It seems that this change is not enough.

Can you help me solve the problem?

**Comment by leezer3** [comment]
Hmm....

Something isn't quite right there :(

This change isn't helping:
https://github.com/leezer3/OpenBVE/wiki/Errata#lighting-behaviour-with-the-same-texture-defined-for-both-daytime-and-nighttime
```
CreateMeshBuilder,
AddVertex, 0.213, 0.146, 0.082, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.0, 0.006, 0.0, 0.46, -0.888,
AddVertex, 0.213, 0.0, 0.006, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.146, 0.082, 0.0, 0.46, -0.888,
AddFace, 0, 2, 1,
AddFace, 1, 3, 0,
LoadTexture, base.bmp,
SetEmissiveColor,255,255,255
SetColor, 255, 255, 255, 255,
SetTextureCoordinates, 0, 20.0, -7.0,
SetTextureCoordinates, 1, 19.0, -6.0,
SetTextureCoordinates, 2, 20.0, -6.0,
SetTextureCoordinates, 3, 19.0, -7.0,
```
Changing the screen to be emissive (the correct way to do it in the first place, not using this bug) helps, but doesn't explain why our alpha isn't working.

**Comment by s520** [comment]
It was a blind spot.
On my branch, this looks like he is doing what he wants.
The reflection image is blended well.

The fact that the alpha doesn't work isn't the example object alpha.png, right?

**Comment by leezer3** [comment]
Some more playing and testing shows that applying my 'fix' above to the object actually produces what appear to me to be technically correct results after fixing the linked bug- My error.

(Object Viewer's nighttime lighting isn't actually at complete pitch black)

I however have found a minority of nighttime routes using this 'effect'.

Haven't got a good answer as to how to get around it at the minute; I think we may have to revert the errata by default, but add something to control it by default in the options :(

**Comment by leezer3** [comment]
Hang on, mixing branches and confusing even myself here :/

In order to make the alpha work right and not break anything existing, we'd need an entirely new blend mode- Subtractive blending.

Working copy:
https://github.com/leezer3/OpenBVE/tree/Subtractive

Amended object:
```
CreateMeshBuilder,
AddVertex, 0.213, 0.146, 0.076, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.0, 0.0, 0.0, 0.46, -0.888,
AddVertex, 0.213, 0.0, 0.0, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.146, 0.076, 0.0, 0.46, -0.888,
AddFace, 0, 2, 1,
AddFace, 1, 3, 0,
LoadTexture, alpha.png, no.bmp,
SetBlendMode,Subtractive
SetColor, 255, 255, 255, 255,
SetDecalTransparentColor, 0, 0, 255,
SetTextureCoordinates, 0, 11.6955, -7.5,
SetTextureCoordinates, 1, 11.3653, -7.0324,
SetTextureCoordinates, 2, 11.6955, -7.0324,
SetTextureCoordinates, 3, 11.3653, -7.5,

CreateMeshBuilder,
AddVertex, 0.213, 0.146, 0.082, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.0, 0.006, 0.0, 0.46, -0.888,
AddVertex, 0.213, 0.0, 0.006, 0.0, 0.46, -0.888,
AddVertex, 0.0, 0.146, 0.082, 0.0, 0.46, -0.888,
AddFace, 0, 2, 1,
AddFace, 1, 3, 0,
LoadTexture, base.bmp,
SetEmissiveColor,255,255,255
SetColor, 255, 255, 255, 255,
SetTextureCoordinates, 0, 20.0, -7.0,
SetTextureCoordinates, 1, 19.0, -6.0,
SetTextureCoordinates, 2, 20.0, -6.0,
SetTextureCoordinates, 3, 19.0, -7.0,

ScaleAll, 50.0, 50.0, 50.0,
```

**Comment by leezer3** [comment]
Notes:
* Not implemented in the old renderer, quick and easy job.
* Both Subtractive and DaytimeSubtractive allowed for the blend mode at the minute, probably ought to restrict it to just DaytimeSubtractive.
* Interesting question- Is there a 3D standard for faces using subtractive blending (absorb light?)

**Comment by s520** [comment]
Thanks!
I want him to try it.

Is "3D standard" an example object? Or is it an example of processing?

**Comment by leezer3** [comment]
By that, I mean an existing format (DirectX, Wavefront etc.) which implements this already.

If there's already a common standard or notation, then aligning with it is good practice.
