### ISSUE TITLE
Color shift when using new renderer

### ISSUE THREAD

**Issue by RetentiveGOAT** [leezer3/OpenBVE#429]
### Description

When using the new renderer, the exterior textures on my trains appear to be a lot darker than they are supposed to be.

### Reproduction

This happens with every train, on any route.

## Route

n/a

## Train

n/a

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system: Windows 10 Pro
* Method of control: Keyboard
[log.txt](https://github.com/leezer3/OpenBVE/files/4163376/log.txt)

**Comment by leezer3** [comment]
Link to something broken please.

I strongly suspect it to be this, in which case the change is intentional and produces 'correct' behaviour:
https://github.com/leezer3/OpenBVE/wiki/Errata#lighting-behaviour-with-the-same-texture-defined-for-both-daytime-and-nighttime

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/a89b3909b6ad646543842772fae949cdc3cec3c6

Current build may fix your issues, but it's *really* hard to tell without something broken.....

**Comment by leezer3** [comment]
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2020-02-09.zip
