### ISSUE TITLE
"Review last game" button is always disabled

### ISSUE THREAD

**Issue by Talkless** [leezer3/OpenBVE#430]
### Description

That button is always disabled for me on Debian Sid, using v1.7.1.2  .deb package from website. Funny thing is.. it works via Wine, i.e. if I use Windows build, install .NET and launch OpenBVE via `wine` :) .

### Reproduction

Launch Birmingham Cross city South, with Class 323, exit game, see disabled button.

## Route

Birmingham Cross City South
https://www.railsimroutes.net/bve_trainsim/x-city_south.php

## Train

Class 323 
https://www.railsimroutes.net/bve_trainsim/x-city_south.php

## Logs

Nothing. I see no errors in console output.

### Related information 

* Operating system - Debian Sid amd64
* Method of control - Joystick

**Comment by leezer3** [comment]
I'd guess you've got the black box disabled on the Debian install. Will check later, but:

Options ==> Detail of Simulation ==> Enable Black Box

**Comment by Talkless** [comment]
> Options ==> Detail of Simulation ==> Enable Black Box

This did the trick, thanks!
