### ISSUE TITLE
Dead Link in the Example Route Documentation

### ISSUE THREAD

**Issue by cwfitzgerald** [leezer3/OpenBVE#438]
On: https://openbve-project.net/documentation_hugo/en/examples/demoroute.html

http://bve.jpn.org/jr113.html 404's.

Also I can't file issues against the new documentation repo :)

**Comment by cwfitzgerald** [comment]
Nevermind, it only 404's if you try to access via https, which I have a force-https plugin enabled. I don't know if this is worth noting or not.

**Comment by leezer3** [comment]
Fixed the issues.

Not sure anything can be done about the 404, will think on it.
