### ISSUE TITLE
Cannot target .NET Framework 2.0

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#441]
### Description
While developing a plugin, I found the latest OpenBVEApi.dll that comes with the release, is targeting .NET Framework v4.6.1. Which makes a plugin which dependents on it impossible to target a lower version of .NET Framework.

### Related information 
* Windows 10 1709

**Comment by s520** [comment]
Why are you trying to target .NET Framework 2.0?
The minimum working version of the main program is already 4.6.1.
Are you trying to support older main program versions too?

**Comment by leezer3** [comment]
Absolutely correct, that's something else that needs updating by the look of it.....

Is there any specific reason you want 2.0?

**Comment by s520** [comment]
The possible basis is the following document.
https://openbve-project.net/documentation_hugo/en/plugins/overview.html

This document instructs us to target 2.0.

**Comment by leezer3** [comment]
Sorry, I'm aware of that- Should have been clearer :)

With a release version using the 4.6.1 target, reverting to 2.0 is hard to say the least. (And IIRC some of the dependencies require later anyway?)

All I think probably needs doing is that page updating to 4.6.1.
Anything targeted on the older API still works, just means that new stuff isn't backwards compatible.

**Comment by s520** [comment]
Yes. I feel the same way.
I don't think it is necessary for newly developed plugins to target 2.0.

**Comment by leezer3** [comment]
Framework target updated in the documentation :)
