### ISSUE TITLE
The sound problem of OpenBVE

### ISSUE THREAD

**Issue by lewisliiiii** [leezer3/OpenBVE#457]
### Description

When I am turning my viewpoint, sometimes the game will be no sound

### Reproduction

-> MTR Disneyland Resort Line (Disneyland Resort ➜ MTR Siu Ho Wan Depot)
-> MTR South Island Line (Admiralty ➜ South Horizons)

## Route

https://hkrailsimcentre.weebly.com/2101536554.html
https://hkrailsimcentre.weebly.com/3633532171.html

## Train

https://hkrailsimcentre.weebly.com/2101536554.html
https://hkrailsimcentre.weebly.com/3633532171.html

## Logs

[openBVE Bug Report13_04_2020.zip](https://github.com/leezer3/OpenBVE/files/4466639/openBVE.Bug.Report13_04_2020.zip)

### Related information 

* Sound

**Comment by leezer3** [comment]
Which sounds are you missing & exactly where are you placing the camera?

Sounds are directional to an extent, so if your listener position (camera) is facing away from the source of the sound, it'll be quieter than if facing it.
I wouldn't expect everything to cut out though.

Second- Is it just the one route or everything?

**Comment by lewisliiiii** [comment]
The train's running sound.
When I place my camera that facing the doors, it will happen.
And I think this issue will happen in each routes or trains...

**Comment by leezer3** [comment]
That suggests you're running out sounds available when the door sound triggers so it cuts one off.

See if this helps:
First page of Options- Increase the number of sounds. 32 ought to be plenty; I can't remember off the top of my head what the default is.

**Comment by lewisliiiii** [comment]
I had increase the number to 100 (the top number) before but it still :(
![image](https://user-images.githubusercontent.com/56731752/79075558-3171eb00-7d26-11ea-9684-da8321570816.png)

**Comment by leezer3** [comment]
I believe this was fixed by 1.7.2.0
