### ISSUE TITLE
Control over the sequence of the plugins

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#459]
As openBVE uses a trial-and-error schema to select a plugin for parsing a file, which makes the sequence of the plugins actually being loaded matter. Although this would not cause significant problem as long as the CanLoad field does not overlap each other, but it would cause some extra file operations. I wonder if it would be possible to have a way to control the sequence of the plugins being loaded.

In my case, I am trying to implement a custom plugin to read my customized model files, which I would also want it to be under the extension "csv". It feels like some evil hack, but it is for easier converting. In this case I would like my plugin to fire up before the Object.CsvB3d parser, as the later one only uses the extension to determine the file type.
There is a more-or-less working solution for this though, as OpenBVE uses
```
files = Directory.GetFiles(folder);
```
to enumerate the plugins. According to MSDN, the order of the returned file names is not guaranteed, but seems to be alphabetically sorted. So naming my plugin Axxxxxxx.dll would effectively fire it up before CsvB3d parser. But as it is not guaranteed there is likely to be different cases on different platforms, which would cause my plugin to fail.

I cannot think of a easy way to eliminate the overlap of the field of my plugin and the original CsvB3d parser, as changing the extension requires extra work on replacing all references in the files. But my plugin can check the file based on its content, so it would handle it correctly as long as it is fired up earlier than the CsvB3d parser.
I would like to know if we can make the sequence guaranteed, for example, just lift a finger and sort the files once - it would not break any current functionality. And it would guarantee my plugin to work fine.
```
files = Directory.GetFiles(folder).OrderBy((a) => Path.GetFileName(a));
```
Or maybe more sophiscated way to sort the plugins (a bit like FML in minecraft which uses metadatas to judge the sequence), but that would be too complex for such a little problem.

**Comment by leezer3** [comment]
Honest answer here-
Use another extension, sorry. 
If you have a 'magic' header or something, I could probably block your files, but that's an equally bad solution.
A unique format should equal a unique extension, and preferably a unique file header too. Plain text formats are a mess otherwise.

---

Some finer detection of whether a file is actually CSV / B3D is on the list of things I need to get around to, but that'll probably entail a re-write of the entire thing, and I'm currently doing that in the route parser.

**Comment by zbx1425** [comment]
Well, I do have a magic header for these files. It consists of a few invisible control characters for better distinguishing.
And my plugin would check if the csv file given has that header. If not so, it would report not being able to load this file, and thus pass the job to the built-in csv parser.

I would like to ask for sorting the plugins by file name. That would effectively give my plugin priority as its name starts with A.
Although this hack is a bit dirty, it would guatantee it to work without changing any cureent behavior. As far as I can tell the Directory.getFiles seems to be already always returning alphabetically sorted list on Windows. So this can achieve this objective without doing any harm.

**Comment by leezer3** [comment]
Let me have your control sequence bytes and I'll block them, but I'm not at all happy with it as a solution.


Alphabetic sorting is an even worse mess, not going there.
(Just for example, someone renames the plug in, or produces a marginally modified version of it)

**Comment by zbx1425** [comment]
Thanks a lot.
It is something about right management, so you might be opposed to it. Sorry for that. But I consider taking this step is more than vital for the situation here. The developers are losing motivation and the community is falling apart.
Because of the difference in time, I have to go to bed, and would get back to you in a few hours.
Feel free to reject me if you actively reject developers implementing rights mamagement by using parser plugins.
Many thanks.

**Comment by leezer3** [comment]
I'm willing to block your files from the CSV plugin, but nothing further- You're correct that the lack of copy protection was one of the fundamental principles when this sim was founded, and something that I support in general.
As such, I won't distribute your plugin etc, but at the same time I'm not actively trying to block or hamper you; that causes just as much harm as including it in the first place.

---

Incidentally, as a secondary thing / note:
If a plugin crashes, the next in the list will be tried. Need to think about whether throwing a not supported exception is actually better than gracefully returning and adding a log message that loading failed as is the current. This is OK when there's only a single plugin that can load any given content type, but with multiple in the equation....

**Comment by zbx1425** [comment]
A file of my format must be longer than 32 bytes. And when the first 16 bytes are read into 4 uint32s, they would be 0x554c544eu, 0x4d524453u, 0x14131211u and 0x00811919u.
This is my code used to determine the format:
```
public const uint MagicA = 0x554c544eu;
public const uint MagicB = 0x4d524453u;
public const uint MagicC = 0x14131211u;
public const uint MagicD = 0x00811919u;

public static bool IsNautilusFile(BinaryReader reader) {
    if (!File.Exists(path)) return false;
    using (FileStream stream = new FileStream(path, FileMode.Open, FileAccess.Read)) {
        if (stream.Length < 32) return false;
        using (BinaryReader reader = new BinaryReader(stream)) {
            uint identifier1 = reader.ReadUInt32();
            uint identifier2 = reader.ReadUInt32();
            uint identifier3 = reader.ReadUInt32();
            uint identifier4 = reader.ReadUInt32();
            // NTLUSDRM
            return identifier1 == MagicA && identifier2 == MagicB &&
                   identifier3 == MagicC && identifier4 == MagicD;
        }
    }
}
```

**Comment by zbx1425** [comment]
I personally think the current implemention of exception handling is good enough. If a plugin returned false on CanLoad then we would keep trying, and if a plugin returned true on CanLoad but false on Load then we stop trying. As long as the plugin can judge if it is their file correctly in the CanLoad function, the framework is fine.
-----
Another side note, as I have seen in the BmpGifJpegPngTiff plugin, when it tries to determine if it can read a file, it directly opens the file and tries to read two uint32 out of it without checking the length of the file. So that means an empty file or a file with less than 8 bytes in length would cause the plugin to encounter an EndOfStreamException and crash?

**Comment by zbx1425** [comment]
Since you have not replied, I would like to remind you that I have already given the magic number to you. I have posted 2 comments in a row and it is likely that one would miss the first one...

**Comment by zbx1425** [comment]
Thanks a lot for your courtesy! It is a great honour to get involved.
And sorry for the late reply.
Have not installed the latest nightly build yet, but after looking through this piece of code:
```
return (BitConverter.ToUInt32(readBytes, 0) == 0x554c544eu && BitConverter.ToUInt32(readBytes, 4) != 0x4d524453u 
&& BitConverter.ToUInt32(readBytes, 8) != 0x14131211u && BitConverter.ToUInt32(readBytes, 12) != 0x00811919u);
```
I wonder why the first comparison is equal and the following three are inequal. In that way can it match the magic numbers?

Anyway this is just a plugin I just finished yet, as demanded. I still have no idea if anyone would be using it in the future. If there is there would only be a couple of them. Hopefully there would be not.
