### ISSUE TITLE
Non-user-friendly error message when installing package

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#462]
Although it sounds a bit stupid, I chose the second option for the user data folder at installation, and thus putting the UserData folder inside C:\Program Files (x86), where writing requires UAC admin privilege.
And when attempting installing packages without the program ran as Admin in UAC, "Unhandled Windows Forms Exception", and "A fatal exception occured inside the UIThreadException handler" popped out, and crashed the program.
I hope we can catch the UnauthorizedAccessException and prompt the user about the problem, then automatically rerun the program as admin.

**Comment by leezer3** [comment]
Crash fixed and more helpful error message added.

Installing addons into a UAC protected folder isn't a good idea, so not going to auto-elevate.
