### ISSUE TITLE
panel2.cfg - 'locobrakepipe' breaks parser

### ISSUE THREAD

**Issue by danielleighton** [leezer3/OpenBVE#472]
### Description
Use of 'locobrakepipe' subject in panel2.cfg results in fatal error parsing the panel config file

### Reproduction
Use a panel2.cfg file with a [needle] section referencing 'locobrakepipe' subject.  This looks to fail with a fatal error due to typo line ~1280 Panel2CfgParser.cs (missing a space before brakepipeindex in the string append).

**Comment by leezer3** [comment]
Fixed, thanks.

I've also added some try / catch blocks so this doesn't take down the entire parser if we get this sort of issue again :)
