### ISSUE TITLE
1.7.1.5 based graphic renderer issues

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#480]
### Description

I checked the based on 1.7.1.5 with graphic renderer issues.

These data uses my new route and objects.

- Dynamic background is changes suddenly(Old Renderer)
  Route: yamabiko171(summer): from Ichinoseki (Dep:17.4830) to Shinhanamaki(Arr:18.1515)
  	1.Starting the route, and jump to Ichinoseki.
  	2.Run to Shinhanamaki, stop at the stop position, then, changes the background suddenly.
  If start from Kitakami(Dep:18.0730), the background changes suddenly after arrive Morioka(Arr:18.2730) and waiting to 18:34:30.
  Dynamicbackground is works well when the NewRenderer is enable.

- When the NewRenderer is enable, DynamicLighting's Light Color illuminated by the light source is not effect

  Route: yamabiko171(summer):

  ​	1.Start the route.
   ![yamabiko171-newrenderer](https://user-images.githubusercontent.com/22734699/81541147-a3813280-93ad-11ea-83fc-5d588f531b55.jpg)  ![yamabiko171-oldrenderer](https://user-images.githubusercontent.com/22734699/81541183-b1cf4e80-93ad-11ea-893a-e8a93a01966b.jpg)

  
  
- The cab brightness also change suddenly.
  Route: yamabiko171(summer): from Ichinoseki (Dep:17.4830) to Shinhanamaki(Arr:18.1515)
  	1.Starting the route, and jump to Ichinoseki.
  	2.Run to Shinhanamaki, before the stop at the stop position, then, changes the cab brightness dark suddenly.

  
  
- At the old renderer, Station name information board do not self-luminous. 
  All routes. Look at the picture of above.
  
- TFO and Extensions.cfg's brightness is not change if the NewRenderer is enable.
  	![TFO-brightness](https://user-images.githubusercontent.com/22734699/81541353-ee9b4580-93ad-11ea-858e-e23104973e84.jpg)  ![TFO-brightness2](https://user-images.githubusercontent.com/22734699/81541369-f22ecc80-93ad-11ea-917a-2264f416b6e2.jpg)
  
- From Korean user reports, car interior's brightness has been darkness from 1.7.0.1 as shown below.
  Coupler side's wall is normally, but ceiling, door sides, floor is dark.
  	![inside-brightnes1](https://user-images.githubusercontent.com/22734699/81541544-39b55880-93ae-11ea-93fb-5c429ba9e035.jpg)  ![inside-brightnes2](https://user-images.githubusercontent.com/22734699/81541557-3d48df80-93ae-11ea-9644-059aa2a8fc5b.jpg)
  
  	When the ObjectViewer using, brightness is change extremely dinamic.
  	Press arrow keys, rotate it, the objects are more bright.
  
  	![objectviewer-dynamic-brightness1](https://user-images.githubusercontent.com/22734699/81541777-9d3f8600-93ae-11ea-9faf-a978166d396e.jpg)
  	side and floor is more bright
  	![objectviewer-dynamic-brightness2](https://user-images.githubusercontent.com/22734699/81541831-b21c1980-93ae-11ea-8342-10a94a32b5fe.jpg)
  	ceiling is a bit bright
  	![objectviewer-dynamic-brightness3](https://user-images.githubusercontent.com/22734699/81541856-bea07200-93ae-11ea-862c-48005f60b023.jpg)

  	X and Y axis's degree is maximum brightness, and Z axis side is dark as shown below picture.
  
  	![ObjecrViewer-bright-issue](https://user-images.githubusercontent.com/22734699/81541966-e1cb2180-93ae-11ea-8b4d-22fca1b70375.jpg)
  
- At also OpenBVE, brightness is changed dynamically. So, also effects to cab interrior.
  
  	![brightness1-1 7 1 5](https://user-images.githubusercontent.com/22734699/81542092-12ab5680-93af-11ea-8b65-54cc0753c31a.jpg)  ![brightness2-1 7 1 5](https://user-images.githubusercontent.com/22734699/81542116-1f2faf00-93af-11ea-8cc9-21dd6549a09c.jpg)

### Route

Route:http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.01_EN.zip

Object:https://drive.google.com/uc?export=download&id=1lc4B8zgq9PhQM8BCEqAGNaU-u47mZET3

### Train

Any trains

### Logs

This is a report. so, nothing logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
### Signs (probably car interior brightness too):
That is caused by this- 
https://github.com/leezer3/OpenBVE/wiki/Errata#lighting-behaviour-with-the-same-texture-defined-for-both-daytime-and-nighttime

Either turn on **Hacks ** or set the faces to emit pure white, e.g.
```SetEmissiveColor,255,255,255```
(This was restored behind the hacks option as of 1.7.1.4)

**Comment by leezer3** [comment]
### Lighting:
[bin_release.zip](https://github.com/leezer3/OpenBVE/files/4611964/bin_release.zip)

Please try the experimental build above.
This definitely fixes the issues with the dynamic light not being applied properly, and looks somewhat better.
Light direction isn't right though, still trying to sort out.

**Comment by ginga81** [comment]
I don't know how to turn on Hack.
And SetEmissiveColor,255,255,255 is extremely bother to add to the already exist object.
Because, the self-illuminate objects a lot of, such as station information and departure information, stop information and etc.
A lot of current contents are using such as loadtexture, same.bmp,same.bmp to self-illuminate.
Also, my newest objects uses so.
I think that this is should add the option.

I tested lighting test build, this is very nice lighting!
Some parts's color is not changed.
This picture is Series-E6's car 11.
Door's inside is not change.
![sendai-E6-light](https://user-images.githubusercontent.com/22734699/81636467-e8a97100-944e-11ea-8678-b9b9aecfa143.jpg)
![E6-11-light](https://user-images.githubusercontent.com/22734699/81636491-fa8b1400-944e-11ea-838f-b5877c14af0b.jpg)

And transparency trouble is half good.
At this test version, long distance's (weak shining) transparency is fine.
Near and shining is more strong, transparency not works suddenly.
This is far, so, zoom in.
![transparent01](https://user-images.githubusercontent.com/22734699/81636565-20181d80-944f-11ea-868d-b96b7e41d48c.jpg)
![transparent02](https://user-images.githubusercontent.com/22734699/81636575-24443b00-944f-11ea-8abb-433b24774137.jpg)

Loading screen trouble is recovered!
When the window size is not change on purpose when loading, the loading screen and indicator is showing!
Thank you very much!
![loading](https://user-images.githubusercontent.com/22734699/81636874-e4ca1e80-944f-11ea-967b-1c801198a836.jpg)

**Comment by leezer3** [comment]
[bin_release.zip](https://github.com/leezer3/OpenBVE/files/4615477/bin_release.zip)

Second test build (the code from the PR above), which I think fixes the lighting properly this time, as opposed to half-way.

Other things:
### Transparency trouble
I think this is the same in both renderers?
It appears to be mipmapping and view angles interacting with the transparency. Going to be a real issue to fix properly :(

### Hacks:
In the options page of the main menu, select this checkbox:
路線別のトラブル修正を有効にする

You can also set the following in your routefile, which does the equivilant:
```
Options.EnableBveTsHacks 1
```

I can probably write a tool to fix all object files in the object directory if this helps?

**Comment by ginga81** [comment]
- Extensions.cfg and TFO's brightness is fixed.

- electric pole's lights's shining transparency is not change.
Old renderer
Biliniear and Bilinear(mipmap) both is not change transparent.
New renderer
Biliniear and Bilinear(mipmap) both is not change transparent.
I am always turn on at Enable hacks for buggy older content.

- Station information board's self-illuminate is not change. I want to shine it such as 1.7.0.3.
![selflight-1 7 0 3](https://user-images.githubusercontent.com/22734699/81729779-80e33c80-94c7-11ea-81ba-c1828830e5e8.jpg)
![selflight-testver-old-and-new](https://user-images.githubusercontent.com/22734699/81729805-8ccefe80-94c7-11ea-8414-a48c2559f289.jpg)
Old and new renderer is not fixed both, but at new renderer, arrow keys camera rotate is not relate the brightness dynamic change.
I think that this change is very nice!
- At the new renderer only, stop marker object is lost.
![newrenderer-lost](https://user-images.githubusercontent.com/22734699/81730591-bb99a480-94c8-11ea-9934-27a689e3dae9.jpg)
![oldrenderer-lost](https://user-images.githubusercontent.com/22734699/81730636-cd7b4780-94c8-11ea-8d8b-d95a41e5e503.jpg)

**Comment by leezer3** [comment]
That's interesting-
Two defined textures (non-identical) are also triggering the ignoring of all scene lighting behaviour.

Restored this also behind the same hack. 

I'll test this some more tomorrow, and then probably merge into main, as these lighting changes are important- Thanks!

**Comment by ginga81** [comment]
From Korean user, when we using the ObjectViewer, the lighting color is dark.
I tested the testversion2, maybe he want to display that ObjectViewer's csv only's picture.
![OLD-csv](https://user-images.githubusercontent.com/22734699/81770409-25429e80-951b-11ea-8369-10f90448b9af.jpg)

But, the testver2's ObjectViewer displays different from he wants.
Csv only and oldrenderer is good color, but if the same csv using by animated's states, the result is dark.
[Object]
 States=samefile.csv
![OLD-animated](https://user-images.githubusercontent.com/22734699/81770452-42776d00-951b-11ea-810a-85eb0fb7411c.jpg)

When we using the NewRenderer, the result is dark, but same brightness between with csv only and animated's States function.
![NEW-csv](https://user-images.githubusercontent.com/22734699/81770672-f37e0780-951b-11ea-918c-e854940106f9.jpg)
![NEW-animated](https://user-images.githubusercontent.com/22734699/81770682-f7aa2500-951b-11ea-9330-0d4ca0e4b41d.jpg)

At the testver2's OpenBVE, OldRenderer's csv and using the animated's states function is the same color and very nice.
![OpenBVE-old-csv](https://user-images.githubusercontent.com/22734699/81771048-f2010f00-951c-11ea-86a0-5fe232a211bf.jpg)
![OpenBVE-old-animated](https://user-images.githubusercontent.com/22734699/81771075-0218ee80-951d-11ea-8fe3-1b0358a1917d.jpg)

At the NewRenderer, the color is the same between with csv only and nimated's states function.
But at the NewRenderer, the objects are more bright and it is transparency.
I think perhaps that the transparent object's issue is the same issue of my stop object, but I reports.
![OpenBVE-new-csv](https://user-images.githubusercontent.com/22734699/81771243-6fc51a80-951d-11ea-900a-2d23fd6d3a2e.jpg)
![OpenBVE-new-animated](https://user-images.githubusercontent.com/22734699/81771253-75bafb80-951d-11ea-894a-a69bd118b9e0.jpg)

**Comment by ginga81** [comment]
At 1.7.1.6 with new renderer, when the rotate by arrow keys, brightness and lighting is works well,  and self emitting color is also good!
Korean user's test car is also good at OpenBVE 1.7.1.6.
Object lost is not happen.
My route's orange pole object is also not lost.

At the ObjectViewer with new renderer, Korean user's test car is still different the brightness.
When the rotate by arrow keys, brightness is change dinamically.

**Comment by ginga81** [comment]
From this sample object's Korean user, he said that at the newest OpenBVE, may be 1.7.1.8, color issue is correctly.
So, color issue is will close.

Transparent Z-order is still not perfectly.

**Comment by ginga81** [comment]
Transparency issue is related and overlaps to #466
Color's issue is correctly.
So, I closed.
