### ISSUE TITLE
Erroneous wireframe in ObjectViewer with new renderer

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#481]
### Description

Broken wireframe display is reported by a local developer when the new renderer is enabled.
Expected behavior, with the old renderer:
![Old_GL1 2](https://user-images.githubusercontent.com/25097028/81637183-4e462f00-9448-11ea-8c88-ec86fba07033.png)
Erroneous behavior, with the new renderer:
![New_GL3 0](https://user-images.githubusercontent.com/25097028/81637203-5dc57800-9448-11ea-89f5-46892b9bd7bb.png)

### Reproduction

Model used:
[cowtransfer-1589255726597.zip](https://github.com/leezer3/OpenBVE/files/4613319/cowtransfer-1589255726597.zip)

### Related information 

Nightly build 2020-05-07 (1.7.231.668)

------
BTW the new renderer received high favorable comments among the local developers for its significent boost in performance. Thank you for your awesome work!

**Comment by leezer3** [comment]
Will look later, but I suspect fixed by https://github.com/leezer3/OpenBVE/commit/adb7f1b5d88819e8b3a392c98939685e6c87ace1 so likely OK in the current release?

**Comment by zbx1425** [comment]
It seems that adb7f1b is pushed at May 6th but the bug is reproducted on May 7th nightly build.
Will contact that developer to test the model again on the latest nightly build.

**Comment by leezer3** [comment]
I'll take a look later, thats easier.

**Comment by leezer3** [comment]
Nope, definitely broken :(

Going to work now, I'll take a proper look later; Something really funny is going on with this one.

**Comment by zbx1425** [comment]
Yup, this spider-web-alike thingy looks absolutely hilarious.

**Comment by leezer3** [comment]
Will be fixed when https://github.com/leezer3/OpenBVE/pull/482 is merged.

Want to do a little more testing on it first though.
