### ISSUE TITLE
ObjectViewer fails to load extensions.cfg on 0521 and 0522

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#485]
### Description
A developer who was trying out the latest nightly build 0521 and 0522 reported that ObjectViewer cannot load any extensions.cfg file.
No error message was seen and no model was loaded.

### Reproduction
The developer stated that loading any extensions.cfg will reproduce this problem.
I have not personally tested it out yet.

### Related information 
Nightly Build 2020-05-21 & 2020-05-22

**Comment by leezer3** [comment]
Wanders away swearing repeatedly :P

This is exactly why I'm trying to merge everything into shared libraries- Merge a small set of unused code bits, and something else falls over because of a stupid expectation....
