### ISSUE TITLE
panel.xml failed to load on 1.7.1.5

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#487]
### Description
Loading a panel.xml file with multiple screens caused instant crash on OpenBVE 1.7.1.5.
Also, in 1.7.1.4, the touch element was not working.
It is not yet tested on latest nightly build.

### Reproduction
Loading this train seems to crash OpenBVE 1.7.1.5 every time.

## Train
Touch Elements Test Train by Ginza81
[TouchElements-testtrain.zip](https://github.com/leezer3/OpenBVE/files/4673326/TouchElements-testtrain.zip)

## Logs
```
2020/5/24 星期日 17:12:49
OpenBVE 1.7.1.5 Crash Log
Program is running on the Windows backend
Current screen resolution is: Windowed 1280px X 720px 
Current routefile is: F:\Program Files (x86)\openBVE\UserData\LegacyContent\Railway\Route\ZBX\TestRoute.csv
Current train is: F:\Program Files (x86)\openBVE\UserData\LegacyContent\Train\Tutrial-train
The current routefile caused the following exception: 
System.InvalidOperationException: Failed to generate the required vertex array handle- No openGL context.
   在 LibRender2.VertexArrayObject..ctor()
   在 LibRender2.VAOExtensions.CreateVAO(Mesh& mesh, Boolean isDynamic, VertexLayout vertexLayout)
   在 LibRender2.Objects.VisibleObjectLibrary.ShowObject(ObjectState State, ObjectType Type)
   在 OpenBve.Graphics.NewRenderer.UpdateVisibility(Double TrackPosition)
   在 LibRender2.BaseRenderer.UpdateViewingDistances(Double BackgroundImageDistance)
   在 OpenBve.TrainManager.ParsePanelConfig(String TrainPath, Encoding Encoding, Train Train)
   在 OpenBve.Loading.LoadEverythingThreaded()
   在 OpenBve.Loading.LoadThreaded()   在 System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   在 System.Environment.get_StackTrace()
   在 OpenBve.Loading.LoadThreaded()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
Current program memory usage: 113.31mb
System memory free: 11883mb
```

### Related information 
Windows 10 1709

**Comment by leezer3** [comment]
That's a little confusing.

The error says that it's failing to generate the VBO for the touch element on the panel, which therefore says GL3.0 renderer due to no openGL context.
It should have fallen over long before this though, the train is the last thing to load. 

Possibly we're catching all other errors where GL3.0 is not available, but this one slipped through as touch is uncommon?

Try the GL1.2 renderer as a starting point and see if that crashes. Will investigate more later.

**Comment by zbx1425** [comment]
It seems to crash no matter if the "Enable New Renderer" is enabled or disabled.

**Comment by leezer3** [comment]
I can't reproduce this at the minute, but have added a try / catch block on spec to the function where it falls over.

Current build may sort it, but may also crash elsewhere as a result of this change, see what happens.

**Comment by zbx1425** [comment]
![image](https://user-images.githubusercontent.com/25097028/83270489-2225fe80-a1fb-11ea-9358-806444f62950.png)
Here are more information regarding the Graphics Card.

**Comment by zbx1425** [comment]
By the way, I am a bit willing to hear your opinion on https://bveworldwide.forumotion.com/t1931-loading-plugin-from-route .
I can achieve that with Harmony.Lib right now, but I hope there can be a way to achieve that without requiring patching, since the exposed interface can change at any time.
I understand that this is not a very useful technique and it feels both unnecessary and hard to implement, though. So thanks a lot.

**Comment by zbx1425** [comment]
The latest build solved the problem. Thanks a lot!
