### ISSUE TITLE
Dynamic background is not work and car brightness is not change at 1.7.1.6

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#489]
### Description

At Old renderer, dynamic background is not works. The background changes suddenly.
At new renderer, dynamic background is works well.
Dynamic lighting is works well at the both renderer.

At New renderer, extensions.cfg cars and TFO cars is not change the car's brightness for example at the tunnel.
At old rendedrer, brightness is works well.

### Reproduction

This issue happens at all data for using by dynamic background,  extensions.cfg and TFO cars. So, route and cars is any choose.

## Route

Any

## Train

Any

## Logs

This issue is not crash.
So, no logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Extensions.cfg issue should be fixed by the commit above. 
(Not actually extensions.cfg per-se, forgotten to update the brightness where there was only a single texture)

Dynamic background issue sounds to me like a missing blend statement, will try and get that sorted ASAP.

Someone always finds a critical bug after a new build has been pushed :)

**Comment by ginga81** [comment]
I tested at https://github.com/leezer3/OpenBVE/tree/4047245fa4ecc5e3131bd0095621a9ba6bf78c34
The cars brightness at new renderer is fixed.
I think that the GL version is inversion displays with 1.2  and 3.0.
The fps is half down at new renderer such as old renderer at the new renderer.
But, at the old renderer, especially driver's view, it is very fast such as new renderer.
outer-view is the same fps with new and old, slow and half down such as old renderer.
And the TFO loading time is very long at new renderer.
I am waiting for fix the dynamic background.

**Comment by leezer3** [comment]
Should fix the dynamic backgrounds.

The renderer display definitely isn't inverted though.

**Comment by leezer3** [comment]
From a very brief few tests, the new renderer FPS appears largely unchanged to me.
On heavy externals / TFOs, I'm seeing the expected FPS boost.

Potentially silly question-
You're not building and launching from a development environment (Mondevelop?) are you?
If you're doing this, it'll probably be attaching a debugger, which is likely to slow things nastily.

**Comment by leezer3** [comment]
Might help:
https://github.com/leezer3/OpenBVE/commit/3852c4b26404cbcdbde545635c32eee944a3f1f3

Just noticed that certain combinations of the **Load in Advance** and **Unload Unused Textures** could accidentally disable the new renderer.

**Comment by ginga81** [comment]
I tested https://github.com/leezer3/OpenBVE/commit/ee84635232c1660e89707bc222ef62a4508666ff
All of this time issues are fixed!
At the loading is very slowly, as you say, I am debugging from monodevelop.
When I run from built exe file directly from bin_debug, the loading speed is recorvery.
I am very sorry.
I will try to the programming, so after released Morioka, I am challenging to compile recently.

**Comment by leezer3** [comment]
Good.

Also, if you're not debugging, selecting the release build in MonoDevelop will produce much better FPS.

**Comment by ginga81** [comment]
I tested release build. Too fast!
Thank you very much!

At the other hands, I found camera is not work at F4 key.
Not rotate automaticaly towards the train, and forward route objects are not draw.
While the objects are not drawing, fps is incredibely down.
Another camera keys, F2 and F3 are works.
![camera-not-works](https://user-images.githubusercontent.com/22734699/83653794-2e44fe00-a5f7-11ea-9013-c2cefe9af79d.png)

**Comment by leezer3** [comment]
Will take a look in a bit or tomorrow.

**Comment by leezer3** [comment]
Current build should now fix this (bracket got into the wrong place somehow, took me a while to find that....)

Please let me know if you've seen anything else- Could do with pushing a fixed version soonish.

**Comment by ginga81** [comment]
I think that these issues including with the camera F4 rotate are all fixed.
I found when the camera rotate to the side, the ground is white at the old renderer.
New renderer is not white.
I thought that this issue have been fixed, causes by Track.fog.
https://github.com/leezer3/OpenBVE/pull/476
May be it fixed only new renderer?
![front](https://user-images.githubusercontent.com/22734699/83889306-f61ff580-a785-11ea-8a47-02a1e702a1ac.jpg)
![side-new-renderer](https://user-images.githubusercontent.com/22734699/83889338-fe783080-a785-11ea-9074-30f993606478.jpg)
![side-old-renderer](https://user-images.githubusercontent.com/22734699/83889374-08019880-a786-11ea-8025-76117f37ae60.jpg)

**Comment by leezer3** [comment]
Which routefile please?

I can't get this to reproduce at the minute, although I have discovered and fixed a glitch with emissive faces & identical day/ night textures on the old renderer looking for it.

Second question- Is it only in that approximate area, or does this manifest across the whole route?

**Comment by ginga81** [comment]
Route file is any.
Have to enable Track.fog.
For example https://github.com/leezer3/OpenBVE/issues/466 's
https://github.com/leezer3/OpenBVE/files/4536911/transparent-trouble-sampleroute.zip

Second question:
This happens may be all Track.fog applied area.
So,I cannot answer this happens all of route or not.
At the past issue, @s520  said that when remove Tfack.fog, this phenomenon does not occur.

**Comment by leezer3** [comment]
That's odd, I can't reproduce at all on the demo route above.

I wonder if this might be a Linux driver specific issue somehow....
@s520 if you're able, can you try and reproduce this at all?

**Comment by ginga81** [comment]
@s520 is now busy.
I think perhaps he can active from next week.

**Comment by leezer3** [comment]
No problem.

I think I'll probably put out a release at some stage next week if nothing else comes up, this is probably minor enough to have sitting around.

**Comment by ginga81** [comment]
I asked to @s520 .
He said that at his windows, also white.

I thought that when the camera rotate to the side, become the white is not specification.
But from 1.4.3, all OpenBVE are white when the camera rotate to the side.
I checked the version of 
1.4.3.0
1.5.3.9
1.6.0.0
1.7.1.3
So, the new renderer is also have to white.

But, in my personal opinion, this white phenomenon is not best.
I wish that the white phenomenon is not happen also old renderer.

**Comment by ginga81** [comment]
This issue is fixed at 1.7.1.8.
So, I closed.
