### ISSUE TITLE
Series-E5's emitting is disabled, darkness(nigittimetexture's important phenomenon found at old version)

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#490]
### Description

If the nighttimetexture is set to csv object, emitting light is disabled.
When the case of tunnel or night, self emitting is not.

case1:nigittimetexture is different file
LoadTexture,../kyoutuu/ceiling_gc_d.png,../kyoutuu/ceiling_gc_n.png

case2:nighttimetexture is the same file
LoadTexture,../signs/maku/hayabusa_morioka/morioka_g_en.png,../signs/maku/hayabusa_morioka/morioka_g_en.png

Both case is dark when Track.brigitness is low.

This phenomenon happens from 1.7.1.0 or newer.
To enable the self emitting at the new version, have to not set the nighttimetexture, and use SetEmissiveColor,255,255,255.
This phenomenon is found by Series-E5's partner uv creator, F81_tec200.

He found that this phenomenon is if set to the nighttimetexture, the lighting program is disabled from 1.4.3 to version 1.7.0.3.
If the light effect is disable by the OpenBVE's inside program, nighttimetexture is not effect by 'black color light'.
As a result, if Track.brigitness is low, texture is bright.

@S520 found:
https://github.com/leezer3/OpenBVE/blob/56156853943dcf58b717b94238c8c2a0b973020f/source/OpenBVE/Graphics/Renderer.cs#L567-L582

From 1.7.1.0, if the nigittimetexture is set, light effect is enable.
So, the nighttimetexture is effected by 'black color light'.
As a result, if Track.brigitness is low, texture is darkness.

So, this information is not happen at the newer version.
https://github.com/leezer3/OpenBVE/wiki/Errata#lighting-behaviour-with-the-same-texture-defined-for-both-daytime-and-nighttime

This issue is may be related to
https://bveworldwide.forumotion.com/t1932-problem-with-color-and-emissivecolor-commands#19811

### Reproduction

https://drive.google.com/uc?export=download&id=15B98GOoz19jV4eWGiaiwRi6ReHkSBAjS
file is 1.animated.

## Route

This is not route trouble. So, no link.

## Train

This is not train  trouble. So, no link.

## Logs

This issue is no crash. So, no crash log.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)
![E5-dark](https://user-images.githubusercontent.com/22734699/83973609-b5a9ae80-a922-11ea-980d-3879372782cf.png)

**Comment by s520** [comment]
@leezer3 
Long time no see.
I will resume my activities little by little.

Now, the emitting condition that we have been thinking so far was to specify the same texture file for daytime and nighttime.
However, the only correct condition seems to be to specify a night texture.

**Comment by leezer3** [comment]
Apologies, I ought to have updated that errata: I discovered this issue a little while ago, although I hadn't connected it to that specific piece of code; That makes a lot of sense :)

https://github.com/leezer3/OpenBVE/commit/72e43ac7a078276f9bf1f73b689bb3877d7684af#diff-540d0e3a1df1ff7f3da002b2654273e1

The main sim should look OK but not quite identical (with hacks enabled), it's just Object Viewer that is wrong. 
We could perhaps improve the hack by adding a material flag to disable ambient lighting (as opposed to emitting pure white) in this case.


Unfortunately, the dual daytime / nighttime texture thing is a horrible mess, brought about I suspect to try and cope with a lack of a decent light model, and no way to add an emissive map.

**Comment by leezer3** [comment]
Something funny going on here-
The linked object is crashing every (new renderer) version of Object Viewer I've tried. Found one small bonus issue so far, but not the cause of the crash :(

Works fine in Route Viewer and the main sim, still investigating....

**Comment by leezer3** [comment]
Crash fixed (de-activating the shader appears to clear the last bound VBO), and I've made some more changes to the hack handling of day / night textures based upon the findings from here.

This won't affect the linked BVE Worldwide thread though.

**Comment by ginga81** [comment]
This problem is not a bug, as it originally uses SetEmissivecolor.
So, this issue is closed.
