### ISSUE TITLE
RouteViewer crash at the linux environment

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#492]
### Description

1.Run RouteViewer.exe
2.Drop in a route.
Show the message bellow, and crash.

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x39c7b79
  Serial number of failed request:  410
  Current serial number in output stream:  411
AL lib: (EE) alc_cleanup: 2 devices not closed

If we press F7 key and open a route file, the loading gauge is 100%, but not show a route,looping eternally.

This issue is also reported by a Hong Kong's user.
But, his machine spec and route is not reported to me.
The OS is reported to me using by Ubuntu(version is not reported).

But, when I use monodevelop, this is not happen.
1.Run monodevelop, and set to the breakpoint at RouteViewer/ProgramR.cs line 278.
UpdateCaption();

2.drop down a route to the game window.

3.From here, by the 'step-in' run.

4.Processing the UpdateCaption by step-in, back to the end of FileDrop(), then continue to run.

If I load by F7 key, before reach UpdateCaption();, looping eternally.

### Reproduction

Route:
https://github.com/leezer3/OpenBVE/files/4536911/transparent-trouble-sampleroute.zip

## Route

https://github.com/leezer3/OpenBVE/files/4536911/transparent-trouble-sampleroute.zip

## Train

RouteViewer is not need train data.

## Logs

RouteViewer is not output logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
That's an X crash, so the backed somewhere, and unlikely to be something we've done.

It looks to me like it doesn't like updating the window title (Route Viewer does this when loading is finished)
Commenting out the contents of this function is likely to make the crash go away:
https://github.com/leezer3/OpenBVE/blob/master/source/RouteViewer/ProgramR.cs#L658

Can probably add a check for running under Linux and not update the title though, will try and reproduce later.

**Comment by leezer3** [comment]
Try the current build.

I couldn't get it to crash, but loading was stuck at the end of the loop. 
(Dunno it worked on Windows but not Linux, but it now works on both there)

**Comment by ginga81** [comment]
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x3ffb852
  Serial number of failed request:  1176
  Current serial number in output stream:  1176
AL lib: (EE) alc_cleanup: 2 devices not closed

I tested release build by monodevelop of drag and drop read route of the https://github.com/leezer3/OpenBVE/commit/b97ea166d7ad8cbf48cce08683c256cfb87a9631, but crash by above meesage.

F7 key's eternal loop is fixed and show route.
And alternative, I think that it is the good timing to fix this.
If you can,  I hope that I want to show the Asian font to the Window title.
![Window-title-asianfont-broken](https://user-images.githubusercontent.com/22734699/84533494-2ede4280-ad23-11ea-8243-9546990a1917.png)

**Comment by leezer3** [comment]
Ah, thought it was only one issue, not two....

Will investigate the other.

### Asian font:
That rather suggests to me that it's not a Mono issue but a GTK one. I don't think OpenTK does anything more than pass the request back to the X window server to set the text on the window title.

Have you got anything else (non-Mono) with a Japanese window title you can try?

You might also try using gnome-tweaks to change the default window title font to something you know contains a full set of Japanese characters.

**Comment by ginga81** [comment]
Nautilus, Nemo, gedit, and libreoffice can show the Japanese font on the Window title.
I changed to the Noto CJK font by gnome-tweak, but not change at the RouteViewer.
![gedit-japanesefont](https://user-images.githubusercontent.com/22734699/84538145-1fafc280-ad2c-11ea-98ab-ad4febba3048.png)
![window-title-libreoffice](https://user-images.githubusercontent.com/22734699/84538026-d6f80980-ad2b-11ea-810d-8733c5f01996.png)

**Comment by zbx1425** [comment]
I have attempted it, and can provide additional detail based on my PC.
When a csv fill is drag-dropped into the window, it can be loaded, but the program crashes instantly after several frames have been rendered. No message box popped up. The same error was reported:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x142b41
  Serial number of failed request:  933
  Current serial number in output stream:  934
AL lib: (EE) alc_cleanup: 2 devices not closed
```
 - But it is worth noticing that I have **once** coincidentally got it working correctly. That was the first time when I tried dragdrop. Further attempts of the exactly same action resulted in crash.

[System Information](https://termbin.com/bdyp)

**Comment by leezer3** [comment]
Can't explain the crash at the minute.....
It's not the window title or anything, just dumps out on us somewhere in the first frame or two.

X11 crash, so something in the backend, not us.

It's almost certainly threading related, but I can't see how currently; If I dump a message box anywhere in call stack it works perfectly.

**Comment by leezer3** [comment]
Window titles:
OpenTK sets the window title via XStoreName (calls this function here eventually):
https://github.com/opentk/opentk/blob/3.x/src/OpenTK/Platform/X11/Functions.cs#L138

This is not unicode aware.

Will try and patch that and submit a PR to them; the way to set a unicode window title is via XChangeProperty

**Comment by leezer3** [comment]
https://github.com/opentk/opentk/pull/1079

Window titles were simple. Will see what the OpenTK guys have to say on the subject.
If necessary, I'll fork the 3.0 version of OpenTK and add our own Nuget package.

**Comment by leezer3** [comment]
Should have fixed the crash after dragging / dropping by calling Application.DoEvents()

My suspicion is that there was an event pending in the queue (mouse movement most likely), and the window handle changes after the drag / drop event. No idea how / why, but don't complain about it if it works :)

**Comment by ginga81** [comment]
At 1.7.1.7, in my environment, RouteViewer is works well.
Thank you veru much!
Wait after report from Hong Kong's user and more already reported users, I report here again.

**Comment by zbx1425** [comment]
RouteViewer of 1.7.1.7 is working well in my environment as well.
The "X11 Error encountered" is still reported in the terminal, but now the program no longer crashes.
Opening a route file by F7 and drag-dropping are both working now.
Thank you very much!

**Comment by zbx1425** [comment]
@ginga81 Shall we close this issue?

**Comment by ginga81** [comment]
We still do not receive report, but our environment is normally.
So, I think we can close this issue.
If they reports again, we can create new issue.

**Comment by ginga81** [comment]
At the newest build, this issue is fixed.
So, this issue is closed.
