### ISSUE TITLE
parts of Panel2.cfg object blinking randomly from 1.7.1.7

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#498]
### Description

The brightness changes unintentionally according to the surrounding brightness.
At Series-E6's digital speed bar graph is blinking.
When a train is running, some of panel's brightness, for example the right side's digital speed meter is  is must bright always, but effected from Track.Brightness.

For example, Series-N700A's 7-segments digital number object is works correctly.
 In other hands, LCD digital speed meter, bar graph, digital watch and more's brightness is changes unintentionally to dark.
And about the cause, F81_tec200 found that if **DaytimeImage and NighttimeImage is the same file**, **only load DaytimeImage**.
For example, one of object the bar graph what is brightness changes unintentionally, the file name is bg of a png file.
This object is using the same file day and night.
In other hands, 7-segments digital number object's file is digi_num and digi_num_n, which is different file using properly.

### Reproduction

Route is any, but must set Track.Brightness for checking
Train:
Series-E6
https://youtu.be/yRBr-Dsa1U4

Series-N700A
https://www.youtube.com/watch?v=tBweD9T2b3Y

## Route

Any, but must set Track.Brightness for checking

## Train

Series-E6
https://youtu.be/yRBr-Dsa1U4

Series-N700A
https://www.youtube.com/watch?v=tBweD9T2b3Y

## Logs

This issue is no crash. So, no logs.

### Related information 

Windows 10

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Should be fixed by https://github.com/leezer3/OpenBVE/commit/1325bd0ec76758cc5ae4a6a2b631155e563ae48d

**Explanation:**
The 2D cab is rendered with lighting disabled, but still uses some material properties, which were only being set by the new renderer with lighting enabled.

**Comment by ginga81** [comment]
At OpenBVE-2020-07-02.zip, blinking issue is fixed.
But, still not fix these area.
These originarities are always bright, but there are interlocking with brightness.
![E6-brightness1](https://user-images.githubusercontent.com/22734699/86378484-af5de680-bcc4-11ea-944a-15fba738a0ad.jpg)
![E6-brightness2](https://user-images.githubusercontent.com/22734699/86377899-e8e22200-bcc3-11ea-88d5-d95b8a5c6a87.jpg)
