### ISSUE TITLE
Erroneous color and orientation when using TGA textures

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#499]
### Description
When some TGA textures are used in a model, their colors are apparantly incorrect, and some appear upside down.
![image](https://user-images.githubusercontent.com/25097028/86992321-d429f080-c1d3-11ea-9aa8-bf6daa09922a.png)

### Reproduction
Reproduced on both old and new renderer.
This model is used: [tgabug.zip](https://github.com/leezer3/OpenBVE/files/4894225/tgabug.zip)

### Related information 
Windows 10 2004
Intel UHD Graphics 630

**Comment by leezer3** [comment]
Horizontal and vertical transfer orders transposed :/

Rest of the commit is just a little tidying noise.
