### ISSUE TITLE
1.4.8.0011: joystick doesn't always register axis zero

### ISSUE THREAD

**Issue by jsiren** [leezer3/OpenBVE#5]
When returning a spring-loaded joystick axis rapidly to zero, it tends to get stuck on some low value. 

To reproduce: map the SINGLE_FULLAXIS, POWER_HALFAXIS, and BRAKE_HALFAXIS controls to spring-loaded joystick axes. Start driving normally. First increase power, then center the power axis rapidly. The power is often left on (P1) instead of returning to neutral. The same happens with brake. With rapid manipulation of the handle, it is possible to have the controller in the centre position, and the brake and power simultaneously on, even if the train has a combined handle (class 323).

There is an easy workaround: return power and brake to the centre slowly, one step at a time. Also, if either does get stuck, slowly move the controller to the affected direction and back.

This may to be a bug in Michelle's code, since it already appeared in older versions even before the OpenTK port. I thought it was a mechanical fault in my joystick, a dirty optical sensor or something to that effect, but jstest does register zero reliably every time. Nevertheless, I'm willing to accept the possibility of a mechanical failure. Also, rapid motions are slightly unrealistic anyway.

**Comment by leezer3** [comment]
It's a fundamental problem with the structure of Michelle's code, and the nature of joystick polling in general.

Both my code, and Michelle's process the joystick once a frame- She was reading the SDL event queue, whilst I'm polling the joystick state directly.
The changed control state is then queued for processing in the next frame.

In order for this approach to work 100% reliably, the joystick state must remain static for three frames (e.g. Frame 1- Joystick is read, Frame 2- Joystick is processed & Frame 3- Control is cleared and ready for re-use)
If this doesn't happen, then the control can get stuck in an unexpected state, as it's trying to process the axis with regards to a position that it's no longer in.
In practice, the joystick threshold setting means that small changes in the axis state are disregarded, and this covers most cases, unless you are deliberately moving the joystick rapidly, as you've noticed.

Joystick axis being an analog control means that it's much harder to fix this than keyboard keys.

Will think about it, but expect no quick fixes.

**Comment by jsiren** [comment]
I suspected it had to do with polling. Like I said, it's not a big issue, and it's easy to work around with slow handling of the controls, so in my opinion this issue is not urgent.
