### ISSUE TITLE
New ObjectViewer will not free memory after reload/object deletion

### ISSUE THREAD

**Issue by LubuntuKHYT** [leezer3/OpenBVE#507]
### Description

ObjectViewer after v1.7.0.3 would not free video memory after object deletion/reload
of object. If the VRAM is about to be full and you keep reloading the object(maybe 3-5 more times depending on the object), there will be white texture. Clearing the object also won't free the video memory(unless you close the window). This does not happen before the new render update.
### Reproduction

Load any object(Train's extension.cfg is more effective, take MTR SP1900 EMU for example) in ObjectViewer above 1.7.0.3. On reload, you will see the memory just bump up instead of staying on the same VRAM level like before(You can check on W10 taskmgr/GPU-Z). When it's about to max out, just reload like 3-6 more times. Then you will see white texture, along with error messages:

No plugin found that is capable of loading texture E:\Path\MTR West Rail Line SP1900 EMU\exterior\111.png
Plugin Texture.BmpGifJpegPngTiff.dll raised the following exception at LoadTexture:Out of memory.

Using the Old (GL 1.2) and the New (GL 3.0) make no difference on this issue.

## Train

[Google Drive Link](https://drive.google.com/file/d/0B5mnFfKjPZGoNklqN1VTcE8xRHM/edit)

## Logs

Not in-game problem, attached ObjectViewer report instead. Problem starting from line 10.
[log.txt](https://github.com/leezer3/OpenBVE/files/5055052/log.txt)

### Related information 

* OS: Windows 7 Build 7601 SP1 (Happens too on my previous Windows 10 1909/2004 install)
* Control Method: Keyboard

![GPU-Z_2020-08-11_14-07-51](https://user-images.githubusercontent.com/28094366/89863152-1c29a200-dbdc-11ea-968d-82cc8a0e5d77.png)

**Comment by leezer3** [comment]
Been meaning to look into this.

We seem to have a memory leak in that something is holding onto a reference to the VBOs used for GL3.

Investigating at the minute.

**Comment by leezer3** [comment]
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2020-08-19.zip

Should now be fixed from the current build onwards.
