### ISSUE TITLE
Typo in RouteInterface.cs

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#510]
https://github.com/leezer3/OpenBVE/blob/7101479c9056c5381e9a7bd660184d7105e8e4aa/source/OpenBveApi/Routes/RouteInterface.cs#L28

I personally thought It should indicate whether loading the route is successful, instead of sound.

**Comment by leezer3** [comment]
Thanks, copy + paste error.....

Feel free to submit PRs for anything like this you spot.
