### ISSUE TITLE
Texture address file error

### ISSUE THREAD

**Issue by ManuelMejias** [leezer3/OpenBVE#513]
Hello I'm reporting some interesting bug 

I have designed some environment than contain roads, bridges , houses, terrain, etc.

Due to the extensive textures  I must use a aliasing method to call textures on upper folders 

Using "..//" to move up a directory.
![IMG_20200819_114625_6.jpg](https://user-images.githubusercontent.com/38114108/90659123-51ed0d00-e212-11ea-95eb-4ca516aded0d.jpg)

The result was white textures, this doesn't happen on older version like 1.5*

While using "../" I was able to get running these textures without white faces.

![IMG_20200819_115238_1.jpg](https://user-images.githubusercontent.com/38114108/90659313-85c83280-e212-11ea-91bc-8a7fb5b01dff.jpg)

**Comment by leezer3** [comment]
Fixed.

It's not a good idea to use double-forward slashes in paths etc. though, as they're a pretty common comment indicator. (what this was intending to be stripping)
