### ISSUE TITLE
New rendered setcolor issue using track.brightness

### ISSUE THREAD

**Issue by ManuelMejias** [leezer3/OpenBVE#514]
Some parts of the train use setcolor to avoid apply new textures. The new rendered on 1.7.1.6 wasn't doing the brightness effect. However a bit step into 1.7.1.8 include brightness effect but partially only on textures.

![IMG_20200819_132506_0.jpg](https://user-images.githubusercontent.com/38114108/90669343-83b8a080-e21f-11ea-9685-a4a7da338a1d.jpg)

![IMG_20200819_132307_8.jpg](https://user-images.githubusercontent.com/38114108/90669376-90d58f80-e21f-11ea-9b29-31d41298187a.jpg)

**Comment by leezer3** [comment]
I *think* this has been fixed on the latest development build.
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2020-09-19.zip
