### ISSUE TITLE
Alpha texture not rendering on 1.7.2.0

### ISSUE THREAD

**Issue by LubuntuKHYT** [leezer3/OpenBVE#533]
### Description

Alpha texture will not render on v1.7.2.0 (Happens on RouteViewer, in game and ObjectViewer)

### Reproduction

Use Object Viewer to load an object with alpha texture assigned to it, the texture became invisible
But it will display properly on 1.7.1,8

### Related information 

* OS: Windows 7
* Method of control: Keyboard

### Demo object
[Demo.zip](https://github.com/leezer3/OpenBVE/files/5276293/Demo.zip)

**Comment by s520** [comment]
This issue has been fixed in the current nightly build.
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2020-09-24.zip
