### ISSUE TITLE
CsvRwRouteParser.Parser code looks suspect & instead of &&, | instead of II

### ISSUE THREAD

**Issue by shooking** [leezer3/OpenBVE#536]
### Description

Please describe the issue you are experiencing.

I am looking at code in Plugins->Route-Route.CsvRw->Namespaces->NonTrack->Route.cs->Parser->ParseRouteCommands

I am pretty sure C# is like C in that | is a bitwise or and || is a logical or.
Similarly for & v &&

So when I see code like

```
namespace CsvRwRouteParser
{
	internal partial class Parser
	{
		private void ParseRouteCommand(string Command, string[] Arguments, int Index, string FileName, double[] UnitOfLength, Expression Expression, ref RouteData Data, bool PreviewOnly)
		{
			switch (Command)
			{
...
				case "ambientlight":
				{
					if (Plugin.CurrentRoute.DynamicLighting)
					{
						Plugin.CurrentHost.AddMessage(MessageType.Warning, false, "Dynamic lighting is enabled- Route.AmbientLight will be ignored");
						break;
					}

					int r = 255, g = 255, b = 255;
					if (Arguments.Length >= 1 && Arguments[0].Length > 0 && !NumberFormats.TryParseIntVb6(Arguments[0], out r))
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "RedValue is invalid in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
					}
					else if (r < 0 | r > 255)
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "RedValue is required to be within the range from 0 to 255 in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
						r = r < 0 ? 0 : 255;
					}

					if (Arguments.Length >= 2 && Arguments[1].Length > 0 && !NumberFormats.TryParseIntVb6(Arguments[1], out g))
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "GreenValue is invalid in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
					}
					else if (g < 0 | g > 255)
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "GreenValue is required to be within the range from 0 to 255 in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
						g = g < 0 ? 0 : 255;
					}

					if (Arguments.Length >= 3 && Arguments[2].Length > 0 && !NumberFormats.TryParseIntVb6(Arguments[2], out b))
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "BlueValue is invalid in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
					}
					else if (b < 0 | b > 255)
					{
						Plugin.CurrentHost.AddMessage(MessageType.Error, false, "BlueValue is required to be within the range from 0 to 255 in " + Command + " at line " + Expression.Line.ToString(Culture) + ", column " + Expression.Column.ToString(Culture) + " in file " + Expression.File);
						b = b < 0 ? 0 : 255;
					}

					Plugin.CurrentRoute.Atmosphere.AmbientLightColor = new Color24((byte) r, (byte) g, (byte) b);
				}
					break;
```
it seems to me what is really meant is

(currently line 350)
```
--		else if (r < 0 | r > 255)
++			else if (r < 0 || r > 255)
```
similarly for g and b

The pattern is repeated in the file

If I was more skilled in git I would pull the code, propose the changes (after building).

**Comment by shooking** [comment]
I have run recent git pull thru a static analyzer.
More than happy to try to make suggestions once I get up to speed with git etc.
I see you have bugs in the Dispose at program shutdown - analyzer suggests this too.

**Comment by v1993** [comment]
Please enclose your code into ``` to make it show up properly.

OpenBVE developer have already [commented on this](https://github.com/leezer3/OpenBVE/issues/521#issuecomment-682160888).

**Comment by shooking** [comment]
thanks for the tip - done. The crux is someone is using | as if it were || - I dont think that is what they intended?

**Comment by v1993** [comment]
The comment I've linked explains why it is not too much of a problem and what devs think of it. Either way, this is already covered in another issue and probably can be closed.

**Comment by leezer3** [comment]
Our specific example here definitely isn't doing anything too interesting, and there's no way it can go wrong.
Either way would be valid with no issues in this case, but the current implementation is (probably) insignificantly faster.

In this case, we're working with a single number that cannot be null (as it's initialised a couple of lines above)
All the current code does is execute the comparison on both sides simultaneously (as opposed to linearly with a double pipe) and return false if either condition is met.

You can more clearly see this by inspecting the IL in your favorite decompiler.
Original:
```
    IL_17d5: ldloc.s
    IL_17d7: ldc.i4.0
    IL_17d8: clt
    IL_17da: ldloc.s
    IL_17dc: ldc.i4
    IL_17e1: cgt
    IL_17e3: or
    IL_17e4: stloc.s 
```
Double-pipe:
```
    IL_17d5: ldloc.s
    IL_17d7: ldc.i4.0
    IL_17d8: blt.s
    IL_17da: ldloc.s
    IL_17dc: ldc.i4
    IL_17e1: cgt
    IL_17e3: br.s
    IL_17e5: ldc.i4.1
    IL_17e6: stloc.s
```
Only real difference is that the double-pipe performs a branch ( **br.s** ) to determine which variable to pop from the stack, as opposed to keeping the value in the stack.


Whilst it gets a tad more complex if the second test is the return from a method call (as linear execution might not call the method, causing potentially unexpected / expected results elsewhere) there's nothing fundamentally wrong with this pattern here, it's just more complicated & less common, and I suppose easier to get inadvertantly wrong.

**Comment by shooking** [comment]
I see now one can use the | it's just I am so much more familiar with ||
for lazy evaluation. I am evaluating a code analyzer and needed some .NET -
hence I chose OpenBVE.

Thanks for helping evaluate checker.
