### ISSUE TITLE
Departure Sound played right after the simulation starts

### ISSUE THREAD

**Issue by LubuntuKHYT** [leezer3/OpenBVE#538]
### Description

When loading a train with Route.RunInterval, the departure sound will play right after the simulation starts
Then it will play one more time before departure time

### Reproduction

Load any route with Preceding Trains on v1.7.2.0(or latest nightly build)/The route provided below

## Route

[wrbve_v300.zip](https://github.com/leezer3/OpenBVE/files/5297865/wrbve_v300.zip)

## Logs

[log.txt](https://github.com/leezer3/OpenBVE/files/5297905/log.txt)

### Related information 

* OS (Windows 7 x64)
* Method of control (Keyboard)

**Comment by leezer3** [comment]
Seems to have been an issue going right back to 1.4.2-
They forgot to check whether the game was still in minimalistic simulation when triggering the sound.
This caused sound to be played as soon as the game started.

**Comment by Kenny-Hui** [comment]
The same thing happens again after the shift of TrainManager (Seems to be, at least on Nightly build)

**Comment by leezer3** [comment]
Sorry, missed that one....
Moving the train loading out of the main thread meant they were no longer blocking some bits and so the state value i was checking was then wrong.
