### ISSUE TITLE
[Suggestion] Track.Announce on all cars

### ISSUE THREAD

**Issue by LubuntuKHYT** [leezer3/OpenBVE#545]
Track.Announce already existed back in BVE2, back then there's only cab view in-game and the announcement would play in the cab

However, most (if not all) trains nowadays would play announcement across all cars, wouldn't it make more sense to play announcement across all cars in OpenBVE?

Please consider about this, thanks!

**Comment by leezer3** [comment]
It would have to be a different command entirely, but not unreasonable.

Too much legacy stuff is going to be relying on the driver car behaviour of the default announce.

**Comment by leezer3** [comment]
That was actually quite easy to add.

New commands:
**AnnouceAll
DopplerAll**

These behave in exactly the same way as the **Announce** and **Doppler** commands, but are triggered by the front axle of each car, as opposed to the driver's car.

**Comment by Kenny-Hui** [comment]
Didn't have time to test before, but is it possible to improve this?
The announcement are not synchronized between different car. If it start playing on the end of the car, start playing on the first car, then a while later start playing the second car etc (and would cause loop)

If it start playing on the first car, I would still hear duplicated announcement on other car (but the delay is not as severe as at the back)

Maybe utilizing train.dat/extension.cfg car length to offset the announcement on the other car would solve the issue? Thanks!
