### ISSUE TITLE
Unrecognised command enablebvetshacks

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#547]
### Description
Playing on the latest nightly build, the Options.EnableBveTsHacks seems to be unrecognised.

### Reproduction

Add "Options.EnableBveTsHacks 1" on any route, and you will see an error in RouteViewer/In game

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/5397102/log.txt)

### Related information 

* OS: Windows 7 Ultimate SP1
* Method of control Keyboard

**Comment by leezer3** [comment]
My fault.

It was actually being used, but the error was being generated accidentally.

TLDR:
https://github.com/leezer3/OpenBVE/commit/6924f412dde328589fc15574221e04b5e60b2973 introduces a better / more readable method of parsing commands from within the routefile in most places.
This is parsed somewhere different, and got missed from this list.
