### ISSUE TITLE
Inconsistent OpenTK version requirements

### ISSUE THREAD

**Issue by danfe** [leezer3/OpenBVE#548]
While building OpenBVE under FreeBSD, where we have special `makenuget` target to list all dependencies, I couldn't help to notice that for OpenTK, both versions **3.1.0** (e.g., in `source/Plugins/Object.Animated/packages.config`) and **3.2** (e.g., in the main `source/OpenBVE/packages.config`) are required.  Since they differ only by the minor version number, perhaps this dependency can be satisfied by a single version, so downstream packagers have one less dependency package to pull and worry about?

Another thing is that apparently, version **3.2** should really be **3.2.0**: it fails to fetch when spelled as **3.2** and when I go to https://www.nuget.org/packages/OpenTK/3.2 it also shows it as **3.2.0**.

**Comment by leezer3** [comment]
Good spot.

It's probably Visual Studio auto-generating / truncating the version number, but that makes perfect sense.
The two packages left on 3.1.0 were accidental.

IIRC we should build / work with anywhere from 2.0 through 3.2.0, although there are definitely some joystick / linux related patches in later versions.
4.0 is a complete library re-write, and I haven't even thought about testing with it at the minute.
