### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#549]
### Description
The route/train loading screen appears to have a "border" at the bottom, is there any way to make it so that it will always cover the window? (This doesn't look very obvious with the default image as it's also gray, but it doesn't look that good on route with custom loading screen)
![image](https://user-images.githubusercontent.com/28094366/96826478-064f1d80-1466-11eb-858c-2848b3d3443c.png)

### Reproduction

Load any route and you should see a gray border at the bottom of the window.

### Related information 

* Operating system: Windows 7 SP1
* Method of control: Keyboard

**Comment by leezer3** [comment]
This depends on the screen resolution.

If your aspect ratio doesn't match that of the image, it does that rather than stretching it.

**Comment by v1993** [comment]
Since those images don't carry any important information, how about cropping them to fit instead?

**Comment by Kenny-Hui** [comment]
Thanks, that's what I meant
However for compatibility of different route, it might've been more sensible to have an options to toggle it
Anyways, thanks for your hard work!

**Comment by Kenny-Hui** [comment]
Seems unnecessary, since we may still lose information on the image if we scale to fit (if the logo is in any corner)

Closing this
