### ISSUE TITLE
Package Management: Uninstallation dependency check inoperative

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#551]
There is a flaw in the package installation handler at [formMain.Packages.cs#L110](https://github.com/leezer3/OpenBVE/blob/fe7aaf7c763c0f5dcb11cfda0d4518abdc63b980/source/OpenBVE/UserInterface/formMain.Packages.cs#L110):
```
List<Package> Dependancies = Database.checkDependsReccomends(currentPackage.Dependancies);
if (Dependancies != null)
{
    //We are missing a dependancy
```
The `currentPackage.Dependancies` List (reference type) is directly passed to the `Database.checkDependsReccomends` function, where: [Packages.Database.cs#L124](https://github.com/leezer3/OpenBVE/blob/fe7aaf7c763c0f5dcb11cfda0d4518abdc63b980/source/OpenBveApi/Packages/Packages.Database.cs#L124)
```
public static List<Package> checkDependsReccomends(List<Package> currentList)
{
  if (currentList == null)
  {
    return null;
  }
  foreach (Package currentDependancy in currentList.ToList())
  {
    switch (currentDependancy.PackageType)
    {
      case PackageType.Route:
        if (DependancyMet(currentDependancy, currentDatabase.InstalledRoutes))
        {
          currentList.Remove(currentDependancy);
        }
```
All dependencies that are met got removed. Since `currentPackage.Dependancies` is passed as reference, now all dependency information on the current manipulating package got removed.
So, none of the dependency information got stored into the package database, which completely breaks the dependency check at uninstallation, and allows the player to possibly break a dependency when uninstalling packages,

To fix the problem, the implemention of `checkDependsReccomends` should be changed from
```
public static List<Package> checkDependsReccomends(List<Package> currentList)
{
  if (currentList == null)
  {
    return null;
  }
  foreach (Package currentDependancy in currentList.ToList())
  {
```
to
```
public static List<Package> checkDependsReccomends(List<Package> currentList)
{
  if (currentList == null)
  {
    return null;
  }
  currentList = currentList.ToList();
  foreach (Package currentDependancy in currentList.ToList())
  {
```
Sorry for not being able to submit a PR, because my IDE has not been properly set up.

**Comment by zbx1425** [comment]
Another problem is that, even if this is fixed and the dependency info is written into packages.xml, uninstallation dependency check is still inoperative. This might need further investigation...

**Comment by leezer3** [comment]
Thanks.

Uninstall method:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/UserInterface/formMain.Packages.cs#L488

Similar bug there, I'll fix that and let's see what happens.
(I'm sure I tested this....)

**Comment by zbx1425** [comment]
Nope, the Uninstall method is more broken now.
https://github.com/leezer3/OpenBVE/blob/e9dfa4a33f76f7cf4db8dd7d69869c91b4841a11/source/OpenBVE/UserInterface/formMain.Packages.cs#L491
It seems that the `Database.CheckUninstallDependencies` is intended to receive the package to be uninstalled as its paramter, not its dependencies.
Now every package with dependencies will not uninstall at all.
I think L491 should be `Database.CheckUninstallDependancies(new List<Package>(new[] {packageToUninstall}))`

**Comment by leezer3** [comment]
Hmm.

The whole thing is wonky :/

May take a day or two to re-write.

**Comment by leezer3** [comment]
So, I couldn't reproduce the failure to uninstall.
However, the dependancies weren't being stored right (as when we install a new package, we need to store it's GUID in anything that it depends on)

Please however try the current build. This solves that, and I can't see anything else immediately wrong, but this part of the code is still likely to have some unexpected bugs.....

Longer term, the package database is a little bit of a mess,
It really wants changing to a key / dictionary setup, but this isn't serializable by default, which is presumably why it got done as a list in the first place (can't remember.....)
https://stackoverflow.com/a/1728996/722627

Will think about that at some stage when I've got time.

**Comment by zbx1425** [comment]
I am currently working on a [third-party package manager for OpenBve](https://github.com/BVEContentService/BVEPackMan/blob/main/source/PWPackMan/ILocalRegistry.cs), so I hope the API can be unchanged...
Otherwise I'll have to update the bindings as the package.xml upgrades :D

---

I don't personally think storing both the dependants and the dependencies in the database is a good idea (or it's not? Sorry but didn't read the code carefully). A two-way binding is just too easy to get broken (if someone tries to edit the file manually, or by some oversight in code, as they have to all be updated when a new pack gets installed), and then we'll end up in a state of uncertainity.
I think only storing the dependencies, and then enumerate all packages to check for dependencies on each manipulation (like before) would be a better idea. The time cost should be affordable, since I think no one would ever have 1000+ packages installed even in the future.

**Comment by leezer3** [comment]
API is unchanged.
Database is also very little changed, this was the simplest way I could think of, as it isn't relational.

It's not really a two-way binding (not that complicated), just a simple list of GUIDs.
On uninstall, we check if these are still present in the DB, and show the error listing these if so.

Enumerating all packages on install / removal is seriously not a good idea. that's how you get more performance issues than we've got already.

With regards to editing the database file manually, this is what I'd call user beware territory.
Code oversights are always possible, but this isn't limited to the database by any means. 

Finally, please remember that this was designed from the start to be as simple as possible, and little more than a slightly more advanced archive extractor (a good comparision would be something like Mod Organizer for Skyrim etc.) :)
I very deliberately haven't built for any online / curation functionality, this caused far too much trouble the last time around.

**Comment by zbx1425** [comment]
I now see your point about the change in design, and I agree that online funtionality should be the territory for third-party tools.

---
My worry is that, if you have multiple different versions of OpenBVE installed on the same system (which is quite common), and the database format got changed, then all older versions will not work, as the database is shared between all of these versions.
Even if the database format is backward-compatible, the older version still cannot modify the database in the correct way.

So if there is not a better way than asking the user to upgrade their OpenBVE installation to the latest version, then restoring the older API is not needed since everything are not backward-compatible anyway. I think I'll just update the API binding after the next release and set a minimum version requirement.

---
Just tested the last nightly build and it now all works. Thanks!
However, the package name is shown twice if a package being uninstalled is the dependency of another package.
Packages that reproduces this behavior:
https://api.zbx1425.tk:8953/bcs-src/zbx1425.outlook.com/TFODemo_Routes.zip
https://api.zbx1425.tk:8953/bcs-src/zbx1425.outlook.com/TFODemo-Series103.zip (Dependency)

**Comment by leezer3** [comment]
Thought of that :)

If the version is older, it'll run an upgrade / scan to generate the correct fields.
If opened by an older version, it's backwards compatible & it'll just cause the scan to be re-done next time round. (As the new version number field is missing)

Going forward, if the version is bumped, the program now recognises this & shows an appropriate error popup.
