### ISSUE TITLE
The doors on both sides will open inexplicably.

### ISSUE THREAD

**Issue by Dingzaai** [leezer3/OpenBVE#561]
### Description

When opening the game, if the train is not in the stop state, the doors on both sides will open inexplicably.

### Reproduction

All lines set to "stop only but not open" will have this error at the beginning of the game.

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

## Logs

There is no error report, but the train will automatically open the doors on both sides.

### Related information 

* Windows 10
* Keyboard

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/384d60ece88c414f99cdb932acbbddd89c207406

Apologies, that was accidental.
0 managed to get linked with both sides by mistake, N was unaffected.

Will try and get a newer build pushed out this week.
