### ISSUE TITLE
64-bit OpenBVE build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#562]
Currently with Large Address Aware set (Hope I got that right, forgot the name), OpenBVE is able to utilize around 3.5GB of memory.

But as route became more detailed and more scenery is being made, it's easy to hit the limit.

I am using a 1GB 650 Ti BOOST, on an unreleased (also unfinished Hong Kong route). The route end up taking 4-5GB of memory. And on an Intel HD 4600, it end up using 9GB of system RAM.

I understand that switching to 64bit build is not something that could be done instantly, but is there any plan to make some progress in the future?

Thanks for your hard work!

**Comment by leezer3** [comment]
To be exact, it'll build and run in 64-but perfectly.

The trouble is that it breaks 90% of train plugins. (Anything using the legacy Win32 dlls)

I can add a 64 bit variant without too much trouble if you want.
Will take a closer look / think later; this did get experimented with in the past, but I think you're the first to *need* it:
https://github.com/leezer3/OpenBVE/pull/230

**Comment by Kenny-Hui** [comment]
Thought there are some cross-platform compatibility issues when I posted this
Thanks, it would be appreciated!

**Comment by leezer3** [comment]
The cross-platform issue is Mac OS.

This is because the Mono forms implementation on Mac isn't 64-bit. (and is also what's breaking the most recent OS-X versions)
I'm really hoping the Mono team manage to patch winforms for x64.

Not a lot we can do there, and you're I think the only person who is really pushing the 32-bit limit this hard.
It might be interesting to look in your routefile to see if anything can be optimised, but if it's anything like the last HK stuff I looked at, at this level, the power of 2 rule for textures is *majorly* important. Remember that if you go 1 pixel over the size, it'll be upscaled internally to the next valid power of 2. There is absolutely nothing I can easily do about this, it's a fundamental rule of math and memory.

**Comment by Kenny-Hui** [comment]
I personally haven't looked at them yet, but there's probably some optimization that could be done before the initial release.

The problem is that is only Phase 1 of a Hong Kong Route (Tuen Ma Line)
Later when they have to work on the full route, it's never going to be enough VRAM.

Unfortunately I don't think I can share the route here (Private route). But I will see what I can find.

**Comment by Kenny-Hui** [comment]
Knew it, most of the texture are not in the power of 2.
I tried resizing all of them (Mostly downscale, unless the texture is only 10 pixel below the next power of 2).
After doing some testing, it's just enough to reach to the end of the route in F1 (although missing texture is still visible in the end, still better than before)
However it still doesn't seems to be enough to render the train exterior.

Without going deep into the HK MRT network, the red rectangle is the current route, and it already seems to exceed the 32-bit memory limit.

![image](https://user-images.githubusercontent.com/28094366/102750198-61d35400-43a0-11eb-9b5a-efce9861d754.png)
Integrated graphic are even easier to hit the limit. I am concerned that in the future when the full route is available, you need at least 8-12GB dedicated VRAM in order to play the full route. Then alot of players are frustrated because they can't play.

Just asking if it's possible to implement 64-bit build on next year or something, since not many public route can hit the limit at this point. Thanks!

**Comment by s520** [comment]
@leezer3 
It has been a while.
I'm feeling a little better today, so I came to see GitHub.

I think it's very unlikely that a 64-bit version of WinForms will be added to Mono.
Microsoft has already released .NET 5, and the .NET Framework is ending.
I think Mono will end in the same way.

Therefore, other UI frameworks are required to work on macOS.
Some candidates are Avalonia, Xamarin Forms, etc.

Also, when changing the UI framework, I think it is better to move to .NET 5 or later in consideration of the future.

**Comment by leezer3** [comment]
No trouble.

Other than the MacOS issue, everything else is fixable without too much trouble, all that needs doing is to move the Win32 plugins out of the base process.
There is an old experimental build which does just this here:
https://github.com/leezer3/OpenBVE/pull/230
This works nicely on Win32, but at the time didn't work nicely on Linux. It got pushed to the back of the queue as nobody was really attempting to push the 32-bit limit & there were more important things to play with.

---

MacOS wise, there is the following:
https://github.com/mono/mono/issues/6701
https://github.com/filipnavara/mac-playground

For minimum effort, it'd probably be possible to use this on all platforms (if I understand it right).
I will try and have a play at some stage soon, but Christmas and the current situation mean I'm a little busy right now too....

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/tree/WinPluginProxy

Need to fix the RailDriver before merging (solution in the older PR can be considerably improved), but that'll give us working 64-bit on Win32 & Linux at least as a good starting point :)

**Comment by leezer3** [comment]
[Experimental64Bit.zip](https://github.com/leezer3/OpenBVE/files/5735388/Experimental64Bit.zip)

Try the above.

This build should work with both 64-bit and 32-bit.
If using 64-bit, a separate child process will spawn (along with an associated debug console window) to host legacy plugins.

You can tell it's running under 64-bit from the version number in the main menu, which now has 64-bit appended when appropriate.
I will update the log files and in-game debug display at some point.


Feedback would be appreciated please; This *should* work, and I can't think of anything that would immediately go wrong, but it's a somewhat fundamental change, so expect the unexpected.

**Comment by Kenny-Hui** [comment]
Did a little testing
It seems there's no ATS sound (but looping ATS sound does sound)
OS_ATS Security key doesn't work

That's all I can find for now, I've told others to test it as well.

**Comment by leezer3** [comment]
Thanks :)

I'll do a little digging, must have messed something up with the sound. IIRC the previous branch dates from before SoundManager which is probably why.

Can you also clarify which security key, on which train also?
(A1, B1 etc.)

I've tried basic operations with UK stuff (AWS, wipers etc.) which all appear to be OK.
We're probably missing something somewhere, but it's so much easier to test when I know what's broken.

**Comment by leezer3** [comment]
Sound definitely works with UKTrainsys stuff.
First test I had to hand:
http://www.bvecornwall.co.uk/wordpress/br-class-50/

AWS horn definitely works on startup, engine sounds and all the associated bits I can immediately think of work too,

Going to need a link to your broken train to see what it's doing differently.

**Comment by Kenny-Hui** [comment]
Probably all security key on OS_ATS on all trains.

I haven't tested Del Ins Home End PgUp PgDn since I haven't found trains that utilize then yet, but the number keys on the keyboard doesn't work. (Switching back to 1.7.1.3 works fine)

Also when the simulation starts with OS_ATS trains, I heard AirZero being played, and the reverser is set to neutral (Via the plugin, but the HUD still says F)

This is a known issue in OS_ATS when jumping stations, but it shouldn't triggers on the start of the simulation

**Comment by Kenny-Hui** [comment]
> Sound definitely works with UKTrainsys stuff.
> First test I had to hand:
> http://www.bvecornwall.co.uk/wordpress/br-class-50/
> 
> AWS horn definitely works on startup, engine sounds and all the associated bits I can immediately think of work too,
> 
> Going to need a link to your broken train to see what it's doing differently.

Weird, I can't hear any ATS sound even with 3 different plugin

Anyway, here it is: https://drive.google.com/file/d/1YsoW0FA3wKmwTRFvhePm39HQr2Cj7Oyu/view?usp=drivesdk

Function doesn't seems to work for me

Unfortunately there's no ATS sound in this, I will try to find another (hopefully publicly available) train that has ATS sounds

**Comment by leezer3** [comment]
That strongly suggests to me that the proxy application is failing to communicate with the main program, which would also explain why sound etc. is not working.

Most likely explanation is that you've got an antivirus firewall blocking it.
https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/firewall-instructions

**Comment by Kenny-Hui** [comment]
I will try these steps tomorrow (actually today), thanks

Though All plugin does not have sound
But only OS_ATS security key doesn't work, which is very weird

I also didn't see other devs reporting anything, I might try it later on a different machine

**Comment by Kenny-Hui** [comment]
Running on Windows 7, after allowing OpenBVE on firewall (or even completely disabling firewall), the sound still did not work.
On OS_ATS, my best guess is it fails to parse the panel indicator part in the config file? All other system in OS_ATS works fine.

After testing your br-class-50, it seems the sound do play, but some at an extremely low volume. I've recorded a video of it.
The first one is v1.7.2.3, and the second one is the experimental 64bit build linked above.
https://www.youtube.com/watch?v=vpdj1YvNzCo

Unfortunely I don't think my VM is happy about it, will have to find another win10 host and see
![image](https://user-images.githubusercontent.com/28094366/103068511-3ea2e180-45f8-11eb-8baf-e305b3875815.png)

**Comment by Kenny-Hui** [comment]
Nope, same result on Windows 10 1909

**Comment by leezer3** [comment]
That crash makes a little more sense.

Try deleting the file OpenAL32.dll from the main game folder & see if that gives you sound working sensibly.
Thinking about how to get this working right.

**Comment by Kenny-Hui** [comment]
Unfortunely the sound still seems broken after deleting OpenAL32.dll

**Comment by leezer3** [comment]
Dunno  not many more ideas at the minute.

Have you tried a train with no plugin?
Would be useful to see if it's a wider sound issue. 
(Math rounding issue maybe, still thinking)

**Comment by Kenny-Hui** [comment]
Didn't see any issues with the sound itself.
.NET plugin can also play sound just fine. Just Win32 plugin are having some problems

**Comment by leezer3** [comment]
[64-bit experimental 2.zip](https://github.com/leezer3/OpenBVE/files/5741947/64-bit.experimental.2.zip)

Try this one, altered the approach slightly. (not commited, let's see if it works first)

**Comment by Kenny-Hui** [comment]
Still the exact same issue, I'll try it on my another machine and see does it make a difference. (My main pc's sound config is slightly weird anyway)

**Comment by leezer3** [comment]
Pity :(
I was hoping that might fix OS_ATS (some implementations use the panel array as data storage) but obviously not.

I'd also try another (minimal) test route and see if that helps at all, in case we're fighting with station sounds or something.

**Comment by leezer3** [comment]
[64-bit experimental 3.zip](https://github.com/leezer3/OpenBVE/files/5743387/64-bit.experimental.3.zip)

Attempt number 3....
Discovered single play sounds weren't working correctly, which explains a lot.

**Comment by Kenny-Hui** [comment]
Was about to sleep, so didn't do alot of testing

But the sound issue seems to be resolved (At least on class 50), the alarm volume is normal again

Will try other train tomorrow, thanks!

**Comment by Kenny-Hui** [comment]
Now some other plugin's ATS sound will just.. not stop.
Here's an example train: 
[KCRWR_SelTrac_Test_Train.zip](https://github.com/leezer3/OpenBVE/files/5744094/KCRWR_SelTrac_Test_Train.zip)

(Turn down your volume before launching)
The ats sound just keeps looping.

Ins: Mode selector (Off direction) (Sound\signal_trainoff.wav should be played once when it's off. But instead it keeps looping)
Del: Mode selector (ATO direction)

**Comment by leezer3** [comment]
[64-bit experimental 4.zip](https://github.com/leezer3/OpenBVE/files/5747346/64-bit.experimental.4.zip)

I think that's now fixed.

Note that it's still not happy running multiple instances (this may not be supported, and isn't really a sensible use-case in the first place)

**Comment by Kenny-Hui** [comment]
Yep, sound definitely works properly now, and OS_ATS now works. Thanks!
