### ISSUE TITLE
Malfunction in the latest nightly build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#563]
### Description

Something has terribly gone wrong with the latest nightly build, I don't see a specific pattern for now but some of them include:

Unrecognised command background.x encountered in the Structure namespace at line 26, column 1 in file E:\Rail\Railway\Route\route.csv

Unrecognised command background.aspect encountered in the Structure namespace at line 27, column 1 in file E:\Rail\Railway\Route\route.csv

And other wallend command error (It doesn't seems the wall got generated at all)

And it doesn't seems to be able to parse the Animated Objects Demo route.
![image](https://user-images.githubusercontent.com/28094366/100820738-d4c86980-3489-11eb-9d0b-5c31184f4689.png)

### Reproduction
Animated object demo route is a good example, but I think alot other route also has issues

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/5626634/log.txt)

### Related information 

* Operating system: Windows 7
* Method of control: Keyboard

**Comment by leezer3** [comment]
Backgrounds I can reproduce and have fixed.

The animated object demo route is an issue with your choice of folder structures.
You've stored your files in **E:\Rail\Railway** and have then created per-route subfolders below this.
As we've found a Railway folder with contents, we assume this must be right.

Simple answer is to rename the folder to remove railway from it's name.

**Comment by Kenny-Hui** [comment]
Thanks!
Also it seems some object just refuses to load, will take a look tomorrow

**Comment by leezer3** [comment]
Examples please ;)

**Comment by Kenny-Hui** [comment]
Shutted down the PC, sorry
I have only tried 2 routes, but here's what I found:
Cube command with an AddFace below would make the CsvB3d Parser plugin not load (Object not set to an instance of object)

Not sure what's the purpose of adding AddFace below a cube, but removing it does nothing. And it's likely I am the only one who encountered these weird objects.

On the other route, it seems some rail objects are not being switched (Probably because it fails to load the object?).

I am not sure about this one as I don't think it relies on cube command, I can probably give you the object tomorrow if I can reproduce it in ObjectViewer

**Comment by Kenny-Hui** [comment]
My bad, doesn't seems there's anything wrong with object parsing.
Though it seems some walls are not being generated in the latest nightly build.
![image](https://user-images.githubusercontent.com/28094366/100976785-fd7c5c00-357a-11eb-8ddd-1c8b01134620.png)

Route:
https://drive.google.com/file/d/12BfZz95emdiKpUoJM6eakitzxTRMqotC/view?usp=sharing

**Comment by leezer3** [comment]
Entirely my own fault, but triggered by BVE being inconsistant.
Walls / dikes use 0 for both directions, but stations use 0 for no direction.

One of the more recent changes has been to add a helper function to convert this into a nice 'readable' direction internally, and I overlooked this difference once when adding the function (set 0 to both, as I was obviously testing with a station) & then set 0 to none when the station door sides were reported as being wrong....

Now hit a little harder!

**Comment by Kenny-Hui** [comment]
Should be resolved!
