### ISSUE TITLE
Not reflected the Informations Default Displaying Plugin (for testing)'s parameters.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#564]
### Description

I set this screenshots settings.

![勾配などが反映されない](https://user-images.githubusercontent.com/22734699/102114048-1dfebd00-3e7d-11eb-9881-d50bfc55dd55.png)

But, not reflected these parameters.
When I set to all parameters, but the display is 
I set to the clock, speed is kmph, DistNextStation is Km, and fps.
But the displaying is stop is miles, gradient and speed is mph.

![Screenshot from 2020-12-15 02-10-29](https://user-images.githubusercontent.com/22734699/102114911-1ee41e80-3e7e-11eb-9166-2ef308bc583e.png)

OpenBVE's version is
v1.7.416.1319-travis
1.7.2.0 is correctly.

Could you please confirm this?

### Reproduction

This is some options trouble, so the route is any.

## Route

This is some options trouble, so the route is any.
So, no links.

## Train

The train is any.

## Logs

This issue is no crash, so no logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Will take a look.

I have a suspicion this might need another setting enabling, but I can't remember off the top of my head.

**Comment by ginga81** [comment]
This trouble has been fixed at 1.8.0.2.
So this issue is closed.
