### ISSUE TITLE
1.7.2.2 cannot start

### ISSUE THREAD

**Issue by danfe** [leezer3/OpenBVE#565]
Version 1.7.2.2 builds fine on the FreeBSD, just as 1.7.2.1 does, but cannot be run, emitting the following to the console:
```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'TrainManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'TrainManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'TrainManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'TrainManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```
Version 1.7.2.1 starts and runs normally.  Any ideas how to fix this?

**Comment by leezer3** [comment]
Now that's interesting.
TrainManager.dll is a new shared library this build, but it's entirely our code.

How did you build exactly?
Wonder if there's a configuration specific issue with the makefile or a relative path issue :/

Will try and spin up a VM and reproduce over the next day or two.

**Comment by danfe** [comment]
> How did you build exactly?

Provided you have FreeBSD system with the ports tree checked out under `/usr/ports`, it's just as simple as `cd /usr/ports/games/openbve`, `vi Makefile`, bump `PORTVERSION` to 1.7.2.2, `make makesum`, `make install`, `openbve`.

Under the hood the build is using provided `makefile` with some modifications (like disabling `nuget restore` because those are handled by the framework and lowering `MIN_MONO_VERSION`).

**Comment by danfe** [comment]
Oops, mea culpa, `TrainManager.{dll,pdb}` had been missing from the packaging list and thus has did not make it into the package.  I don't know how I've missed this.  Sorry for the noise, everything is working. :-(

**Comment by leezer3** [comment]
No matter.

TrainManager.dll is the next phase of combining the under the hood code (as currently a lot of the editors and viewers use duplicated dummy code)
This makes maintenance and bug finding much easier :)
