### ISSUE TITLE
Rivatuner statistics server incompatibility with non-power of two sized texture

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#566]
### Description

When using Rivatuner statistics server to display the stats with Raster 3D rendering mode/Other overlay utilities (Photo 1), any non-power of two sized texture on the width would result in some sort of texture corruption (Photo 2)

Photo 1
![image](https://user-images.githubusercontent.com/28094366/102590170-1ecc7300-414b-11eb-9c28-46612c7a883b.png)

Photo 2
![image](https://user-images.githubusercontent.com/28094366/102590333-5b986a00-414b-11eb-94e5-758540d5b7e6.png)

Pattern (At least for me):
256x128 Texture: No corruption
256x129 Texture: No corruption

257x128 Texture: Corruption
257x130 Texture: Corruption

### Reproduction

1. Install MSI Afterburner with Rivatuner statistic server
2. Go to settings, monitoring tab and enable any graph by clicking the "Show in On-Screen Display"
3. Go to On-Screen Display, click more at the bottom right, and make sure the options are the following (Photo 3)
4. Launch OpenBVE, and start the route provided below. (This also applies to object viewer and route viewer)
5. If successfully reproduced, you can see the texture are corrupted in the first station (Might also happen in other overlay)

Photo 3
![image](https://user-images.githubusercontent.com/28094366/102591262-b54d6400-414c-11eb-8fed-bbcd399fc620.png)

## Route and Train
https://drive.google.com/file/d/1ytcipDvetRKiMr6swbkR-w76f129Z1ke

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/5714502/log.txt)

### Related information 

* Operating system: Windows 7
* Method of control: Keyboard

**Comment by JonnyTech** [comment]
Does the corruption occur with Windows 10?

**Comment by Kenny-Hui** [comment]
> Does the corruption occur with Windows 10?

It should, also I found out alot of overlay utilities also causes the same corruption

Was trying to record a video of an route performance, that's why I needed the overlay

**Comment by leezer3** [comment]
I don't think there's anything we can do for that- It primarily proves why the power of 2 rule is a thing. 
I suspect it'll most likely corrupt with texture widths upto about 384px and then be OK upto 512px.
(Essentially, it looks to me like it's clipping the texture in-memory at the nearest power of 2 boundary)

We just upload the textures to OpenGL & the drivers handle it internally at the minute.

There is actually code in there to deliberately resize things to the nearest power of 2 before uploading ot OpenGL, but this is a memory and performance killer & so is disabled.
I suppose I could re-enable ths with a hidden option, but at the end of the day this is an uncommon driver bug not us.
