### ISSUE TITLE
Problems with "COBRA M5" joystick

### ISSUE THREAD

**Issue by v1993** [leezer3/OpenBVE#57]
MonoDevelop said:
`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: button
  at OpenTK.Input.JoystickState.SetButton (JoystickButton button, Boolean value) [0x0000b] in <filename unknown>:0
  at OpenTK.Platform.SDL2.Sdl2JoystickDriver.OpenTK.Input.IJoystickDriver2.GetState (Int32 index) [0x00070] in <filename unknown>:0
  at OpenTK.Input.Joystick.GetState (Int32 index) [0x00000] in <filename unknown>:0
  at OpenBve.Joysticks.Initialize () [0x00013] in /home/v/compile/OpenBVE/openBVE/OpenBve/System/Input/Joysticks.cs:49
  at OpenBve.Program.Main (System.String[] args) [0x005d7] in /home/v/compile/OpenBVE/openBVE/OpenBve/System/Program.cs:224
`
My joystcik in lsusb output:
`Bus 005 Device 003: ID 11c0:5603`

**Comment by leezer3** [comment]
It's an issue with OpenTK & joysticks with you over 32 buttons. I have an
open pull request here to fix the issue, although there is some discussion
about changing it a tad:
https://github.com/opentk/opentk/pull/344

I will upload a fixed .DLL here when I'm home.

**Comment by v1993** [comment]
I tested your .dll. OpenBVE wasn't crash, but I saw too many buttons. Indicators dosesn't react to mooving/pushing with fixed .dll.

**Comment by leezer3** [comment]
Please try the in-game configuration.

The SDL2 backend does not detect button/ axis motion in the main form, which is one of the reasons why the in-game configuration menu was added.

Not sure why it's detecting too many buttons, how many does it have, and how many do you think it should have?
Is it possible it's detecting a hat as 4 buttons or something similar?

**Comment by v1993** [comment]
Joystick have got: 5 buttons, one turner (detected as buttons, 3 positions), two hats (only one detected as buttons, 8 positions). About asixes: Froward/Backward; Left/Right; Turning Left/Right, one wheel, one hat detected correctly. In game menu configuration isn't user-friendly, so I can't find options like 'Brake full asix' and other. Why SDL2 doesn't work?

**Comment by leezer3** [comment]
Best I can tell you is that it's something to do with the way that OpenTK receives joystick events.
It only appears to be registering for SLD2 joystick events when the gamewindow is instantiated, but why I have no idea.
JakubVanek did suggest trying to P/Invoke SDL2 to allow background events, but that had no effect, so I'm out of my depth on fixing it in OpenTK.

I'm currently working on improving the situation a little as follows:
* Allow selecting of OpenTK backend in the configuration file- Whilst I'd prefer leaving OpenTK to it's own devices, this is probably a good option.
* Show an appropriate error message in the controls menu if using SDL2.

**Comment by leezer3** [comment]
That should help a bit.
Whilst I'm not thrilled, the default is now not to use the SDL2 backend, so I think setting controls should work for you in the menu.

I don't think it'll do anything for your other issues though. I'd **guess** that the extra buttons are probably cosmetic, and it may well work fine, but no guarantees.

Unless I get my hands on a joystick that produces this sort of error, my hands are tied in fixing it.
I have the following joysticks/ controllers here which all work fine FYI:
Generic joystick (4 buttons, 1 hat, 3 axis), identifying itself as MegaWorld USB Game controller
PS3 Sixaxis pad
Xbox360 wired pad

**Comment by v1993** [comment]
Where can I find configuration file?

**Comment by v1993** [comment]
Sorry, I slove this problem. My current result:
Default building: preferNativeBackend = true -- no any joysticks, preferNativeBackend = false -- crash
My manually builded .dll from your opentk repo: preferNativeBackend = true -- no any joysticks again, preferNativeBackend -- message about problems with SDL2 backend, but I can see joystick.

**Comment by v1993** [comment]
It's my manually builded opentk.dll:
[OpenTK.dll.zip](https://github.com/leezer3/OpenBVE/files/183677/OpenTK.dll.zip)

**Comment by leezer3** [comment]
OK, so I've done some major digging into this!
Some technical discussion at the tail end of the OpenTK pull request, but in essence the commit above should improve things massively.

With your manually built OpenTK.dll, **preferNativeBackend** should work in both cases now.
**preferNativeBackend = true** should also allow you to use the main menu to configure the joystick, although you may find that you need to move the stick once for it to be detected.

**Comment by v1993** [comment]
OK, but now I've got new problem: hat doesn't work correctly, it register wrong positions. Also, now is normal count of buttons, but I can see two hats (joystick have got two, but first hat is working as buttons).

**Comment by leezer3** [comment]
Not a lot I can do on that I'm afraid. (At least not without the stick in my hands)

Does jstest-gtk recognise the correct joystick layout, or is that broken as well?
If that's also broken, then you'll need to change the layout in the kernel joystick driver. I think you can do that via jstest-gtk, but I don't know enough about what the stick is reporting or for that matter kernel driver development.

**Comment by v1993** [comment]
jstest-gtk give me correct results (one hat with correct positions).

**Comment by leezer3** [comment]
OK, so it's an OpenTK mapping issue then.

I can't do much without the stick, sorry.
Is this it?
https://www.alzashop.com/defender-cobra-m5-d354042.htm?layoutAutoChange=1

**Comment by v1993** [comment]
Yes, It's my model!
