### ISSUE TITLE
extensions.cfg Reversed = True state no longer properly reversing object

### ISSUE THREAD

**Issue by RetentiveGOAT** [leezer3/OpenBVE#573]
### Description

When adding the trains bogies in the extensions.cfg file, and changing the state of "reversed" from false to true, the bogies no longer reverse correctly, some objects will reverse and produce undesired behavior, while others will stay the same

### Reproduction

Check any NYCTA equipment on BVEStation, and change the "reversed" state of any of the trains bogies from false to true in the trains' extension.cfg file

### Related information 

* Operating system: Windows 10
* Method of control: Trustmaster HOTAS One Joystick

**Comment by leezer3** [comment]
Can you try the latest nightly build please?

I think this was fixed by https://github.com/leezer3/OpenBVE/commit/c0af89b29eaf33e945f1b57ba0248565dba21b27

**Comment by RetentiveGOAT** [comment]
The wheels for the reversed bogies are still turning in the opposite direction relative to the trains movement in the latest nightly build.

**Comment by leezer3** [comment]
Fixed.

(matrices are not fun....)
