### ISSUE TITLE
[Request] Retry if OpenAL failed to initialize

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#575]
### Description
The change to OpenAL Soft allows more than 16 sounds to be played at the same time, however it's also noted in the commit that the most recent version (1.20.0) doesn't like OpenTK. As a result it's 1.15.1 now.

The problem is version below 1.16 will result in OpenAL failing to initalize sometimes on some computers
(And it just happens that my computer is affected)

It's unlikely we can get this to 1.16(?), but is it possible to retry if it fails to initialize?
It annoys me everytime I want to do some quick development especially with Motor Sound
Thanks for your considerations!

![image](https://user-images.githubusercontent.com/28094366/105274743-c7ea0b80-5bd8-11eb-879b-9c40d943830c.png)
![image](https://user-images.githubusercontent.com/28094366/106998039-d92d3d80-67be-11eb-9985-60a11c516c53.png)

### Related information 

* http://openal.org/pipermail/openal/2017-May/000637.html
* Operating system: Windows 7, Windows 8.1 and Windows 10
* Method of control: Keyboard

**Comment by leezer3** [comment]
I'll try 1.16 and see if that works as a first port of call before we do anything else.
I haven't tried a self-built version of OpenAL / debugging it, that's on a list of things I ought to do.....

How many retries does it take you to launch succesfully?

**Comment by Kenny-Hui** [comment]
It really depends, sometimes I restart it one time and it works. But sometimes even after 5 tries I can't get it working

**Comment by zbx1425** [comment]
The same happens on my computer, OpenAL errors sometimes occur randomly, and for me restarting once usually fixes it.
Their might be some connections between some certain circumstances, but I'm not sure.

**Comment by leezer3** [comment]
1.17 seems to work, so I've dropped that in for the minute.

Le me know if this helps before we try playing silly games with retrying :)

**Comment by Kenny-Hui** [comment]
Tested around 35 times, no crash for me. (Usually it crashes at around 20 times max)
Still have to wait others to see is it just my luck or it has been solved

**Comment by Kenny-Hui** [comment]
Tested 100 more times, no crash in the latest nightly build (others doesn't seems to be able to reproduce it either)
Assuming it's fixed, closing issues
