### ISSUE TITLE
StateChangeSound have to insert dummy wav file to FileNames at the first file

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#578]
### Description

If we are attempt to sound by StateChangeSound, we have to insert dummy wav file to FileNames at the first file.

I tested these pairs
|  StateFunction  |  FileNames pairs  | result  | 
| ---- | ---- | ---- |
|  leftdoorstarget  |  O5A.wav,O4F.wav,O4C.wav  | sound |
|    |  O4F.wav,O4C.wav  | no sound |
|  leftdoors  |  O5A.wav,O4F.wav,O4C.wav  | sound |
|    |  O4F.wav,O4C.wav  | no sound |
|  doors  |  O5A.wav,O4F.wav,O4C.wav  | sound |
|    |  O4F.wav,O4C.wav  | no sound |
|  pilotlamp  |  O5A.wav,O4F.wav,O4C.wav  | sound |
|    |  O4F.wav,O4C.wav  | no sound |

For example:
```
[object]
states = On.csv,Off.csv
StateFunction = leftdoorstarget
[StateChangeSound]
FileNames = O5A.wav,O4F.wav,O4C.wav
```

If set this pair, O4F.wav,O4C.wav is sounds. But O5A.wav do not sound.
```
[object]
states = On.csv,Off.csv
StateFunction = leftdoorstarget
[StateChangeSound]
FileNames = O4F.wav,O4C.wav
```
If set this pair, there is no sound.

At the my Ubuntu, if set the pilotlamp, the first time is sounds O4C.wav.
The second time presses door L or R buttton, the sounds both of O4C.wav and O4F.wav with the same time.
The third time or later, the sound is O4C.wav and O4F.wav alternately.

## Route

Please test this sample route and animated file.
[statechangesound.zip](https://github.com/leezer3/OpenBVE/files/5887633/statechangesound.zip)

## Train

Any train

## Logs

This issue do not crash.
So, no logs.

### Related information 

My PC's SPEC:
OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)
Not use Joysticks

**Comment by s520** [comment]
> At the my Ubuntu, if set the pilotlamp, the first time is sounds O4C.wav.
The second time presses door L or R buttton, the sounds both of O4C.wav and O4F.wav with the same time.
The third time or later, the sound is O4C.wav and O4F.wav alternately.

#580 does not completely solve this problem.
Please watch the following video.
In this video, I manually closed and reopened the left door that was open at the beginning of the scenario.
I open the door around 12 seconds, but the pilot light is blinking and the indicator at the bottom center of the screen is not visible.
This phenomenon does not depend on a specific route or vehicle, and it also occurs in v1.5.0.10.

https://user-images.githubusercontent.com/29241703/106455800-07193600-64d0-11eb-8170-15f2aac0183e.mp4

**Comment by leezer3** [comment]
Interesting.

If I recall, some of this must be related to a deliberate design decision.
Assume we have a long announcement (for example) attached to the state change, as opposed to your much shorter air hiss.
In this case, it's clearly not desirable for the first playing sound to be abruptly terminated if the change is triggered for a second time.
Presumably, we must be detecting the fact that the first sound is still playing and queuing the second one behind it.

Will try and do some digging later in the week.
