### ISSUE TITLE
Applying Notch crashes on the latest Nightly build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#579]
### Description

I am not sure if this is in the todo list already, but releasing brake will cause the game to freeze for a few seconds, then crash with Object reference not set to an instance of an object.

### Reproduction

Start the game with a random train (Class 50 should do)
When releasing the brake, the game would freeze and crash

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/5898125/log.txt)
[OpenBVE Crash- 2021.1.30[22.43].log](https://github.com/leezer3/OpenBVE/files/5898126/OpenBVE.Crash-.2021.1.30.22.43.log)

### Related information 

* Operating system: Windows 10 Pro 20H2
* Method of control: Keyboard
* Nightly build date: OpenBVE-2021-01-30

**Comment by leezer3** [comment]
Doesn't much suprise me, sorry......

At the minute, as you can probably see I'm halfway through a bunch of very major internal work.
This the final part of shifting the TrainManager into it's own shared assembly, which in turn will allow train loading to be offloaded to plugins :)

**Comment by Kenny-Hui** [comment]
Oops sorry, closing this for now

**Comment by leezer3** [comment]
No big deal.

Haven't fixed it yet (maybe later), but I'd much rather people reported things to me *before* it makes it into a full public build!

**Comment by leezer3** [comment]
Fixed that one and done a bunch more work.

Only thing I'm **aware** of being broken (once it builds) is that the station adjust text isn't working.

**Comment by Kenny-Hui** [comment]
Haven't tested other train yet, but if the train hits a bumper (Track.Buffer). The runi.wav will keep playing (unless you reverse for around over 1km/h, then the sound will update)

**Comment by leezer3** [comment]
That's likely an older bug, but will take a closer look at that.
