### ISSUE TITLE
Lighting incorrect whilst camera is inverted

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#582]
### Description

I don't know since when (v1.7.1.0?) when using default normals on a object, looking upside down will cause the face to darken.
I assume it's intentional(?) to simulate some materials, but I don't think stuff like road will darken in real life when looking upside down. I can disable it by using EmissiveColor, but that would mean using the dynamic lighting XML would have no effect to the face (And I want to use dynamic lighting)

I briefly searched the documentation, but it doesn't seems I can find anything related to the new lighting changes, is this a part of GL3 or I just missed smth in the docs?

### Reproduction

Any setcolor/textured face without EmissiveColor/same day and night time texture and without custom normals
Look upside down, and the face should darken
Note: Faces that does not have emissive enabled as shown below, will illuminate correctly when looking forward
![image](https://user-images.githubusercontent.com/28094366/107111586-422eb700-688c-11eb-9e8f-63567e324334.png)

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by leezer3** [comment]
Now that's wierd.
It's not intentional either.

It's doing it with both renderer types too, which is somewhat odd. My suspicion is that it must have something to do with the camera angle, but I'm going to have to try to isolate it before I can give you any further details.
Going to have to do some digging.

**Comment by leezer3** [comment]
Introduced by https://github.com/leezer3/OpenBVE/pull/397

Need to backtrack exactly where though, that's a big PR....

**Comment by leezer3** [comment]
I think that's now fixed.

Also makes the new renderer lightining better in some cases. (The inversion was actually highly useful in finding the underlying issue!)
