### ISSUE TITLE
[Minor] few things that might not be behaving correctly

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#584]
### Description
It's weird to create that many bug report that almost no one will notice, but at the same time I think possible bugs should be reported when found, so here we are...

1. Raildriver set calibration (Launch button) will crash with an **Unhandled Windows Forms Exception** if no controller is connected
(See image section 1, has been broken since 1.7.0)

2. On Advanced Options, only the Package Management will adapt the window size change and the input device plugin will never fit (See image section 2), intentional? **imo: The Input Device Plugin should also utilize full width**

3. SanYing Input configuration window have a weird size that does not (barely) fits all content inside (See image section 3)

4. HUD Color changed since new render since GL3, intentional? (See image section 4)

5. In game customize control will not make changes immediately, only after a restart.
(Prob not bug, just requesting a feature to apply control changes immediately)

### Reproduction
1. Don't plug in a raildriver controller, then go to settings and click the "Launch" button on RailDriver section.
You will get an OpenBVE error msg saying **No RailDriver controllers detected**.
But after that, it would show an **Unhandled Windows Forms Exception** dialog, then the program crashes after clicking OK.

2. Go to the advanced page, then start expanding the window horizontally
Only the Package Management section will utilize the full width

3. Go to advanced page, Input Device Plugin section. Enable SanYingInput, then click config.
The **Save and close**, **Discard** button will not be fully displayed

4. Get in game with v1.7.1.0+, the color doesn't seems to be as saturated as before (v1.7.0.3 or below)

5. Get in game, press **Esc**, then click Customizable Control.
Now reassign a button and pressing the newly assigned button will not do anything

### Image section
![image](https://user-images.githubusercontent.com/28094366/107125314-1e975b00-68e4-11eb-9484-3bb03ed763fd.png)
![image](https://user-images.githubusercontent.com/28094366/107125339-5d2d1580-68e4-11eb-9eb0-5ff6ec84e240.png)
![image](https://user-images.githubusercontent.com/28094366/107125373-96658580-68e4-11eb-956a-be3994f2262e.png)
![image](https://user-images.githubusercontent.com/28094366/107125436-083dcf00-68e5-11eb-9342-1c099d3f750c.png)

### Related information 
* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by leezer3** [comment]
Fixed 1, 2 and 3

I can't remember if 4 was intentional or not, although it rings a bell. Not really worth chasing though.

Will try and take a look at 5 at some stage, this *should* work off the bat, but it might be a little more complex to find.

**Comment by Kenny-Hui** [comment]
Also, on black box exports, CSV files extension are still .txt
![image](https://user-images.githubusercontent.com/28094366/107237487-bf5f5500-6a61-11eb-865b-33b907facfbf.png)

Below are bugs found on lubuntu 20.10:
1. Can’t focus on About box (The "About OpenBVE" Form), nor can you close it.
You need to close it via taskbar/force terminate it

2. Clicking the “Visit Offical Websites” will result in a **Cannot find the specified file** error
![image](https://user-images.githubusercontent.com/28094366/107237902-37c61600-6a62-11eb-979a-cf6e55a9f80e.png)

3. This appears everytime a save dialog pops up (Export black box data, create new package etc.)
![image](https://user-images.githubusercontent.com/28094366/107237947-457b9b80-6a62-11eb-983f-a1eb93bcce50.png)

4. Cannot view the previous log in “Report Problem” (Button does nothing)

Can't find any bugs in-game yet

**Comment by leezer3** [comment]
2 is an issue with the 6.* series of Mono IIRC.
https://github.com/mono/mono/pull/20821

Will try and look at the rest this week.

**Comment by leezer3** [comment]
Fixed the blackbox extension (Blame Michelle!)

The About box seems to work OK here. (Takes about a second to popup, but otherwise works just fine)

Can't reproduce the save dialog issue either.

All of this is on Debian Buster, with the Mono official repositories. (not the Debian preinstall)

What desktop and Mono version are you using?
Unfortunately, these may well go down as a DE glitch.

**Comment by Kenny-Hui** [comment]
I am running LXQt (without any updates).
And the latest stable mono release (6.12.0) (Following the instructions from mono-project)

**Comment by Kenny-Hui** [comment]
Switched to [Ubuntu Unity](https://ubuntuunity.org/) 20.04
**Visit Offical Websites** works, so this is probably LXQt's issue? (I haven't updated LXQt, that could be why)
I've found out the **About Box** can't be selected/closed only after I open the **Report Problems** dialog.

Haven't tried the regular version (GNOME 3) yet, doesn't work well with my system :(
(The majority plays OpenBVE on Windows anyways, chances are they won't purposely click on every button and see what it does)

**Comment by Kenny-Hui** [comment]
Still quite buggy
Unfortunately I don't have a Linux machine, so I can't test what works and what doesn't.
This shouldn't be a big deal either if Debian works. There might be some configuration issue on my end (It's also a live CD).

Closing this for now
