### ISSUE TITLE
PerformanceCounter call in CrashHandler may cause unhandled exception

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#585]
https://github.com/leezer3/OpenBVE/blob/9a74bfb51187f7d6ed7e6b4015afe1c4e951e8a4/source/OpenBVE/System/Functions/CrashHandler.cs#L151
https://github.com/leezer3/OpenBVE/blob/9a74bfb51187f7d6ed7e6b4015afe1c4e951e8a4/source/OpenBVE/System/Functions/CrashHandler.cs#L228

A player reported encountering the unhandled exception "Cannot load Counter Name data because an invalid index '' was read from the registry".
It turned out that `System.Diagnostics.PerformanceCounter` is used in CrashHandler. However, Windows keeps some counters cache in the registry and `PerformanceCounter` depends on it, so if the user accidentally has the registry corrupted, the crash handler will generate an unhandled exception.

Although maybe unlikely, this seems already likely enough to happen on a few OpenBVE players.
I recommend surrounding this call with try/catch blocks, and give up writing system memory info if it cannot be fetched via PerformanceCounter.

**Comment by leezer3** [comment]
Fixed it, although if this is crashing, as he's discovered there are likely wider system issues at work, so I'm by no means convinced of the value of it.
