### ISSUE TITLE
Bumping into the buffer will crash the game on specific route

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#586]
### Description

This has also happend in v1.7.2.4
When colliding into the bumper at the last station on the route below. It would cause the game to crash with:
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

### Reproduction
Download the route provided below
Launch OpenBVE with the route **東鐵線南行 (落馬洲→紅磡) - MLR** or **東鐵線南行 (落馬洲→紅磡) - SP1900**
(Sorry for the need to match chinese character on the filename)

Jump to the last station, then power the train towards the buffer. After hitting the buffer, it will crash

## Route
MTR East Rail Line
https://drive.google.com/file/d/1zpwDV01qHbtR82oGvriBF7whogG3woko/view

## Train
Any

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/5975303/log.txt)
[OpenBVE Crash- 2021.2.13[15.40].log](https://github.com/leezer3/OpenBVE/files/5975302/OpenBVE.Crash-.2021.2.13.15.40.log)

### Related information 
* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by leezer3** [comment]
Thanks :)

That's another *old* bug you've just found, must have been a typo by Michelle.
