### ISSUE TITLE
Route.InitialViewpoint won't render train exterior (Also mismatching documented behavior)

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#587]
### Description
In the OpenBVE Documentation of Route.InitialViewpoint:

> 0 : The camera will be placed in the cab. (Default)
> 1 : The camera will be placed in ‘Track Camera’ mode.
> 2 : The camera will be placed in ‘Flyby Camera’ mode.
> 3 : The camera will be placed in ‘Flyby Zooming Camera’ mode.

What actually happended:
1 = Track Camera, but only the cab is rendered. It should also render the train exterior
2 = Still track camera with no exterior rendered. This does not match the documentation
3 = Flyby camera with no exterior rendered and no zooming. This does not match the documentation

### Reproduction

Add an Route.InitialViewpoint command, it doesn't seems to follow the documented behavior
### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard
* OpenBVE Version: v1.7.2.4

**Comment by leezer3** [comment]
Hmm.

The documentation is a little wonky as it's missing an option, dunno how that happened...

This is what you ought to be seeing:
0: Cab
1: Exterior
2: Track camera
3: Flyby camera
4: Flyby camera (zooming)

4 wasn't working (typo) & I've fixed this.

I can't reproduce missing exteriors though.
Does this look a little more sensible now? Might need the specific train to test if it's doing something funny.

**Comment by Kenny-Hui** [comment]
Figured it out, you have to use Route.Runinterval.

Then the train infront will get rendered, but the player's train's exterior won't get rendered.
(The cab will render, and will still be on top of other object. Only how the camera behave changes)

**Comment by leezer3** [comment]
Still doesn't reproduce for me with RunInterval
I added a train 400s ahead of the player train, and both appeared as expected. Also worked with one ahead and one behind for good measure.

My suspicion is that it must be something to do with the exterior animated files on whatever train you're using.

For reference, I've been testing with the following:
**Trains:**
D1000 Western
81xx (2d & 3D cabs)
Class 37 & loaded steel carriers

**Routes:**
Plymouth
Odaykufan ATS Test route

**Comment by Kenny-Hui** [comment]
You're right, not even the animated object route can reproduce. I just can't find the cause of this (It's route dependent)

Luckily I've found a light weight working sample, the route that has issues is **KCR_West_Rail_WithTrainInterval.csv**
[wrbve_v300.zip](https://github.com/leezer3/OpenBVE/files/5981103/wrbve_v300.zip)

Note: 2D Cab will not be rendered resulting in an invisible train
![image](https://user-images.githubusercontent.com/28094366/107938185-eec11500-6fbf-11eb-810d-a52e82548f57.png)

**Comment by leezer3** [comment]
Somewhat smaller reproduction:
```
With Route
    .Change -1
    .Gauge 1435
	.RunInterval -60
	.InitialViewpoint 2

With Options,
	.ObjectVisibility 1
	.EnableBveTsHacks 1

With Train
    .Folder kcrwr_sp1900


With Structure
    .Rail(5) kcrwr\rail\rail_dark_stain.b3d


    .FreeObj(161) kcrwr\station\tww_001.b3d

    .FreeObj(253) kcrwr\tunnel\kfmetun-end.b3d


Structure.Beacon(0) kcrwr\rail\nullrail.b3d

Texture.Background(1) kcrwr\back\dark.bmp

With Track

32775
     .Railtype 0; 5
32800
     .Sta Tsuen Wan West; 19.4211; 19.4238; ; -1; 0; ; ; 15; 50;kcrwr\standback.wav

33025
     .Stop 0; 1; 1

40000
     .Sta Turn Back Siding; 19.5119; T; ; 0; 0; ; ; 15; 50

40225
     .Stop 0; 0.5; 0.5
```

Still trying to get to the bottom of it.
My suspicion at the minute is that it's going to be related to disposal of the pretrain.

**Comment by leezer3** [comment]
Ah:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Simulation/TrainManager/Train/Train.cs#L323

The train *should* get introduced automatically before the simulation starts.
However, if an AI train remains in the section, this doesn't happen, so we need to force-introduce it. This wasn't taking account of the viewpoint.
