### ISSUE TITLE
What is the current open source license of openbve?

### ISSUE THREAD

**Issue by kmsimproject** [leezer3/OpenBVE#589]
### Description

I tried to develop a game using the source of openbve, but I saw discussing the license, but it didn't specify what the license was. What is your current license?

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system
* Method of control (Keyboard, joystick, RailDriver)

**Comment by leezer3** [comment]
Please see the discussion in the following issue:
https://github.com/leezer3/OpenBVE/issues/305

Essentially, OpenBVE is licenced as Public Domain (or nearest equivilant) as a legacy of the original developer Michelle.
We've never found a compelling enough reason to change it, although it's somewhat of a mess.
Newer contributions are licenced under BSD.
