### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kmsimproject** [leezer3/OpenBVE#590]
### Description

Sorry for asking again. You said it's a form close to the public domain, but is it okay to mark the source? And is it possible to distribute it as an open source?

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system
* Method of control (Keyboard, joystick, RailDriver)

**Comment by leezer3** [comment]
If you want to fork or distribute as open-source, then public domain is appropriate, apart any newer code, which is covered by the BSD-2 licence specifically, and which will be noted in the file header.

If you cannot distribute legally as public domain under your juridistiction (I know nothing about Korean copyright law), then the best thing to do would probably be to consider the entire project as covered by BSD-2.

(Both situations are fundamentaly identical anyway, assuming you have the good manners to credit the others who have worked on the code)

**Comment by kmsimproject** [comment]
@leezer3 The copyright law in Korea is applied when a copyright holder died in 1962, so can openbve be used as a public domain?

**Comment by leezer3** [comment]
That's different & unrelated.

You probably can, but again I am no expert in Korean law.

**Comment by kmsimproject** [comment]
@leezer3 okay

**Comment by kmsimproject** [comment]
Can you give me a link with all the sentences in BSD-2?  It's hard to find. ):

**Comment by leezer3** [comment]
https://opensource.org/licenses/BSD-2-Clause
https://olis.or.kr/license/Detailselect.do?lId=1093

**Comment by kmsimproject** [comment]
@leezer3 Thank you for the Korean information link, so what should I write for the year and copyright holder?

**Comment by leezer3** [comment]
Year is when last updated.

The copyright holder would probably be something like the OpenBVE Project.

**Comment by kmsimproject** [comment]
Thank you.

**Comment by kmsimproject** [comment]
Any definite author information?

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/blob/master/Contributing.md

Any file specifically written by someone recently should have a licence header. (If they thought it needed it)
Reworked / original code does not.

**Comment by kmsimproject** [comment]
@leezer3 I can't do a new modification of openbve?
