### ISSUE TITLE
[Bug?] "Exit to the main menu" consumes a lot of memory

### ISSUE THREAD

**Issue by enjoysoftware** [leezer3/OpenBVE#599]
### Description
I often use the "Exit to the main menu" button in OpenBVE's Esc menu, but repeating this many times makes my computer less responsive. It can fill up memory and eventually make your computer completely unresponsive.
When I open and check Task Manager, I see a lot of openbve and cli processes that need to be terminated. The only way to terminate them is to use Task Manager. It seems that they are not  terminated automatically when I click "Exit to the main menu".

This issue has been confirmed on Ubuntu and Windows 10.
![memory](https://user-images.githubusercontent.com/47489953/112431185-874a7200-8d82-11eb-9e73-5b33f9d65da1.png)

### Related information 

* Ubuntu 20.04 LTS,Windows 10
* Control: Keyboard and mouse
OpenBVE 1.7.2.4

**Comment by leezer3** [comment]
I can't reproduce this on Windows.

On Linux, this is somewhat of a known (desktop environment / distribution dependant) issue for which I don't have any good fixes / ideas. (It's something somewhere in the OpenTK windowing library interacting with specific X / WM versions)

**Comment by enjoysoftware** [comment]
So is the only way to solve this problem is to change the desktop environment?
