### ISSUE TITLE
Segfault at startup on E2160

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#601]
### Description

A player reported that OpenBVE would not function correctly after he upgraded to 64bit Windows 10, and it worked before when he was using 32bit Windows 7.
He stated that updating graphics driver would not help.

When using the latest 1.7.2.4, Segfault occured at startup (memory 0x0 referenced by instructon 0x0 cannot be read)
When using 1.4.1.2, all textures, including the texts for UI, would not load.
![87d957367657aca](https://user-images.githubusercontent.com/25097028/112750808-4c07a780-8ffd-11eb-8a76-e0f860dd28a0.jpg)
When using 1.2, the textures loaded correctly.

### Related information 

Windows 10
Pentium E2160 and its built-in GPU

**Comment by leezer3** [comment]
Not a lot I think we can do there, the graphics drivers are clearly broken terminally.

The E2160 doesn't have an integrated GPU either, so either the CPU model is wrong or it's not integrated graphics.
Laptop of some sort?
