### ISSUE TITLE
[Fixable?] Cursor will remain hidden on in-game menu

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#604]
### Description

In game, after ~15 seconds of inactivity within the game window, the cursor will be hidden until you move the cursor again.
However if the user pressed Esc to bring up the game menu while the cursor is hidden, the cursor will not reappear until you are back in-game. (You can still select things, but the cursor is invisible).

### Reproduction

Hover the mouse above OpenBVE's game window until the cursor becomes invisible.
Then press Esc
Your cursor will remain hidden

(My best guess is the code hiding/showing the cursor is tied to the main game, so it becomes stuck when the game is paused. Although I am not familiar with how OpenBVE works internally, and whether it's fixable in the short term or not)

### Related information 

* Operating system: Windows 10 2004
* Method of control: Keyboard

**Comment by leezer3** [comment]
Dead easy.

I've left it hidden if no mouse movement is detected (keyboard / joystick only).
