### ISSUE TITLE
NullReferenceException in UpdateTopplingCantAndSpring

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#605]
# Description

A player reported a crash on the latest version.
![2dd60fc6c0842b70.png](https://user-images.githubusercontent.com/25097028/114561644-53d37700-9ca0-11eb-9f94-ca66e99d5978.png)

# Train

https://cowtransfer.com/s/31a02372469044

**Comment by leezer3** [comment]
This was *probably* fixed by 1.7.4.0

I can't get it to crash here, but if this persists, some more details on exactly what was happening at the time would be useful.
