### ISSUE TITLE
ObjectViewer crash when reloading an object after Enabling Train settings

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#607]
### Description

In 1.7.3.1 and the latest nightly build, if you press F10 and check the "Enable Train" box, then click either "Apply" or "OK".
ObjectViewer will crash when reloading (F5) after enabling train
This does not need an object to be loaded

### Reproduction

Launch ObjectViewer in versions above 1.7.2.4
(I don't know does this exist in 1.7.3.0 since I can't get the train settings window to show up)
Press F10, check the "Enable Train" box. Click "Apply" or "OK".
Then press F5, after a few seconds ObjectViewer will crash.

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by leezer3** [comment]
Fixed, thanks.

As you've probably seen you don't actually need to reload to alter stuff in the train dialog, and I hadn't noticed this.
Was because it was trying to update a non-existant coupler.
