### ISSUE TITLE
ObjectViewer locking files when using invalid syntax in ANIMATED file

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#610]
### Description

When using invalid syntax on ANIMATED files (e.g. RotateYFunction, 2.5). After reloading, the object seems to get unloaded from the viewer. But when trying to edit the files back, OpenBVE will lock the file unless I press del key.

### Reproduction
[test.zip](https://github.com/leezer3/OpenBVE/files/6357188/test.zip)
When loading a.animated, the viewer window will still be blank. But it has locked the file.
If you use Notepad++, modify it, then save it. It will say "Save failed" and ask if you want to launch Np++ in Administrator
Even after launching administrator, pressing save does not do anything

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by leezer3** [comment]
Fixed. 
Also made the error show up if this is the only file you're loading.

**Comment by leezer3** [comment]
n.b. This doesn't make the file show up with the invalid statement, just not lock.

I'm in two minds as to whether to make the thing show up if everything else is right, but that might break something else :/
