### ISSUE TITLE
DllNotFoundException on Linux on 1.8.0.0

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#612]
# Description

![63d71cd713cfe64d.jpg](https://user-images.githubusercontent.com/25097028/115866044-b8928c80-a46b-11eb-8696-e7960e848427.jpg)

A player reported encountering DllNotFoundException about hid.dll on Linux, causing OpenBVE to fail to start.

This seems to cause version 1.8.0.0 to be inoperative on systems other than Windows.

**Comment by leezer3** [comment]
Arrgh...

It's missing an optional Mono assembly mapping...
Fixed version incoming in a few minutes.

**Comment by Kenny-Hui** [comment]
Unrelated
https://bveworldwide.forumotion.com/t2088-issues-related-to-opening-extensions-cfg-file-in-object-viewer
Can this be fixed before another version got pushed? Thanks!

**Comment by leezer3** [comment]
I've updated everything other than the deb (pulled) and kept the version at 1.8.0.0
(that needs me to manually sort it as Azure isn't)

Will try and deal with that later.

**Comment by leezer3** [comment]
Fixed that one now, and bumped the version to 1.8.0.1 for good measure.

Bugs *always* seem to get found about 5 mins after I push a release :/

**Comment by Kenny-Hui** [comment]
It's normal, not a lot of people download the Nightly build and actually use it frequently (Or they just don't replace it with new builds for a long time)

It even gives some player the impression that OpenBVE is buggy when they found bugs on each stable release.

**Comment by leezer3** [comment]
Unfortunately, I'm only one person, and it's really difficult to test the rather large specturm of stuff which is around.

Automated tests would be good, but the trouble there is that t's near impossible to write them for a game engine like this.
Vectors and stuff like that would be easy (and are on my list of things I ought to do), but it's always train components or differing Mono configurations between systems that catch you out....
