### ISSUE TITLE
Breaker sound bug

### ISSUE THREAD

**Issue by enjoysoftware** [leezer3/OpenBVE#615]
### Description

Sound.cfg has a breaker section that has both off-key and on-key.
When the power notch is turned on, the wav file specified by the `On` key is played, but at the same time as the `On` track is played, the wav track specified by `Off` is also played.

### Reproduction

```
[Breaker]
Off = filename1.wav
On = filename2.wav

```
In the above example, filename1.wav and filename2.wav are both played when the power notch is turned on.

## Train

The train which has the breaker sound

### Related information 

* Any operating system

**Comment by leezer3** [comment]
That's by design.

I'd have to check with BVE2 / BVE4, but I'd assume it replicates their behaviour.

From the documentation for the Off sound:
```
Played once when power is interrupted or resumed. There is a series of circumstances when that can happen, for example when moving from power notch zero to power notch one, or vice versa, assuming the reverser is non-neutral and the brakes are released. The safety systems can also interrupt power.
```

**Comment by enjoysoftware** [comment]
@leezer3 I see.
Thank you for telling.
