### ISSUE TITLE
ObjectViewer Train Settings > Plugin have no effect

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#618]
### Description

After 1.7.3.x or above, if I enable train settings and add a pluginState, there will be no effect.
On 1.7.2.4, it works perfectly

## Animated Object
[Test.zip](https://github.com/leezer3/OpenBVE/files/6371797/Test.zip)
**If pluginState 99 == 1**, it will blink between 2.csv (black cube) and 1.csv (empty)
1.7.2.4: After enabling pluginState 99 to 1, it switches between different object as expected
1.7.3/1.8: After enabling pluginState 99 to 1, it stays on 2.csv (black cube).

### Related information 

* Operating system: Windows 10 20H2
* Method of control: Keyboard

**Comment by HUN-Droid** [comment]
This bug is also known in versions 1.8.x, all pluginState variables hasn't effect in the ObjectViewer, in my case the viewer use the 0 value in each variables.
I use Windows 10 2004.
