### ISSUE TITLE
[Request] ColorAll and EmissiveColorAll in .B3D files

### ISSUE THREAD

**Issue by Xerfix** [leezer3/OpenBVE#620]
This would be a smaller, yet easier way to make lighting to the cars (like turning on interior lights).

I don't if this is even possible, but very useful to the creators of a train, who want to make interior lighting.

**Comment by leezer3** [comment]
Added both.

I'm not convinced this is the quite the right approach for what you're trying to do, but they match the pattern of what we already have available so they're logical.
