### ISSUE TITLE
Sound volume changes depending on the angle (Unreproducible)

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#625]
### Description

I've received a player report that encounters something like this after upgrading to 1.7.3.1:
https://drive.google.com/file/d/1YSzOj20sPJaaUOw3wjhnYdFPBpjRhghl/view?usp=sharing

The loop.wav can't be heard in the cab, and it seems the loop.wav has a very small volume radius, but it seems the volume returns normal when looking backwards.

Unfortunely I can't reproduce this even on the same train and route. Do you have any idea what could possibly break this?
(My best guess are the openAL change, but I just can't manage to reproduce this)

### Related information 
* Operating system: Windows 10 2004
* Method of control: Keyboard

**Comment by leezer3** [comment]
My initial guess would be not enough concurrent sounds available.

It stops the quietest, and the camera (and hence the listener) direction will is part of that.

**Comment by Kenny-Hui** [comment]
Haven't heard from the player since then, closing this. (Assume it's just a driver issues as I haven't seen any other player reporting this)

Will reopen if necessary
