### ISSUE TITLE
Package Management "Uninstall Package" deleted files outside the package selected (Deleted files from my OpenBVE Folder)

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#650]
### Description

I am testing out the Package Management in OpenBVE to see what else I can do with it.
So I installed the Animated Demonstration Route, and then uninstalled it later.

But when I uninstall it, it takes longer than usual.
Until I see the log, it seems to delete some folder from my OpenBVE Collection.
I have to admit that the file structure of my collection is quite messy, that could also be why.
Is there anything that hints what is going on here?

(I also cancelled the Package Management folder browser before I did this. This results in a blank selection on the installation directory. I thought it's just a visual glitch at first, but now I am not sure does this affects the uninstallation)

My package management settings:
![image](https://user-images.githubusercontent.com/28094366/121500055-88e61680-ca10-11eb-82c9-4c77be1c72bd.png)

After pressing cancel on installation directory, here's what happens:
![image](https://user-images.githubusercontent.com/28094366/121500172-a5824e80-ca10-11eb-8563-bfbca815dce3.png)

![image](https://user-images.githubusercontent.com/28094366/121500937-54bf2580-ca11-11eb-9496-de0c1588fab0.png)

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/6630057/log.txt)
(It starts to delete unrelated stuff at Line 97)

### Related information 
* Operating system: Windows 10 21H1
* Method of control: Keyboard

**Comment by leezer3** [comment]
At first glance, I can't see any way whatsover it could do this.

Our uninstall function is here:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Packages/Packages.cs#L383

First thing we do is to load the list of files installed by the package via a simple XML deserialize,
We then delete the contents of this list.

Nowhere does it attempt to get a list of existing files / folders.


Some questions:
* Is everything that got deleted from a package? (I don't think so, judging by some of the paths, but I want to be certain)
* I only see it deleting folders, not files. Were these empty? (again, presuming not)
* Approximately how many packages did you have installed?
* Did you open / close the whole thing between each package operation? (wondering about caching somewhere)

**Comment by Kenny-Hui** [comment]
1. No, some folders are deleted that is not a part of any package.

2. No, I've confirmed that most if not all of the folders contains at least 1 files (From the log, it also seems to delete the entire train folder and some git related files)

3.This is the only package I tried to install, so 1 before uninstalling.

4. I installed the package and uninstalled the package in a single instance.
No restart or game launching in between


I don't see a specific folder pattern either, might want to play it with a VM when I got time.

**Comment by Kenny-Hui** [comment]
![image](https://user-images.githubusercontent.com/28094366/122053000-ea472480-ce18-11eb-906e-d309d357c356.png)
I am still able to reproduce this inside a Virtual Machine (Files redownloaded from the internet)
Maybe this has something to do with the folder being on the root directory of a drive, I am not quite sure yet.

**Comment by leezer3** [comment]
Still can't reproduce this at the minute, but I've made a tweak to the recursion algorithm which may help.

re. deleting empty directories:
Packages shouldn't really be mixed with non packaged content.
If you install and uninstall lots of stuff, you end up with far too many empty folders, and it's a mess (and slows down the speed of filesystem operations such as searching for objects etc.)

**Comment by Kenny-Hui** [comment]
Ah this time it seems to do the trick, thanks! (Not exactly the same file, but still shouldn't affect the result anyway)
(The folder path is accidental as I have no idea how the installation will work initially)
