### ISSUE TITLE
Trembling with Densha de GO controller with Elecom JC-PS101UBK

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#655]
### Description
A Japanese user reported to me with this trouble.
USB Translate converter's data:
Elecom JC-PS101UBK
Densha de GO! controller's data:
TCPP-20001
When these combination use, trembling master controller and brake handle.
Please look these movies.
https://user-images.githubusercontent.com/22734699/122650647-20fda180-d16f-11eb-9d39-35f5e57a6fd4.mp4
https://user-images.githubusercontent.com/22734699/122650642-1ba05700-d16f-11eb-8522-744c55623fd0.mp4

Using exe:OpenBve.exe
He cannot crear the options_denshadego.cfg, and he re-tested.
But he couldn't correctly.
This is options_denshadego.cfg.
```
; Options
; =======
; This file was automatically generated. Please modify only if you know what you're doing.
; Specific options file for the Densha de GO! controller input plugin
​
[general]
guid = 88880925-0000-0000-0000-504944564944
​
[handles]
convert_notches = false
keep_max_min = false
map_hold_brake = false
​
[buttons]
select = 22
start = 23
a = 24
b = 25
c = 26
d = 0
up = 0
down = 0
left = 0
right = 0
pedal = 0
ldoor = 0
rdoor = 0
​
[classic]
hat = false
hat_index = 0
select = 9
start = 8
a = 3
b = 2
c = 1
power1 = 0
power2 = -1
power3 = -1
brake1 = 6
brake2 = 4
brake3 = 7
brake4 = 5
```

### Reproduction
Route:any. This trouble is not relate route.
He use this route.
https://openbve-project.net/files/DemoRoute1.zip

## Route
Route:any This trouble is not relate route.

## Train
Need Notch and brake handle's notch is more than Densha de Go's one.
A reported Japanese player use this train.
https://blog.naver.com/nacf723/222281221028
## Logs
There is no output logs by this trouble.
### Related information
His PC's specs is here.
CPU:AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
RAM:	8.00 GB (6.88 GB can use)
System:	64 bit OS and x64 base processer
Pen and Touch: this device cannot use pen and touch.
Graphic board:AMD Radeon Vega 8 Graphics
VRAM: 1009MB
Windows version:
Edition:	Windows 10 Home
version:	20H2
Install date:	‎2020/‎12/‎01
OS Build:	19042.1052
Experience:	Windows Feature Experience Pack 120.2212.2020.0

@MarcRiera Please check this issue.

**Comment by MarcRiera** [comment]
From the config file, it seems that the calibration procedure is not picking correctly two of the buttons used by the power handle. I'll revise the calibration procedure to fix this.

Try changing the line `hat = false` to `hat = true` in the config and check if the power notches work.

**Comment by ginga81** [comment]
As a reported user, he said that when 'hat = true', nothing change.
Perhaps need compile?

**Comment by MarcRiera** [comment]
I've slightly modified the calibration code in this build: [OpenBVE_210621.zip](https://github.com/leezer3/OpenBVE/files/6687269/OpenBVE_210621.zip)

Please try to calibrate the controller again and check if it works.

**Comment by ginga81** [comment]
He tested this compiled version.
Via the his testing video, I saw the test result. The brake side is correctly works, but power notch side was nothing did. (This video shows not calibration, game window.)

**Comment by ginga81** [comment]
Addtional information:
I obtained upload permission from him.
So, uploaded.
https://user-images.githubusercontent.com/22734699/122937701-247e6c00-d3ad-11eb-996f-30ebb0448b9d.mp4
This is options_denshadego.cfg that was ran by this built test version.
```
; Options
; =======
; This file was automatically generated. Please modify only if you know what you're doing.
; Specific options file for the Densha de GO! controller input plugin
​
[general]
guid = 88880925-0000-0000-0000-504944564944
​
[handles]
convert_notches = false
keep_max_min = false
map_hold_brake = false
​
[buttons]
select = 0
start = 0
a = 0
b = 0
c = 0
d = 0
up = 0
down = 0
left = 0
right = 0
pedal = 0
ldoor = 0
rdoor = 0
​
[classic]
hat = true
hat_index = 0
select = 9
start = 8
a = 3
b = 2
c = 1
power1 = 0
power2 = -1
power3 = -1
brake1 = 6
brake2 = 4
brake3 = 7
brake4 = 5
```

**Comment by ginga81** [comment]
These movies were re-tested by your request.
Please check.
Created by いんば
https://user-images.githubusercontent.com/22734699/122969608-cdd25b80-d3c7-11eb-8c63-b3379d546723.mp4
https://user-images.githubusercontent.com/22734699/122969642-d460d300-d3c7-11eb-934f-d9b537b2250d.mp4

**Comment by MarcRiera** [comment]
Thank you very much! I now see that the adapter is mapping the D-pad to two axes. I will add support for that in a new build.

**Comment by MarcRiera** [comment]
Please try this new build: [OpenBVE_210628.zip](https://github.com/leezer3/OpenBVE/files/6729251/OpenBVE_210628.zip)

Hoping it works this time.

**Comment by hwanghyunseo** [comment]
it's work! thank you!

**Comment by MarcRiera** [comment]
Great! I have created a PR with the necessary changes. Thanks for testing!

**Comment by ginga81** [comment]
From a Japanese user, he said that his environment also works correctly.
Thank you very much!
