### ISSUE TITLE
[Questions] Path/File naming rules in OpenBVE (Linux)

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#656]
### Description
When playing other OpenBVE Content, I've noticed that some files will not be found on Linux. (But it can be found and displayed on Windows)

So I have a few questions:
Must everything be case-sensitive in OpenBVE in linux?
Is there a difference in forward slash and backward slash when specifying path?
Is there any rules for underscore, dash or even space that is parsed differently in Linux?

Only reply if you got time, no hurry.
Thanks!

**Comment by leezer3** [comment]
There shouldn't be, and I can't say I've seen anything.

Any examples?

**Comment by Kenny-Hui** [comment]
Yea I figured, there's nothing to do with the naming scheme :/
I uses GitHub as a versioning control to my route and I am in a middle of refactoring tracks around. (This actually happens a few months ago)
I commited and pushed half of it, but forgot to push the other half that's on my local machine before booting to Linux.

On Linux, I grabbed the copy back from GitHub then played it. That's why I experience missing objects on Linux but not in Windows (I should've just access the local copy, but I thought that accessing user profile in Linux will have to go through all the permission stuff like a Windows dualboot. Plus it's only a live CD so I didn't bothered with it)

I think I am more familiar with Linux now, and hopefully I'll not make the same mistakes of claiming an non-existent misbehavior.
Sorry about that. (Still, good to know that there aren't restrictions on folder and file names)

Also, must I run OpenBVE with sudo on the deb version of OpenBVE? It seems to keep reporting that Texture.Dds.dll can't access "/usr/lib/openbve/Data/In-game/loadingbkg_X.png". Although I will probably raise another issues instead

**Comment by leezer3** [comment]
Nope, definitely not sudo :/
Permissions must be messed up on that one, will look properly later.

**Comment by leezer3** [comment]
Can't see a reason for that one at all, or reproduce it with 1.8.0.2 and Debian 9.

I've tweaked the build script to deliberately chmod those files to 755, which may help, but something's funny at your end I think.
I take it you're definitely installing the deb, not extracting it? That might cause some unexpected issues.

Might be related to it being a livecd.

**Comment by Kenny-Hui** [comment]
I installed it on my main computer running Linux Mint 20.1 Cinnamon x64
And yes I installed it via the deb, but in this case I'll probably use the binary one instead.

**Comment by leezer3** [comment]
Odd, I'll try a VM (probably tomorrow now) and see if I can find something.

Either way, OpenBVE should not need root or sudo under any circumstances, and launching it in this manner is highly likely to cause unexpected issues. Possibly, if you launched it once with sudo it might have broken something permenantly, although I'd have expected this to be the log write permissions if anything.

The next version will extend the **please don't** prompt shown when launching with root priveledges to include sudo.

**Comment by Kenny-Hui** [comment]
Yea I am just asking whether sudo is needed for maybe first time to setup the permission (Some other apps do)
But never actually ran OpenBVE with sudo

I have also never seen this error before even in livecd, which is quite odd. (Maybe this is a Linux Mint things, not sure)

It should also be worth noting that I used the update manager to update all component before I installed OpenBVE using the deb, although it still shouldn't cause issues.

**Comment by leezer3** [comment]
Completely fresh Cinnamon x64 VM works just fine here with the 1.8.0.2 deb.
Absolutely no sign of the errors you're mentioning, so it must be something in your setup.

**Comment by Kenny-Hui** [comment]
![image](https://user-images.githubusercontent.com/28094366/123108674-31fb2b00-d46d-11eb-9a1f-cc1bbfe1d716.png)
Weird, I am still able to reproduce this inside a fresh mint VM installation.

This is the steps I did:
1. Use the manual partitioning, manually splits an ~600MB partition then marks the partition as EFI
2. After installing, I installed mono-complete (Is this required? Or does the OpenBVE package already includes this)
3. Open the OpenBVE deb and installed it via the package manager.
4. Play it

I will probably redownload the iso and see does that make a difference.

**Comment by leezer3** [comment]
You definitely require mono. Not quite all of mono-complete, but most of it.

Can't explain the error though.

```
openBVE Log: 6/23/2021 7:25:58 AM
Program Version: v1.8.0.2

07:25:58  Using openGL 1.2 (old) renderer
07:25:58  Initialising game window of size 960 x 600
07:25:58  Game window initialised successfully.
07:25:58  Initializing the default shaders failed- Falling back to legacy openGL.
07:25:58  Initializing the touch shader failed- Falling back to legacy openGL.
07:25:58  Renderer initialised successfully.
07:25:58  /mnt/hgfs/BVE/Railway : Railway folder found.
07:25:58  INFO: 1 Route loading plugins available.
07:25:58  INFO: 6 Object loading plugins available.
07:25:58  INFO: 1 Sound loading plugins available.
07:25:58  Loading route file: /mnt/hgfs/BVE/Railway/Route/Heavy Coal.rw
07:25:58  INFO: Route file hash 74C2C6F44F9365804FDA5C27633F4E684F2FB3AA45D4BE679B88C436C9F67A47
07:25:58  Route file format is: RW
07:25:59  INFO: Using the Japanese compatibility signal set.
07:25:59  Invalid additional closing parenthesis encountered at line 158 character 25 in file /mnt/hgfs/BVE/Railway/Route/Heavy Coal.rw
07:25:59  Invalid additional closing parenthesis encountered at line 662 character 73 in file /mnt/hgfs/BVE/Railway/Route/Heavy Coal.rw
07:25:59  Missing closing parenthesis encountered at line 861, column 2 in file /mnt/hgfs/BVE/Railway/Route/Heavy Coal.rw
07:25:59  FileName heavycoal\Ballast.b3d not found in Rail at line 23, column 1 in file /mnt/hgfs/BVE/Railway/Route/Heavy Coal.rw
07:25:59  Red is required to be within the range from 0 to 255 in Color at line 26 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Green is required to be within the range from 0 to 255 in Color at line 26 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Blue is required to be within the range from 0 to 255 in Color at line 26 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Red is required to be within the range from 0 to 255 in Color at line 132 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Green is required to be within the range from 0 to 255 in Color at line 132 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Blue is required to be within the range from 0 to 255 in Color at line 132 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground00.b3d
07:25:59  Red is required to be within the range from 0 to 255 in Color at line 26 in file /mnt/hgfs/BVE/Railway/Object/heavycoal/Ground01.b3d

snipped the rest....
```

You aren't using something odd filesystem wise in manual partitioning are you?

Secondary (stupid...) question:
Is the logo / background actually missing from the loading screen?

**Comment by Kenny-Hui** [comment]
1. ext4 on the main partition
2. Nope, just the log displaying it.

Though I've noticed that in the winform menu the language flags is missing, is that normal?

**Comment by leezer3** [comment]
The flags are missing here too, so that I suppose is something.

If they're not missing on the loading screen, just the log error, that smells like an access concurrency problem. Will do some thinking, but I think you can probably just ignore it TBQH.
