### ISSUE TITLE
RouteViewer relation open infinity continue.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#661]
### Description

A Japanese OpenBVE creator CrossHatch's Windows 10, his RouteViewer is connect .csv file, but when he open crick from exprorer, but route file is open infinity continuing open such as his movie.
He said that when he attempt to open a new guimick included route, he didn't open.
(He couldn't check the old version.)

When he updated the newest stable(1.8.0.2), and he related .csv file to the RouteViewer, the newest RouteViewer and ObjectViewer are reciprocal open the nothing data's ObjectViewer and RouteViewer.
When he select an objectdata's .csv open to the ObjectViewer, the action is correctly, open by ObjectViewer automatically.
 Please fix these issues.

https://user-images.githubusercontent.com/22734699/124394446-72468d00-dd3a-11eb-930b-4db57b5fda72.mp4

 This movie is created by CrossHatch
http://kanakyusubway.web.fc2.com/

### Reproduction

He didn't report route data.
But, I think maybe created by him's new guimic included route.

## Route

May be his new guimic builtin route, but maybe not release yet.

## Train

Maybe any.

## Logs

This issues are no logs output by RouteViewer and ObjectViewer.

### Related information 

* Operating system
Windows 10 version is not reported

* Method of control (Keyboard, joystick, RailDriver)
He is maybe not use these.

**Comment by leezer3** [comment]
I'm not quite clear what the video is showing, sorry :(
Your translation is also a little confused.

What I *think* you mean is the following:
I have the object **C:\BVE\Railway\Object\MyObject.b3d**
Open with _Route Viewer_
This should then launch _Object Viewer?_

Similarly, I have the object **C:\BVE\Railway\Route\MyRoute.csv**
Open with _Object Viewer_
This should then launch _Route Viewer?_

Latest commit above should fix these, but please let me know if that's not right.

**Comment by ginga81** [comment]
Sorry to not translation perfectly.
Because I am not use Windows...

From the Explorer, when a file doubleclicked, the exe program is related automatically open.

https://openbve-project.net/documentation_hugo/en/tools/objectviewer.html
'will be started if present inside the same folder as ObjectViewer.exe. This allows you to link CSV files against either Object Viewer or Route Viewer and still have the correct tool opening the file.'

RouteViewer's .csv and ObjectViewer's .csv files is automatically select these files, and automatically open each .exe.

His Windows's automatically open exe feature not works.
And continueing RouteViewer.exe and ObjectViewer.exe are open as shown as the movie.
At the old version, his RouteViewer.exe and ObjectViewer.exe's automatically file selection is works well, but currently version, not works.

Thank you very much to attemt to fix.
I ask again 'Please test a newest daily build' to him.

**Comment by ginga81** [comment]
Additional information:
I heard from him, his new guimicks are Sound section and StateChangeSound fuctions.
When he use these function, the old versions of ObjectViewer wasn't open.
So, he is update the new version of ObjectViewer, then an animated file can open.
But when he is attempt to open by automatic identification of file extensions by explorer of double click of a .csv file, ObjectViewer and RouteViewer are open unlimited such as his video.
As shown the document, RouteVIewer and ObjectViewer's csv file switch is automatically, but when this trouble faces, ObjectViewer and RouteViewer are both open eternally as his video.
At the each programs, when he is drag a file to each exe, or press F7, the files are open correctly.

**Comment by ginga81** [comment]
CrossHatch reported to me that at the 1.8.1.0, this trouble is not happen. So, this issue is closed.
