### ISSUE TITLE
Crash on sound.cfg with empty entries

### ISSUE THREAD

**Issue by zbx1425** [leezer3/OpenBVE#662]
### Description
An sound.cfg with entries that has an empty value crashes the main program. 
![-663c192076a81950](https://user-images.githubusercontent.com/25097028/124473329-c3559000-ddd1-11eb-9d7d-e05514e8207c.png)
In previous versions, this seems to be ignored.

### Reproduction
An sound.cfg with entries that has an empty value.
![Screenshot_2021-07-05-20-40-34-651_bin mt plus](https://user-images.githubusercontent.com/25097028/124473165-91dcc480-ddd1-11eb-9607-df04c94780a7.jpg)

**Comment by leezer3** [comment]
Typical....

It was only the horn sounds (as they've got somewhat special handling due to multi-part being possible), and as per usual it's nothing I've personally tested.
