### ISSUE TITLE
ObjectViewer launches RouteViewer when loading an empty csv file in the latest nightly build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#666]
### Description

Some of us would like to use invisible rail in order to achieve some effect (Maybe it's an abandon tunnel, or an invisible rail on top of road for cars to run on)

A very simply solution is to create an empty csv file, and then use it as rail on the route.
But on the latest nightly build, RouteViewer will just says:
No plugin found that is capable of loading object Path\null.csv
![image](https://user-images.githubusercontent.com/28094366/124917673-ad8cd880-e026-11eb-9902-ef5082a73e0b.png)

When trying to load with ObjectViewer, it will launch RouteViewer with the parameter to the null.csv instead. (And obviously it will fail as there's nothing in the file)
![image](https://user-images.githubusercontent.com/28094366/124918081-3572e280-e027-11eb-9b4f-c379372c0530.png)

It also seems the RouteViewer will show a MessageBox for every parameter, is this for debugging purposes and will be removed in the Final Release? Thanks!

### Reproduction
First, create an empty text document, then rename it to csv
#### RouteViewer:
A. Freeobj the object to any route
B. Load it with RouteViewer on the latest Nightly Build

#### ObjectViewer:
A. Open the empty csv.

### Related information 
* Operating system: Windows 10 21H1
* Method of control: Keyboard

**Comment by leezer3** [comment]
Debug code was accidental :/

Empty objects are actually however somewhat more problematic now that we're actively trying to avoid using the file extension as the guide to what's in the file.
Strictly speaking, the error message is now entirely correct; You can't load an empty object, and it's a horrible kludge to do anything else. Null objects should have been dealt with properly a long time ago now that I see it from this having come up.

---

Let me do some thinking / twiddling.
Essentially, we need the ability to add an 'empty' object anywhere that does repetition / supports the cycle command.
Using something like **-1** to indicate invisible would probably be the best approach, although that feels a little too easy to add accidentally.

**Comment by Kenny-Hui** [comment]
So for now, should I just add a dummy MeshBuilder?
e.g.
```
CreateMeshBuilder,
AddVertex, 0, 0, 0
AddVertex, 0, 0, 0
AddVertex, 0, 0, 0
AddVertex, 0, 0, 0
AddFace, 0, 1, 2, 3
```

**Comment by leezer3** [comment]
That'd probably work, but it's probably worse in some ways; Without chasing through the code, that'll almost certainly produce a world entitiy, and probably have to be considered for depth sorting etc. etc.

It needs 'fixing' so that anything using the existing null object approach works correctly (playing with that at the minute), and a 'new' approach thinking up to avoid having to do this sort of hack in the first place, along with the appropriate log message.

**Comment by leezer3** [comment]
Fixed the issue with null files, although I *really* don't like it.....

The csv / b3d object plugin now checks to see if any route plugin is loading, and if so, essentially assumes that anything with the csv / b3d extension is an object.
Might try limiting it to files under a couple of kilobytes or something, but I can just see someone somewhere having a 30+ line comment in his empty objects :/
