### ISSUE TITLE
Not documented [bogie] section at Extensions.cfg

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#669]
### Description
At 1.8.0.2, [bogie] section is works correctly, but I found that this function is not documented.
I think that it should be document.

**Comment by ginga81** [comment]
At the first post, I was failed key combination.
Not complete yet, but has been posted.
After then, I edited.
I am sorry.
Thank you very much to document!
I found the documented section.
At the your timing, please close this issue.

**Comment by ginga81** [comment]
I re-checked this.
I think that at the Index area, not still insert between 5. and 6.
Currently 5. is still '5. The Exterior section (outdated)'.

**Comment by leezer3** [comment]
Good point, thanks!

Should update itself in a second.
