### ISSUE TITLE
Not works 'Enable Train' at 1.8.0.2's ObjectViewer.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#673]
### Description

When I check to the 'Enable Train' at Train Settings, nothing action.
At 1.7.2.4's ObjectViewer, it works correctly.

### Reproduction

Please use my data.(Series-E5)
https://drive.google.com/uc?export=download&id=15B98GOoz19jV4eWGiaiwRi6ReHkSBAjS
At 1.animated, PluginState[62] can open the coupler cover. (0 or 1)
reverser handle relate headlight and tailright.
Speed is more than 60 km/h, side LED board is not show.
Wheel relate rotate with speed.
Doors can open.(L/R)
Doorlamp can lit relates doors.

## Route

Any

## Train

Please use my Series-E5

## Logs

This issue is not output any log.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
I believe this was fixed by https://github.com/leezer3/OpenBVE/pull/631

Appears to work OK in 1.8.1.0 (pushed this about an hour ago.....)

**Comment by ginga81** [comment]
Oh! 1.8.1.0 was release!
I didn't know.
I test at 1.8.1.0's ObjectViewer, as you say, it works correctly.
Thank you very much for fix!
And this issue close.
