### ISSUE TITLE
routelimit command is not documented

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#674]
### Description

routelimit command is maybe included.
But, not documented.
I think that this command's document should be write.

**Comment by leezer3** [comment]
Not sure that we've got a command routelimit....
Any example at all?

https://openbve-project.net/documentation_hugo/en/routes/csv.html#route
Route.Signal(Aspect) Limit

https://openbve-project.net/documentation_hugo/en/routes/csv.html#track_signalling
Track.Limit(Limit)

**Comment by s520** [comment]
What he is probably saying is:
https://github.com/leezer3/OpenBVE/blob/91bedcb7e24a450a40b1968af08cf4da8e87dcea/source/OpenBveApi/FunctionScripts/FunctionScript.cs#L756-L759

**Comment by leezer3** [comment]
Missed that one, thanks :(

Have now checked all functions in the animated file, and added three more missing, plus fixed a typo.
I *think* that's everything in there. 
(raindrops aren't documented, as they're only used with the internal windscreen code)

**Comment by ginga81** [comment]
Thank you very much for document!
I read manual and found.
So, this issue is closed.
