### ISSUE TITLE
Display 'delay' in ObjectViewer at OpenBVE-2021-07-21.zip

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#676]
### Description

When we using the ObjectViewer at OpenBVE-2021-07-21.zip, and enable GL3.0, and load 'an' .animated, display delays at each part.
GL1.2 is not happen.
When we load from Extensions.cfg, it is not happen.

Please look this video.

https://user-images.githubusercontent.com/22734699/126747243-282535e0-8298-4cf6-8cc4-a305b0284561.mp4

### Reproduction

Any an .animated object.
Please use my Series-E5.
https://drive.google.com/uc?export=download&id=15B98GOoz19jV4eWGiaiwRi6ReHkSBAjS

## Route

This issue happens at ObjectViewer.
So it is not use any route data.

## Train

This issue happens at ObjectViewer.
But, to load Extensisons.cfg, need Train.

## Logs

This issue is not output any logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Thanks, fixed.....

A little complicated:
Previously, we were re-creating the matrices to send to the shader for every face. However, as the renderer internally sorts by Object State for static objects, we can actually cache the matrices on an object-state basis.
This works perfectly so long as we've got more than one object state in the world (i.e. anything other than Object Viewer with a single object loaded). In this case, it needed to reset the cached matrix state whenever the camera moved too.
