### ISSUE TITLE
In some cars, Animated bogie is not display at ObjectViewer

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#678]
### Description

At OpenBVE1.8.1.0, my new data is works correctly with animated bogie.
But, at ObjectViewer, some car's bogie is not display.
This happens at both of Extensions.cfg and an .animated.
And both of GL1.2 and 3.0.
![Screenshot from 2021-07-24 13-01-50](https://user-images.githubusercontent.com/22734699/126856980-2324bfc3-36b3-4114-879b-f7343d4f9319.png)
![Screenshot from 2021-07-24 13-02-29](https://user-images.githubusercontent.com/22734699/126856983-8c84fff2-2cb7-49df-bd7d-31976544789a.png)

### Reproduction

Please download my new Series-E2-1000.
https://drive.google.com/uc?export=download&id=1zFYwnFi5ywHFBPjD0O0nwKec1FmcDUHL

## Route

This issue happens at ObjectViewer. So, do not need any route.

## Train

Series-E2-1000's Train is created by F81_tec200.
https://www.youtube.com/watch?v=mSYEMUcHomE

## Logs

ObjectViewer is not crash.
So no logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Now, that's *really* odd....

Your file isn't found, but I can reproduce with D1015.
It's related in some way to https://github.com/leezer3/OpenBVE/issues/645
If the code from this is rolled back, they re-appear.

They work in the main game, so this must be Object Viewer related somehow. Going to do some thinking.......

**Comment by leezer3** [comment]
So, our issue is with this transformation:

https://github.com/leezer3/OpenBVE/blob/3ab13bafd0e4b710814b6686b578d41bb2ed6671/source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs#L772

Reverting this to the old method puts our bogies back where they should be.
Still investigating.....

**Comment by leezer3** [comment]
Very odd, that appears to have been coincidental....

Issue seems to be that we weren't updating the physics for the bogies in Object Viewer (hence the internal Up vector never being updated)

Please try the latest, bogies should now be there.

**Comment by ginga81** [comment]
I tested OpenBVE-2021-07-26.zip.
All bogies are displaying, and rotate wheels!
Thank you very much for fix.
If you are ok, please close.
