### ISSUE TITLE
SetEmissiveColorAll is not works at ObjectViewer

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#679]
### Description

Even if  I added to the end of any .csv file, for example Series-E5/10_E514/E514-body.csv to 'SetEmissiveColorAll, 255,255,255', not bright at night lighting.

### Reproduction

Please download Series-E5.
This is not use SetEmissiveColor.
LoadTexture, daytimeimage, daytimeimage style.
https://drive.google.com/uc?export=download&id=15B98GOoz19jV4eWGiaiwRi6ReHkSBAjS

## Route

This is not use any routedata.

## Train

This issue is only happen at object.

## Logs

This issue is not output any logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by leezer3** [comment]
Fixed, sorry for the delay (missed this....)

**Comment by ginga81** [comment]
This issue was reported from a user to me.
So, I tested my Series-E5 and report issue.
Thank you for fix this issue!
