### ISSUE TITLE
long horn eternaly continue 0.1ms sounds while the Densha-de Go! plugin enable

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#681]
### Description

When we are using a long horn sounds using train, and when we are enable Densha de Go plugin settings is enable (If the controller is connect or not, the result is the same), the long horn sound is continue to sound.
This sound is long about 0.1ms per 1 sec.
And while this issue is happening, the long horn settings keyboard cannot sound.
the another normal keyboard sound sounds correctly.

Normally, even the plugin is enabled, the horn have to sounds when we are only keyboard pressed.
But, even we are not press keyboard, this issue is continueing the long horn sounds.
And, while enableing the Densha de Go plugin, long horn keyboard is not work.

### Reproduction

Train:
Please use F81_tec200's Series-E4.
https://www.youtube.com/watch?v=-bjdICkOPD0

## Route

Any

## Train

Please use F81_tec200's Series-E4.

## Logs

This issue is not crash.
So no any logs.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

Ihave...
Densha de Go Type-II (USB)
Densha de Go Ryojo-hen controller(USB)
(But, this isuue is not need these)

**Comment by MarcRiera** [comment]
I can recreate this with other trains and I have located the issue. Regardless of the state of the controller, a key release event is issued and OpenBVE seems to always play the horn loop end sound when this happens.

I'll push a fix later, thanks for reporting!
