### ISSUE TITLE
Crash when pausing the game for too long

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#685]
### Description

I usually have a habit of pausing the game, AFK for around ~20 minutes, then come back and un-pause the game.
However on the 64-bit variants of OpenBVE, I've noticed that most of the time, it will crash when I attempt to un-pause the game.

**UPDATE:** From my own testing, it crashes somewhere between 5min and 10min. Though I don't have time to test for each individual minute to find out the exact limit

### Reproduction
- Launch 64-bit OpenBVE with a C++ Plugin
- Pause OpenBVE, wait for ~10 min
- Un-pause the game
- Game freezes for a few seconds, then crash

## Logs
[OpenBVE Crash- 2021.8.10[17.29].log](https://github.com/leezer3/OpenBVE/files/6967012/OpenBVE.Crash-.2021.8.10.17.29.log)

### Related information 
* Operating system: Windows 10 21H1
* Method of control: Keyboard

**Comment by leezer3** [comment]
That should sort it, although I wouldn't be surprised if there were other unrelated places which object to large pauses.
(I know I fixed a similar issue where the physics of a train stopped on a hill went nuts ages ago....)

**Comment by Kenny-Hui** [comment]
Thanks, fixed
