### ISSUE TITLE
[Request] Swap loading order

### ISSUE THREAD

**Issue by HUN-Droid** [leezer3/OpenBVE#694]
## Swap loading order at loading train content
The reason is to prevent the created addon from modification with the plugin itself.

### Reasons
Unfortunately, I often come across people who have scattered the work of others. The creator asks in vain for anyone to use his work only with his permission, unfortunately quite a few do not do so. For this reason, several authors have indicated that they will not publish anything as long as this phenomenon persists. If the addon could somehow be protected from modification and re-use of its parts, several add-ons would be published. And there would be no problem with copyright either.

### Solutions
Now the plugin is loaded after everything else. If the plugin has a function, which is called before the train is loaded, the plugin can protect the train files. Before the train will be loaded, the plugin can deploy the necessary files, and at the end of the game (or after the loading), the plugin can delete the files. This can protect a bit more the product. If anyone have a better idea, I am open to discuss.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/pull/670

My reasoning remains exactly the same as in this PR discussion.
You want to (essentially) allow plugins to pass in random encrypted content with no oversight. This is contrary to all best security practies and incredibly dangerous to boot,

Further, supporting restrictive practices like this goes against all the principles of OpenBVE.
This is not the solution, sorry.

**Comment by HUN-Droid** [comment]
@leezer3 Yes, I know the danger, but with the plugin anyone can do dangerous things even now. That is not controlled. But don't worry, I have many ideas to protect my product with my solution. It is complicated, but will work, and anyone, who want to modify my product, he will be in for a big surprise. And the product will be protected with some trickies to not steal the objects, textures, sounds and other resources.
