### ISSUE TITLE
Data folder & keyboard controls assignment

### ISSUE THREAD

**Issue by JakubVanek** [leezer3/OpenBVE#7]
Hi!
I want to ask where I can obtain new Data folder. When I'm trying to start openBVE with old Data folder, the only thing that happens is a bunch of MessageBoxes informing me that controls.cfg format has changed.
This is the part of code causing the flood:
```c#
LoadControls(string FileOrNull, out Control[] Controls){
...
//We've discovered a SDL keybinding is present, so reset the loading process with the default keyconfig & show an appropriate error message
Thread Message = new Thread(() => MessageBox.Show("An older key-configuration file was found." + Environment.NewLine + "The current key-configuration has been reset to default.", Application.ProductName, MessageBoxButtons.OK, MessageBoxIcon.Hand));
Message.Start();
LoadControls(OpenBveApi.Path.CombineFile(Program.FileSystem.GetDataFolder("Controls"), "Default keyboard assignment.controls"), out CurrentControls);
return;
...
}
```
I have the old default keyboard controls assignment file, which causes infinite recursion. There should be some test if it's not loading default, if so, use some inbuilt default. And could you please provide a link to download actual Data folder?
Thanks,
JakubVanek

**Comment by leezer3** [comment]
That's mostly my issue, hadn't thought of that particular little piece of fun.....
I'd hadn't quite expected someone to build from source with the old data folder!
Will sort out a graceful failure mode tomorrow, although I'm not fond of adding hardcoded fallbacks.

I've added the most recent Data folder to the source (Oversight- It wasn't in Michelle's source either), along with an appropriate build event to copy it into the compile directory.

**Comment by JakubVanek** [comment]
Thanks! :+1:
