### ISSUE TITLE
[Question] is openbve using instancing object ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#701]
Hello

Is openbve use or can use instancing object ?
Especially with object in route.

AFAIK when using freeobj command we only define the position for one object only isnt it ?

**Comment by leezer3** [comment]
You'll have to be a little clearer as to what you mean.

However, if it's what I think, with the new (GL3) renderer enabled:
A single (static) FreeObj is mapped to a single OpenGL VBO / IBO instance, and this is drawn with the appropriate positional matricies, as opposed to each object state being stored in it's transformed state.

**Comment by adfriz** [comment]
Sorry sir, i mean i just want to know if openbve already using instancing object in route, if already using instancing object is this automaticly mark by the renderer if the object is the same and can reusing it ?.  Because AFAIK using instancing only need 1 draw call if the object is the same and can save a lot of memory and make more fps.

**Comment by leezer3** [comment]
It does that to a certian extent, primarily for static objects involving no transparency.

For anything dynamic (trains, animated objects etc.), or objects involving transparency, the relative positions / depths need to be recalculated on a per-frame basis.

**Comment by adfriz** [comment]
Ok i understand now, thanks sir.

I ask this because i want to edit someone route, change their object like a house, building etc with my object. 

One more question, if i had 1 static object and also contain a texture like jpg, if i use more than once a route is this also count as instancing that object by the renderer ?
