### ISSUE TITLE
A couple of relatively critical OS X issues

### ISSUE THREAD

**Issue by mdiamond14** [leezer3/OpenBVE#71]
Cross posted from: http://bveworldwide.unlimitedboard.com/t1229p400-new-openbve-build-testers-please#14393

Heads up, the Mac download link for openBVE RC4 on http://openbve-project.net/ leads to a 404 error page.

Also, im getting this error when i try to make a package:

http://i.imgur.com/w56BoiR.png

Additionally, packages seem to be installing in the wrong place. Aren't they supposed to install to either the directory where one has previously been loading routes/trains from (for existing installations)? This directory is in a hidden folder and is different from the legacycontent directory inside of the .App.

http://i.imgur.com/mzX7dV1.png

Perhaps a solution to this issue would be to have separate "Content Packages" and "Manually added content" selection tabs on the "start new game" dialog. 

Thanks for all your help!!

**Comment by leezer3** [comment]
Arrgh...

TravisCI (Which generates the Mac builds automagically for me) has had a major outage. Something still isn't working right at their end, I'll package the current version manually in a minute.

Package creation hasn't been tested on the Mac, but will do that as something is obviously wrong.
The website label shouldn't be showing through the form either, doesn't do that on Windows or Linux.

The Mac installation directory is also something on the list of stuff I need to really think about.
Michelle/ Odakyufan never provided an official Mac app, so there's no framework in place to handle things in a 'Mac' manner. Installing content inside the application seems to me to be a *seriously* bad idea, especially as I've come across people who just run apps from a mounted dmg.
I decided not to use the existing routes/ trains folder for packaged content (At least by default), as the installation/ uninstallation stack still isn't nearly as robust as I'd like it to be. 
Additionally, if you can avoid it, it's a bad idea to mix managed and unmanaged content.
