### ISSUE TITLE
OpenTK.DisplayDevice throws exception in 1.8.2.0+

### ISSUE THREAD

**Issue by danfe** [leezer3/OpenBVE#712]
I've tried to update FreeBSD port to version 1.8.2.0 and then 1.8.2.1 but they both won't start now, showing the window that says "Unhandled exception: The type initializer for 'OpenTK.DisplayDevice' threw an exception".  This is probably related to cloning of OpenTK in order to stop depending on the outdated OpenTK package.

Anything I can provide or help to track down and fix this problem?

**Comment by leezer3** [comment]
Can't think how :/
The OpenTK fork doesn't change anything fundamental, and only adds one XServer call, which has been tested on Linux, and ought to be supported on anything remotely more than a potato....

Have you got a full stacktrace for the exception? (Might be in the log)

Will try and spin up a VM later in the week and see if anything happens for me, although BSD isn't something I've tried before.

**Comment by danfe** [comment]
> Have you got a full stacktrace for the exception? (Might be in the log)

No, it's pretty much nothing in the logs:
```
15:19:57  WARNING: Program crashing. Creating CrashLog file: /home/danfe/.config/openBVE/Settings/OpenBVE Crash- 2021.12.03[15.19].log
15:19:58  WARNING: Program crashing. Creating CrashLog file: /home/danfe/.config/openBVE/Settings/OpenBVE Crash- 2021.12.03[15.19].log
  --8<--  --8<--  --8<--
03.12.2021 15:19:58
OpenBVE 1.7.766.438-danfe Crash Log
Program is running on the Unknown backend
Current screen resolution is: Windowed 960px x 600px 
```
In some older logs, it was more rich:
```
15:11:51  Using openGL 1.2 (old) renderer
15:11:51  Initialising game window of size 960 x 600
15:11:53  Game window initialised successfully.
15:11:53  Initializing the default shaders failed- Falling back to legacy openGL.
15:11:53  Initializing the touch shader failed- Falling back to legacy openGL.
15:11:53  Renderer initialised successfully.
```
In the log from 2020.10.27, it also managed to deduce the backend (SDL2):
```
27.10.2020 12:17:19
OpenBVE 1.7.404.146-danfe Crash Log
Program is running on the SDL2 backend
Current screen resolution is: Windowed 960px x 600px 
```

**Comment by leezer3** [comment]
So, I've just installed a fresh FreeBSD virtual machine, using the XFCE desktop environment.

I've then installed the current OpenBVE port. (1.8.1.0)
This fails to load, with the following stacktrace:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenTK.Input.Joystick' threw an exception. ---> System.PlatformNotSupportedException: Please, refer to http://www.opentk.net for more information.
  at OpenTK.Platform.Factory+UnsupportedPlatform.CreateJoystickDriver () [0x00000] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenTK.Input.Joystick..cctor () [0x00005] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
   --- End of inner exception stack trace ---
  at OpenBve.Input.JoystickManager64.RefreshJoysticks () [0x00007] in <79640a5729ad495588343d50c0759088>:0 
  at OpenBve.Program.Main (System.String[] args) [0x0007b] in <79640a5729ad495588343d50c0759088>:0
```

The curent nightly build isn't giving me a stacktrace at all.

Dropping back to a manual download 1.7.1.3 gives me an identical issue.

Am I missing a port or a kernel module to enable joystick support?
Feels like I've not installed something.

**Comment by leezer3** [comment]
Issue with the older versions found:
Your port doesn't specifiy SDL2 as a dependancy, and if it's not installed, we get the above behaviour.

The X11 backend *ought* to work on BSD as well, which is a little concerning. I'm investigating exactly what's going on, but might take a while....

**Comment by danfe** [comment]
> Am I missing a port or a kernel module to enable joystick support?

AFAIK we don't have anything like that.  My setup is just a laptop running pretty much vanilla FreeBSD with no external devices except the wired USB mouse.  Now that you've mentioned joysticks, there is a patch in the port which forcibly calls `Joysticks.RefreshJoysticks()` to avoid the crash with `System.PlatformNotSupportedException` on the same calls below unless I call it there first, but that's probably an issue for another day (it could also be a Mono-on-FreeBSD-specific bug, which is why I didn't report it).  Still, perhaps it could be useful it there was a way to completely disable joystick initialization/support.

> Your port doesn't specifiy SDL2 as a dependency, and if it's not installed, we get the above behaviour.

Yes, the port does not specify it, but I normally have it installed, and I always build OpenBVE locally for testing and playing.  I didn't notice before whether it was or not automatically picked up, but of course I should have, good point.

Last but not least, I want to thank you for the trouble of setting up FreeBSD machine for testing.  Not many developers would do that today, sadly.

**Comment by danfe** [comment]
Ah, one thing you may want to check is whether OpenGL programs run fine in your VM.  Something like installing `graphics/mesa-demos` port/package and running `fire` should be sufficient.

**Comment by leezer3** [comment]
GL is fine (Object Viewer and GLXGears are OK)

Route Viewer gives me a different stacktrace entirely:
```
Unhandled Exception:
System.DllNotFoundException: openal32.dll assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.Alc.OpenDevice(string)
  at SoundManager.SoundsBase.Initialize (OpenBveApi.Hosts.HostInterface host, SoundManager.SoundRange range) [0x000d6] in <66e900750e6f45448e11de992e914137>:0 
  at OpenBve.RouteViewer.OnLoad (System.EventArgs e) [0x0010c] in <358bfc9f0bfb4f0cbf5399713b061aa9>:0 
  at OpenTK.GameWindow.OnLoadInternal (System.EventArgs e) [0x00000] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x0008f] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenBve.Program.Main (System.String[] args) [0x003d4] in <358bfc9f0bfb4f0cbf5399713b061aa9>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: openal32.dll assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.Alc.OpenDevice(string)
  at SoundManager.SoundsBase.Initialize (OpenBveApi.Hosts.HostInterface host, SoundManager.SoundRange range) [0x000d6] in <66e900750e6f45448e11de992e914137>:0 
  at OpenBve.RouteViewer.OnLoad (System.EventArgs e) [0x0010c] in <358bfc9f0bfb4f0cbf5399713b061aa9>:0 
  at OpenTK.GameWindow.OnLoadInternal (System.EventArgs e) [0x00000] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x0008f] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <791d08df1a7948a4b0f6aebfd6cbb1ae>:0 
  at OpenBve.Program.Main (System.String[] args) [0x003d4] in <358bfc9f0bfb4f0cbf5399713b061aa9>:0 
```

My strong suspicion at the minute is that the dllmap is broken.
The Mono documentation states that **freebsd** is a valid OS, and therefore presumably it wouldn't be caught by the existing Linux entry.

Not quite sure why things may have broken, but let me do a little more fiddling.

**Comment by leezer3** [comment]
So, with the three commits linked above, we should (hopefully) be working again.

The OpenTK X11 backend seems to be broken on FreeBSD, wheras the SDL2 one is OK.
I'm not sure why OpenTK decided to default to this when forked (AFAIK I haven't changed anything in this regard), but I've changed things so that it'll deliberately force the SDL2 backend. I've also added platform detection for FreeBSD and implemented your patch into the main tree.

Will investigate the OpenTK X11 backend at some stage in the future and see if that can be fixed to work properly, but that's lower priority since I've got the thing working :)

**Comment by danfe** [comment]
> So, with the three commits linked above, we should (hopefully) be working again.

I confirm, and will be updating the port soonish.  I'll also make sure to properly register dependency on SDL2.  Thank you again for outstanding support and involvement.

> Will investigate the OpenTK X11 backend at some stage [...] but that's lower priority since I've got the thing working :)

Sure thing, no problem.

**Comment by danfe** [comment]
> So, I've just installed a fresh FreeBSD virtual machine, using the XFCE desktop environment.

One last thing I wanted to ask.  In your VM, did you observe the blurred fonts, as if there were some DPI mismatch, like on the attached screenshot of mine?  It got that way not so long ago, and I'm trying to understand if that's just me, or something got broken in the Mono/GDI/X11 stack.

![blurred](https://user-images.githubusercontent.com/1132291/144704045-61d98bcb-7c95-4e19-b427-9315dff2f4ec.png)
