### ISSUE TITLE
animated speed is very quickly from 2021-11-20

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#716]
### Description

from OpenBVE-2021-11-20.zip, the door open and close animation is very quickly, that is reported from a Japnanese user.
He said that this is happen at 32bit version, but at Linux, 32 and 64 bit is not different displaying version what is 64 bit.
I tested the OpenBVE-2021-11-17.zip, at this version, the door open and close animation is very real.
But from OpenBVE-2021-11-20.zip, the animation is very quickly.
Please fix this issue.

### Reproduction

the Outer-view object:
http://kanakyusubway.web.fc2.com/bve/train/15700/

Route:any

## Route

any.

## Train

The train outer-view is here.
http://kanakyusubway.web.fc2.com/bve/train/15700/

## Logs

This issue is not output any logs.

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
I hate some of the legacy junk sometimes.....

After implementing motor tables into the XML, we needed to move the sound loading to last, so this worked right. 
Door speed is (of course....) determined by the length of the sound file, which hadn't been loaded at this point.

I've fixed this, and implemented the door related parameters into train.xml (This will also allow setting of an opening / closing speed independantly of the sound file length)
