### ISSUE TITLE
When the select 'back to main menu' , OpenBVE is create a zombie process of 'mono-sgen' everytime.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#720]
### Description

I run 'mono OpenBve.exe', and I select 'back to main menu' , OpenBVE is create a zombie process of 'mono-sgen' everytime.

I think that this is related to 
https://github.com/leezer3/OpenBVE/issues/599
![Screenshot from 2021-12-23 15-31-48](https://user-images.githubusercontent.com/22734699/147202674-bc4d0986-206f-4cc5-80c8-00a0424be0c1.png)

### Reproduction

This is OpenBVE's program problem. so ,no any data.

## Route

This is OpenBVE's program problem. so ,no any data.

## Train

This is OpenBVE's program problem. so ,no any data.

## Logs

This problem do not crash. So, no logs

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
See whether the build from today is any better.

I *think* this may help.

**Comment by ginga81** [comment]
I tested the newest daily-build.
mono-sgen's zombie process isn't create.
Thank you very much for fix!
So, this issue is closed.
