### ISSUE TITLE
Can't run from 1.8.2.0 on WIne

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#723]
### Description

From 1.8.2.0, we can't run OpenBVE on Wine.
These error dialog shows and crashed.
![Screenshot from 2021-12-28 20-46-05](https://user-images.githubusercontent.com/22734699/147564736-059c5f87-ec78-4bad-b224-4cafa2c70c02.png)
![Screenshot from 2021-12-28 20-46-09](https://user-images.githubusercontent.com/22734699/147564741-3bad44d9-8fdd-4ff9-8fcf-69e04dd11ede.png)

How to enable on wine:
Type
```
WINEPREFIX=~/.WineOpenBVE15 wineboot
WINEPREFIX=~/.WineOpenBVE15 winetricks -q d3dx9 dotnet48 fakejapanese_ipamona vcrun2013
```

And run OpenBVE
Type
```
WINEPREFIX=~/.WineOpenBVE15 wine ./OpenBve.exe
```

fakejapanese_ipamona is for japanese font.
I don't know need VCruntime2013, but it found at crash log. So I installed.

Wine version:
wine-7.0-rc2

I tested some daily builds.
OpenBVE-2021-10-25.zip can run on Wine.
But OpenBVE-2021-10-27.zip can't run.

I think that it relates perhaps
https://github.com/leezer3/OpenBVE/issues/712

### Reproduction

This issue happens at OpenBVE's main program's. so no need any data.

## Route

This issue happens at OpenBVE's main program's. so no need any data.

## Train

This issue happens at OpenBVE's main program's. so no need any data.

## Logs

This issue is not crash so no output any logs.

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by v1993** [comment]
What's the point of using WINE? OpenBVE runs with mono from what I remember.

**Comment by leezer3** [comment]
Legacy Win32 train plugins.

Don't forget a lot of stuff relies on these for advanced functionality.

Will try and take a look later in the week.
Not sure the FreeBSD issue is likely to be related per-se; this feels more like WINE not liking the attempt to pull out the DPI.

**Comment by ginga81** [comment]
I was reported from a Japanese user about this issue.
If we are using wine now, for example these issuees aren't happen.
https://github.com/leezer3/OpenBVE/issues/722
https://github.com/leezer3/OpenBVE/issues/720
And he says that font isn't display perfectly, and when he pressed quit button, OpenBVE is force close.

Sure, I know that OpenBVE is run on mono.
And I always run OpenBVE on mono.

**Comment by leezer3** [comment]
Try today's build.
I've found & fixed the issue within the OpenTK fork, and it now appears to work for me.

Also added WINE to our detected platforms, although we don't do anything with it other than log that.

**Comment by ginga81** [comment]
I and his PC can run on wine again!
Thank you very much for fix!
So, this issue is closed.
