### ISSUE TITLE
[Question] is the triangle strip function make the game performance better ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#724]
When i click F10 i see a text say triangle strip = 0.

I dont know what is that, but is this effect the performance in some place ?

If yes how i make my object use that function ?  is this gonna automaticly processed by the game it self ?

**Comment by leezer3** [comment]
Not exactly, it's the opposite.

Triangle strips are a specific type of polygon, which are usually generated by some 3D modelling software.
In general (BVE handcoded) objects, these will be decomposited into pure triangles as part of the loading / optimisation process.

If you're using a massive poly-count object which breaches the polygon optimisation threshold ( https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Objects/ObjectTypes/StaticObject.cs#L479 ), then these will be kept.
