### ISSUE TITLE
[Request] add an option to clamp coordinates value if use more than 4 digit of decimal

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#725]
When i make an object or addon using csv exporter in blender the vertex, texture and vertex normal coordinates always had too much decimal number, usually more than 10 digit.

I wonder can we get an option only calculate the value if no more/ more than we specified.

Like if the vertex coord is 1.736826282 just take 4 number after the " . " 

I dont know if we do this the mesh and other attribute gonna broken when loaded.

**Comment by ginga81** [comment]
@adfriz 
This repository is OpenBVE's main project.
And your issue is for csv exporter.
csv exporter's repository is not here.
The repository is 
https://github.com/maisvendoo/blenderCSV/
So, you have to write issue to that repository.

**Comment by leezer3** [comment]
https://github.com/maisvendoo/blenderCSV/blob/master/io_scene_csv/CSV.py#L78

```
mesh.vertex_list.append((Round(sx, 4), Round(sy, 4), Round(-sz, 4)))
```

Alter the others in the same way, and it'll round them as you want.
IIRC you can do this with Excel on the output file too by playing with the cell formatting, although that introduces a different type of mess.

Rounding (not clamping!) as a global option isn't a good idea, as this may cause Z-fighting.

**Comment by adfriz** [comment]
thanks leezer3 i will test it
