### ISSUE TITLE
[Bug]sound.xml and flange sound

### ISSUE THREAD

**Issue by enjoysoftware** [leezer3/OpenBVE#726]
### Description

When driving a train using sound.xml, the flange sound is not played on the curve. Sound seems to play normally when using sound.cfg.

### Reproduction

Generate a sound.xml file from sound.cfg using CarXmlConvertor.exe. If it is a bug on the OpenBVE side, this problem seems to occur even if you do not use CarXmlConvertor.exe.

## Train

Any trains that have flange sound and sound.xml file

### Related information 

* Windows 10 and Ubuntu 20.04 
* Keyboard

**Comment by leezer3** [comment]
Hmm...

CarXMLConvertor seems to have been omitting the flange sounds, which I've now rectified.
Other than that, it appears OK at first glance.

**Comment by enjoysoftware** [comment]
Now, when I checked it, CarXmlConvertor worked without any problem. Thank you for fixing it.
