### ISSUE TITLE
B3D EmissiveColorAll error(s)

### ISSUE THREAD

**Issue by HUN-Droid** [leezer3/OpenBVE#727]
### Description

B3D `EmissiveColorAll`/`EmissiveAll` does not work, and not clear, which should be the right one. In the documentation is `EmissiveColorAll`, but in the 1.8.1.0 ver. description on main webpage is `EmissiveAll` command is added. And besides, none of it works.

### Reproduction

I have an object, but this in this object, both "All-type" commands aren't working. The `EmissiveColor 255,255,255` command works, but I don't want to copy-paste for all sections, because this object has a lot of [MeshBuilder] sections and this is exported and converted from a 3D modeller software. The ObjectViewer accepts both version of the command, there is no error at `EmissiveAll 255,255,255` and also no error at `EmissiveColorAll 255,255,255` command. I tried both type of command in the game (in OpenBVE, not in ObjectViewer), but it doesn't matter, which command and which display is used, all of them were black (in ObjectViewer made I "dark" with the 'L' key, and in OpenBVE I used the "Track.Brightness" command in the route with value 200 and 0). I have never encountered such an error before.

### Images

![kép](https://user-images.githubusercontent.com/47685838/148095191-d35bdb15-5ddb-4e9c-987a-e56498dfa1c0.png)
![kép](https://user-images.githubusercontent.com/47685838/148095271-a3a8391a-bbcd-4f22-8359-0b1e7165ad89.png)

### Related information 

* Operating system is Windows 10 21H2 with AMD Ryzen 3000 series processor and nVidia  GTX16** series GPU.
* I use 1.8.2.1 64bit OpenBVE, and it's ObjectViewer, and it is newly installed

**Comment by leezer3** [comment]
Should be EmissiveColorAll

I think I've found what's going on (related to the command order), so please try the most recent nightly.

**Comment by HUN-Droid** [comment]
Thanks, I'll try ASAP and I'll write my experience with the nighly build.

**Comment by HUN-Droid** [comment]
It works well, thanks for the repair. I'm waiting this function in a release.
