### ISSUE TITLE
Cannot load/install openbve package

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#730]
### Description

cannot load and install train in a package format

### Reproduction

install a package trains, a pop up will appear say "this file does not appear to be a valid openbve package"

## Train

http://www.bvecornwall.co.uk/wordpress/br-class-310-emu/

## Logs

no logs only pop up appear

### Related information 

* Operating system
* windows 10 21H2, Intel i3 2328m,  nvidia gt630m
* Method of control
* Keyboard, and mouse

tested on openbve 1.8.2.2 portable/zip version

**Comment by adfriz** [comment]
update:

BROKEN: 1.8.2.2 zip version
NOT BROKEN : 1.8.2.1 , 1.8.2.0 , 1.7.3.1 all zip version

it seems only 1.8.2.2 get broken

**Comment by leezer3** [comment]
That's interesting.
SharpCompress (the library used to handle ZIPs) got updated.

This shouldn't affect things, and definitely didn't here, but sounds like something isn't right on your machine.
Let me investigate a little....

**Comment by leezer3** [comment]
Arrgghh...

Locally built version works fine, but the downloaded version doesn't.
Investigating....
