### ISSUE TITLE
[Request] make openbve package use password like a normal zip archive

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#731]
currently openbve package only a zip archive with extra file to make sure the main program recognize it.
if this package can use a password like any zip file this gonna make that addon more secure from thief, not only the main program need to recognize a password protected package it also need to have a pop up appear for a user input the password when it loaded. also the creator can put custom message when pop up appear before the user input the password.

**Comment by Hibiii** [comment]
That wouldn't help prevent people from stealing any packages.
Adding a password prompt would only mean more hassle for the user while providing no real security.
Someone that wants to steal a package could just open the package in an archiver program with the password, extract the contents, and make another package.

**Comment by leezer3** [comment]
Agreed.

This also goes well against Michelle's original aims, for absolutely no useful gain I can see.

As a general matter of principle, I'll possibly consider adding convience features [extraction / proper install of *any* ZIP archive as a package is on a long list of tihngs I haven't got round to, which might include a password prompt for encrypted ZIPs], but I've got no intention of adding this sort of thing to packages.
It's simply not needed, or within the ethos of this sim as a whole.

**Comment by adfriz** [comment]
well that very unfortunate, but that ok i understand. and if i want to instal someone addon packages but they didn't say what the password is, its a bit annoying :|
