### ISSUE TITLE
[Request] make extra tabs for installed packages

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#733]
### Description

Please make extra tabs that directly to packages directories, currently if a user installed a packages they need browse into system c directories and need to go to C:\Users\(user names)\AppData\Roaming\OpenBve\LegacyContent\ to access the installed packages, the bad thing is if the user is not know that AppData folder is hidden and they need to click show hidden items option to see that folder.

if this a user just a kids that use their parent computer or someone that not too understand computer in general they have a chance to mess around with system files.

see image below as example
![A](https://user-images.githubusercontent.com/76892624/151743467-3991d5e1-9bfa-408f-9ea5-c4012756b85a.jpg)

**Comment by leezer3** [comment]
Good idea, thanks.

IIRC Michelle's implementation had this too, but might have been in a separate main form tab altogether.
