### ISSUE TITLE
[Request] Make the extra key know which is checked first

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#736]
### Description

when changing some controls i see if we add the extra key (shift, ctrl and alt) the order always like this :

if shift added first then add ctrl the combination like this : SHIFT+ CTRL + THE KEY
if ctrl box checked first then shift the combination i expect should like this: CTRL + SHIFT + THE KEY
 BUT the combination we got is the same like before (SHIFT + CTRL + THE KEY)  
![A](https://user-images.githubusercontent.com/76892624/152325580-641e8aba-7a69-4a1d-8506-53a9b0a3555a.jpg)

if the sequence of this combination is not fixed like now, we will get more key combination that we can map to some feature in the future.

### Related information 

* Operating system windows 10
* Method of control (Keyboard and mouse)
* openbve 1.8.2.3 64 bit zip version

**Comment by v1993** [comment]
If this happens, please replace checkboxes with some different interface. It would be very confusing as to what exact key combination is required, since same highlighted checkboxes could mean different things.

**Comment by adfriz** [comment]
v1993 Sorry i dont get it, are you adding more suggestion to my request or what ?

I think checkbox is right for the extra key because you can add three of them to your assigned key/command.

Anyway if my request is implemented, this not only make more room for new key combination this also open a way to make the .animated file to follow and use our custom key combination to run a function like raising/lowering a pantograph.

**Comment by adfriz** [comment]
Isn't we already had indicator to see what key combination in controls section in main menu ?
Is on very right part of controls section.
You gonna see a combination like ctrl+x , ctrl-v etc.


Well for me is usefull if the user use keyboard only, especially limited amount of key like laptop keyboard that dont have a numpad or a simple desktop keyboard that only had 60-70% keys than full keyboard with a lot of Fkeys, separate numpad and another key like page up/down and home.

Yeah i know that not related to this request, but i dont know we can use that security function key to utilized to our trains 😂 i though that only for security function like ATC.
Yeah making some key to run a function that we make need an another request.

**Comment by leezer3** [comment]
This is a nuts way of trying to do things, and I'm not going to even try and implement it.

A laptop still has more than enough keys available with modifiers involved. 
(At *minimum* 26 letters x 3 possible modifier combinations, so 78 possibilities!)

If you need more, please plug in a joystick, external keyboard or similar.
