### ISSUE TITLE
[Question?] Camera resets to default state after reloading in RouteViewer

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#738]
### Description
Camera now always resets after reloading since 1.8.2.1, all the way to the latest nightly build
I am assuming this has to do with fixing #707.
In my opinion it does make things a little more redundant to preview changes on the route.
Just wondering, is the reset necessary as a workaround or it's just a left over for further diagnosing of the issue?

### Reproduction
- Launch OpenBVE v1.8.2.1+
- Open a random route
- Move your camera
- Press F5 to reload
- The camera would then reset to the default state, looking forward

### Related information 

* Operating system: Windows 10 21H2
* Method of control: Keyboard

**Comment by ginga81** [comment]
https://github.com/leezer3/OpenBVE/issues/707 has been fixed, so I also think that when we are reviewing a route, the camera position will 'not' reset is better.
To move to the camera at everytime, it is very bother.

**Comment by leezer3** [comment]
Try that, should be OK now.

**Comment by ginga81** [comment]
Thank you very much for not reset camera position!
