### ISSUE TITLE
[Request]Can we use Pi constant word without 3.1415 at Animated Object?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#739]
### Description

A Japanese user suggested me.
When we use Pi at Animated Object function, we write to 3.141592 directly.

For example, if we can write such as
RotateYFunction=64*PI/180

we are more smoothly to create.
Can you consideration with this idea?

### Reproduction

This is an idea's suggestion. So no route.

## Route

This is an idea's suggestion. So no route.

## Train

This is an idea's suggestion. So no train.

## Logs

This is an idea's suggestion. So no output any logs.

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
Added :)
