### ISSUE TITLE
[Bug] texture broken when using sharp transparency mode in object viewer

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#742]
### Description

Some texture get transparent if load an animated file or extension cfg file.

### Reproduction

Load any .animated file or extension cfg file, change transparency mode to sharp, move the camera further from the train, see the texture get transparent while you move away from the train.

## Route

No route

## Train

Shinkansen E5

## Logs

No logs

## Image

![Annotation 2022-02-23 135439](https://user-images.githubusercontent.com/76892624/155277090-a59169dc-57ee-4d9b-920c-ca89275853ae.jpg)
![Annotation 2022-02-23 135514](https://user-images.githubusercontent.com/76892624/155277094-d49aba65-4e93-4ae1-bd07-2e0c531cfe05.jpg)
![Annotation 2022-02-23 140322](https://user-images.githubusercontent.com/76892624/155277095-92882337-171c-43b8-aeaf-e841896ec371.jpg)
![Annotation 2022-02-23 140055](https://user-images.githubusercontent.com/76892624/155277096-d44b6f78-87c7-4907-9bc2-3aedc4f32dfc.jpg)
![Annotation 2022-02-23 140131](https://user-images.githubusercontent.com/76892624/155277098-605a47b1-a1bd-487b-ac79-61bd519c4968.jpg)

### Related information 

* Operating system : windows 10 64 bit
* Method of control : Keyboard and mouse
* Tested on OpenBVE V1.8.2.3 portable and nightly builds 2022-02-15

## Note
It seems only affect shinkansen addon made by ginga81 because when i test with my personal addon it didnt get same result like this.

I dont know if this because using PNG texture with alpha channel or not, because i have delete the alpha channel for the train body and still get same result.

**Comment by leezer3** [comment]
This is expected behaviour in **Sharp** if overlapping alpha / transparencies are present.

It's a complicated result of the fact that this mode lacks depth blending, which it trades for performance.

Sharp transparency mode should really be only used if you're struggling for FPS.
In some ways, I'd remove it, but I don't like dumping existing features.
