### ISSUE TITLE
[Bug] texture not appear correctly if object had hole/concave shape in it

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#747]
### Description

when exporting an object from blender to csv/b3d the texture will appear broken if the object have a hole/concave shape and not pre-triangulated the face around that shape before exporting.

### Reproduction

just test object i attached in object viewer.

## Route

no route

## Train

no train

## Logs

no logs

### Related information 

* Operating system windows 10 20H2 64 Bit
* Method of control : Keyboard and mouse
* Tested in openbve 1.8.2.3 zip ver

[test.zip](https://github.com/leezer3/OpenBVE/files/8166738/test.zip)

![a](https://user-images.githubusercontent.com/76892624/156299711-83e88f6a-9da0-4662-93b7-4761a137eb45.jpg)
![b](https://user-images.githubusercontent.com/76892624/156299718-b399555b-48e4-4780-a6e0-e25a4319c3d1.jpg)
![C](https://user-images.githubusercontent.com/76892624/156299720-c61ed6c8-e536-4c93-8f67-7d8b068192d8.jpg)
![D](https://user-images.githubusercontent.com/76892624/156299722-c9505eaa-f863-4f3f-8cd0-1c337b8d6869.jpg)

**Comment by leezer3** [comment]
That's a bug with the Blender exporter.
It's splitting all faces into 4 vertice squares, and failing to take into account that the top faces of the object don't work well with it's algorithm.

Nothing we can do with this, the exporter needs fixing, or just select to triangulate in Blender.
