### ISSUE TITLE
[Question] Contribute Bahasa Melayu(Malaysia) Language Translation

### ISSUE THREAD

**Issue by samaliftech** [leezer3/OpenBVE#754]
Hi,
Is there any way to add Malay language to OpenBVE or I need to send xlf that contain Malay translation to you? It is because some of malaysian having trouble to understand English and Indonesian.
Thanks

**Comment by leezer3** [comment]
I think you've found the Transifex project for at least the documentation?

The main language is also on there:
https://www.transifex.com/openbve/openbve-xliff-test/dashboard/

I've added Malaysian as an available language to both, and I think you now need to request access to them. (It doesn't recognise you on a search for some reason....)

If you prefer, you also ought to be able to either create a pull request with an XLF or attach it here by dragging it into the editor. (May need zipping first)

**Comment by samaliftech** [comment]
> I think you've found the Transifex project for at least the documentation?
> 
> The main language is also on there: https://www.transifex.com/openbve/openbve-xliff-test/dashboard/
> 
> I've added Malaysian as an available language to both, and I think you now need to request access to them. (It doesn't recognise you on a search for some reason....)
> 
> If you prefer, you also ought to be able to either create a pull request with an XLF or attach it here by dragging it into the editor. (May need zipping first)

What should I named the XLF file if I attached it here? Should I named it ms_MY or what?

**Comment by leezer3** [comment]
Yeah, that's fine.

We'll also need a flag too. Is this correct (I presume so, but you're local!):
https://en.wikipedia.org/wiki/Flag_of_Malaysia#/media/File:Flag_of_Malaysia.svg

**Comment by samaliftech** [comment]
Yes, its correct

**Comment by samaliftech** [comment]
I am working on Malay Translation at Transifex now. It may be take a couple of day to complete translate 1,054 strings. But I feels weird because Malay and Malay(Malaysia) is same except Malay(Brunei) because Malay(Brunei) have few word that have same word but different meaning to compare with Malay(Malaysia).

**Comment by samaliftech** [comment]
Hope you can update the translated string of Malay to latest version in your code. I already tested the translation file and it seems 2 string has mistake. So, i already updated the string at Transifex just now and its all done. So, I can close this issue now. Thanks.
