### ISSUE TITLE
hmmsim1 basic route object wrong way error

### ISSUE THREAD

**Issue by hwanghyunseo** [leezer3/OpenBVE#760]
### Description

Please describe the issue you are experiencing.

hmmsim1 basic route is object error.

## Route

https://apkpure.com/kr/hmmsim-train-simulator/com.Jeminie.Hmmsim

## Train

https://apkpure.com/kr/hmmsim-train-simulator/com.Jeminie.Hmmsim

## Logs

no log

### Related information 

* Operating system
* Method of control (Keyboard, joystick, RailDriver)
* error object image:https://ibb.co/Gv5N02h
* fix object source:youtube image link:https://ibb.co/wQ6qrTt
* please fix it.

**Comment by Lastorder-DC** [comment]
`please fix it.` - Why? Are you paying developer to fix that? It's very rude to say like that.
also, Hmmsim developer said that It's illegal to extract default route of Hmmsim/Hmmsim 2(that's why hmmsim's own format is used at route)
