### ISSUE TITLE
Clicking "None" in Customize Controls menu crash the game

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#762]
### Description

When there's an control with no command, the in-game menu will show as "None"
But when you click on it, it crashes the game.
![image](https://user-images.githubusercontent.com/28094366/160250603-9adaa5ee-bc41-403b-8d45-300447f9195f.png)

### Reproduction
- Add an empty control
- Launch the game
- Pause menu -> Customize Control
Clicking a "None" would crash

# Logs
[OpenBVE Crash- 2022.3.27[01.23].log](https://github.com/leezer3/OpenBVE/files/8355998/OpenBVE.Crash-.2022.3.27.01.23.log)

### Related information 

* Operating system: Windows 10 21H2
* Method of control: Keyboard
* OpenBVE Version: 1.8.3.0

**Comment by leezer3** [comment]
Thanks :)

Have sorted the crash and hidden the **none** entries for good measure.
