### ISSUE TITLE
[Nightly Build] Unable to move the Notch Forward

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#765]
### Description

On the latest Nightly Build, I am unable to move the power notch on a traditional train.dat configuration
The brake notch will still work properly, but pressing Z does nothing when the notch is neutral.
(The AI does manage to move to P1 for a few frames, before returning back to neutral)

## Train
[Tram_168.zip](https://github.com/leezer3/OpenBVE/files/8357815/Tram_168.zip)

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/8357821/log.txt)

### Related information 

* Operating system: Windows 10 21H2
* Method of control: Keyboard
* OpenBVE Version: 1.7.879.1073-vsts 64bit (2022-03-26)

**Comment by leezer3** [comment]
Fiddle, copy + paste error.....

Made a slight improvement too, so that it'll check for a non-zero spring return time.
