### ISSUE TITLE
My most of Tohoku-Shinkansen routes can't load from 1.8.3.0

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#769]
### Description

1.Run OpenBVE1.8.3.0
2.Choose Tohoku-Shinkansen route.
3. At the right textarea, shows 'Index was outside the bounds of the array.'

*Only Max-xxxx data, these are can load. This is maybe relate this fix.
https://github.com/leezer3/OpenBVE/issues/729
東北新幹線Maxやまびこ149_v0.01.csv
東北新幹線Maxやまびこ203_v0.01.csv
東北新幹線Maxやまびこ35_v0.01.csv

### Reproduction
These routes are can't load.
from Sendai:
東北新幹線はやぶさ1_fromSendai_v0.07 (summer).csv
東北新幹線はやぶさ1_fromSendai_v0.07 (summer-rain).csv
東北新幹線はやぶさ1_fromSendai_v0.07(winter).csv
東北新幹線はやぶさ27_fromSendai_v0.07(summer).csv
東北新幹線はやぶさ27_fromSendai_v0.07(summer-rain).csv
東北新幹線はやぶさ27_fromSendai_v0.07(winter).csv
東北新幹線はやぶさ95_fromSendai_v0.07(summer).csv
東北新幹線はやぶさ95_fromSendai_v0.07(summer-rain).csv
東北新幹線はやぶさ95_fromSendai_v0.07(winter).csv
東北新幹線やまびこ161_fromSendai_v0.07 (summer).csv
東北新幹線やまびこ161_fromSendai_v0.07 (summer-rain).csv
東北新幹線やまびこ161_fromSendai_v0.07(winter).csv
東北新幹線やまびこ171_fromSendai_v0.07(summer).csv
東北新幹線やまびこ171_fromSendai_v0.07(summer-rain).csv
東北新幹線やまびこ171_fromSendai_v0.07(winter).csv
東北新幹線やまびこ39(200系向け)_fromSendai_v0.07(summer).csv
東北新幹線やまびこ39(200系向け)_fromSendai_v0.07(summer-rain).csv
東北新幹線やまびこ39(200系向け)_fromSendai_v0.07(winter).csv

From Omiya:
東北新幹線はやぶさ1雨_v0.09.csv
東北新幹線Maxやまびこ149_v0.01.csv
東北新幹線はやぶさ1晴_v0.09.csv
東北新幹線はやぶさ27_v0.09.csv
東北新幹線やまびこ11_v0.09.csv
東北新幹線やまびこ219_v0.09.csv
東北新幹線あおば201_v0.09.csv
東北新幹線やまびこ5_v0.09.csv

## Route

From Omiya:
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-v0.09.zip
To change english name:(Overwrite this data.need Touhogu-Shinkansen-Routedata-v0.09.zip)
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Additional-TimetableData_and_en_datas_for_v0.09.zip

From Sendai(EN):
http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.01_EN.zip

Objects:
https://drive.google.com/uc?export=download&id=1lc4B8zgq9PhQM8BCEqAGNaU-u47mZET3

## Train

any

## Logs

This issue happens at the mainmenu.
So, no logs

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
That's really odd.

As far as I remember, literally the only change in the route parser was to add special-case handling to a file which decided it wanted to use a relative path to the train folder.
Will investigate later...

**Comment by ginga81** [comment]
At 1.8.3.1, it maybe fixed!
Thank you very much for fix!
So, this issue is closed.
