### ISSUE TITLE
Legacy Panels are not correctly resized on Full Screen view

### ISSUE THREAD

**Issue by OnyxPhoenix** [leezer3/OpenBVE#77]
Legacy BVE Trains, had 640x480 to 1024x768 (bmp) textured Panels.

OpenBVE versions prior to 1.5.*, used to resize these panel textures, to the window size, even in the "Full Screen" view on higher resolution displays, so, this tiny panels from old trains have been resized to meet the screen size and no "transparent edges" were found around the control panel of the cockpit

However, I use a "homemade" train with a 1024 x 768 resolution panel base, but the 1.5 series of OpenBVE put the panel at the window center and the space around seems to be transparent from the driver's eye.

noTextureResize = false

1024x768 train panel / 1600x900 display:

![openbve14](https://cloud.githubusercontent.com/assets/20334899/16647990/7cd40518-43f7-11e6-9692-bb0ac995168c.png)
![openbve15](https://cloud.githubusercontent.com/assets/20334899/16647999/831cad3a-43f7-11e6-9b1d-12273cee54a4.png)

**Comment by leezer3** [comment]
This is working OK for me with the BVE4 and 2 trains I've got (Lots of them!)
First thing to check-
Have you turned off the camera restriction at all? ( **CTRL + R** by default)

Having said that though, the panel image should never be stretched- The expected behaviour (Including in 1.4.3.0) is to adjust the zoom, and for the user to pan onto any 'missing bits' , so I'm a little intrigued as to how this actually worked in the first place.

Which operating system are you running please?

A copy of the train would also be good with stripped out sounds.
My suspicion would be that the panel.cfg / panel2.cfg is buggy.

**Comment by OnyxPhoenix** [comment]
Yup. camera restriction disabled, default zoom, panel2.cfg has been tested with other OpenBVE versions, the only one that fails to load the panel full screen size is 1.5.0.* :) panel size: 1024x768 Default Zoom and... this happens only on "Fullscreen Mode" on "windowed mode" panel fits the size of the window...

Digital speed position on panel was corrected after the capture, because this panel was from another train (lower version) but I've tested both versions of the panel and keeps working on OpenBVE versions but 1.5* I'll try to send the train for tests.

**Comment by leezer3** [comment]
Please do.

This has popped up on BVE Worldwide, which would appear to be the same, or a potentially related issue:
http://bveworldwide.unlimitedboard.com/t1305-help-with-panel-positioning#14413

SteveGR's post suggests that *both* texture dimensions must be to the power of two for things to work correctly at all times. I'll have to check the code and do some testing with odd sized images and see if I can reproduce anything......

**Comment by OnyxPhoenix** [comment]
Update:

Panel (same panel2.cfg) got fixed on 1.5.0.7

**Comment by leezer3** [comment]
That would suggest a typo in the _*[This]*_ section of your Panel2.cfg then.

I made a couple of changes for 1.5.0.7 which reject clearly invalid values (To fix a couple of existing BVE2 trains)

Without a full copy of your train, there isn't much I can do to test though.
