### ISSUE TITLE
Unable to close the door with train.xml

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#770]
### Description

Recently I converted a train into the xml format using the CarXmlConvertor.exe, but when I start the game/jump to any stations it will just immediately says:
**Boarding Complete**

It also seems I can't close the left door

## Train
[repo.zip](https://github.com/leezer3/OpenBVE/files/8398839/repo.zip)

### Related information 

* Operating system: Windows 10 21H2
* Method of control: Keyboard
* OpenBVE Version: Nightly Build 2022-03-30

**Comment by leezer3** [comment]
Thanks, fixed.

Might actually get all of the bugs out if someone actually uses it :P
