### ISSUE TITLE
[Question] is there a playable build for other branch ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#773]
Hello

I just wanna know is there any playable for branch build that i can test it ?
Im intrested with bve5 parser branch and switchable track branch, i want to test it but it seems i need to compile it my self, unfortunately i still dont understand how to build it 😅.

Also AFAIK daily builds is using master branch isnt it ?

**Comment by ginga81** [comment]
1.download monodevelop and install(Linux and Mac).
https://www.monodevelop.com/
Or use VisualStudio(windows).
To use the monodevelop at windows, have to build.

2.download source code.
2-1.change branch to as you like.
This example is S520's Bve5 route parser.
![howtobuild1](https://user-images.githubusercontent.com/22734699/161684017-4f50c08d-333e-4abd-be38-7cd8d4bba1a9.png)

2-2.Press green 'Code' button, and press Download zip.
![howtobuild2](https://user-images.githubusercontent.com/22734699/161684058-18115f4d-09cc-4d62-bec6-877484129f9f.png)

2-3.extract sourcecode at any folder.
![howtobuild3](https://user-images.githubusercontent.com/22734699/161684149-7906ba6a-41dc-4874-aca3-1b940c35ce22.png)

3.change the folder, and doubleclick OpenBVE.sln, then VS or monodevelop are run.
![Screenshot from 2022-04-05 14-05-20](https://user-images.githubusercontent.com/22734699/161684194-e4426b3f-8008-4bb4-a938-67365b96e973.png)

4.build the project.
At the monodevelop, choose 'Build' 'Rebuild All'.
![howtobuild4](https://user-images.githubusercontent.com/22734699/161684236-5a1ebff4-ca45-4dec-b6c3-37f74c70d071.png)

5.The build is complete, and no error, OpenBve.exe has been created under bin_debug folder.
![howtobuild5](https://user-images.githubusercontent.com/22734699/161684263-3f2d505d-8843-4057-89a3-0eafaf1a492a.png)

6.Run  bin_debug's OpenBve.exe.

I don't know why, I can't build by 'Unknown MSBuild failure. Please try building the project again' error happen at OpenBveApi.csproj.

**Comment by ginga81** [comment]
Sorry, I am a linux user.
I don't use Windows.
So, I can't answer.

**Comment by leezer3** [comment]
If you install the .Net workload in Visual Studio, it *ought* to automatically take care of the rest.

The OtherTracks branch is probably functionally complete in terms of game mechanics, but the UI is not.

**Comment by ginga81** [comment]
I don't know why the current source is a compilation error.
When I built it before, I distributed the compiled one without any error, but I am in trouble because it cannot be built with the current source.
Should it be create a new issue?

**Comment by leezer3** [comment]
Here is probably fine.

Try switching the active runtime version via Menu --> Project --> Active Runtime

You might want to also try building from the command-line. Issuing a **make** command in the project root directory should work in this case.

**Comment by ginga81** [comment]
Thank you very much!
When I choose 'Project'->'Active configuration'->'Debug' to 'Release', then I have no error with compile.
I can continue to release with compiled.

**Comment by adfriz** [comment]
Thanks everyone, i will try it soon 😁

If i encounter an error or something i will open this issue again.
