### ISSUE TITLE
[Bug?] Game and ObjectViewer crash during startup with NullReferenceException

### ISSUE THREAD

**Issue by sando-gm** [leezer3/OpenBVE#777]
### Description

the game (version 1.8.3.1 on LInux) crashes during startup. It seems to load the route properly, but gets stuck while loading the train and then returns to the main menu and generates an error log file with a message like this:

System.NullReferenceException: Object reference not set to an instance of an object
  at OpenBve.Graphics.NewRenderer.RenderScene (System.Double TimeElapsed, System.Double RealTimeElapsed) [0x008f8] in <07e95528eaee435d8992c020652a08f2>:0

The ObjectViewer crashes on startup, too, and throws a very similar error message:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at ObjectViewer.Graphics.NewRenderer.RenderScene () [0x0000f] in <22745032aff74ad982e72dd26d2a54d3>:0

The RouteViewer is working correctly.

Interestingly, the RouteViewer says that he would use the "old" renderer (OpenGL 1.2), but we can read "Using openGL 3.0 (new) renderer" in the game's log file. Maybe that is the problem because my system is a bit older (see below).

### Reproduction

Seems to happen with any route/train or object. Got the same error with freshly-compiled version from source code.

### Logs

See attachment.

### Related information 

* Operating system: Ubuntu 20.04.4 LTS
* Method of control: Keyboard

### Additional Information:
$ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]
$ apt list --installed | grep -i opengl
llibopengl0/focal-updates,focal-security,now 1.3.2-1~ubuntu0.20.04.2 amd64  [Installiert,automatisch]
libqt5opengl5/focal-updates,focal-security,now 5.12.8+dfsg-0ubuntu2.1 amd64  [Installiert,automatisch]
libtaoframework-opengl3.0-cil/focal,focal,now 2.1.svn20090801-14 all  [installiert]
 
[openBVE_Bug_Report_2022-04-10.zip](https://github.com/leezer3/OpenBVE/files/8459651/openBVE_Bug_Report_2022-04-10.zip)

**Comment by ginga81** [comment]
I am using Ubuntu 20.04 now.
What route and train data crash happen?
Please link for crash Train and Route.
These are already written at template bellow, because the another person can't test.
### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

**Comment by leezer3** [comment]
I think it's this from the log:
http://bve.altervista.org/news03.html

Will try and take a look, but probably will be Tuesday or Wednesday.

**Comment by leezer3** [comment]
It would definitely appear to be the S75 route I linked above.

The version I've got in my archives (or that I can pull off the Internet Archive) however doesn't appear to be the one you're using.
Similarly, the only BR-475 I'm aware of was that by Martin Scholtz from BVE-Berlin, but you appear to have a slightly different folder name of **BR 475 Halbzug**

A link to exactly what you're trying would be useful at this point, however those I've got work OK, which suggests to me that it's probably something at your end.
I note that it attempts (and fails) to use GL3- Please try disabling the New Renderer from the second page of options and see if this helps matters.

**Comment by sando-gm** [comment]
Okay, I have put together two examples now:

## Example 1
### Route:
https://www.mediafire.com/download/cn6obvnlsbcxjid/Berlin_S75.7z
### Train:
http://www.mediafire.com/file/8tyi8yr3n7alon1/Cercanias_DB_BR_423.zip/file
(The BR475 series train does not seem to be available on the internet any longer.)

## Example 2
### Route:
from http://www.bvemetro.hu/
--> budapesti K-Ny-i metróvonal (2-es metró)
--> openBVE Letöltés http://www.bvemetro.hu/download/palyak/palyak.php?menu=202
--> Letöltés ZIP http://www.bvemetro.hu/download/palyak/down_M2zip_openBVE_2012.php
(Unfortunately, the web page does not allow you to download the file directly.)
Route "M2_Deli-Ors_openBVE_Ev.csv"
### Train:
http://www.bvemetro.hu/download/jarmuvek/Ev_openBVE.zip (auto-selected by route)

The issue **seems to appear in v1.7.1.1**. The game seems to work OK until v1.7.1.0. From v1.7.1.1 onwards I receive that "System.NullReferenceException" error message. This persists up to the current version v1.8.3.1.

In both cases, disabling the new renderer did _not_ help. But interestingly, both renderers work OK with v1.7.1.0, and no more with v1.7.1.1.

The Object Viewer seems to be affected **from v1.8.2.0 on**. Its "System.NullReferenceException" error message looks similar to the one above, maybe these two things are linked to each other.

## Logs
[OpenBVE_issue_0777_02_GameCrash.tar.gz](https://github.com/leezer3/OpenBVE/files/8506113/OpenBVE_issue_0777_02_GameCrash.tar.gz)
[OpenBVE_issue_0777_03_ObjectViewerCrash.tar.gz](https://github.com/leezer3/OpenBVE/files/8506114/OpenBVE_issue_0777_03_ObjectViewerCrash.tar.gz)

**Comment by leezer3** [comment]
I can reproduce Object Viewer failing, and have fixed this for the current nightly build.
This also has some other experimental twiddling, and in your case should be tried with the new renderer specifically disabled from options.
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2022-04-19.zip

However, nothing I can find at the minute in the main game- All of your exanples work correctly for me on both Linux and Windows.

My best guess at the minute is that your graphics driver is failing in some way we don't like when requesting GL3 features, something like returning **null** when compiling a shader, rather than actually throwing an exception.
I believe you should be using the amdgpu driver and have the proprietary firmware blobs installed for correct functionality.

**Comment by leezer3** [comment]
Good, that at least means it's not terminal :)

Silly question- does anything at all work in the main game?

**Comment by leezer3** [comment]
Another thought:
Do the routes work in Route Viewer?

This will tell us if the train has a bearing.

**Comment by sando-gm** [comment]
Yes, the named routes work in the RouteViewer. So do the other routes in my collection that I have tested so far.

But the thought about the train is interesting. Indeed the main game behaves as if it had a problem processing the train:
The loading screen first says "loading route" and the progress bar moves to 50%. Then it says "loading train", and the progress bar moves on to 62 %, sometimes 67 %, stops, is cut back to 50 %, and then the game window disappears and the main menu shows up again.

**Comment by leezer3** [comment]
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2022-04-26.zip

I think I've found it (motion blur, which I usually have disabled.....)

Please try this build and see how things work.

**Comment by sando-gm** [comment]
Yes, this build works perfectly. Thank you very much. :-)

**Comment by leezer3** [comment]
1.8.3.2 should now be going live on the main site.
