### ISSUE TITLE
[Bug?] Error window not appear in main program

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#781]
### Description

Error window not appear in main program but it appear in object viewer and route viewer.

### Reproduction

Play some route that have error or missing object in it. The window wont pop up only red text on top left appear saying how much error or missing object.

## Route

Any

## Train

Any

## Logs

No crash, no logs

### Related information 

* Operating system : windows 10 64bit
* Method of control : keyboard, mouse
* OpenBVE 1.8.3.1 zip

NOTE: I dont know is this known behavior or not because if i remember old bve (around 1.4.x) i stil have error window pop up in main program.

**Comment by leezer3** [comment]
Not a bug.

The error window is useless for most players.
They are in the log, or can be viewed with Route Viewer.
