### ISSUE TITLE
[Question] will the texture loaded again ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#786]
Hello i have a question related to object states like in #783 .

Let say If i have 1 texture that have 1K resolution, that texture contain 3 small texture for 3 object.

If i change the object states ingame will it load the texture again or it only load the other mesh ?.

I ask this because there a potential feature like swapable train livery and also potential heavy RAM usage if all states load even if the user didnt want to change the the states.

**Comment by leezer3** [comment]
If the texture is in memory, state changes will not effect it.

If Unload Unused Textures is on, textures will get unloaded after IIRC 1 min or so from the last access.

**Comment by adfriz** [comment]
Oh its automaticly unloaded after some minute if unload unused is on, that nice.

Is this also applied to object too ? If we in 2nd object states will the first states object get unloaded both mesh and texture ?

**Comment by leezer3** [comment]
Texture yes, mesh no.

Don't forget also that the end-users system may well do something similar behind the scenes in the case of low memory etc.

As few textures as possible, as small as possible.
Changing texture is the single most costly operation in the render path

**Comment by adfriz** [comment]
Oh ok.

My option for this change state feature either:
1. 1 texture contain 3 small texture shared for 3 object states. Or
2. 1 texture for 1 object states.

But base on your answer maybe option 1 is better because its only change the mesh.

Anyway thanks leezer3.
