### ISSUE TITLE
[Question] what is kiosk mode ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#787]
What is kiosk mode in main program ?

**Comment by leezer3** [comment]
It hides / disables various option in-game.

Stuff like the Exit menu option, fullscreen etc.
It'll also reset to AI driver after some time of player inactivity.

Its intended for public exhibition & similar. We've got a couple of museums that were using this at one stage :)

**Comment by adfriz** [comment]
Oh that what it mean, i though word kiosk is like a booth/stand for selling something 🤣. 

I think better change the name that to showcase/showroom/exhibition .

**Comment by joeyfoo** [comment]
*Kiosk mode* is a common phrase used in the IT industry to describe a mode that's designed for public use: https://en.wikipedia.org/wiki/Kiosk_software
