### ISSUE TITLE
[Question] about pluginstate behavior

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#792]
Hello

I want to ask about pluginstate behavior.

Is pluginstate only accept 2 state ?, because my statefunction formula using plugin state only accept 2 state, im using nested if statement and pluginstate[] variable.

**Comment by leezer3** [comment]
Nope, can be whatever you want.

That suggests your if stament is probably wrong- Post it.

**Comment by adfriz** [comment]
please check my formula.

what i want is if the plugin state in 0 use obj1, when in 1 use obj2, when in 2 use obj3.
state 0 is the first state index isnt it ?

sorry its hard for me to read the nested if statement.

[test.zip](https://github.com/leezer3/OpenBVE/files/8790544/test.zip)

**Comment by adfriz** [comment]
@leezer3 any thought about my formula ??

**Comment by leezer3** [comment]
You're way overcomplicating this one.

```
StateFunction = pluginstate[10]
```

That will work with the given pluginstate variable.

However:
Your issue with your function is that you've reversed the true / false variables.
From the documentation-
***If[cond,truevalue,falsevalue]***

You've nested your ifs inside the true value state, so it'll never work.
Two alternatives, which should both work:
```
StateFunction = if[pluginstate[10] != 0, if[pluginstate[10] != 1, if[pluginstate[10] != 2, 1, 2], 1], 0]

or

StateFunction = if[pluginstate[10] == 0, 0, if[pluginstate[10] == 1, 1, 2]]
```

**Comment by adfriz** [comment]
thanks leezer3 its works like a magic !

im also using the second option for my formula to simulate LOD based on cameradistance, below is the formula i use.

`statefunction = if[cameradistance >= 30, 2, if[cameradistance >= 20, 1, 0]]`

honestly i dont know this lod technique is usefull or not 😅
