### ISSUE TITLE
Set door state from plugin

### ISSUE THREAD

**Issue by HUN-Droid** [leezer3/OpenBVE#793]
### Description

I want to set the status of the doors from a train plugin (for example, I have to close the doors on both sides at the same time). I not found any method for this. Is there any way to do this, or I want a new thing?
Thanks in advance.

**Comment by leezer3** [comment]
Missed this.....

Don't actually think there's a way to do this specifically with the current plugin architecture.
Could add something easily enough, but this isn't backwards compatible, which may present a problem.

The backwards compatible way to do this would be simply to implement your own door state variable.
Catch the existing virtualkeys up / down for the door keys, just pass it to your own handler, and instruct users to ignore the L/R OSD. Not especially clever, but works right back.....

Additions wise, I'll need to think a bit about where this wants adding, as it might also involve a bit of a rework on the entire door mechanism; I'm sure someone has mentioned in the past modifiying the door button so that it has a minimum length of press and similar stuff.....

**Comment by HUN-Droid** [comment]
Capturing the door buttons sounds ok, but I thought about it a lot and it's
not a good solution. I found problems: when I lock the doors, and handle by
myself, the game thinks the train has not stopped at the station, or it's
running with opened doors. So the timetable goes into wrong, the rating and
blackbox also go to negative points and warnings. So sad :(
I tried to simulate a keypress or a keydown event for the game, but I had
no success. So if you know how to do this, it is also fine :)

Christopher Lees ***@***.***> ezt írta (időpont: 2022. aug.
4., Cs, 17:06):

**Comment by leezer3** [comment]
I was actually thinking of one of the VirtualKeys (for example A1, which on the default install is mapped to **Insert** )
These are specifically provided for plugins to do what they like with, and have no effect unless you do something in the plugin and pass it back via the Panel variables or the virtual handles.

You'd probably want to set the routefile to not open doors at all stations.

**Comment by HUN-Droid** [comment]
Actually I detect, handle and use a lot of button in my plugin (not only
the Security_X keys, but even the named buttons, i.e. the GearUp,
WiperSpeed and so on). But I can't control the doors, as I want. For
example I modell a train, which has only one door closing switch, and this
closes all the doors on both side of the train.

**Comment by leezer3** [comment]
Added a couple of delegate methods for opening and closing the doors to the .Net plugin interface.

After thinking about it, the ElapseData isn't a particularly good place for it- The doors state is affected by passengers, the interlock etc. and thus needs to be a call to attempt to set, as opposed to a simple set.

Not sure when a full release will be pushed yet (unfortunately no way to make this backwards compatible), but this is likely to be once the glitches in the fonts PR are shaken out,

**Comment by HUN-Droid** [comment]
@leezer3 According this update, I found that the DoorInterlockStates don't seem to work, i can't lock the doors so they can be changed, until they are locked. The new functions are working, thanks for the work. And while we're at it, if Lock did work, which one would be stronger? The new setter function or the Lock? Thank you for your reply in advance.

**Comment by leezer3** [comment]
They appear to be working here, so not initially sure.

First thought:
Are you trying to interlock closing?
The current code *only* interlocks opening of the doors, not closing.
Could add a close interlock, but that might get a little messy.

**Comment by HUN-Droid** [comment]
Well, that is interesting. I used the interlock before this update to disable closing the doors, until the warning sound beeps for at least two seconds. And yes, I tried to lock, and then close with the new delegate and to my surprise, the doors were closing. Maybe a potential solution, to set the door for lock closing and/or lock opening, and this for the both side. I know, this is eight different lock state, but I think, it could be a smoother door handling with this.

**Comment by leezer3** [comment]
Can't explain why that was working at all :/ 
(Sound length maybe- if using a non XML train, IIRC the door speeds are calculated from sound lengths)
https://github.com/leezer3/OpenBVE/blob/master/source/TrainManager/Train/Doors.cs

The door interlock state is only ever checked in the OpenDoors function.

Let me do some thinking. Any changes here need to remain backwards compatible, as there are definitely users of the current interlock state, and so we don't want to break it.

**Comment by HUN-Droid** [comment]
Maybe a new lock, similar to the current lock, which is by default unlocked, but it can lock only the closing? And this lock can be still at his functionality: locking the door opening. And this will be fine, the old trains do not use this lock, but the new trains can use, if they want. It has no effect on old trains because the unlocked default value.

I checked the CloseDoors(bool Left, bool Right) function in the code and it checks the Interlock state, before it closes the doors. (maybe I'm wrong, I'm not pro in code analysing)

**Comment by leezer3** [comment]
Sorry, you're right, it's checked in both.

I've just specifically tested things, and it would appear to be working for me.
Mega stripped down plugin here:
```
using OpenBveApi.Runtime;


namespace PluginTest
{

	public class Plugin : IRuntime
	{
		private CloseDoorsDelegate closeDoors;

		public bool Load(LoadProperties properties)
		{
			properties.Panel = new int[256];
			closeDoors = properties.CloseDoors;
			return true;
		}

		public void Unload()
		{

		}

		public void SetVehicleSpecs(VehicleSpecs specs)
		{

		}

		public void Initialize(InitializationModes mode)
		{

		}

		public void Elapse(ElapseData data)
		{
			data.DoorInterlockState = DoorInterlockStates.Locked;
		}

		public void SetReverser(int reverser)
		{
		}


		public void SetPower(int powerNotch)
		{

		}


		public void SetBrake(int brakeNotch)
		{

		}


		public void KeyDown(VirtualKeys key)
		{
			closeDoors(true, true);
		}

		public void KeyUp(VirtualKeys key)
		{

		}


		public void HornBlow(HornTypes type)
		{

		}


		public void DoorChange(DoorStates oldState, DoorStates newState)
		{

		}

		public void SetSignal(SignalData[] signal)
		{

		}

		public void SetBeacon(BeaconData beacon)
		{

		}

		public void PerformAI(AIData data)
		{

		}
	}
}
```

Timing issue perhaps? 
Can't think of anything especially good at the minute...

**Comment by HUN-Droid** [comment]
Interesting. If I'm correct, this plugin tries to closing the both side doors, if any button is pressed? I'll check it with a similar plugin, but Security_A1 would be lock, A2 unlock both side doors, and B1 and B2 opens and closes the left doors, C1 and C2 the right doors. And let see, what is happening.

**Comment by HUN-Droid** [comment]
"Timing issue perhaps?
Can't think of anything especially good at the minute..."
I commented out all Interlock using parts from the code, so I don't think it's possible. Just Security_A1 locks and I tried to close with Security_A2 or F5/F6 keys

**Comment by leezer3** [comment]
My posted code forces all doors to locked.
It also sets it so *any* keypress on a key passed to the plugin will trigger a door close attempt.

Stepping through this in the debugger shows that both of these appear to be working.

Happy to take a look into your source if you want and see if I can see anything.

**Comment by HUN-Droid** [comment]
I'd be happy to show you the code, but I wouldn't share it with the public. Is it possible to continue this "face to face" somewhere? Maybe on email, messenger, discord, etc.

**Comment by leezer3** [comment]
leezer3 (a) bvecornwall.co.uk is going to be the best place to send it.
