### ISSUE TITLE
Allow train plugins to get speed limits

### ISSUE THREAD

**Issue by HengYeDev** [leezer3/OpenBVE#800]
### Description

Train plugins should be able to get the current speed limit and the distance to the next setting of the speed limit to simulate train safety systems.

**Comment by MarcRiera** [comment]
That's actually already available, although it's a bit of a hidden feature. You can get the route speed limits via `SetBeacon` for track sections with ATC. The beacon type `-16777214` passes the speed limit, while `-16777215` passes the track state (whether it's compatible with ATC or not).

You can find the corresponding code here: https://github.com/leezer3/OpenBVE/blob/master/source/RouteManager2/Events/Transponder.Types.cs

**Comment by leezer3** [comment]
Thanks.
[Technically, those I think are internally generated by the route parser]

I'll try and document those properly next week.
