### ISSUE TITLE
Track.stop is unresponsive by car number away from 'all cars'

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#804]
### Description

When we are Track.stop set, it does not respond even if car numbers are specified at a distance farther than 'all cars'.

Cases that work correctly:
When both numbers are in ascending order and all cars are at the farthest distance

Case that does not work:
1.Stop-not-work.csv
If 'all cars' are in front, .Stop(x;x;x;car no) beyond that will not respond.

2.Stop-not-work2.csv
The description order of the csv file is ascending order of car numbers. Only the distance of 'all cars' is just before.

3.Stop-not-work3.csv
The csv file's writing order is ascending order according to car numbers, only 'all cars' distance is the most of far away, but the writing order is the first.

Even the train.dat's #car section's NumberOfMotorCars and NumberOfTrailerCars set to any cars, route's stop distance is 100m.

I don't think there is any reason why 'all cars' must be the innermost, so I think it should be possible to set it anywhere.

Even if this is not the case, it will not work unless 'all cars' are specified in ascending order and the farthest distance.

### Reproduction

Please use this sample routes.
[Track_stop_issue.zip](https://github.com/leezer3/OpenBVE/files/9149091/Track_stop_issue.zip)

## Route

Please use this sample routes.

## Train

Use this zip's train or any.

## Logs

This issue is not output any logs.

### Related information 

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
Done some modifications to the search pattern, which I think will help.

It should now work in the following way:
1. If the number of cars is found, this should now be used wherever the stop point is located.
2. If the number of cars is **not** found:
    - When an all-car stop is present, this will be used unconditionally, wherever it is located.
    - If an all-car stop is not present, the stop list will be searched to find the closest number of cars **above** that of the player train. This stop point will be used,

**Comment by ginga81** [comment]
It's working fine!
thank you very much!
With this, the stop position of the Tohoku Shinkansen can be illuminated only where it corresponds in the animation!
It has been resolved, so close it.
7 cars
![Screenshot from 2022-07-31 06-55-13](https://user-images.githubusercontent.com/22734699/182001896-11ba190d-c2c8-40f5-a5a2-bcdf645db711.png)
12 cars
![Screenshot from 2022-07-31 06-58-18](https://user-images.githubusercontent.com/22734699/182001897-f1e899f3-0ab4-46e8-b522-2c820d1bafda.png)
16 cars
![Screenshot from 2022-07-31 07-04-26](https://user-images.githubusercontent.com/22734699/182001899-13da9d5b-dd98-4809-befd-714821d8f5b2.png)
17 cars
![Screenshot from 2022-07-31 07-11-15](https://user-images.githubusercontent.com/22734699/182001902-66ab732b-9ebb-400d-8d84-6e94797c6610.png)
