### ISSUE TITLE
Error on Windows install

### ISSUE THREAD

**Issue by HUN-Droid** [leezer3/OpenBVE#806]
### Description

I got an error while I install the game on Windows.
![kép](https://user-images.githubusercontent.com/47685838/184546357-1cd14305-bd8a-4b48-904d-1060097d008d.png)
The install is successful, and I can play without any known errors, after clicking OK on the error message.

### Reproduction

When I install the openBVE, I allways get this error. Uninstall, and then a new clear install, same thing. Newly installed windows, the same error. Always I get this error. If I remember correctly, this thing has been around since version 1.6.

### Related information 

* Operating system: Windows 10 21H2

**Comment by leezer3** [comment]
Can I have a setup log please?

Run the setup file as per this:
```
setup.exe /log=log.txt
```

File will be quite large, so might require zipping before attaching.

**Comment by HUN-Droid** [comment]
[log.txt](https://github.com/leezer3/OpenBVE/files/9333923/log.txt)
It is 400KB, so not a large file size :) I hope, it can help.

**Comment by leezer3** [comment]
```
2022-08-14 20:46:56.742   Dest filename: C:\Program Files (x86)\openBVE\NDP461-KB3102438-Web.exe
2022-08-14 20:46:56.742   Time stamp of our file: 2022-08-04 14:41:20.000
2022-08-14 20:46:56.742   Installing the file.
2022-08-14 20:46:56.755   Successfully installed the file.
2022-08-14 20:46:56.755   Exception message:
2022-08-14 20:46:56.755   Message box (OK):
                          Internal error: Expression error 'Runtime error (at 20:2939):
```


https://github.com/leezer3/OpenBVE/blob/master/installers/windows/openbve.iss#L210
It's attempting to install .Net 4.6.1 and the web installer is crashing when launched.

Can't think of an immediate reason for this (it's a plain Microsoft file), but can probably switch this so it's not called on later Windows versions.

**Comment by leezer3** [comment]
Still can't reproduce, however, the next release will have some more error checking going on in the installer. (aiming to put this out in a few days)

It will probably no longer show the message box (I've added various checks around this point), but an installer log would still be useful, as it might hopefully log what's actually going wrong now....
As another possible thought, I'm wondering if it was initally installed by a different user, and hence you've not got write priveleges in the settings folder or something :/

**Comment by HUN-Droid** [comment]
It is my personal PC, only I can access the PC. I have installed all the programs, the windows and all the stuffs. And yeah, I am administrator, and I granted the installer to do their stuff. So the access is possible, if I think correct.
Btw thanks for the bug fixing :)

**Comment by HUN-Droid** [comment]
The 1.8.4.1 installer works perfect, thanks @leezer3 !
I close this issue.
