### ISSUE TITLE
[Question] is texture that not in power of two is using more RAM/VRAM ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#808]
As the title said.

**Comment by leezer3** [comment]
Yes, absolutely.....

It's a fundamental mathematical principle, and is integral to the way computers work.
https://en.wikipedia.org/wiki/Power_of_two
https://www.katsbits.com/tutorials/textures/make-better-textures-correct-size-and-power-of-two.php

**Comment by adfriz** [comment]
Thanks leezer3
