### ISSUE TITLE
[Question] what value is the default camera in degree/FOV ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#809]
I just curious what the default value for in game camera in openbve ? How wide it is in mm and FOV ?

**Comment by ginga81** [comment]
Regardless of the software, I think it is difficult to calculate the viewing angle of the camera in terms of 35mm.
For example, can Unity produce such a value?
I don't think so.

**Comment by leezer3** [comment]
It's dynamically calculated based upon the screen aspect ratio:

Your defaut starting vertical viewing angle is 45 degrees, but this is affected by your camera zoom setting.
https://github.com/leezer3/OpenBVE/blob/master/source/LibRender2/BaseRenderer.cs#L887
https://stackoverflow.com/questions/56726176/is-glmperspectives-fov-parameter-defined-as-half-the-angle-of-the-field-of-vi

**Comment by adfriz** [comment]
> Regardless of the software, I think it is difficult to calculate the viewing angle of the camera in terms of 35mm. For example, can Unity produce such a value? I don't think so.

Well... i didn't know much about unity, but isn't game engine such as unity already have a feature to freely manipulate the camera properties?



> It's dynamically calculated based upon the screen aspect ratio:
> 
> Your defaut starting vertical viewing angle is 45 degrees, but this is affected by your camera zoom setting. https://github.com/leezer3/OpenBVE/blob/master/source/LibRender2/BaseRenderer.cs#L887 https://stackoverflow.com/questions/56726176/is-glmperspectives-fov-parameter-defined-as-half-the-angle-of-the-field-of-vi

Thanks leezer3
