### ISSUE TITLE
[Request] Make each Animated object in the nest have independent variables

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#815]
The variables of the Animated object are unified within a section (like a car, or one of the car's two bogies, or a coupler. recently added), This makes the movement of the multiple wheels in this part using the Animated object synchronised, but it doesn't have the linkage like the linkage that drives the locomotive.
Wish there was a switch to have an animation object have separate variables in the nest, which would allow for gaps in the animation of multiple objects in the same section. (The animation gap for each object is not noticeable, I really... request a feature for a little thing.)

Independent Variable Switch.animated
```
[Object]
IndividualSubject = True
```

This can be a lot of thinking about things like the location of objects...

**Comment by leezer3** [comment]
I think you're mis-understanding the way the current speedometer works, or your translation is missing something somewhere :)

We don't really have a concept of induvidual axles / speeds at the minute (another structural issue, but not one that's likely to be easily solved)
All cars have two 'axles', which define the two track based pivot points of the car.
The speedometer is calculated from the front axle of the car it is attached to.

A link-driven locomotive would by defnition have all wheels syncronised, as otherwise it'd tear itself apart.
If you're looking to have slightly non-synchronous wheels on a non-link driven locomotive consider adding / subtracting a small random value based upon speed to give your desired effect. I'd guess something along these lines as a starting point:
```
RotateXFunction = value + [delta * speedometer / RADIUS_OF_THE_WHEEL] + if[speed > 0 ,random[0, 0.0017 * [speed / 10]]  , 0]
```
(Untested, but would give something like 1/10th of a degree or so randomly added per frame at a reference speed of 36km/h)

**Comment by JunmoreHeavyBox** [comment]
I understand that a car has two bogies that each have their own speedometer variables, what I'm thinking is that assuming the bogie is also a car (bogies stacked with vehicles, like an 81XX train), the steering of this trolley The frame part uses a model of wheels. Such a bogie (actually a car) has its own speedometer variable for both wheels.

**Comment by leezer3** [comment]
As far as I can see what you're actually asking for is to get the speed of the wheel rotation, which only has a tangential relationship to the speedometer.

The current setup simply doesn't allow for this to be calculated, hence the standard formula uses the speedometer, and assumes that the wheel moves in tandem with the ground position.
Adhesion / wheelslip are handled internally by simply dropping the applied acceleration output, as opposed to true simulation of the wheel position.

Only way around this at the minute I think is something like the random formula I posted above. 

I've added two animated functions which may help a little with what you're trying to do:
**WheelSlip** returns 1 if the driver car is experiencing wheelslip.
**WheelSlip[Car]** returns 1 if the specified car is experincing wheeslip.

**Comment by JunmoreHeavyBox** [comment]
Thank you, I never thought about this random number function, mine would just use unadorned random numbers to make messy objects. I'm not very good at Animated functions, and I think this new variable might have some benefits for other developers.

Sorry to trouble you.

**Comment by JunmoreHeavyBox** [comment]
Still thinking about the motion function for my brake slip wheel spark...
Before updating this new variable, I got the slip state of the vehicle through this function.
```
(speedometer+(speedometer-speed)
Less[(speedometer-speed),SPEED-RATIO]
```

The WheelSlip variable is now the 01 switch, can it be changed to the speed difference?
It is replaced by `Less[(WheelSlip-speed),SPEED-RATIO]`

**Comment by leezer3** [comment]
The random function is already in the documentation (under numeric functions), and the new wheelslip function has also been added, although this will only be in the daily builds until the next release.
If possible, I'd suggest using the most compatible functions possible- Plenty of users are still using older versions unfortunately.

Unfortunately, we simply don't calculate the speed difference, hence why I've gone for the simple on / off state at the minute.

**Comment by JunmoreHeavyBox** [comment]
Can the train plugin consider getting the `WheelSlip` variable? Mathematically it shouldn't be necessary.
Now that there is this variable, there is room for manipulation.

**Comment by JunmoreHeavyBox** [comment]
in this question
A section uses an Animated object, and Animated acts as a container for more objects.
These things I have prepared should explain something.

This is a train using LOD Animated objects

https://user-images.githubusercontent.com/114210303/192902787-ce70c35e-9ae7-47f0-a881-e56d9a667b83.mp4

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

[Animated Independent Wheel.zip](https://github.com/leezer3/OpenBVE/files/9669305/Animated.Independent.Wheel.zip)

**Comment by leezer3** [comment]
Your sample is acting as I'd expect, although not as you'd like :)
The camera distance is calculated from the transformed child object's origin, not that of the root object. 

It really wants something closer to this in your root object:
```
[Variables]
0 = cameraDistance<50
1 = cameraDistance<30
2 = cameraDistance<10

[Object]
States = ModelCarF3.b3d,ModelCarF2.b3d,ModelCarF1.b3d,ModelCarF0.b3d
StateFunction = If[Variables[0],If[Variables[1],If[Variables[2],0,1],2],3]
Position = 0,0,-9
```
That could probably be added easily enough for single objects, but without a bunch of thinking about it, I'm not sure about passing them down a chain of animated objects.

**Comment by JunmoreHeavyBox** [comment]
- Getting an inch: the WheelSlip subject room for manipulation.

The Panel Animated object can now produce a wheel spin warning light, but the 2D Panel does not.

I think for most trains it would be sufficient to use only one condition.
Will there be abstract sand-filled containers in the future? I think this one condition is for that purpose.
Idea demonstration Sound.cfg
```
[WheelSlipSand]
SprinkleSand = Buzzer.wav
;Need to sprinkle sand to improve wheel adhesion.
```
In the event of a wheel slip alarm, the sound is cycled through the cab.

I came up with this idea because of LKJ's sound materials. These things I want to say should be done by the CTCS0-LKJ2000 train plugin. I don't care whether the plug-in exists or not. I want to mention this and increase the number of words.
Unimportant demonstration Sound.cfg
```
[ATS]
;[CTCS0_LKJ2000]
SLIP_POWER = 空转.wav
SLIP_BRAKE = 轮滑.wav
;Loop Playback
SLIP_POWER_ALARM = 注意手柄防溜.wav
SLIP_BRAKE_ALARM = 注意管压防溜.wav
SLIP_POWER_ACTION = 手柄防溜动作.wav
SLIP_BRAKE_ACTION = 管压防溜动作.wav
;Play once
```
