### ISSUE TITLE
Sounds (which are written into .animated file) cannot do playbacking if this .animated file is in another .animated file's [Include] section

### ISSUE THREAD

**Issue by BPI-919** [leezer3/OpenBVE#822]
### Description

Hi, I tried grouping the [Sound] sections of .animated file(s), for purpose to avoid "code" duplications and also to make the positioning of the sounds within a specific 3D-object me easier. However, I ran into a problem during this process: When it's time to playback, the sounds are not hearable.
Please let you read the information below for the details (which are in the Logs section).

Thanks,
Andrew

## Route

This is a WIP route (Suburban Railway Lines H8 and H9 in the agglomeration of Budapest - HU), it is not downloadable yet. However, I hope that the screenshots will help you to identify my problem.

## Train

It is not a train-specific issue. It occurs with any train.

## Logs

I attached 4 screenshots below:
- In the first one (This is the route file with .csv extension), in line 27, you can see how the second file (which is in the second screenshot) is be included into this one.
- In the second one (H8_Structure.include), in line 359, you can see how the third file (which is in the third screenshot) was declared to this one. Of course, it has been used in the With Track section too, it is believable without screenshot.
- In the third one (This is the main .animated file, which collects the related .animated-s - I wish it could be worked properly...), in lines 2 and 3, you can see how the fourth file (which is in the fourth screenshot) was included to this one.
- In the fourth one (This contains an [Object] section with an "empty" object file and also contains 3 [Sound] sections. The 3 [Sound] sections include the sounds, with the appropriate path. I actually put an [Object] section at the beginning of the .animated file, in matter from this step, I hoped the sounds would be played in the game properly, but unfortunately I didn't hear them...), you can see the "invisible" .b3d file and the 3 problematic [Sound] sections.
Interestingly, if I move any sound (section) into the parent-animated (in which you can find this one by an [Include] section, in this case the parent-animated is: "peron_orskoz.animated"), OpenBVE plays this sound, properly. In the same "session", unfortunately, the other sounds (which stayed at the same location) could not be heard when it was the time to play the sounds.

### Related information 

My PC:
- Name: ASUS K401LB (notebook / Laptop computer)
- OS: Windows 10 Home 64 bit 21H2
- Memory: DDR3L 8 GB (4 GB + 4 GB)
- 1000 GB SSD (C:) + 24 GB SSD (D:)
- Intel Core i5-5200U CPU @ 2.20 GHz
- Intel HD Graphics 5500 & NVIDIA GeForce 940M

OpenBVE Version:
Latest Stable: 1.8.4.2 64-bit (2022.09.10.)
![kép](https://user-images.githubusercontent.com/66689434/195995446-6deed9d5-f34c-4712-9ff7-b67aee0bf009.png)
![kép](https://user-images.githubusercontent.com/66689434/195995453-dc599637-c009-44db-87ec-7db8f2780e6d.png)
![kép](https://user-images.githubusercontent.com/66689434/195995460-38459d94-c422-4e74-95c3-1d29c81979fc.png)
![kép](https://user-images.githubusercontent.com/66689434/195995468-e9f1ca36-b58f-4099-b95a-f5ea148598b8.png)

**Comment by BPI-919** [comment]
![kép](https://user-images.githubusercontent.com/66689434/199099371-9cf40c58-769f-4e7d-9d6c-826333e528ae.png)
![kép](https://user-images.githubusercontent.com/66689434/199099470-242d5976-d6bd-4fb0-8de0-1f574179f46d.png)
I think I solved this problem, however I could not push it... :/ Can I get permission? O..O

**Comment by leezer3** [comment]
You need to fork yo your githhub account, add that as a remote, then PR from there :)

**Comment by leezer3** [comment]
Looking at what I think you've done, the sound probably wants cloning, not copying.

IIRC the sound class is a reference type, and that'd mean the soundsource would be shared between all instances, which would in turn probably mess up things if multiple copies are in audibility range.

**Comment by BPI-919** [comment]
Does not my code going to be good like this now? :/ In fact, I was a little surprised when I heard my "solution" works. :D 
During the coding I also used currentHost.AddMessage, but finally I got rid of that.
