### ISSUE TITLE
[Question] is Openbve will use RAM if the VRAM full ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#823]
is Openbve will use RAM if the VRAM full ?

I haven't try it though, im very cautious because my pc only had 1GB of vram 😅 i dont want something bad happend.

**Comment by Lastorder-DC** [comment]
1GB VRAM should be enough to run most of routes.

**Comment by adfriz** [comment]
Yeah you right, i havent ecounter any out of memory error even with pretty dense route and trains, i just curious though if openbve will use ram when vram full or it will crash or the OS will manage it to use the ram.

**Comment by leezer3** [comment]
Yes, although it doesn't exactly work like that....

The graphics driver will swap out to system memory, but it might also unload textures to disk.
Remember that the on disk size bears no relation to VRAM size / use.
