### ISSUE TITLE
train.xml Notch Description bug/suggestions

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#826]
### Description

Currently for whatever reason, the notch description (brake) in train.xml is shifted by one
For example:
```
<NotchDescriptions>
	<Power>0°;10°;15°;20°;25°;30°;35°;40°;45°</Power>
	<Brake>0°;10°;15°;20°;25°;30°;35°;40°;45°</Brake>
</NotchDescriptions>
```

The `N` notch would be 0°, `B1` however will be **15°** rather than **10°**.
I have to insert another `0°` like this to work properly:
```
<NotchDescriptions>
	<Power>0°;10°;15°;20°;25°;30°;35°;40°;45°</Power>
	<Brake>0°;0°;10°;15°;20°;25°;30°;35°;40°;45°</Brake>
</NotchDescriptions>
```

Another suggestion is if it's possible for the EMG notch to also have a notch description?
Currently the Emergency Brake shows **0°**, my idea is have 7 brake notches (0° - 40°), then the 45° is displayed when Emergency Brake is applied

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Train

[Train.xml.txt](https://github.com/leezer3/OpenBVE/files/9893174/Train.xml.txt)
(Get rid of the .txt extension)

### Related information 

* Operating system: Windows 10 22H2
* Method of control: Keyboard

**Comment by JunmoreHeavyBox** [comment]
I had this problem and then concluded this list after testing.
`EB,B0,B1,B2,... ,Bn-1`
Although it looks a bit awkward when writing the handle angle.

**Comment by Kenny-Hui** [comment]
> I had this problem and then concluded this list after testing. `EB,B0,B1,B2,... ,Bn-1` Although it looks a bit awkward when writing the handle angle. You should adjust the position of `45°` in the list.

Thanks, didn't know how I overlooked this

**Comment by JunmoreHeavyBox** [comment]
@leezer3 I have a request for something to be added to the development documentation.

**Comment by leezer3** [comment]
Sure, what exactly?

**Comment by JunmoreHeavyBox** [comment]
As stated in the question. I would like to add the information NotchDescribed.

**Comment by JunmoreHeavyBox** [comment]
> Sure, what exactly?

In detail. I originally mentioned the lack of NotchDescriptions in some of the documentation in Issue 821, No. 12. I was adding issues to the comments revision and didn't realise you hadn't read. silly me.

> 12. The development documentation for NotchDescriptions does not contain a reference list of the relationship between the list positions and the handle notches.

**Comment by JunmoreHeavyBox** [comment]
@leezer3 Excuse me.

> In detail. I originally mentioned the lack of NotchDescriptions in some of the documentation in Issue 821, No. 12. I was adding issues to the comments revision and didn't realise you hadn't read. silly me.
> 
> > 12. The development documentation for NotchDescriptions does not contain a reference list of the relationship between the list positions and the handle notches.

I don't know your reading habits.
I want to use @ as little as possible, and reduce or even not repeat comments. (^_^)

**Comment by leezer3** [comment]
Its on the list to get to.

**Comment by JunmoreHeavyBox** [comment]
Thanks you for adding the documentation.
I've looked at it and the brake handle part looks a bit inaccurate.
`EB,8,7,6,5,4,3,1,HLD,N`
In actual use it should be
`EB,N,HLD,1,2,3,4,5,6,7,8`


 - Here are some additional documents that can be adopted.
Trains using three-stage pressure automatic air brakes.
`EMG,REL,LAP,SRV`
The brake handle and loco brake handle can be used either way, depending on the brake type and loco brake type used on the train.
Reversing handle.
`N,F,R`

**Comment by JunmoreHeavyBox** [comment]
@leezer3 Have a look at the previous comments. Corrections and additions to the reference list regarding notch descriptions.

**Comment by JunmoreHeavyBox** [comment]
@leezer3 Excuse me, once again. Look at the comments.
Comments on changes to the notch description document.

**Comment by JunmoreHeavyBox** [comment]
Thank you Leezer3!
The problem completely solved in the documentation.
