### ISSUE TITLE
[Bug] Game keeps crashing when I move the camera

### ISSUE THREAD

**Issue by SavageKris4851** [leezer3/OpenBVE#834]
### Description

Currently on version 1.8.4.2 for OpenBVE. When I move the camera angle in-game, the game immediately crashes.

### Reproduction

Moving the camera angle in any way.

## Route

Any route

## Train

Any train

## Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/10027044/log.txt)
[OpenBVE Crash- 2022.11.16[20.32].log](https://github.com/leezer3/OpenBVE/files/10027047/OpenBVE.Crash-.2022.11.16.20.32.log)

### Related information 

* Operating system: Windows 10
* Method of control (Keyboard, joystick, RailDriver): Keyboard + Mouse

**Comment by leezer3** [comment]
I believe that to be fixed in the current daily build.

(It's a side effect of you having the camera move key set to H, which is also mapped to headlights)
