### ISSUE TITLE
ObjectBender not run at Linux?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#838]
### Description

When  I run the ObjectBender.exe, get this error and can't create.

Could not load file or assembly 'OpenBveApi, Version=1.5.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. ファイルが見つかりません。

Is this error by my fault?

I am using ObjectBender what the OpenBVE is 1.8.4.3's one.

### Related information 

I am using by wine, and create .bat file and run ObjectBender.exe.
such as
wine cmd < "./bat&sh/railmakeL.bat"

railmakeL.bat
".\ObjectBender.exe" .\csvs\RailShinkansen5m-Dark.csv .\makerails\dark\SR300LD.csv -n=5 -s=5 -b=25 -r=-300 -g=1435 -u=0 -v=0

My PC's spec:
OS:Ubuntu 20.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.11.0-40-generic, LLVM 12.0.0)

**Comment by leezer3** [comment]
Have you copied the file somewhere else?
Your error suggests so.

It expects to be in the main OpenBVE folder, as it uses some of the API libraries.

**Comment by ginga81** [comment]
Also
'Copying the OpenBveApi.dll alongside ObjectBender.exe will probably work if this is the case.'
could done!
Thank you very much!
