### ISSUE TITLE
[BUG] Object based background only works in old renderer

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#842]
### Description

as title said

### Reproduction

just use the object based background (try the object on #841 )

## Route

tested on demo route

## Train

any

## Logs

no crash no logs

### Related information 

* Operating system: windows 10
* Method of control (Keyboard and mouse)
* openbve : 1.8.4.2 and 1.8.4.3 main program and route viewer

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/781a9f303f1b29b978b52cb24593da886908086d

That's really odd, reversing that fixes the issue :/
If anything that should have the opposite effect.

**Comment by leezer3** [comment]
Fudge, of course....
The background is rendered in screen space, not camera space, hence the overload.
