### ISSUE TITLE
Opening OpenBve issue

### ISSUE THREAD

**Issue by hope332** [leezer3/OpenBVE#843]
I don't know why but every time I tried to open bve it's saying “OpenBVE” cannot be opened because the developer cannot be verified. I don't know what to do or how to fix this problem.

**Comment by leezer3** [comment]
I'm presuming you're on an Apple Mac?

https://www.lifewire.com/fix-developer-cannot-be-verified-error-5183898

Essentially, Apple charge a not insignificant amount for a code-signing certificate to bypass this.
Unfortunately, we're a relatively small open-source project.
