### ISSUE TITLE
[Question] which method is better for this mesh ?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#845]
hello

i have an object that contain electrical mesh for my trains that need duplicated in several position, in 1 car we must have 5 electrical components.

i curious which method should i use for the best performance, the object has 150 faces with 1 256x256 px jpg texture, the object is static.

method 1: export as 1 continuous mesh data in 1 b3d file (1 meshbuilder section is contain 5 duplication and 1 load texture command)
method 2: export separately to each meshbuilder section but combined in 1 b3d file (5 meshbuilder section, 5 load texture command)
method 3: same as method 2 but each 1 meshbuilder is for 1 b3d file so we have 5 separate b3d file.

im going to reference the b3d to each car .animated file using [include] command, which one should i use??

**Comment by leezer3** [comment]
Essentially, 1 and 2 will be optimised internally to be identical.

3 is likely to be marginally slower, but not much.

For 150 faces with the same texture, it's not especially worth worrying about.
You need to eliminate texture switches and transparency for any really meaningful effect on more modern computers.

**Comment by adfriz** [comment]
Understandable, thanks leezer3
