### ISSUE TITLE
Plugin Backwards Compatibility

### ISSUE THREAD

**Issue by markthree** [leezer3/OpenBVE#85]
Hello, plugins from openBVE 1.4.2 do not seem backwards compatible with openBVE 1.5 RC5.

I was looking forward to using 1.5's features for my routes, but the loading screen sends me back to the main menu.

**Comment by leezer3** [comment]
Any chance of a train link please?

Some versions of OS_ATS are unreliable, but other than that it ought to be
OK.

Other than that:
In the bottom left corner, you should also see a link to report problems.
Please try running something that doesn't work and then posting the zip
file this creates. (This contains the last log file, and the log it
hopefully generated when it crashed)

**Comment by markthree** [comment]
Thank you for your swift reply.  I could not find the .zip, but I have two logs.

`openBVE Log: 08/13/2016 02:54:39 PM

The train plugin YUSOdakyufanAts.dll caused a critical error in the route and train loader: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
`

and here is the crash log

`08/13/2016 02:54:58 PM
OpenBVE 1.5.0.5 Crash Log
Program is running on the Windows backend
Current screen resolution is: Windowed 856px X 480px 
Current routefile is: C:\Program Files (x86)\OpenBVE 1.4.2\Userdata\LegacyContent\Railway\Route\TTC Routes\Bloor-Danforth Line\v2.0 Routes\Bloor-Danforth Westbound v2.0 Non-TR.csv
Current train is: C:\Program Files (x86)\OpenBVE 1.4.2\Userdata\LegacyContent\Train\Toronto Subway T1 YUS B6 sounds\front YUS
Current train plugin is: YUSOdakyufanAts.dll
The current train plugin caused the following exception: 
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at Plugin.TTCAcademy.LoadForm()
   at Plugin.TTCAcademy..ctor()
   at Plugin.Train..ctor(Int32[] panel, PlaySoundDelegate playSound)
   at Plugin.Plugin.Load(LoadProperties properties)
   at OpenBve.NetPlugin.Load(VehicleSpecs specs, InitializationModes mode)
   at OpenBve.PluginManager.LoadPlugin(Train train, String pluginFile, String trainFolder)
   at OpenBve.PluginManager.LoadCustomPlugin(Train train, String trainFolder, Encoding encoding)
   at OpenBve.Loading.LoadEverythingThreaded()
   at OpenBve.Loading.LoadThreaded()
Current program memory usage: 189.05mb
System memory free: 6566mb
`
The train is being uploaded, and will be available in 15-30 minutes.

**Comment by markthree** [comment]
Here is the train I am using. Download via Google Drive.

https://drive.google.com/file/d/0B22vFMv-zxKOSlZEOTJSRmRNQmM/view?usp=sharing

**Comment by leezer3** [comment]
Thanks, I'll download & take a look in the debugger, but will probably be
tomorrow or Monday now as I'm at work.

From the log, it looks like the train is attempting to connect to the
internet/ spawn a browser, which doesn't like the fact that the threading
in the loader has been fixed.
Probably a plugin bug, but I'm sure we can get this fixed :)

**Comment by markthree** [comment]
Something similar to that, the application freezes when launching that in fullscreen mode in openBVE 1.4.2. I'
![image](https://cloud.githubusercontent.com/assets/20269990/17645259/58a1e388-616e-11e6-8c62-ffa9d9366c7f.png)

**Comment by leezer3** [comment]
Your zip isn't public, so I've asked it to give me access, think it's sending you a mail.

From a quick dig in the plugin source for the two I can find in this thread ( http://t2pfilms.ca/forum/index.php?topic=599.0 ), you're downloading sounds from your site under certain conditions, and also triggering a web-browser to login on init.

Doing it this way is going to be problematic to say the least; The sim was never designed with this sort of thing in mind.
According to the specs, any plugin should be able to be loaded in any thread without user interaction, and they should handle threading properly.

I'd suspect that adding the **[STAThread]** property to the methods which launch the downloading and webrowser will probably solve your problem, but I can't do anything without proper source code to your plugin. (Viewing in the decompiler shows me the problem, but doesn't let me rebuild or actually step it in the debugger)

**Comment by leezer3** [comment]
Secondary notes:
I tried something essentially along these lines in BVEC_ATS (The Advanced Driving window)
This works OK on Windows, but has massive problems under anything else.

I'm happy to work with the train developer to provide some official API methods of retrieving a file from a URL, but the login would need to be separated from the main program, sorry- Mixing Winforms and OpenGL windows just isn't reliable enough.

**Comment by markthree** [comment]
https://drive.google.com/file/d/0B22vFMv-zxKOSlZEOTJSRmRNQmM/view?usp=sharing

updated

**Comment by markthree** [comment]
I think I accidentalyy

**Comment by leezer3** [comment]
Got it, thanks.

It's the same issue as the two I linked above, and will require the plugin developer to fix it at their end, or for me to implement the HTTP file fetching properly in the API.

Please ask them to drop me a mail or drop into this topic and I can help them sort it out.
