### ISSUE TITLE
[Question] Untranslated item in Train Editor 2

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#860]
### Description

I have found some untranslated items, even though I have added translations to the translation file. There are also untranslated items that are not in the translation file.
Sorry there are a bit too many pictures.

Panel settings section
![驾驶室部分](https://user-images.githubusercontent.com/114210303/215814371-337632af-4795-4625-8a69-3f98a0ab6dda.png)

Sound settings section
![声音引用部分](https://user-images.githubusercontent.com/114210303/215814637-ec545f61-bbbb-4baa-8d5b-468b21b4a869.png)

Some small things
![小地方1](https://user-images.githubusercontent.com/114210303/215814707-e707d3e2-9aeb-4281-ba20-e2fddd114fdd.png)
![小地方2](https://user-images.githubusercontent.com/114210303/215815385-9485a679-1784-4660-be42-ff9247e1a016.png)

Things that are not in the translation file.
1. The Electric Brake in the Delay section of the Car settings tab and the Output button in the Status tab.
![翻译文件中没有1](https://user-images.githubusercontent.com/114210303/215810177-a8ac33d3-8fd2-4337-9c97-63c3bcd4eec0.png)
2. Delay set window of the Car settings tab.
3. The Panel settings tab's Subject window.
4. Touch Element window in the Touch section of the Panel settings tab.
![翻译文件中没有2](https://user-images.githubusercontent.com/114210303/215812595-f16e62a9-aa04-453f-9f72-9779754e90b6.png)
5. Import and Export window.
![翻译文件中没有3](https://github.com/leezer3/OpenBVE/assets/114210303/46810b17-2e5f-414e-8234-abd8e3060d3c)

Only because I was not comfortable with the incomplete translation of Train Editor 2, I did some "Chineseization", mainly by copying existing translations and fixing the machine translation.
I have no intention of contributing to the translation.

### Reproduction

[Test_zh-CN_TrainEditor2.xlf.txt](https://github.com/leezer3/OpenBVE/files/10548240/Test_zh-CN_TrainEditor2.xlf.txt)
This is a sample of my abridged version of the Chinese translation file, please only use it in Train Editor 2.
Using the translations in Train Editor 2 with recognisable differences but all covered should reproduce the problems in the screenshots.

**Comment by JunmoreHeavyBox** [comment]
@leezer3 I've always cared about it, please deal with it.

**Comment by JunmoreHeavyBox** [comment]
Urge and Opinion

**Comment by leezer3** [comment]
Done a bunch of them, will try and look at the rest.

**Comment by JunmoreHeavyBox** [comment]
I made a file to try.
[TE2TranslateTest.ZIP](https://github.com/leezer3/OpenBVE/files/13446752/TrainEditor2TranslateTest.ZIP)

**Comment by leezer3** [comment]
I think that's everything in your file.

Please check that nothing is now unexpected, as it's very hard to cross-check something in chinese.

**Comment by JunmoreHeavyBox** [comment]
Sigh, all right. The translation worked fine, except for the ("this", "centre", "name") part and the ("timetable", "location") part that got deleted by mistake.

**Comment by JunmoreHeavyBox** [comment]
This thing isn't over yet. Here's a file to try. No surprise this should be the last.
[TrainEditor2MoreTranslateItem.ZIP](https://github.com/leezer3/OpenBVE/files/13466177/TrainEditor2MoreTranslateItem.ZIP)

**Comment by leezer3** [comment]
Added, along with a couple of others.
Have however moved the messages to a slightly better place in the translations file.

Please consider trying a pull request though. It's a *lot* easier to manage things this way than me merging it manually across a bunch of files....
