### ISSUE TITLE
Error - "An unhandled Windows Forms Exception occured" when installing package

### ISSUE THREAD

**Issue by eldomtom2** [leezer3/OpenBVE#861]
### Description

When I try to install a package through the package management menu, this error immediately appears.

## Logs

[openBVE Bug Report01_02_2023.zip](https://github.com/leezer3/OpenBVE/files/10556783/openBVE.Bug.Report01_02_2023.zip)

### Related information 

* Operating system - Windows 7 64-bit

**Comment by leezer3** [comment]
Second report of this....
https://github.com/leezer3/OpenBVE/issues/859

I can't explain this at the minute- It thinks the background thread used for packages is busy, but I can't reproduce.
I have made a change in the latest nightly build to check for this condition, but something funny is happening. I'll try a Windows 7 box later.
