### ISSUE TITLE
[Bug] Freeze when loading 3d object other than csv while using ScaleFunction in animated files.

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#870]
### Description

Program freeze and not responding if try loading an animated file that reference mesh file as .obj that have ScaleFunction command in it.

### Reproduction

Create .animated file, reference an .obj file either using [Object] or [Include] command, add ScaleFunction below it, test it in object viewer.

## Route

No route
## Train

No train

## Logs

Sorry i forgot it.

### Related information 

* Operating system : windows 10 21h2
* Method of control : keyboard and mouse
* openbve: 1.8.4.4 instaler version

Note: 
i have not try it on main program, you can try the .obj object i attached from my other issue.
This bug actually i encounter several days ago but i just remembered to report now 😅. 
Maybe i can try reproduce it on next couple days if i not forget it.

**Comment by leezer3** [comment]
Works just fine for me I'm afraid- Please can you try again and see if you can reproduce?

The function you're trying might also be interesting.

**Comment by Kenny-Hui** [comment]
There's only `ScaleXFunction`, `ScaleYFunction` and `ScaleZFunction`, are you sure it's typed correctly?
I noticed that the sim will freeze when there's any animated function that is not recognized.

We should've incremented `i` here before continuing,  otherwise it will be stuck in the loop.
https://github.com/leezer3/OpenBVE/blob/b00cc373e015ffe5aa78f6bc954e7091b8223b70/source/Plugins/Object.Animated/Plugin.Parser.cs#L231-L235

**Comment by adfriz** [comment]
@leezer3 
here the file 
[test.zip](https://github.com/leezer3/OpenBVE/files/10975648/test.zip)

I only write `scalexfunction = 2` 

Tested in object viewer 1.8.4.4 both installer and portable version, when drag & drop the animated file to object viewer it suddenly freeze and not responding, maybe a memory leak ??

But when i test in object viewer 1.9.0.0 portable ver its worked perfect fully no freeze at all 😀

**Comment by adfriz** [comment]
should i mark this issue as solved ??

**Comment by leezer3** [comment]
Things make a little more sense now.

1.8.4.4 doesn't have the ScaleFunctions, hence the bug found by KennyHui freezes it.
I've fixed that, and the animated parser will now skip unknown sections properly (as opposed to returning nothing, which was the intended prior behaviour)
