### ISSUE TITLE
Objects don't show when we changes the camera at 1.9.0.0.

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#872]
### Description

When we are driving, we changes camera, the objects don't show.
case 1:when press F2, backward's objects don't show such as bellow.
if we press the car no change key(default 1 and 7 numkey), resume show all objects.
If nothing to do, the forward objects flows to back, finally, all objects are shown.
This isn't happen when we are jumping station.

![Screenshot from 2023-03-14 23-48-00](https://user-images.githubusercontent.com/22734699/225048474-32f69bd4-1d31-48f0-a023-dfef300fbc88.png)

case 2:when press F4 and the camera pans to forward automatically, the objects aren't show such as bellow.

![Screenshot from 2023-03-14 23-48-49](https://user-images.githubusercontent.com/22734699/225048513-8cb375d4-a8e2-48ce-8eca-3f54bd361a64.png)

### Reproduction

This happens maybe all route.

## Route

This happens maybe all route.

## Train

This is happens maybe default gray box cars.
But, need the outer-views for better.

## Logs

This issue don't crash.
So, no logs.

### Related information 

My PC's spec:
OS:Ubuntu 22.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (polaris10, LLVM 15.0.6, DRM 3.47, 5.19.0-35-generic) (0x67df)

**Comment by leezer3** [comment]
I wish people would report these before I push out a release, not an hour afterwards :)

I think I can reproduce, and this appears to be being caused by program (as opposed to user) generated camera angle movements, with no position movement.

Please see if this build corrects the issue:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2023-03-14.zip

**Comment by ginga81** [comment]
I think fixed!
Thank you very much!
Please close this.
I'm currently in the process of making Series-E7 and from Tokyo to Omiya.
So, I can't always for testing.
The official release is always suddenly, and not annouce before, so I also this time I recognized this bug when I played after knowing the release.
If possible, I would appreciate it if you could put a cushion on Release Candidate etc. and let me know before the official release.
