### ISSUE TITLE
[Bug] Transparent texture overlapping causes issues

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#879]
### Description

Didn't look into the exact detail yet, but there will be sort of a "dithering" pattern if you put a semi-transparent face on top of another semi-transparent face.

### Reproduction
1. Launch Object Viewer
2. Load the Object
3. Move your camera around the face colored red (That face has an alpha value of 254)
4. If successful, you will get results similiar to the following:
![image](https://user-images.githubusercontent.com/28094366/227482610-5f15ece8-ef51-4cf1-8cd7-462d7d0c411f.png)

## Object
[repo.zip](https://github.com/leezer3/OpenBVE/files/11060537/repo.zip)

### Related information 

* OpenBVE Version: Latest Nightly (2023-03-23)
* Operating system: Debian 12 Bookworm
* Method of control: Keyboard

**Comment by leezer3** [comment]
![142](https://user-images.githubusercontent.com/7688245/227491175-ddf5e850-edf5-4c63-b60d-8fbeab2b1f6e.jpg)

First observation is that it doesn't appear to have ever worked properly. This is from Michelle's last build.
Viewing one transparency through another is a PITA. These are close enough and in the same object that its always going to be messy.

Interestingly, the current GL1.2 renderer is nearly right:
![gl12](https://user-images.githubusercontent.com/7688245/227492381-4d8dfe76-954e-4d3b-a651-ceaa7f220c17.jpg)

I can't see an immediate cause for the haloing, so this may be an artifact of the GL blend-mode settings.

**Comment by leezer3** [comment]
Minor observation, which won't be helping:
We're putting the front face into the opaque list. It should be in the transparent list.

**Comment by leezer3** [comment]
Please try the new build.

I think I've found this. I'm not especially happy, but I can't find anything else bust as a result.

**Comment by Kenny-Hui** [comment]
Doesn't seems to resolve it.
The above bug where the face behind is completely transparent is because of Transparency Quality set to Sharp.
(Could be a bug, but either way it never worked properly and players are encouraged to use Smooth Transparency Quality)

p.s. This bug started appearing in 2023-03-15 nightly build, 2023-03-14 worked fine.

**Comment by leezer3** [comment]
Ah, another issue entirely :/

Partially reverted that- I see what's happened, and let's see whether that's any better.

**Comment by Kenny-Hui** [comment]
Fixed as of the latest build, thanks.
