### ISSUE TITLE
[Bug] Crash when restoring camera while viewing on non-cab car

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#880]
### Description

OpenBVE will crash if you switch to a car that is not the cab's car on exterior view, then switch back to the cab.

### Reproduction

1. Open any route and train that has multiple cars
2. Go to F2, switch your camera to cars other than the cab's car (Usually the first car) (Numpad 1/7)
3. Press F1 to return to cab
4. Witness crash

## Route

Any.

## Train

Any.

## Logs

[log.txt](https://github.com/leezer3/OpenBVE/files/11064759/log.txt)
[OpenBVE Crash- 2023.3.25[01.05].log](https://github.com/leezer3/OpenBVE/files/11064760/OpenBVE.Crash-.2023.3.25.01.05.log)

### Related information 

* OpenBVE Version: Latest Nightly
* Operating system: Debian 12 Bookworm
* Method of control: Keyboard

**Comment by ginga81** [comment]
I did the same with 1.9.0.1 and it indeed crashed.

>2023/3/26 19:12
>OpenBVE 1.9.0.1 Crash Log
>Program is running on the Linux backend
>Current screen resolution is: Windowed 960px X 600px
>Current routefile is: /home/user/デスクトップ/東北新幹線テスト用/v1.00/Railway/Route/とーほぐ新幹線v1.00/A0直線デモルート (左側光源).csv
>Current train is: /home/user/デスクトップ/東北新幹線テスト用/Train/A_Tec_E6E5full(outer) へのリンク/Tec_E6
>Current train plugin is: BVEC_ATS.dll
>1 file(s) not found
>37 error(s)
>The current routefile caused the following exception:
>System.NullReferenceException: Object reference not set to an instance of an object
>  at OpenBve.MainLoop.RestoreCameraSettings () [0x000e7] in <7388252d63624f6fb83c63b45e2f8bd3>:0
>  at OpenBve.MainLoop.ProcessControls (System.Double TimeElapsed) [0x01a57] in <7388252d63624f6fb83c63b45e2f8bd3>:0
>  at OpenBve.OpenBVEGame.OnRenderFrame (OpenTK.FrameEventArgs e) [0x002e4] in <7388252d63624f6fb83c63b45e2f8bd3>:0
>  at OpenTK.GameWindow.OnRenderFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <13d03852c6254f51840d199e801a688e>:0
>  at OpenTK.GameWindow.RaiseRenderFrame (System.Double elapsed, System.Double& timestamp) [0x0000c] in <13d03852c6254f51840d199e801a688e>:0
>  at OpenTK.GameWindow.DispatchRenderFrame () [0x00038] in <13d03852c6254f51840d199e801a688e>:0
>  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x00104] in <13d03852c6254f51840d199e801a688e>:0
>  at OpenTK.GameWindow.Run () [0x00000] in <13d03852c6254f51840d199e801a688e>:0
>  at OpenBve.MainLoop.StartLoopEx (OpenBve.LaunchParameters result) [0x001fc] in <7388252d63624f6fb83c63b45e2f8bd3>:0
>  at OpenBve.Program.Main (System.String[] args) [0x0061d] in <7388252d63624f6fb83c63b45e2f8bd3>:0   at System.Environment.get_StackTrace () [0x00000] in <de882a77e7c14f8ba5d298093dde82b2>:0
>  at OpenBve.Program.Main (System.String[] args) [0x00000] in <7388252d63624f6fb83c63b45e2f8bd3>:0
>Current program memory usage: 730.29mb
>System memory free: 0mb

**Comment by ginga81** [comment]
I tested the daily build and it was fixed.
Thank you very much for fix!
Please check if there is no problem with @Kenny-Hui's environment, and if it is okay, please close it.

**Comment by Kenny-Hui** [comment]
Fixed, thanks.

**Comment by ginga81** [comment]
@Kenny-Hui 
Please close this.

**Comment by Kenny-Hui** [comment]
I believe the issue has already been closed?
