### ISSUE TITLE
TE and TE2 won't open

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#881]
### Description

Title

## Logs

> errors_filesystem_invalid
![TEIssue](https://user-images.githubusercontent.com/114210303/227946997-75bec6e8-3fa1-4ac2-b99c-945230e64834.png)

### Related information

* OpenBVE Version: 
DailyBuild 2023-03-23 - 2023-03-26

**Comment by leezer3** [comment]
Now that's odd.
Does the main program work?

It's failing to find the required DLLs, translations etc. 
The filesystem is our internal resolver for those.

**Comment by JunmoreHeavyBox** [comment]
This is only the case with TE and TE2, all other are fine.

**Comment by JunmoreHeavyBox** [comment]
Tested, the issue started appearing in the daily build 2023-03-19.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/f676c6d229122f36778facdf455a2d0f10338749

Now that's interesting.
I added a specific exception where an empty path was supplied, as opposed to waiting for the generic one. I can't think why we'd be deliberately hiding the generic one only, but will try and take a proper look tomorrow.

**Comment by JunmoreHeavyBox** [comment]
Fixed thanks! (^∪^)

Just another problem with TE2.
I obviously have TE2 turned off, but I can still see it in Task Manager, and I have to be in Task Manager to actually turn it off...
