### ISSUE TITLE
Minimizing all windows will cause the game to crash

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#883]
### Description

This will only happen if the game is in progress.

## Logs

[openBVE Crash.log](https://github.com/leezer3/OpenBVE/files/11113747/openBVE.Crash.log)
[openBVE Crash x32.log](https://github.com/leezer3/OpenBVE/files/11114060/openBVE.Crash.x86.log)

### Related information 

* openBVE version: DailyBuild-2023-03-28
* OS: Windows 7

**Comment by leezer3** [comment]
This crash is inside the Intel integrated graphics drivers, and not something I think we can do anything about. 
I can find reports elsewhere of Minecraft doing the same, which suggests its not anything we do.
Certainly doesn't happen here :/

GL1.2 might help if you're not using it already.

**Comment by JunmoreHeavyBox** [comment]
I got it...
