### ISSUE TITLE
Game crashes when switching camera

### ISSUE THREAD

**Issue by AwardedStatue97** [leezer3/OpenBVE#884]
### Description

When switching cameras away and back, the game crashes (Happens on every route or train for me)

## Logs

[openBVE Bug Report02_04_2023.zip](https://github.com/leezer3/OpenBVE/files/11131171/openBVE.Bug.Report02_04_2023.zip)

**Comment by ginga81** [comment]
In the log, you are playing 1.9.0.1.
This issue is fixed at 1.9.0.2,
https://github.com/leezer3/OpenBVE/issues/880
Please try 1.9.0.2.

**Comment by leezer3** [comment]
Should be fixed in public 1.9.0.3, so closing this.
