### ISSUE TITLE
Texture rendering issue in Object Viewer

### ISSUE THREAD

**Issue by BPI-919** [leezer3/OpenBVE#885]
![kép](https://user-images.githubusercontent.com/66689434/230466646-4f07b846-b46a-44f1-80d7-eacc5897177e.png)
![kép](https://user-images.githubusercontent.com/66689434/230466807-fd1b94b3-c731-4a40-8ac8-f5706ce41bd6.png)

I use the latest version of OpenBVE (1.9.0.3). My OS is: Windows 11 64-bit 22H2.

When I wanted to open an .animated file, which includes 8 pieces of .b3d object: 4 pieces from the Kobanya-Ujpest.b3d and 4 pieces from the Ujpest-Kobanya.b3d , I faced that the objects and the textures are not rendered properly.
For the .b3d object files I use .png texture format, and I also use a Transparent color. The size of the 2 pieces (1 + 1) of textures are: 16538px * 1775px, and 1.57 MB.

It is very interesting, that when I try to load this .animated file, sometimes it loads properly, sometimes it doesn't, and in that case when it doesn't, sometimes I get 2 error messages, but sometimes I don't get any error messages...

In this example, you can see the 2 error messages. The first message tells us that there are not enough memory to load the texture file, but when I open the Windows task manager, I see that the memory should be enough to display the textures. So I can only think that there aren't enough allocated space / allocated memory for this texture rendering.

Could someone take a look at of this kind of issue, please?

Thanks,
Andras

**Comment by leezer3** [comment]
That's an insane size texture, and I'm not at all surprised something is overflowing somewhere.
The PNG decoder will need memory, and the texture in memory is probably going to take the better part of 500mb+ (not trying to calculate powers of 2 on the phone...)

I'll take a look, but you should seriously consider downsizing the texture considerably.
Anything above 4096px a side is realistically going to be oversize, and I don't want to guarantee what results you're likely to get.

**Comment by BPI-919** [comment]
![kép](https://user-images.githubusercontent.com/66689434/230481529-0fa0f492-ab46-4b3c-a060-978cce1f80c9.png)
It is loading successfully at this moment... And it can... 

![kép](https://user-images.githubusercontent.com/66689434/230481804-741baffa-d622-444c-bd4d-1b75cbdfe552.png)
Memory also enough.

**Comment by leezer3** [comment]
It's not just Object Viewer.
Windows handles decoding the PNGs through libgdiplus, and the .Net framework, all of which have internal limits.

Couple of older Stackoverflow links:
https://stackoverflow.com/questions/2932436/net-gdi-image-size-file-codec-limitations
https://stackoverflow.com/questions/29175585/what-is-the-maximum-resolution-of-c-sharp-net-bitmap
Same principle still applies though.

**Comment by leezer3** [comment]
I can reproduce unreliability (black texture), but no out of memory errors.

I'm afraid this is a Windows issue I can't do much if anything about.
Please drop the size of your texture to something more sensible.

**Comment by BPI-919** [comment]
That's okay. I resized the texture to 4096px * 440px, and now it works fine.
