### ISSUE TITLE
[Question] is non 1:1 texture with power of two resolution will always get rounded to 1:1 resolution?

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#887]
As the title said.

I have a 1024 x 512 px texture that contain several image of trains route map horizontally, i make in that resolution so it will easier to edit later and the texture will not so blurry.

Will the texture get rounded internally to the biggest resolution ? Like the original is 1024 x 512 px, but because computer more efficient using power of two texture it will loaded as 1024 x 1024 px and using more ram/vram.

My goal is making my trains as efficient as possible, both on ram/vram usage and disk usage(file size).

I have already using several technique to optimize it like: using less geometry, using custom normals for smooth surface, pack many texture into 1 or 2 texture atlas, separating transparent and non transparent to different b3d file or different meshbuilder section, using color command for transparency, using lossy image format as jpg or using highly compressed non-transparent png.

**Comment by leezer3** [comment]
Your question isn't especially clear, but:

The texture will be stored in VRAM at 1024 x 512
Each axis is clamped to the nearest power of 2; These do not need to be identical.
GL pulls a subset of pixels from the texture on each render pass (determined by the texture-coordinates)
These do not need to be any specific size, and the only sort of seams etc. introduced will be where the texture wraps around

**Comment by adfriz** [comment]
understandable, thanks leezer3.

I thought both height and width will using the biggest power of 2 😅
