### ISSUE TITLE
[Bug] Glitches when route not reversed on latest Nightly Build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#889]
### Description

On the latest nightly build on a normal non-reversed route, train would jump to the last station of a route at the very start of the simulation.

When jumping to the first station, the time of the simulation will be set to the last station of the route instead of the first.

In the "Interior Camera" mode (F2), the control for switching between cars are reversed (Numpad1 to go forward and Numpad7 to go backward instead of the opposite.

Sometimes the train could also be shown in the wrong position on F3 and F4 camera but I can't reproduce it reliably across different routes :(

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Any (Animated Object Demo Route in this case)

## Train

Any

### Related information 

* Operating system: Debian 12
* Method of control: Keyboard

**Comment by leezer3** [comment]
Thanks, will take a look later.

Must have messed something up in the merge, sure it wasn't at the wrong station in the branch :(

**Comment by leezer3** [comment]
See if that's any better- Hopefully fixed the start location and F2 glitches.
Also fixed that underrun was reported as overrun when in reverse.

I can't see anything that would cause the F3 / F4 camera on a first look- was this on a reversed route or normal?

**Comment by Kenny-Hui** [comment]
Yea that's much better
Also nevermind I figured about the position thing, it's a loop line (But not a perfect loop), that's why I see the train off-track on the other terminus.

I guess I just haven't tried jumping to the other end of the terminus, turning on QuadTree makes much more sense :P
