### ISSUE TITLE
Touch activated faces wrong somehow (?)

### ISSUE THREAD

**Issue by leezer3** [leezer3/OpenBVE#891]
### Description

https://github.com/leezer3/OpenBVE/issues/890
@ginga81 is experiencing flickering. I can't reproduce, however I've found a different bug:
If using touch based faces on a reversed routefile, this doesn't work- No touch cursor is visible.

Somewhat suggests a sorting issue somewhere (?)
https://github.com/leezer3/OpenBVE/commit/807824b91e45b7856df460f1e3e661518b33b729

This exposed the fact that the painters algorithm (used to determine visibility for transparent faces) has differences when using QuickSort versus Stable sort.
Possibly a similar issue- Need to investigate this somewhat.

**Comment by ginga81** [comment]
Did you happen to know the issue https://github.com/leezer3/OpenBVE/issues/893 already?
If so, sorry for creating an issue.
After creating the issue, I looked at the comments and didn't realize it was already being talked about.

**Comment by leezer3** [comment]
The reversed routefile issue is going to be a different bug :)

I suspect it's a case of needing to reverse the touch matrix somewhere, but haven't really looked into that yet.
