### ISSUE TITLE
Touch elements not working properly at 2023.4.30's build

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#893]
### Description

Thank you very much to https://github.com/leezer3/OpenBVE/issues/890 for the fix.
I tested it.
It seems that there is no problem with the 890 fix, but it seems that the touch element has not been fixed compretely, so I will propose it the another an new issue.

・If we switch the camera once (F2-F4, NUM KEY7), the touch screen will switch normally if it is the default zoom position.
・If we zoom in from the driver's view, the switched screen will be displayed, but if we zoom in more, the first screen will appear the hide of second screen.
In particular, if we move it up, down, left, or right after zooming in, the layer will be in the foreground, and the enlarged display will appear as if it were brought to the foreground with the same size ratio from the center point.
As a result, it changes and the size of the screen becomes unusal, so it can be see.

The touch screen returns to its original size when we touch it on the default screen, zoom in, and switch the camera again, but the touch area remains the zoomed-in range of the switched screen, so the touch recognition range shifts as a result.

I think that you are busy, please fix it.

### Reproduction

Please use this route.
https://github.com/leezer3/OpenBVE/issues/614

## Route

Please use this route.
https://github.com/leezer3/OpenBVE/issues/614

## Train

Please use this train.
https://github.com/leezer3/OpenBVE/issues/614

## Logs

This issue don't crash. So no log.

### Related information 

My PC's SPEC:
OS: Ubuntu 20.04 LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board: NVIDIA GeForce RTX 3060(nvidia-driver-525 - distro non-free)

**Comment by leezer3** [comment]
See if the build from today works any better- Reproduced by playing with the zoom levels.

The touch stacking seems to want a complete show / hide cycle to make the sort work OK.

**Comment by ginga81** [comment]
I hope you are doing well!
Also, the flicker was gone.
so it will be closed.
