### ISSUE TITLE
The selected route is corrupt: no objects defined.

### ISSUE THREAD

**Issue by godzilla7806** [leezer3/OpenBVE#897]
Of course, when you want to start an openbve game they will fail saying. "The selected route is corrupt: 
 No objects defined. This happens to me more than once. Today I was goanna to play the NYCT-7 Pack but every time I tried to fix it, this error says the same thing. please someone tell me anyway to fix it.

**Comment by leezer3** [comment]
This doesn't make much sense at the minute.
The error in the title is *normally* caused by not installing a route correctly.

Please link to the route.

**Comment by godzilla7806** [comment]
I have Legacy Content written twice.

**Comment by leezer3** [comment]
Again, please *link* to the route in question- The website where it can be found.

**Comment by godzilla7806** [comment]
Legacy Content 

Railway

Route 

BMT 

IND

IRT

**Comment by godzilla7806** [comment]
├─── Railway		# The top-level directory for all routes
|    ├── Route		# Route files are in this folder
|    ├── Object		# Object files are in this folder
|    └── Sound		# Sound files are in this folder
└─── Train		# Trains are stored as subdirectories of this folder

**Comment by godzilla7806** [comment]
never mind the NYCT-7 pack works now.
