### ISSUE TITLE
Unable to change Anisotropic Filtering level in Options

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#898]
I have my Interpolation settings for the main game set to Anisotropic Filtering however I am unable to change the level of anisotropic FIltering level above 0. Even if I type the numbers in, if I leave the page and come back it resets to 0. I am using the 3rd May Nightly Build but this has happened since 1.9.0.3. Why does this happen? Is it an issue my end or is it something else? The Anisoptropic Filtering level works fine for Objectviewer and Routeviewer.

Thanks

**Comment by leezer3** [comment]
Please try the build from today- This should fix the issue if you load the game once.

**Comment by soyachoin104** [comment]
I have downloaded today's nightly build and loaded the game once and restarted. It's now fixed for me. Thank you very much
