### ISSUE TITLE
The Train no longer loads with a route like it used too

### ISSUE THREAD

**Issue by liammcsh2008** [leezer3/OpenBVE#899]
So I was opening up Maastricht HSR Like I always do. But for some reason, the route wouldn't load like it used to. The Train is not that big, and the route doesn't take up a lot of space

Update: The crash is being caused by a train in which I downloaded from the internet and repainted it

### Reproduction

Open Up the route I am using.
Wait until the bar reaches 50%
The game then crashes

## Route

https://www.mediafire.com/file/9r6tfx0zx8xxikm/Maastricht_Route_Pack.rar/file

## Train which is causing the crash

[AEL.zip](https://github.com/leezer3/OpenBVE/files/11594916/AEL.zip)

## Log

[openBVE Bug Report29_05_2023.zip](https://github.com/leezer3/OpenBVE/files/11594874/openBVE.Bug.Report29_05_2023.zip)

### Related information 

* Windows 11
* Using Keyboard

**Comment by leezer3** [comment]
Please try 1.9.1.1-
Should be available in a few minutes.

**Comment by liammcsh2008** [comment]
I updated the game: And it was fixed.
