### ISSUE TITLE
OpenBVE v19.1.0 fails to launch on macOS

### ISSUE THREAD

**Issue by andylin2004** [leezer3/OpenBVE#900]
### Description

OpenBVE fails to open on v1.9.1.0 on macOS. OpenBVE will briefly run before it gets to [this line](https://github.com/leezer3/OpenBVE/blob/b1b1cd3836c23d97c1f8986480dabb33e77fd894/source/OpenBVE/System/Input/ProcessControls.cs#LL155C4-L155C4) and closes itself out with no crash logging occurring. I can comment out this line of code to fix it, but I kinda want to know what the point of this line is first before doing such a thing. 

### Reproduction

Simply launch OpenBVE v1.9.1.0 on a macOS machine. OpenBVE will briefly open up, but ends up closing itself.

### Related information 

* Operating system
macOS 13.4
* Method of control (Keyboard, joystick, RailDriver)
Keyboard

**Comment by andylin2004** [comment]
This is the error Visual Studio throws: 
<img width="1304" alt="Screenshot 2023-05-30 at 10 40 24 AM" src="https://github.com/leezer3/OpenBVE/assets/60021592/e960ab4e-d18f-4981-8c32-226bd4d6428d">

**Comment by leezer3** [comment]
Really odd :/

That was added as we've got some Korean developers who want to take raw keyboard input, which required an API parameter to block the main sim.

This is going to be with the GL3 menu isn't it?
Might want an in-game check in that case as the player train may be null at that point- Will think about it properly when back from work.
