### ISSUE TITLE
[Question/Bug] Cannot use Win32 plugin under Wine

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#905]
### Description

Before the 64-bit build are introduced, we were able to run Win32 train plugin under Wine.
After the 64-bit changes were made in 1.8.0.0, I am no longer able to run Win32 train plugin with the following message:
`The train plugin <filename> can only be used on Microsoft Windows or compatible.`.

I checked the [source code](https://github.com/leezer3/OpenBVE/blob/master/source/TrainManager/SafetySystems/Plugin/Plugin.Functions.cs#LL298C1-L298C1) and the comment says `//WINE doesn't seem to like the WCF proxy :(`, but this even occurs under 32-bit mode and I don't think we need WCF if we're running in 32-bit mode.
Is there suppose to be a missed if check for 64-bit `(IntPtr.size != 4)` or am I missing something?

### Reproduction

1. Run the latest version of OpenBVE under Wine on a Linux machine (And under 32-bit mode)
2. Select a random route and train with Win32 Plugin
3. The plugin failed to load with `The train plugin <filename> can only be used on Microsoft Windows or compatible.`

### Related information 

* Operating system: Debian 12
* Method of control: Keyboard

**Comment by leezer3** [comment]
That bit of code doesn't come into it.
Look above the bit above that if condition- it checks exactly that.
https://github.com/leezer3/OpenBVE/blob/7bff14baeb47684c62e6869c4445bf6b3f56bef0/source/TrainManager/SafetySystems/Plugin/Plugin.Functions.cs#L282

It's probably something internally to WINE not respecting the 32-bit flag (the 32-bit executable is actually an anycpu executable with the force 32-bit flag set as opposed to 'true' 32-bit)- Mono definitely has this issue, and they've stated it to be a wontfix.
TBQH, this is unsupported at best, and any changes would really need to come from Mono.

**Comment by Kenny-Hui** [comment]
I am aware that Mono doesn't respect the 32-bit flag, but my wine prefix is setup to be 32-bit only and the executable is 32-bit.
Assuming Wine executed this in 32-bit correctly (Which it probably is), this if statement will still get triggered.
It's an OR statement and Wine meets the first condition (Platform not MS Windows), which means this block would be executed regardless of 32-bit or 64-bit if it's not on Windows, and since it's not Windows it will always refuse to load Win32 plugin regardless of what architecture the process is.

I think the block could look something like:
```
if(TrainManagerBase.currentHost.Platform != HostPlatform.MicrosoftWindows && TrainManagerBase.currentHost.Platform != HostPlatform.WINE) {
    // Not Windows nor Wine, probably not Windows compatible, refuse to load the plugin and state it's Windows only
    return false;
}

if(IntPtr.Size != 4) { // OpenBVE ran as 64-bit
    if(TrainManagerBase.currentHost.Platform == HostPlatform.MicrosoftWindows) {
        // Load the plugin with the proxy interface under Windows
    } else {
        // No WCF
        return false;
    }
}
```

If the intention is to block all Win32 train plugin from loading on non-Windows platform, even under Wine, then that comment is wrong (not just due to WCF) and I think it should be noted somewhere in the release note.

**Comment by leezer3** [comment]
Good point.
That might want redesigning a bit- Let me think on it a bit,

**Comment by leezer3** [comment]
That should be better I think. It should now handle WINE and detect the 64-bit version of WINE to boot.

However, WINE is not really a supported configuration, and it just tends to introduce another layer of nasty complications.

**Comment by Kenny-Hui** [comment]
Fixed, thanks.
