### ISSUE TITLE
openbve crashing when loading route and train

### ISSUE THREAD

**Issue by footballbeast89** [leezer3/OpenBVE#906]
### Description Yesterday I was using the southbound v line and all of a sudden the train stopped abruptly. I couldnt move so I exited the game re opened loaded the route again but now it crashes and  brings me to main menu. Now every route crashes and brings me to the main menu I am not sure what to do now.
Please describe 

### Related information 

* Operating system
* Method of control (Keyboard, joystick, RailDriver)

**Comment by footballbeast89** [comment]
openbve keeps crashing and returning to the main menu everytime I try to load a route

**Comment by footballbeast89** [comment]
s

**Comment by leezer3** [comment]
Please provide a log & crash log.
These can be found by clicking the 'Report Problem' link in the bottom left of the main menu.

**Comment by footballbeast89** [comment]
[openBVE Bug Report23_06_2023.zip](https://github.com/leezer3/OpenBVE/files/11849262/openBVE.Bug.Report23_06_2023.zip)

**Comment by leezer3** [comment]
Now that's odd.
Do you have any joysticks / gamepads plugged in?

Wondering if you unplugged one during the game, and it confused things a little.

**Comment by leezer3** [comment]
Please try the build from today:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2023-06-23.zip
