### ISSUE TITLE
[Suggestion] Allow multi object position in .animated file

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#909]
current method to write [object] in .animated file.
```
[object]
States = chair.b3d
Position = -1.15, 0.05, 7.8
RotateXFunction = Your Formula
```
if we want to put multiple object in different position we mostly use like this
```
[object]
States = chair.b3d
Position = -1.15, 0.05, 7.8
RotateXFunction = Your Formula

[object]
States = chair.b3d
Position = -1.15, 0.05, 5 
RotateXFunction = Your Formula

etc...
```
My proposed method of writing is
```
[object]
States = chair.b3d
Position = x1, y1, z1, x2, y2, z2, x3, y3, z3 and so on...
RotateXFunction = Your Formula
```
the method above means the chair object will get duplicated to 3 position when the .animated file is loaded.
this also simplify the duplication in the .animated file. 

instead making multiple [object] block you just write one and specify more XYZ positions for that object.
and we can change the formula for that object in multiple positions with just one command.

some example is like positioning 2 row of seats and give some `RotateXFunction` command.
look at video below i demonstrate in blender.

https://github.com/leezer3/OpenBVE/assets/76892624/25c263ec-e0ed-4728-a2a1-e0b310860395

although i dont know how to make it bounce effect in openbve 😅

**Comment by leezer3** [comment]
No, sorry.

The position is a single, unambiguous 3D vector.
Similarly, the rotation applies to the object as per states only.

Your proposal is a confused mess.
