### ISSUE TITLE
[Question] Train headlights state

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#912]
### Description

I am a bit confused on the intended behavior of #771, specifically regarding the number of headlight states.
Judging from the description, it means that **train.dat** train will have a On/Off headlight state, so 2 states, but the code that implements it only has 1 state.
https://github.com/leezer3/OpenBVE/blob/1054cc5598afec21e7967c448eafc499848acdc9/source/Plugins/Train.OpenBve/Train/BVE/TrainDatParser.cs#L1267

This should result in 2 state by the original code, but commit https://github.com/leezer3/OpenBVE/pull/771/commits/2f5851e80abe05f04d87e64985689a3c8fb4d2d5 (likely unintentionally) changed this behavior, as it uses the `>=` operator instead of `>` for the plugin headlight rollover check, so now we need to add 1 to the headlight state. (2 for 2 headlight state).

Should this behavior be "fixed", or should other internal bits and docs be shifted to accommodate for this change?

**Comment by Kenny-Hui** [comment]
It would be appreciated if this can be looked at, thanks.

**Comment by leezer3** [comment]
Typo.

AFAIK there's nothing using the headlights at present however. 
Actually adding proper multiple light sources is on the (long) list of things to do, which would turn this into something actually useful.....
