### ISSUE TITLE
NYCT Q and R not running

### ISSUE THREAD

**Issue by jimbog41** [leezer3/OpenBVE#915]
### Description

Simulator crashes when loading NYCT Q and R. I get sent back to desktop and the start screen. I can view the routes with Route Viewer. 
### Reproduction

Does not run both NYCT Q and R.

## Route

(https://www.bvestation.com/download/81)
Dependencies are linked on the download page.

## Train

(https://www.bvestation.com/download/73)

## Logs

[OpenBVE Crash- 2023.7.29[22.51].log](https://github.com/leezer3/OpenBVE/files/12207420/OpenBVE.Crash-.2023.7.29.22.51.log)
[log.txt](https://github.com/leezer3/OpenBVE/files/12207421/log.txt)

### Related information 

* Windows 11
* Keyboard

**Comment by leezer3** [comment]
I believe this is fixed in the current mightmy.
