### ISSUE TITLE
[question]Do we have to build 1.9.1.2RC ourselves?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#920]
https://github.com/leezer3/OpenBVE/releases/tag/1.9.2.2
This release note only has source code, no pre-built ones, has RC changed our operation to build RC ourselves?

**Comment by Kenny-Hui** [comment]
You can probably download it in https://vps.bvecornwall.co.uk/OpenBVE/Stable/

The release tag seems to be mistyped as 1.9.2.2

**Comment by leezer3** [comment]
Not yet.
Kiosk mode us still causing issues, so will be replaced tonight / tomorrow.

**Comment by ginga81** [comment]
Either way it seems fine, so I'll close this issue.

**Comment by leezer3** [comment]
OK, let's try again.

New build (correctly numbered!) and hopefully with a few less issues.....
