### ISSUE TITLE
[Bug] GL Menu, scrolling with the mouse on route loading screen would crash

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#924]
### Description

After selecting route and train under the new GL Main Menu, the window will be changed to a route loading screen.
If you attempt to scroll your mouse during the loading screen, the window would close and a crash report would be generated.

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Any.

## Train

Any.

## Logs

[openBVE Bug Report08_08_2023.zip](https://github.com/leezer3/OpenBVE/files/12283843/openBVE.Bug.Report08_08_2023.zip)

### Related information 

* Operating system: Debian Testing (Trixie)
* Method of control: Keyboard

**Comment by leezer3** [comment]
Thanks :)
I've also as a result of this discovered that it was possible to start the camera spinning / panning with a right-click on a loading screen, so these are now also ignored.
