### ISSUE TITLE
[Bug] Cannot apply Sanders to XML Train

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#931]
### Description

I've read through the documentation and attempted to implement Sanders by adding a **<Sanders>** node to **car.xml**, but I am unable to get Sanders working.

I've assigned sound to **sound.xml**, and an animated object with the variable `Sanders` that will appear if Sander has been activated, but neither of which responds.

My sander keybind is also binded properly (S key), at this point I am a bit puzzled, it's very likely I've made some stupid mistake somewhere preventing this from working, but I couldn't pinpoint on what it is...

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Train
[repo.zip](https://github.com/leezer3/OpenBVE/files/12388715/repo.zip)
(Big Red Box should appear in exterior view if Sander is activated, and there should also be sound coming out, but I am unable to get either working)
### Related information 

* Operating system: Debian Testing (Trixie)
* Method of control: Keyboard

**Comment by Kenny-Hui** [comment]
https://github.com/leezer3/OpenBVE/blob/a1ac10b0b7a9c805c67dfeb192a40954ae0306ae/source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.CarNode.cs#L629

This overrides the Sanders ReAdhesionDevice set earlier when parsing the train.xml

**Comment by Kenny-Hui** [comment]
Nice now it worked, but I've noticed that when PressAndHold, it seems that the sander will still reset when the OS key repeat kicks in resulting in constant toggling when actually holding the key. (Maybe OS Dependent?)

**Comment by Kenny-Hui** [comment]
I am a bit confused on the implementation of sanders...

https://github.com/leezer3/OpenBVE/blob/cdf65f179307c67bba260b6b57c3e87b96dfd198/source/TrainManager/Car/Systems/Sanders.cs#L39C26

Firstly, the **Update** method for sanders uses the parameter name "timeElapsed", but AbstractReAdhesionDevice suggest that it is "CurrentAcceleration", and the parameter seems to be the train's acceleration output, is this originally meant to be conditionally called with different value?

Also looking the *if* block around it, it seems the ReAdhesion devices are only ever updated on specific conditions
(Specifically, if DecelerationDueToMotor is 0, the train is a motor car, Reverser is not neutral, power is being applied, and no Hold Notch/EM brake applied)

https://github.com/leezer3/OpenBVE/blob/cdf65f179307c67bba260b6b57c3e87b96dfd198/source/TrainManager/Car/CarBase.cs#L1353

I don't think that is suitable for sanders, as it means the Update method will essentially not get called when the train is not accelerating (But you can toggle it on and off anytime), then stuff like it not reducing the sand level and the loop sound not being be called will happen. (It also seems there's no code that will stop the sander loop sound after it started looping)

**Comment by leezer3** [comment]
Hmm.
Something must have got broken somewhere (and this is why we need more people actually trying these sorts of experiments- it's all well and good cooking up something, but it needs someone actually trying to practicallly implement it) :/

I'll need to dig into exactly when / how the readhesion device is being called to check the conditionals, but the initial logic idea was that (obviously?) it would only be activated by the driver on wheelslip, which should meet the current conditions.
Might need to be tweaked a bit....

**Comment by Kenny-Hui** [comment]
Fixed in #939 and #940
