### ISSUE TITLE
[Question] Some problems with uncoupling carriages

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#933]
### Description

- I uncoupled the front carriages, the separated carriages become easier to push and it's motors power remain under control and the animations are broken.

- When uncoupling the rear null at the end of the train, the message "Unable to uncouple this car." should be prompted instead of "Uncoupling the rear of car number N-1?"
![Uncoupling Prompt Problem](https://github.com/leezer3/OpenBVE/assets/114210303/c475a5ab-1ca1-4c29-be67-ebd50fcc6ac7)
I use the 1M8T train.

### Mention

- #821 item 4

https://github.com/leezer3/OpenBVE/assets/114210303/6dff4cde-1f1e-484d-a308-df1941254c5d

"Articulated" Bogie
This problem is in a sense a punishment for rough coupling behaviour.

- I translate the uncouple prompt, but the uncouple key translation item is not yet available.

### Related information 

* OpenBVE Version: Build 2023-08-21

**Comment by leezer3** [comment]
This should now be mostly sorted with the above commit.
* Motor still running- Forgot to change the train reference when uncoupling at the front.
* Missing translations added.
* Fallback translation for controls sorted so it actually works.
* Unable to uncouple prompt is now correct for rear car.

Pushing and the bogie glitch needs to be looked into a bit more.

**Comment by JunmoreHeavyBox** [comment]
Fixed, Thank!
