### ISSUE TITLE
[Bug&Questions] Uncoupling fixed coupler crash

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#936]
### Description

I fixed some couplers to be semi-permanent, I tried to unhook the front fixed coupler on the last car and the game crashed.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

[OpenBVE Crash- 2023.8.23[22.30].log](https://github.com/leezer3/OpenBVE/files/12446629/OpenBVE.Crash-.2023.8.23.22.30.log)

### Related information 

* OpenBVE Version: Build 2023-08-23

### Other

- The uncoupler sound only plays when the head car of the original train is uncoupled from the back car.

- When I use the emergency brake, the detached train will emergency brake with my train, but not release.
I'm still torn on whether I should keep this feature or not. It's similar to the emergency brake button provided at the station...

**Comment by JunmoreHeavyBox** [comment]
Urge.

**Comment by leezer3** [comment]
Build from today will sort out the coupler sound (accidentally restricted that to the driver car) and have looked at the brake systems some more.

It will now not follow the EB brake actions of the player train- 
This needs a new configuration item somwhere to allow it to work properly (basically needs an uncouple action, so that we can have either EB, or nothing)- Thinking about that at the minute, but I think the probable answer will be at least temporarily to apply EB to the decoupled portion.

Other thing I'd quite like is to add brake pipe isolating cocks, forcing EB to apply to all portions unless closed after uncoupling (as per real life)
However, adding something like this requires another key assignment or sorting out a popup to do the job. Not so much difficult, as the scope of this keeps expanding from a simple change.

I can't however reproduce the crash at the minute- Please share the train.dat and train.xml

**Comment by JunmoreHeavyBox** [comment]
All I know is that I set CanUncoupled to False on the last coupler, none of the other couplers are written.

**Comment by JunmoreHeavyBox** [comment]
The middle coupler is surrounded by the fixed coupler and has no problem decoupling it from behind. Oddly enough, when I try to decouple from the front, it becomes a fixed coupler.
```
<Car>CarTC.xml</Car>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car>
<Car>CarMC.xml</Car><!--Here to uncoupler front car-->
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Car>CarTC.xml</Car>
```

**Comment by JunmoreHeavyBox** [comment]
Urge agin

**Comment by leezer3** [comment]
OK, that should stop the crashing and the separate glitch where the camera jumps to a different car on uncoupling the front.

**Comment by JunmoreHeavyBox** [comment]
Ok. but these consists still don't uncouple the front.
```
<Car>CarTC.xml</Car>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarT.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car>
<Car>CarMC.xml</Car><!--Here to uncoupler front car-->
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarT.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarT.xml</Car>
<Car>CarT.xml</Car>
<Car>CarTC.xml</Car>
```
```
<Car>CarMC.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car>
<Car>CarMC.xml</Car><!--Here to uncoupler front car-->
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car>
```

**Comment by JunmoreHeavyBox** [comment]
ahh, Things aren't simple. Consider other coupler consists...

**Comment by JunmoreHeavyBox** [comment]
I have not set CanUncoupled, but the last two couplers are not uncoupled.


The coupler is fixed, but can be uncoupled at the front.
```
<Car>CarMC.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car>
<Coupler>
    <CanUncoupled>False</CanUncoupled>
</Coupler>
<Car>CarMC.xml</Car><!--Here to uncoupler front car-->
<Car>CarMC.xml</Car>
```

**Comment by leezer3** [comment]
OK, please try the build from today.

Indicies are giving me a headache......
The coupler when uncoupling the front is on the preceeding car, but to actually get the 'right' display number we need to add one.

Other additions to this are a new tag, **UncouplingBehaviour** to control the brake settings when uncoupling.
This isn't perfect, as the uncoupled consist currently has a dummy brake handle, so is unlikely to reflect an applied service brake correctly when uncoupled. ( https://github.com/leezer3/OpenBVE/pull/934 will help with this)
```
/// <summary>Emergency brake is applied to both consists</summary>
Emergency,
/// <summary>Emergency brake is applied to the player consist</summary>
/// <remarks>The uncoupled consist will retain the previous brake setting</remarks>
EmergencyPlayer,
/// <summary>Emergency brake is applied to the uncoupled consist</summary>
/// <remarks>The player consist will retain the previous brake setting</remarks>
EmergencyUncoupledConsist,
/// <summary>The brake is released on the uncoupled consist</summary>
/// <remarks>The player consist will retain the previous brake setting</remarks>
ReleasedUncoupledConsist,
/// <summary>The brakes are released on both consists</summary>
Released
```

**Comment by JunmoreHeavyBox** [comment]
It's fixed. Almost.
Then add documentation for UncouplingBehaviour.

Still no sound is heard when the front car is decoupled and there is something wrong with the numbers in the decoupling description.
> Uncoupling the DIRECTION of Car Number 11, 21, 31,... ,91, 101, 111, 131, 141...

#
Suggestions for uncoupling description.
My translation is such that it looks like it's saying that it's the index cart that's being decoupled... I thought about that meaning.
> 已解挂后方的车厢 [index]

Add a variable to it, I wanted to translate it like this.
> 在 [index] 号车解挂了后方的车厢

**Comment by leezer3** [comment]
Fixed the string interpolation issue.

With the translation, could probably do something, but would prefer not to, as this is easier and less prone to typos.
I don't understand enough of the nuances of Chinese- Is this a matter of looking nicer or being more understandable?

**Comment by JunmoreHeavyBox** [comment]
... comparison

> 已解挂 后方 的 *车厢 i* (及 随后的 车厢)
Decoupling the rear *carriage i* (and subsequent cars)// Supplement

> 在 *i 号 车* 解挂了 后方 的 车厢
On *car num i* decoupling the rear carriages

**Comment by JunmoreHeavyBox** [comment]
Close the Issue for the topic.
