### ISSUE TITLE
[Bug] Train shakes on high frame rate

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#941]
### Description

If **Vsync** is turned off and the in-game frame rates reaches a very high fps (~300), the train would start shaking vertically.

https://github.com/leezer3/OpenBVE/assets/28094366/6404e004-7f3f-4780-b613-659d5ce25bc4

**Linux only, inaccurate timer, see below.**

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

[TFO Demo Route by ginga81](https://drive.google.com/file/d/17GEHSa13GMeS7G1cVe7GkuMdkP_GyhNt/view?usp=sharing)

## Train

[Hong Kong LRV P4](https://github.com/HKTSS/LRV-P4/releases/download/2.0.1/HKTSS.MTR.Light.Rail.Phase.IV.v2.0.1.zip)

## Observation
- Happens on any camera mode that associates with the train itself (So all camera mode except F3)
- Excessive shaking only noticeable on F1, but the train itself still do shake vertically ever so slightly in other camera mode.
- Most noticeable when acceleration/deceleration changes rapidly, especially stopping to 0km/h after EMB/FSB.

### Related information 

* Operating system: Debian Testing (Trixie)
* Method of control: Keyboard

**Comment by Kenny-Hui** [comment]
Unrelated, but is there an explanation on what does the `TimeElapsed > 0.0` check does?
https://github.com/leezer3/OpenBVE/blob/c67a3dd24e65b229649dc28437acf84519c3f64e/source/OpenBVE/System/Input/ProcessControls.cs#L429

This would return false the higher the fps is (I assume due to precision it gets rounded down to 0), and it would almost be impossible to zoom with ~500-600fps / extremely incremental zooming. (600fps would be near impossible to achieve back then before the new renderer, so it's does make sense this is not discovered earlier)

Might be overthinking again, but given the description I think it could be related to #812. (RouteViewer doesn't do the TimeElapsed check, and Outer-View usually results in less fps)

**Comment by leezer3** [comment]
It shouldn't ever return false.
The FPS is a double, so should be happy with figures well into the tens of thousands.

That would glitch something rotten at higher FPS though.

I would suspect that the check was probably for when paused / in the old menu, but that's only a suspicion.
That can probably be changed though.

**Comment by Kenny-Hui** [comment]
Double *in theory* should be able to handle very accurate precision, from my testing TimeElapsed itself only returns either 0.004 or 0.0 in higher fps, haven't looked too deep on that though.

For the TimeElapsed check itself, I think that might be it.

https://github.com/leezer3/OpenBVE/blob/54bb4ef8b947c1bb7afbc62b5f3989a2e0eb0eea/source/OpenBVE/System/GameWindow.cs#L108C20-L108C20

Although I think we now do detect menu type before processing controls, so removing this shouldn't be a problem?

**Comment by leezer3** [comment]
I've just had a thought:
It'll be being triggered by the internal control repeat mechanism which runs on it's own timer, which is why we've not had any reports of stuff glitching at high FPS.

Could probably just add a check that we're in the normal interface mode. I *think*.....

FWIW, the TimeElapsed variable won't work too well with breakpoints (I'm assuming that's what you're doing)
https://github.com/leezer3/OpenBVE/blob/54bb4ef8b947c1bb7afbc62b5f3989a2e0eb0eea/source/OpenBVE/System/GameWindow.cs#L284-L292

Can't see a reason otherwise; If it was actually only returning .0004 or 0.0, essentially nothing would work properly if at all, as it's the main timer tick.

**Comment by leezer3** [comment]
Incidentally, I seem to need a faster graphics card.....

Can't get much above 150fps even with everything turned down to the minimum on the TFO demo route.

**Comment by Kenny-Hui** [comment]
I just Console.WriteLine the result, and removing the check seems to solve the issue, although I agree there's probably no way it would get rounded down like that, there would be too many flaws.
I will look at it further tomorrow.

Not being able to reproduce high frame rates may make this more convoluted though, removing the TFO from the basic TFO route doubled my FPS (300->600), although with 150 FPS it may still not be enough.

**Comment by leezer3** [comment]
What's rather interesting is that my FPS seems to cap out there.
Load something much more complex (e.g. my Plymouth) and I'm still sitting at ~150

VSync is off, must be something driver / Windows related somewhere....

My first suspect would be this little set of code here, which updates the camera based upon the simulated driver head bounce in 3D cabs, which you could probably try commenting out)
(FWIW, might even be worth stopping all driver head simulation. Interestingly, if we comment out the driver body update, head bounce still occurs)

https://github.com/leezer3/OpenBVE/blob/54bb4ef8b947c1bb7afbc62b5f3989a2e0eb0eea/source/OpenBVE/Game/World.cs#L277-L333

**Comment by Kenny-Hui** [comment]
Getting 300-400fps here on Windows, slightly lower than Linux, but *should be* enough to reproduce this.
Interestingly I cannot reproduce any oddities on Windows, so maybe this is just a Linux/Mono thing.

I will try commenting this code later on and see if that helps.
However I noticed Windows returns a much more accurate TimeElapsed value (0.0029107, 0.0030099) and it would almost never return false, a bit unlikely but I think something on the main tick timer could be wrong under Linux/mono, probably resulting in both the control not responding and the odd camera jumping.

**Comment by Kenny-Hui** [comment]
So far it *seems* to be actually the case, the entire main loop timer is not so correct on non-Windows system.
On Windows it uses the performance counter so no problem with that
On other OS in `CPreciseTimer.GetElapsedTime()`, `Environment.TickCount` only has a precision of 4ms on my system, so it can't return anything in between.

**Comment by leezer3** [comment]
Hmm.

The timer code is pretty elderly, which means that any workarounds in there may now be moot :/
I seem to recall that the stopwatch was unreliable (at the time anyway) on Mono.

**Comment by Kenny-Hui** [comment]
Stopwatch *should work* (at least nowadays), although internally I think it roughly does the same thing as our CPreciseTimer code (Performance Counter on Windows, DateTime on other OS), shouldn't be that much different from just using `DateTime.UtcNow.Ticks` in our timer code.

**Comment by leezer3** [comment]
https://github.com/dotnet/coreclr/pull/2293
https://github.com/xamarin/xamarin-android/issues/2641

By the looks of things, at the time the timer code was written (2015....) Mono was using CLOCK_MONOTONIC
CoreCLR (in it's infancy then) changed to using CLOCK_MONOTONIC_COARSE, and Mono seem to have pulled this in c. 2018
That doesn't mean of course that it ever worked at ~300fps; I think you're probably one of the first to try reaching those heady heights......

Unfortunately DateTime.UtcNow.Ticks would appear to probably have the same issue:
http://web.archive.org/web/20100411072449/http://blogs.msdn.com/ericlippert/archive/2010/04/08/precision-and-accuracy-of-datetime.aspx

Stopwatch is *probably* the answer, but I suspect we may well end up falling into a different set of holes along the way, and it's something that would want testing on Apple and BSD just in case that breaks something else.
Shouldn't do, but we know the current setup works OK in most cases.

A completely different approach might be to alter the target render frequency.
https://github.com/leezer3/OpenBVE/blob/54bb4ef8b947c1bb7afbc62b5f3989a2e0eb0eea/source/OpenBVE/Graphics/Screen.cs#L135-L136

If we limited this to say 150fps, that might well get around the problem, but might end up in a different hole in the swiss cheese....

**Comment by leezer3** [comment]
Added a FPS limit, which is read from the options file if present, but not in the main menu using the OpenTK method in my post above.

Linux / OSX are now limited to 200fps by default. See if that helps, but I'm a little wary of other glitches creeping in.....

**Comment by Kenny-Hui** [comment]
Works on the latest nightly build, closing this as worked around.
