### ISSUE TITLE
Hello! everytime i try to load my route it says this "The selected route is corrupt:   No objects defined."

### ISSUE THREAD

**Issue by monkee12333** [leezer3/OpenBVE#946]
### Description

Please describe the issue you are experiencing.

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

### Related information 

* Operating system
* Method of control (Keyboard, joystick, RailDriver)

**Comment by leezer3** [comment]
Can you please be a little more specific about the route?

This error generally means that it can't find the appropriate objects, which tentds to be a installation issue somehow.

To help, we need the route in question and details of how / where you've installed it.

**Comment by monkee12333** [comment]
> Can you please be a little more specific about the route?
> 
> This error generally means that it can't find the appropriate objects, which tentds to be a installation issue somehow.
> 
> To h-+
