### ISSUE TITLE
Toleranceing for some values.

### ISSUE THREAD

**Issue by afarlie** [leezer3/OpenBVE#95]
Got plenty of errors on old rw routes and B3D objects about out of range colors?

Would it be reasonable to consider implementing an option to cap colors at saturation? (i.e anything above 255 gets clipped down?)

**Comment by leezer3** [comment]
If I recall (Need to check), it'll clip to 255, so the error itself is actually essentially harmless.

The primary problem with these is that BVE2, and to a certain extent BVE4 handled reduced color palettes differently, in that if a file was reduced to 16 or 256 colors, it effectively reduced any transparent color declarations to their equivalent in the reduced palette;
To be more exact (for example), a 16 color bitmap can technically hold 16 shades of red, but the transparency parser was treating these as the 16 primary colors present in the windows palette. 

Transparencies are unlikely to change, but if you've got any specifically broken objects I'll take a look.

**Comment by afarlie** [comment]
Another issue, I've found with a very old route of mine is  ., being inserted as synonym for 0.0 :(

**Comment by leezer3** [comment]
Sample please, I can't do anything unless I can reproduce it.

In general, the decimal point being interpreted as a number tends to be desirable (e.g. .225 being recognized) , but sometimes it goes awry.
Not sure whether this can be easily fixed, but I can certainly take a look.

**Comment by afarlie** [comment]
The sample would must likely be a Beta of my "Beck Line" route  (I recently recovered this  from someone else in the BVE sim community. )that was being worked on Stephen Cross and others, which I can't upload here for licensing reasons.  If you can drop me an e-mail privately, I'll see what I can dig up.

**Comment by leezer3** [comment]
Dropped you a message.

**Tolerancing:**
This fix makes time values generated by RouteBuilder work:
https://github.com/leezer3/OpenBVE/commit/9ed64b4a14be65df7ed047e09643139e98a0fd70

**Comment by afarlie** [comment]
It wasn't time values that I has having issues with.

It was Z veretx part in some AddVertex lines which was the main concern,  in the file these "0.0," was written as ".," in csv and B3D files. Mostly this was to do with specfic rail objects and may well have been an issue in an earlier version of TrackGen (or it's predecessor tools) that was resolved previously, It's unfortunate that I seem to have some objects based on an older tool.

Visually, I can't see anything unusal, but OpenBVE is understandably a lot stricter than the old style BVE2/4 parser I'd been doing development work with, previously.

**Comment by leezer3** [comment]
OK, now I know what you're on about.
The files in question will have come from Richard Gellman's **Power Rail Generator** which generated LU & BR 3rd rails, plus some pits and a couple of other bits. 

Your files will display correctly, just ignore the errors. This particular error isn't going to change.
