### ISSUE TITLE
Adding an option for resetting keyboard control?

### ISSUE THREAD

**Issue by mrwhosethesus** [leezer3/OpenBVE#953]
Is it possible to add an option to reset the control for the keyboard? I changed some keyboard settings on OpenBVE and now some of the controls on the game aren't working properly. Currently running macOS Sonoma 14.1 on M1 MacBook Air.

**Comment by leezer3** [comment]
Good point- I'm sure this can be done with no trouble.

I can't remember offhand where the options are stored on Apple, but deleting the controls.cfg file will reset everything to default.

**Comment by leezer3** [comment]
OK, so the file in question may be found at /users/**YOU**/.config/openBVE/Settings/1.5.0/controls.cfg

(the .config folder is hidden by default in Finder, so you'd need to use terminal or press **CMD + SHIFT + PERIOD** to show it)
