### ISSUE TITLE
[Bug] Loading specific route into openbve or route viewer make the program not responding and use too much RAM. 

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#955]
### Description

as title said.

### Reproduction

just load the route, either in openbve itself or route viewer.

## Route

try load this route: https://www.mediafire.com/file/q9g8ojc55c5ezo7/Yogyakarta-Madiun.rar/file

*my friends found this link, we already test it in newest openbve and route viewer but it make the app not responding.

## Train

no trains.
## Logs

no logs, the app immediately hang and not responding when the route loading progress bar reached 100%.
### Related information 

* Operating system: windows 10
* Openbve: 1.9.2.3 64 bit
* Method of control : keyboard and mouse.

NOTE: my friend said he try load the route with the oldest openbve version he got, he got openbve 1.2.12 and its loaded he said.

here some image i capture when i tried to load the route with newest openbve version.

![a1](https://github.com/leezer3/OpenBVE/assets/76892624/2c581d75-d987-4f56-8845-b2c89827139e)

in my task manager its immediately use too much ram and high cpu usage.
![a2](https://github.com/leezer3/OpenBVE/assets/76892624/c8d1d942-6518-4a27-8317-81e975f76c89)

and here a screenshot from him.

![a3](https://github.com/leezer3/OpenBVE/assets/76892624/8be9bc15-aa9b-46a1-a490-dcf330db8d5d)

not too realistic route in terms of graphics, but im curious what thing that make this route cannot loaded in newest openbve.

**Comment by leezer3** [comment]
So, the primary issue is some quite creatively 'broken' animated objects, which are used as grounds- Large numbers of similar objects:
`
[object]
states=..\Tree\field2.b3d
rotateXfunction=sin[time/3]/2
position=0,-2,29
`

I think the author was attempting to create a swaying grass effect with this.

It will load (eventually), but it's got all sorts of issues, and I'm not sure this is easily fixable.

**Comment by leezer3** [comment]
The PR above gets the loading time back to something more sensible, but I want to do a considerable amount of testing before merging it into the main public branch, as I don't want to break something else.

(Note: I seem to be missing various of the objects with just your link, but this doesn't really matter at this point)

FWIW, I note that this must have been built with an relatively early (pre GL3 I'd say) build from this project, as Michelle's 1.4.3 doesn't load it :)

**Comment by leezer3** [comment]
Fixed in the current daily build, although the fix for the minute is controlled by a hacks option as I'm not certain it won't break other stuff.

(n.b. your download is missing a bunch of the objects, and so things appear somewhat broken, and I haven't really tested the route itself)
