### ISSUE TITLE
FPS limit causes train shaking and breaks input device plugin

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#957]
### Description

When running a build after [3c60308](https://github.com/leezer3/OpenBVE/commit/3c60308112db56110ee35425b9624b293472e057) (including the latest stable release) under Linux, trains seem to shake. The shaking seems to affect the whole car body (not just the driver's head/body), because it is visible from the interior and exterior views. It matches the original problem in #941, but happens even with low framerates (20-30 fps). It is reduced when "Loading sway" is disabled in the options.

In addition, after that very same commit, the Densha de GO! input device plugin is broken. The plugin reports KeyUp/KeyDown events correctly, but they are missed by the main program.

Both issues are fixed if the FPS limit is set back to 0.

### Reproduction

Same train and route as #941.

### Related information 

* Operating system: Arch Linux (up to date, November 3rd, 2023)

**Comment by leezer3** [comment]
Now that's interesting and somewhat odd.

Something must be going on internally to OpenTK that it doesn't like, and that's OS timer related somehow.
I can't immediately think why it would glitch *below* the limit though :(
IIRC you said that Debian isn't missing the keyinputs, so I'd wonder whether we're hitting some sort of Mono bug on Arch which is lining up with another hole in the swiss cheese.....

Is your Debian box running the Debian packaged Mono version, or the one direct from Mono?
Trying to think about triaging whether this is Mono version related, or distro related (pig to trackdown if so....)

**Comment by leezer3** [comment]
Probably be next week, but I'll try and run up a PR using a Stopwatch to replace the timer and disabling the FPS limit by default.
That'll be interesting too.....

**Comment by MarcRiera** [comment]
I just grabbed Ubuntu 23.10, ran it live, ran OpenBVE and managed to recreate the issue with OpenBVE 1.9.2.3, with the above route and train. I get both the shaking and the broken input plugin. It happens regardless of the version of Mono: the version packaged in Ubuntu (6.8.0.105) and the latest in the Mono repos (6.12.0.200).

The key events from the input plugin are not missed 100%. Buttons always work and handles rarely work. The thing is, handles are translated to a KeyDown event when moved and a KeyUp event the next frame, which is a short time. Before finding out about the FPS limit, I tried making the plugin constantly fire KeyDown/KeyUp events for the handles and then they worked reliably. So the main program was skipping certain events, it seems.

**Comment by Kenny-Hui** [comment]
Yup that seems to be the case, I originally only checked if the fps cap worked properly then closed the issue assuming it's fixed, shortly after that I've noticed that it also happens with the fps cap limit, but I thought it's something on my end so I just didn't bother chasing further

**Comment by leezer3** [comment]
Ouch :(

In that case, the FPS limit probably needs reverting entirely; I'm not really happy with trying to cook up a one-off limiter.
Its odd though I can't get above 150fps on Debian, I'll have to try a different DE for starters and see if that does anything. 
X11 versus Wayland maybe?

**Comment by ginga81** [comment]
I tested it on the daily build of 2023.11.3 to check https://github.com/leezer3/OpenBVE/issues/952, but it responded in the dialog but not in the game.
At least the daily build of 2023.8.2 was already inoperable.
I think there may be some kind of trouble apart from https://github.com/leezer3/OpenBVE/issues/952.

**Comment by leezer3** [comment]
[stopwatch.zip](https://github.com/leezer3/OpenBVE/files/13257545/stopwatch.zip)

Experimental build using the StopWatch instead of our timer.

Please can those who can reproduce see if it helps. 
(I have a sneaking suspicion that we may well discover that we can't get anything other than 4ms precision with this either, but let's see)

Will try and see what I can find out next week at some point, but that might involve some digging in the OpenTK code to see how they're implementing the FPS limiter.... 
For what it's worth, from reading the OpenTK documentation, it states that FPS has an upper clamp to 500hz

**Comment by MarcRiera** [comment]
> [stopwatch.zip](https://github.com/leezer3/OpenBVE/files/13257545/stopwatch.zip)
> 
> Experimental build using the StopWatch instead of our timer.
> 
> Please can those who can reproduce see if it helps. (I have a sneaking suspicion that we may well discover that we can't get anything other than 4ms precision with this either, but let's see)
> 
> Will try and see what I can find out next week at some point, but that might involve some digging in the OpenTK code to see how they're implementing the FPS limiter.... For what it's worth, from reading the OpenTK documentation, it states that FPS has an upper clamp to 500hz

I get no shaking with this build and the input plugin works flawlessly. This is on a range of 70-100 fps, my PC cannot go higher.

**Comment by Kenny-Hui** [comment]
Seems to work flawlessly on my machine with 600-700fps
(Can't explain how my fps is that high either, on Windows it's definitely less than half of that)

**Comment by ginga81** [comment]
＠[MarcRiera](https://github.com/MarcRiera)
I checked on Ubuntu and the TYPE-2 controller worked fine in this build.

**Comment by leezer3** [comment]
Put that into mainline then.

I will note that the current version of this *only* uses StopWatch on non-Windows platforms, which might explain some of the difference- One step at a time....
However, OpenTK *claims* to be internally limited to 500hz (e.g. 500fps), so something isn't quite right somewhere. I'd be surprised if it's actually running at the numbers you're mentioning, especially with the Windows differences, but frankly it's not worth chasing too hard if the thing works OK......

I will (assuming nothing else is broken) try and put out a new release this week.
