### ISSUE TITLE
Critcal Error when loading very old train.

### ISSUE THREAD

**Issue by afarlie** [leezer3/OpenBVE#96]
Namely  the GP38  - http://www.trainsimstuff.org/other-downloads/older-routes/usfreight.zip?attredirects=0&d=1

and specfically it doesn't like panel.cgf

**Comment by leezer3** [comment]
Fixed in the most recent nightly.

This was caused by the texture clip region being outside the bounds of the texture. I've added a check to both width and height, and it'll now work, but generate a warning.

**Comment by afarlie** [comment]
OKay so this will be fixed in RC7 ? Thanks. In the meantime is there a patch I can make to the files for the train, to get it working?

**Comment by leezer3** [comment]
Current nightly fixes it.

In the digital speedo section (IIRC the second to last one, the one
pointing to the numbers bitmap), the width needs to be changed from 15
pixels to 10 pixels.

**Comment by afarlie** [comment]
Can confirm **RESOLVED** in nightly, Thanks :)
