### ISSUE TITLE
[Question] To close the dev tools

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#962]
### Description

Train Editor 2 doesn't close completely, I have to close it on Task Manager.
Pressing alt+f4 in Object Viewer and Route Viewer does not close the window, is it intentional or?

### Related information 

* Windows 7

**Comment by leezer3** [comment]
ALT+F4 not working in the viewers is expected.

Fixed the TrainEditor2 issue.

**Comment by JunmoreHeavyBox** [comment]
After the TE2 fix it closed without asking me to save the changes.
