### ISSUE TITLE
[Bug] ALn501 textures not loading in

### ISSUE THREAD

**Issue by soyachoin104** [leezer3/OpenBVE#971]
### Description

<img width="605" alt="image" src="https://github.com/leezer3/OpenBVE/assets/50995356/1949acbc-1934-4fd2-bc70-639ab9a5612b">

The textures of the end cars do not appear to load in besides displaying a solid colour. I checked in Objectviewer and there are no errors relating to texture loading problems. Currently using 31st October nightly build but I have heard it occurs in 1.9.4.3 as well.

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

http://www.trenomania.it/bve/download/treni/trenieng.asp

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/b606b7c3894ca319341297bb2096c8f6c51917fd

Whatever exported this X expects the texture to be using wrap mode RepeatRepeat.
This is not default ( https://learn.microsoft.com/en-us/windows/win32/direct3d9/texture-wrapping-state )

I need to do a little digging into exactly whether this is supported by any other 3D viewers, but for the minute I've tweaked things so it works again. Might be a little slower with some of the totally outsize objects this was intended to speed up loading, but can't break things at the same time....

Thanks.
