### ISSUE TITLE
Can't load obj file that exported from blender 4.0.2

### ISSUE THREAD

**Issue by adfriz** [leezer3/OpenBVE#973]
### Description

as the title said

### Reproduction

1. download this object https://polyhaven.com/a/rubber_duck_toy
2. import to blender
3. export it as wavefront obj
4. load it to object viewer
5. object viewer cannot load it, it makes an error report like this:
   

>    Error:		The relative path contains invalid characters. in D:\test\rubber_duck_toy_1k\duck.obj
>    Error:		No plugin found that is capable of loading object D:\test\rubber_duck_toy_1k\duck.obj

Here is the exported obj file: 
[duck.zip](https://github.com/leezer3/OpenBVE/files/13622483/duck.zip)

## Route

no routes

## Train

no trains

## Logs

> Error:		The relative path contains invalid characters. in D:\blender stuff\rubber_duck_toy_1k\duck.obj
> Error:		No plugin found that is capable of loading object D:\blender stuff\rubber_duck_toy_1k\duck.obj

### Related information 

* Operating system: windows 10 64 bit
* Method of control: mouse and keyboard
* OpenBVE: tested on nightly builds OpenBVE-2023-12-04 and 1.9.2.3 64 bit

**Comment by leezer3** [comment]
You've exported this file containing full paths.

From the mtl file:
```
map_Kd C:/rubber_duck_toy_diff_1k.jpg
map_Bump -bm 1.000000 C:/rubber_duck_toy_nor_gl_1k.jpg
```

Will sort so this handles a little better, but there should be an option somewhere to export with relative paths, not absolute paths.

**Comment by leezer3** [comment]
Build from today will solve this, but you should export with relative, not absolute paths.

**Comment by adfriz** [comment]
Thanks it works, but unfortunately there still a bug with the texture.

It seems the UV coords is messed up in object viewer, I also exported the object to b3d for comparison.

I only use the diffuse/color only texture for that duck object.

Here is the object file: 
[duck2.zip](https://github.com/leezer3/OpenBVE/files/13626500/duck2.zip)


left is the .obj and right is the b3d one.
![image](https://github.com/leezer3/OpenBVE/assets/76892624/ce3547b1-9447-442c-b23c-2ecf815c20d7)

**Comment by leezer3** [comment]
Fiddle, didn't notice that, fixed.
