### ISSUE TITLE
[Question] LocoBrakeNotch subject not recognised by Object Viewer

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#974]
### Description

I'm using locoBrakeNotch subject and the Object Viewer doesn't recognise it.
The speedometer variable did not follow the speed variable.
Similar inspection...

I haven't made my car yet and just want to test the handle animation in the Object Viewer.

**Comment by JunmoreHeavyBox** [comment]
"urge"

**Comment by leezer3** [comment]
I will look at this, but December is not a good month with Christmas / New Year.
May take a few weeks.

**Comment by leezer3** [comment]
OK, easier than I thought, try the build from today....

**Comment by leezer3** [comment]
Just checked- Speedometer seems to work here.
Are you correctly doing your radians conversion?

Working example from the D1015 cab (this also works with plain speedometer):
```
;Speedometer Needle
[Object]
States = Cab\Needle1.csv
RotateXDirection = -1, 0, 0
RotateXFunction = -3.75 + abs[speedometer[0]] * 0.097
RotateYFunction = -1.05
RotateZFunction = -1.57
Position = -0.475,2.55,9.5575
RotateXDamping = 2, 0.8
```

**Comment by JunmoreHeavyBox** [comment]
I am applying the speedometer variable to the wheel, in the object viewer.
I would like to consider an individually adjusted and synchronised speedometer and speed. Or an amount that differs from the speed value by how much?

**Comment by JunmoreHeavyBox** [comment]
I can only view the differences in speed and speedometer variables in the main game.
This is a reason...
