### ISSUE TITLE
Input device plugins crash the program when passing input since recent changes

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#984]
### Description

Since #972 was merged, input device plugins crash the program whenever KeyUp or KeyDown is called to pass input. I first detected the issue with the Densha de GO! plugin, but DefaultDisplayPlugin is broken as well.

### Reproduction

Enable DefaultDisplayPlugin. Open the config window and enable the display of one or more elements. Then, run any route with any train and the program will crash right after loading is complete.

I have taken the time to try to find when this started and https://github.com/leezer3/OpenBVE/pull/972/commits/f0efbd75867d885b8d8b729b5b010b02d6997c5f is the first commit which breaks the plugins.

### Logs

[openBVE Bug Report31_01_2024.zip](https://github.com/leezer3/OpenBVE/files/14105321/openBVE.Bug.Report31_01_2024.zip)

### Related information 

* Arch Linux (up to date)
* OpenBVE daily build 2024-01-30

**Comment by leezer3** [comment]
Fixed, or at least worked around with the commit above.

There's a control set with the **None** command which is causing issues when it attempts to check for modifiers.
The **None** command probably wants removing entirely, but see if that works for starters.

**Comment by MarcRiera** [comment]
Thanks, I can confirm it's working now.
