### ISSUE TITLE
[Bugs] The given keyword is not in the dictionary

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#990]
### Description

Seems to most routes report the error "The given keyword is not in the dictionary", and cannot be play.

It seems that Object Viewer still doesn't use the locoBrakeNotches variable.
When I Reset Train Settings, locoBrake Notch and locoBrake Notches do not reset to 8 like the other handles.
I need to move locoBrake Notches before I can adjust locoBrake Notch. after Reset I have to move locoBrake Notches again.

Sorry I'm late...

### Related information 

* OpenBVE Version: Build 2024-02-12

**Comment by leezer3** [comment]
No problem.
Fixed the issue with other routes, will look into exactly what's happening with loco brake notch.

**Comment by BPI-919** [comment]
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/b0e42421-aba5-4e87-a89f-9fc24c1de25a)

Dear @leezer3 ,

I have a critical problem, which occurs with every routes.
When I click on the icon of the manually browsed route file, then I cannot see nothing under the "Details" section (on the right side of the attached image), and I also cannot click on the Start button (on the bottom part of the image), this button is inactive. :( 
I switched the language of the OpenBVE (normal, 64 bit) app from Hungarian to English (US) and vice versa, but nothing changed.
I use the latest build of OpenBVE (2024-02-16) and my OS is Windows 11 23H2, 64 bit, so everything is the latest version now, and my computer is also up-to-date at the moment...
It has not been a problem to click onto the Start button so far... (Previously I used the 2024-01-04 build, and it worked fine for me.)

I am going to restart my PC now, maybe it will help, but I am not very optimistic... 
Could You please help me?

Thanks in advance and Regards,
Andras

**Comment by leezer3** [comment]
I can't immediately think of anything.

Most of the changes since then are the language file internals work, which I can't see affecting the start button.
(Your image suggests its failed to load the routefile. I'd have to check the error when home as to where its failing exactly)

Try rolling back to the previously working build as a first step- This will tell us if Microsoft has broken something, or if its me....

Will try and take a proper look later.

**Comment by Kenny-Hui** [comment]
`The given key '1' was not present in the dictionary.`

![image](https://github.com/leezer3/OpenBVE/assets/28094366/80ce63df-7265-4264-ab12-397f3fb43af5)
Very simple routes like the TFO test route and Animated Object Routes works, but not anything other than that

**Comment by BPI-919** [comment]
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/6fead7a5-5c2e-42c8-9110-9cdbb825dfb5)
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/2551e74d-e79d-44e6-85bf-a289396a2fd2)
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/db6b2daa-cdbd-48a6-8f4c-b6649ba1a838)

I also faced now another kind of issue...
When I opened an extensions.cfg file of a train in Object Viewer, I saw these errors.
There are 2 textures with .png extension, and the sizes are not too large: both's resolution is 5906 x 3543 px with 510 kilobytes and 301 kilobytes. I think making these 2 textures visible was not a problem in my previous (2024-01-04) OpenBVE version.

Did it happen, that from the beginning of this year (2024) the Texture.BmpGifJpegPngTiff plugin got a new restriction on the texture resolution? If yes, could You please write the maximum allowed resolution into the OpenBVE Developer Documentation, or just here? Could 4096 x 4096 px be the last (or largest) that can be displayed in Object Viewer, maybe?

**Comment by ginga81** [comment]
I was curious, so I tried it with the daily build of 20240216.
It's true that my route can't be read such as this screenshot.
![Screenshot from 2024-02-18 01-32-47](https://github.com/leezer3/OpenBVE/assets/22734699/c4fef077-086e-4b86-a104-5cf7b1e60135)

**Comment by BPI-919** [comment]
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/f2ecddf6-6145-454e-83ce-4e993016588a)
![kép](https://github.com/leezer3/OpenBVE/assets/66689434/46572e5d-c407-46dc-8011-e33b03aa2ef9)

Jumping back to my first problem: I just opened a route in Route Viewer, and then this pop-up window was appeared. When I clicked on the OK button, another pop-up window...

**Comment by ginga81** [comment]
I rolled back, but I was able to read 20240206.
20240211 wasn't able to read.
So I think the problem occurred with the modification of 20240211.

**Comment by ginga81** [comment]
@BPI-919 I think posting multiple issues in one issue at the same time will cause confusion.
I think from next time, you should make one problem into one issue.

**Comment by leezer3** [comment]
Please try again with the build from today, I think I've found the issue with some routefiles- My apologies.

Translating the error message from @BPI-919 screenshot suggests that this is the same error, so should hopefully solve this too.

**Comment by ginga81** [comment]
My Tohoku Shinkansen data unreadable issue was fixed in build 20240217.
Thank you!
