### ISSUE TITLE
Some problems with the switch menu

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#993]
### Description

![SwitchMenu](https://github.com/leezer3/OpenBVE/assets/114210303/d44ed57b-5923-4e9a-a10a-e37447574c43)

The "Select a Switch To Change:" and "Close" in the switch menu do not have translations applied, and the fonts do not display properly in other languages.
~The switch menu doesn't change as I scaling of the game window.~

~When I exit the switch menu via the switch menu key instead of the close button, the interface mode did not recover.~
~Waiting for the cursor to hide and then opening the switch menu prevents the cursor from being restored instead of restoring it immediaely. I need to check if the cursor is hidden before opening the switch menu.~

~Some commands not work in the menu such as~ REVERSER_ANY_POSITION, ~DEBUG_BRAKE~, ~CHANGE_SWITCH~.
~I change to REVERSER_ANY_POSTION~, DEBUG_BRAKE_SYSTEMS, SWITCH_MENU ~to use and save the control configurations for these commands.~

### Related information 

* OpenBVE Version: Build 2024-02-17
* Method of control: Keyboard

**Comment by leezer3** [comment]
Thanks for testing this.

As you've found, this is still somewhat incomplete, and a lot of things at the moment are seeing what other people can break, and making sure existing (unmodified) content has no new issues, before I try and get things working a little better overall. 

There will almost certainly be other stuff which functions unexpectedly or not at all.

**Comment by JunmoreHeavyBox** [comment]
urge

**Comment by leezer3** [comment]
I believe all of these are now OK.
