### ISSUE TITLE
Game freezes about 0.3 seconds when playing long sound file

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#998]
### Description

When playing a long sound file, the game freezes like a video, probably because it takes a long time to load.
https://www.youtube.com/watch?v=Ig2SLMjCass
https://www.youtube.com/watch?v=XljuMqnQphk

### Reproduction

I used an mp3 file with a mono track of about 3 minutes.
I think this problem probably occurs no matter which route is set.

## Route

Maybe any

## Train

any train

## Logs

This issue don't crash. So no log.

### Related information 

My PC's spec:
OS:Ubuntu 22.04 LTS 64bit
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Memory:31.3GB
Graphic:AMD Radeon RX 590 Series (polaris10, LLVM 15.0.7, DRM 3.54, 6.5.0-21-generic)

**Comment by leezer3** [comment]
Build from today adds a background thread for loading sounds, which should hopefully get rid of the freeze.

**Comment by ginga81** [comment]
I tested it and it worked perfectly, no more pauses due to sound playing!
Thank you very much!
I close this issue.
